"use client";

import { useState } from "react";
import { Drawer, GatedButton } from "@nzi/ui";
import type { ClientSiteReadModel } from "@nzi/contracts";

export function ClientSiteManager({ initialSites }: { initialSites: ClientSiteReadModel[] }) {
  const [sites, setSites] = useState(initialSites);
  const [selected, setSelected] = useState<ClientSiteReadModel | null>(null);
  const [vacating, setVacating] = useState(false);
  const [date, setDate] = useState("");
  function updateSite(next: ClientSiteReadModel) { setSites((current) => current.map((site) => site.id === next.id ? next : next.isRegisteredOffice && site.isRegisteredOffice ? { ...site, isRegisteredOffice: false, version: site.version + 1 } : site)); setSelected(next); }
  return <section className="nz-panel"><div style={{ display: "flex", alignItems: "center", padding: "13px 16px", borderBottom: "1px solid var(--line2)" }}><div><div className="eyebrow">Client boundary</div><h2 style={{ fontSize: 15, margin: "3px 0 0" }}>Sites</h2></div><button type="button" className="nz-btn pri" style={{ marginLeft: "auto" }} onClick={() => setSelected({ id: `new-${Date.now()}`, name: "", isRegisteredOffice: false, inServiceFrom: new Date().toISOString().slice(0, 10), vacatedEffective: null, status: "in-service", version: 0 })}>Add site</button></div><table className="nz-tbl"><thead><tr><th>Site</th><th>Service</th><th>Status</th><th>Boundary</th></tr></thead><tbody>{sites.map((site) => <tr key={site.id} style={site.status === "vacated" ? { color: "var(--t3)", background: "#F2F4F3" } : undefined} onClick={() => setSelected(site)}><td><b>{site.name}</b>{site.isRegisteredOffice ? <span className="nz-st done" style={{ marginLeft: 8 }}>Registered office</span> : null}</td><td>{site.inServiceFrom}{site.vacatedEffective ? ` → ${site.vacatedEffective}` : " → present"}</td><td><span className={`nz-st ${site.status === "vacated" ? "need" : "done"}`}>{site.status === "vacated" ? "Vacated" : "In service"}</span></td><td className="muted">FY24 included · FY25 excluded</td></tr>)}</tbody></table><Drawer open={selected !== null} onClose={() => setSelected(null)} ariaLabel="Edit client site"><SiteForm key={selected?.id} site={selected} vacating={vacating} date={date} setDate={setDate} setVacating={setVacating} onClose={() => setSelected(null)} onSave={(site) => { updateSite(site); setVacating(false); }} /></Drawer></section>;
}

function SiteForm({ site, vacating, date, setDate, setVacating, onClose, onSave }: { site: ClientSiteReadModel | null; vacating: boolean; date: string; setDate: (value: string) => void; setVacating: (value: boolean) => void; onClose: () => void; onSave: (site: ClientSiteReadModel) => void }) {
  const [name, setName] = useState(site?.name ?? "");
  const [inServiceFrom, setInServiceFrom] = useState(site?.inServiceFrom ?? "");
  if (!site) return null;
  const nextStatus = vacating && date ? "vacated" as const : site.status;
  return <div style={{ background: "var(--paper)", marginLeft: "auto", width: "min(460px, 100vw)", minHeight: "100%", padding: 24, overflowY: "auto" }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><div className="eyebrow">Site boundary</div><h2>{site.name || "New site"}</h2></div><button type="button" className="nz-btn" onClick={onClose}>Close</button></div><label className="nz-fl">Site name<input className="nz-inp" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="nz-fl">In service from<input className="nz-inp" type="date" value={inServiceFrom} onChange={(event) => setInServiceFrom(event.target.value)} /></label><label className="nz-fl"><input type="checkbox" checked={site.isRegisteredOffice} onChange={(event) => onSave({ ...site, name, inServiceFrom, isRegisteredOffice: event.target.checked, version: site.version + 1 })} /> Registered office</label><div className="nz-kv"><span className="k">Status</span><span className="v">{nextStatus === "vacated" ? "Vacated" : "In service"}</span></div>{nextStatus === "vacated" ? <div className="nz-banner warn">Vacated effective {date}. This site remains in reporting boundaries for any year it overlaps.</div> : null}<GatedButton className="nz-btn" blocked={!name.trim() || !inServiceFrom || (vacating && !date)} blockedReason="Name, in-service date and (when vacating) effective date are required." onClick={() => onSave({ ...site, name: name.trim(), inServiceFrom, status: nextStatus, vacatedEffective: nextStatus === "vacated" ? date : null, version: site.version + 1 })}>Save site</GatedButton>{site.status === "in-service" ? <><button type="button" className="nz-btn" onClick={() => setVacating(true)}>Vacate site</button>{vacating ? <label className="nz-fl">Vacated effective date<input className="nz-inp" type="date" value={date} min={inServiceFrom} onChange={(event) => setDate(event.target.value)} /></label> : null}</> : <button type="button" className="nz-btn" onClick={() => onSave({ ...site, status: "in-service", vacatedEffective: null, version: site.version + 1 })}>Reinstate site</button>}</div>;
}
