import {getGrantedPortalDeliverables,portalDeliverableHeaders,portalDeliverableKinds,portalPublicationEvidence,withTenantRead} from "@nzi/isolated-backend";
import {portalAuthFailure} from "../../../../../../lib/authResponse";
import {isolatedPool} from "../../../../../../lib/isolatedDatabase";
import {textPdf} from "../../../../../../lib/pdfDocument";
import {currentPortalUserForData} from "../../../../../../lib/portalSession";
export const dynamic="force-dynamic";
export async function GET(request:Request,{params}:{params:Promise<{jobId:string;kind:string}>}){try{const user=await currentPortalUserForData(request),{jobId,kind}=await params,requestedVersion=new URL(request.url).searchParams.get("reportVersionId");if(!portalDeliverableKinds(kind))return Response.json({code:"NOT_FOUND",message:"That deliverable is unavailable."},{status:404});if(!requestedVersion)return Response.json({code:"REPORT_VERSION_REQUIRED",message:"A report version is required."},{status:422});const result=await withTenantRead(isolatedPool(),user.organisationId,db=>getGrantedPortalDeliverables(db,{portalUserId:user.userId,clientId:user.clientId,jobId,reportVersionId:requestedVersion}));if(!result||result.report.reportVersionId!==requestedVersion)return Response.json({code:"VERSION_UNAVAILABLE",message:"That published document version is unavailable."},{status:404,headers:{"Cache-Control":"private, no-store"}});
// F-4a (D5): figures from the report's own view — a site report's documents carry its sites, and say what they leave out.
const record=result.documents.find(item=>item.kind===kind)!,evidence=portalPublicationEvidence(result.report,result.composition),common=[`Client: ${evidence.client}`,`Job: ${evidence.jobNumber}`,`Reporting year: ${evidence.reportingYear}`,`Report scope: ${evidence.scopeLabel}`,`Report version: ${evidence.reportVersionId}`,`Published: ${evidence.publishedAt}`,`Reviewed snapshot: ${evidence.snapshotId}`,`Evidence SHA-256: ${evidence.evidenceHash}`,`Manifest version: ${evidence.manifestVersion}`],scopeLines=[...evidence.scopeTotals.map(item=>`Scope ${item.scope}: ${item.tco2e.toFixed(2)} tCO2e`),...(evidence.unallocatedStatement?[evidence.unallocatedStatement]:[])],measurementLines=evidence.measurements.map(row=>`${row.scopeCode} - ${row.sourceLabel}: ${row.tco2e.toFixed(2)} tCO2e; ${row.factorSet}`),sections=kind==="report"?[{heading:"Publication record",lines:common},{heading:"Verified scope totals",lines:scopeLines},{heading:"Reviewed measurements",lines:measurementLines}]:kind==="certificate"?[{heading:"Certified publication",lines:[...common,...scopeLines,`${result.report.issuer?.displayName??"The issuer"} confirms that this certificate is bound to the immutable reviewed publication identified above.`]}]:[{heading:"Methodology identity",lines:common},{heading:"Method statement",lines:["Results use the factor labels and versions retained on each reviewed measurement in the immutable snapshot.","Scope totals are the sum of reviewed measurement values. Screen, print and downloadable records reference the same snapshot and evidence hash."]},{heading:"Factor evidence",lines:measurementLines}];const pdf=textPdf(record.title,sections);return new Response(pdf,{headers:portalDeliverableHeaders(record,pdf)})}catch(error){return portalAuthFailure(error)}}
