import {randomUUID} from "node:crypto";
import type {PortalPrincipal,StaffPrincipal} from "./auth";
import {AuthorizationError} from "./auth";
import type {PoolLike,Queryable} from "./postgres";
import {withTenantRead,withTenantWrite} from "./postgres";
import {PortalAccessValidationError} from "./portalAccess";
import {VersionConflictError} from "./errors";

export type PortalDataEntryRecord={recordId:string;bucketGrantId:string;quantity:number;unit:string;factorId:string;siteId:string|null;note:string;status:"draft"|"submitted";version:number;submittedAt:string|null};
type EntryInput={bucketGrantId:string;quantity:number;unit:string;factorId:string;siteId:string|null;note:string};
async function boundary(db:Queryable,principal:PortalPrincipal,jobId:string,bucketGrantId:string,now:Date){const found=await db.query<{allowed_factor_ids:string[];allowed_site_ids:string[];allowed_units:string[]}>(`SELECT b.allowed_factor_ids,b.allowed_site_ids,b.allowed_units FROM nzi_console.portal_data_entry_bucket_grants b JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.grant_id)=(b.organisation_id,b.access_grant_id) WHERE b.bucket_grant_id=$1 AND g.portal_user_id=$2 AND g.client_id=$3 AND g.job_id=$4 AND b.revoked_at IS NULL AND g.revoked_at IS NULL AND g.data_entry_starts_at<=$5 AND g.data_entry_expires_at>$5`,[bucketGrantId,principal.userId,principal.clientId,jobId,now.toISOString()]),grant=found.rows[0];if(!grant)throw new PortalAccessValidationError("This data-entry bucket is unavailable or outside its access window.");return grant;}
async function validate(db:Queryable,principal:PortalPrincipal,jobId:string,input:EntryInput,now:Date){const grant=await boundary(db,principal,jobId,input.bucketGrantId,now),unit=input.unit.trim(),factorId=input.factorId.trim(),siteId=input.siteId?.trim()||null,note=input.note.trim();if(!Number.isFinite(input.quantity)||input.quantity<=0||!grant.allowed_factor_ids.includes(factorId)||!grant.allowed_units.includes(unit)||siteId!==null&&!grant.allowed_site_ids.includes(siteId)||note.length>2000)throw new PortalAccessValidationError("Quantity, factor, unit, site or note is outside the authorised bucket constraints.");const factor=await db.query(`SELECT 1 FROM nzi_console.emission_factors f JOIN nzi_console.job_dataset_selections s ON (s.organisation_id,s.dataset_id)=(f.organisation_id,f.dataset_id) WHERE s.job_id=$1 AND f.factor_id=$2 AND f.activity_unit=$3 AND f.active=true`,[jobId,factorId,unit]);if(!factor.rows[0])throw new PortalAccessValidationError("The selected factor and unit are no longer active for this job.");return{unit,factorId,siteId,note};}
async function audit(db:Queryable,principal:PortalPrincipal,action:string,recordId:string,after:Record<string,unknown>){const auditId=randomUUID();await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'portal',$4,'portal_data_entry_record',$5,$2,$6::jsonb)`,[principal.organisationId,`audit-${auditId}`,principal.userId,action,recordId,JSON.stringify(after)]);}
export async function createPortalDataEntryRecord(pool:PoolLike,principal:PortalPrincipal,jobId:string,input:EntryInput,now=new Date()){return withTenantWrite(pool,principal.organisationId,async db=>{const clean=await validate(db,principal,jobId,input,now),recordId=randomUUID();await db.query(`INSERT INTO nzi_console.portal_data_entry_records(organisation_id,record_id,bucket_grant_id,portal_user_id,quantity,unit,factor_id,site_id,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[principal.organisationId,recordId,input.bucketGrantId,principal.userId,input.quantity,clean.unit,clean.factorId,clean.siteId,clean.note]);await audit(db,principal,"portal.data_entry.record.create",recordId,{jobId,bucketGrantId:input.bucketGrantId,version:1,status:"draft"});return{recordId,version:1,status:"draft" as const};});}
export async function updatePortalDataEntryRecord(pool:PoolLike,principal:PortalPrincipal,jobId:string,recordId:string,expectedVersion:number,input:EntryInput,now=new Date()){return withTenantWrite(pool,principal.organisationId,async db=>{const clean=await validate(db,principal,jobId,input,now),found=await db.query<{version:number;status:string}>(`SELECT version,status FROM nzi_console.portal_data_entry_records WHERE record_id=$1 AND portal_user_id=$2 AND bucket_grant_id=$3 FOR UPDATE`,[recordId,principal.userId,input.bucketGrantId]),row=found.rows[0];if(!row||row.status!=="draft")throw new PortalAccessValidationError("Only an owned draft entry can be edited.");if(row.version!==expectedVersion)throw new VersionConflictError();const version=row.version+1;await db.query(`UPDATE nzi_console.portal_data_entry_records SET quantity=$2,unit=$3,factor_id=$4,site_id=$5,note=$6,version=$7,updated_at=$8 WHERE record_id=$1`,[recordId,input.quantity,clean.unit,clean.factorId,clean.siteId,clean.note,version,now.toISOString()]);await audit(db,principal,"portal.data_entry.record.update",recordId,{jobId,version,status:"draft"});return{recordId,version,status:"draft" as const};});}
export async function deletePortalDataEntryRecord(pool:PoolLike,principal:PortalPrincipal,jobId:string,recordId:string,expectedVersion:number,now=new Date()){return withTenantWrite(pool,principal.organisationId,async db=>{const found=await db.query<{version:number;status:string;bucket_grant_id:string}>(`SELECT version,status,bucket_grant_id FROM nzi_console.portal_data_entry_records WHERE record_id=$1 AND portal_user_id=$2 FOR UPDATE`,[recordId,principal.userId]),row=found.rows[0];if(!row||row.status!=="draft")throw new PortalAccessValidationError("Only an owned draft entry can be deleted.");if(row.version!==expectedVersion)throw new VersionConflictError();await boundary(db,principal,jobId,row.bucket_grant_id,now);const version=row.version+1;await db.query(`UPDATE nzi_console.portal_data_entry_records SET status='deleted',version=$2,updated_at=$3 WHERE record_id=$1`,[recordId,version,now.toISOString()]);await audit(db,principal,"portal.data_entry.record.delete",recordId,{jobId,version,status:"deleted"});return{recordId,version,status:"deleted" as const};});}
export async function submitPortalDataEntryRecord(pool:PoolLike,principal:PortalPrincipal,jobId:string,recordId:string,expectedVersion:number,now=new Date()){return withTenantWrite(pool,principal.organisationId,async db=>{const found=await db.query<{version:number;status:string;bucket_grant_id:string}>(`SELECT version,status,bucket_grant_id FROM nzi_console.portal_data_entry_records WHERE record_id=$1 AND portal_user_id=$2 FOR UPDATE`,[recordId,principal.userId]),row=found.rows[0];if(!row||row.status!=="draft")throw new PortalAccessValidationError("Only an owned draft entry can be submitted.");if(row.version!==expectedVersion)throw new VersionConflictError();await boundary(db,principal,jobId,row.bucket_grant_id,now);const version=row.version+1,submittedAt=now.toISOString(),queueId=randomUUID();await db.query(`UPDATE nzi_console.portal_data_entry_records SET status='submitted',version=$2,submitted_at=$3,updated_at=$3 WHERE record_id=$1`,[recordId,version,submittedAt]);await db.query(`INSERT INTO nzi_console.portal_data_entry_review_queue(organisation_id,queue_id,record_id,submitted_version,submitted_at) VALUES($1,$2,$3,$4,$5)`,[principal.organisationId,queueId,recordId,version,submittedAt]);await audit(db,principal,"portal.data_entry.record.submit",recordId,{jobId,version,status:"submitted",queueId});return{recordId,version,status:"submitted" as const,queueId};});}
export async function listPortalDataEntryRecords(pool:PoolLike,principal:PortalPrincipal,jobId:string,now=new Date()):Promise<PortalDataEntryRecord[]>{return withTenantRead(pool,principal.organisationId,async db=>{const {rows}=await db.query<{record_id:string;bucket_grant_id:string;quantity:string;unit:string;factor_id:string;site_id:string|null;note:string;status:"draft"|"submitted";version:number;submitted_at:Date|string|null}>(`SELECT r.record_id,r.bucket_grant_id,r.quantity,r.unit,r.factor_id,r.site_id,r.note,r.status,r.version,r.submitted_at FROM nzi_console.portal_data_entry_records r JOIN nzi_console.portal_data_entry_bucket_grants b ON (b.organisation_id,b.bucket_grant_id)=(r.organisation_id,r.bucket_grant_id) JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.grant_id)=(b.organisation_id,b.access_grant_id) WHERE r.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3 AND r.status<>'deleted' AND g.data_entry_expires_at>$4 ORDER BY r.created_at,r.record_id`,[principal.userId,principal.clientId,jobId,now.toISOString()]);return rows.map(row=>({recordId:row.record_id,bucketGrantId:row.bucket_grant_id,quantity:Number(row.quantity),unit:row.unit,factorId:row.factor_id,siteId:row.site_id,note:row.note,status:row.status,version:row.version,submittedAt:row.submitted_at?new Date(row.submitted_at).toISOString():null}));});}

export type PortalDataEntryReviewItem={queueId:string;recordId:string;portalUser:string;client:string;jobId:string;jobNumber:string;scope:string;sourceLabel:string;quantity:number;unit:string;factorId:string;siteId:string|null;note:string;submittedVersion:number;submittedAt:string};
export async function listPortalDataEntryReviewQueue(pool:PoolLike,principal:StaffPrincipal):Promise<PortalDataEntryReviewItem[]>{if(!principal.permissions.includes("portal.access.manage")&&!principal.permissions.includes("emissions.review"))throw new AuthorizationError("emissions.review");return withTenantRead(pool,principal.organisationId,async db=>{const {rows}=await db.query<{queue_id:string;record_id:string;display_name:string;client_name:string;job_id:string;job_number:string;scope:string;source_label:string;quantity:string;unit:string;factor_id:string;site_id:string|null;note:string;submitted_version:number;submitted_at:Date|string}>(`SELECT q.queue_id,r.record_id,u.display_name,c.name AS client_name,g.job_id,j.job_number,sr.scope,sr.source_label,r.quantity,r.unit,r.factor_id,r.site_id,r.note,q.submitted_version,q.submitted_at FROM nzi_console.portal_data_entry_review_queue q JOIN nzi_console.portal_data_entry_records r ON (r.organisation_id,r.record_id)=(q.organisation_id,q.record_id) JOIN nzi_console.portal_users u ON (u.organisation_id,u.portal_user_id)=(r.organisation_id,r.portal_user_id) JOIN nzi_console.portal_data_entry_bucket_grants b ON (b.organisation_id,b.bucket_grant_id)=(r.organisation_id,r.bucket_grant_id) JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.grant_id)=(b.organisation_id,b.access_grant_id) JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id)=(g.organisation_id,g.job_id) JOIN nzi_console.clients c ON (c.organisation_id,c.client_id)=(j.organisation_id,j.client_id) JOIN nzi_console.job_scope_rows sr ON (sr.organisation_id,sr.scope_row_id)=(b.organisation_id,b.scope_row_id) WHERE q.status='pending' ORDER BY q.submitted_at,q.queue_id`);return rows.map(row=>({queueId:row.queue_id,recordId:row.record_id,portalUser:row.display_name,client:row.client_name,jobId:row.job_id,jobNumber:row.job_number,scope:row.scope,sourceLabel:row.source_label,quantity:Number(row.quantity),unit:row.unit,factorId:row.factor_id,siteId:row.site_id,note:row.note,submittedVersion:row.submitted_version,submittedAt:new Date(row.submitted_at).toISOString()}));});}

export async function decidePortalDataEntryReview(pool:PoolLike,principal:StaffPrincipal,input:{queueId:string;expectedSubmittedVersion:number;decision:"accept"|"reject";note:string},now=new Date()){
  if(!principal.permissions.includes("emissions.review"))throw new AuthorizationError("emissions.review");
  if(!input.queueId.trim()||!Number.isInteger(input.expectedSubmittedVersion)||input.expectedSubmittedVersion<1||input.decision==="reject"&&!input.note.trim())throw new PortalAccessValidationError("A pending submission version and rejection note are required.");
  return withTenantWrite(pool,principal.organisationId,async db=>{
    const found=await db.query<{record_id:string;submitted_version:number;status:string;scope_row_id:string;job_id:string;quantity:string;unit:string;factor_id:string;site_id:string|null;portal_user_id:string;note:string}>(`SELECT q.record_id,q.submitted_version,q.status,b.scope_row_id,g.job_id,r.quantity,r.unit,r.factor_id,r.site_id,r.portal_user_id,r.note FROM nzi_console.portal_data_entry_review_queue q JOIN nzi_console.portal_data_entry_records r ON (r.organisation_id,r.record_id)=(q.organisation_id,q.record_id) JOIN nzi_console.portal_data_entry_bucket_grants b ON (b.organisation_id,b.bucket_grant_id)=(r.organisation_id,r.bucket_grant_id) JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.grant_id)=(b.organisation_id,b.access_grant_id) WHERE q.organisation_id=$1 AND q.queue_id=$2 FOR UPDATE OF q`,[principal.organisationId,input.queueId]);
    const row=found.rows[0];
    if(!row||row.status!=="pending")throw new PortalAccessValidationError("This submission is no longer pending review.");
    if(row.submitted_version!==input.expectedSubmittedVersion)throw new VersionConflictError();
    const reviewedAt=now.toISOString();let scopeRowVersion:number|null=null;
    if(input.decision==="accept"){
      const factor=await db.query<{dataset_id:string;label:string;version:string}>(`SELECT f.dataset_id,f.label,d.version FROM nzi_console.emission_factors f JOIN nzi_console.emission_factor_datasets d ON (d.organisation_id,d.dataset_id)=(f.organisation_id,f.dataset_id) JOIN nzi_console.job_dataset_selections s ON (s.organisation_id,s.dataset_id)=(f.organisation_id,f.dataset_id) WHERE s.organisation_id=$1 AND s.job_id=$2 AND f.factor_id=$3 AND f.activity_unit=$4 AND f.active=true`,[principal.organisationId,row.job_id,row.factor_id,row.unit]);
      if(!factor.rows[0])throw new PortalAccessValidationError("The submitted factor is no longer active for this job.");
      const updated=await db.query<{version:number}>(`UPDATE nzi_console.job_scope_rows SET quantity=$3,monthly_activity_json='[]'::jsonb,notes=nullif(trim($15),''),unit=$4,dataset_id=$5,factor_id=$6,factor_version=$7,factor_label=$8,site_id=$9,quality_tier=NULL,provenance_json=jsonb_build_object('source','client-portal','portalUserId',$10,'recordId',$11,'submittedVersion',$12),lineage_json=jsonb_build_array(jsonb_build_object('reviewState','pending-staff-review')),calculated_tco2e=NULL,override_tco2e=NULL,override_reason=NULL,review_status='pending',reviewed_row_version=NULL,reviewed_by=NULL,reviewed_at=NULL,reviewer_note=NULL,version=version+1,updated_at=$13,enabled=true WHERE organisation_id=$1 AND scope_row_id=$2 AND job_id=$14 RETURNING version`,[principal.organisationId,row.scope_row_id,Number(row.quantity),row.unit,factor.rows[0].dataset_id,row.factor_id,factor.rows[0].version,factor.rows[0].label,row.site_id,row.portal_user_id,row.record_id,row.submitted_version,reviewedAt,row.job_id,row.note]);
      if(!updated.rows[0])throw new PortalAccessValidationError("The canonical scope row is unavailable.");scopeRowVersion=updated.rows[0].version;
    }
    const status=input.decision==="accept"?"accepted":"rejected";
    await db.query(`UPDATE nzi_console.portal_data_entry_review_queue SET status=$3,reviewed_by=$4,reviewed_at=$5,review_note=$6 WHERE organisation_id=$1 AND queue_id=$2`,[principal.organisationId,input.queueId,status,principal.userId,reviewedAt,input.note.trim()||null]);
    const auditId=randomUUID();await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'staff',$4,'portal_data_entry_review',$5,$2,$6::jsonb)`,[principal.organisationId,`audit-${auditId}`,principal.userId,`portal.data_entry.review.${status}`,input.queueId,JSON.stringify({recordId:row.record_id,jobId:row.job_id,scopeRowId:row.scope_row_id,submittedVersion:row.submitted_version,scopeRowVersion,status,reviewNote:input.note.trim()||null})]);
    return{queueId:input.queueId,recordId:row.record_id,status,scopeRowId:row.scope_row_id,scopeRowVersion};
  });
}
