import {randomUUID} from "node:crypto";
import type {PoolLike} from "./postgres";
import {withTenantRead,withTenantWrite} from "./postgres";
import type {PortalSession} from "./auth";
import type {StaffPrincipal} from "./auth";
import type {PortalReportApproval} from "./readModels";

export type PortalReportComment={commentId:string;reportVersionId:string;parentCommentId:string|null;authorPrincipal:"portal"|"staff";authorDisplayName:string;body:string;createdAt:string};
export type StaffReportThread={reportVersionId:string;jobId:string;jobNumber:string;client:string;reportingYear:number|null;comments:PortalReportComment[]};
async function requireGrantedCurrentReport(db:import("./postgres").Queryable,session:PortalSession,input:{jobId:string;reportVersionId:string}){const found=await db.query<{report_version_id:string}>(`SELECT r.report_version_id FROM nzi_console.report_versions r JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id)=(r.organisation_id,r.job_id) JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.job_id,g.client_id)=(j.organisation_id,j.job_id,j.client_id) WHERE r.report_version_id=$1 AND r.job_id=$2 AND r.status='published' AND g.portal_user_id=$3 AND g.client_id=$4 AND g.revoked_at IS NULL`,[input.reportVersionId,input.jobId,session.userId,session.clientId]);if(!found.rows[0])throw new Error("The published report is unavailable or is no longer the current version.");}

export async function listGrantedReportComments(pool:PoolLike,session:PortalSession,input:{jobId:string;reportVersionId:string}):Promise<PortalReportComment[]>{return withTenantRead(pool,session.organisationId,async db=>{await requireGrantedCurrentReport(db,session,input);const {rows}=await db.query<{comment_id:string;report_version_id:string;parent_comment_id:string|null;author_principal:"portal"|"staff";author_display_name:string;body:string;created_at:Date|string}>(`SELECT comment_id,report_version_id,parent_comment_id,author_principal,author_display_name,body,created_at FROM nzi_console.portal_report_comments WHERE report_version_id=$1 AND job_id=$2 ORDER BY created_at,comment_id`,[input.reportVersionId,input.jobId]);return rows.map(row=>({commentId:row.comment_id,reportVersionId:row.report_version_id,parentCommentId:row.parent_comment_id,authorPrincipal:row.author_principal,authorDisplayName:row.author_display_name,body:row.body,createdAt:row.created_at instanceof Date?row.created_at.toISOString():String(row.created_at)}));});}

export async function addGrantedReportComment(pool:PoolLike,session:PortalSession&{displayName:string},input:{jobId:string;reportVersionId:string;body:string;parentCommentId?:string|null},now=new Date()):Promise<PortalReportComment>{const body=input.body.trim();if(!body||body.length>4000)throw new Error("A comment between 1 and 4,000 characters is required.");return withTenantWrite(pool,session.organisationId,async db=>{await requireGrantedCurrentReport(db,session,input);if(input.parentCommentId){const parent=await db.query(`SELECT 1 FROM nzi_console.portal_report_comments WHERE comment_id=$1 AND report_version_id=$2`,[input.parentCommentId,input.reportVersionId]);if(!parent.rows[0])throw new Error("The parent comment is unavailable.");}const commentId=randomUUID(),createdAt=now.toISOString();await db.query(`INSERT INTO nzi_console.portal_report_comments(organisation_id,comment_id,report_version_id,job_id,client_id,parent_comment_id,author_principal,author_id,author_display_name,body,created_at) VALUES($1,$2,$3,$4,$5,$6,'portal',$7,$8,$9,$10)`,[session.organisationId,commentId,input.reportVersionId,input.jobId,session.clientId,input.parentCommentId??null,session.userId,session.displayName,body,createdAt]);await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'portal','portal.report.comment.create','report_comment',$4,$5,jsonb_build_object('reportVersionId',$6,'jobId',$7))`,[session.organisationId,`audit-${commentId}`,session.userId,commentId,commentId,input.reportVersionId,input.jobId]);return{commentId,reportVersionId:input.reportVersionId,parentCommentId:input.parentCommentId??null,authorPrincipal:"portal",authorDisplayName:session.displayName,body,createdAt};});}

export async function listStaffReportThreads(pool:PoolLike,principal:StaffPrincipal):Promise<StaffReportThread[]>{return withTenantRead(pool,principal.organisationId,async db=>{const {rows}=await db.query<{report_version_id:string;job_id:string;job_number:string;client_name:string;reporting_year:number|null;comments:Array<{commentId:string;reportVersionId:string;parentCommentId:string|null;authorPrincipal:"portal"|"staff";authorDisplayName:string;body:string;createdAt:string}>}>(`SELECT r.report_version_id,j.job_id,j.job_number,c.name AS client_name,j.reporting_year,coalesce(jsonb_agg(jsonb_build_object('commentId',m.comment_id,'reportVersionId',m.report_version_id,'parentCommentId',m.parent_comment_id,'authorPrincipal',m.author_principal,'authorDisplayName',m.author_display_name,'body',m.body,'createdAt',m.created_at) ORDER BY m.created_at,m.comment_id) FILTER(WHERE m.comment_id IS NOT NULL),'[]'::jsonb) AS comments FROM nzi_console.report_versions r JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id)=(r.organisation_id,r.job_id) JOIN nzi_console.clients c ON (c.organisation_id,c.client_id)=(j.organisation_id,j.client_id) LEFT JOIN nzi_console.portal_report_comments m ON (m.organisation_id,m.report_version_id)=(r.organisation_id,r.report_version_id) WHERE r.status='published' GROUP BY r.report_version_id,j.organisation_id,j.job_id,c.organisation_id,c.client_id ORDER BY max(m.created_at) DESC NULLS LAST,j.sequence DESC`);return rows.map(row=>({reportVersionId:row.report_version_id,jobId:row.job_id,jobNumber:row.job_number,client:row.client_name,reportingYear:row.reporting_year,comments:row.comments??[]}));});}

export async function addStaffReportComment(pool:PoolLike,principal:StaffPrincipal,input:{jobId:string;reportVersionId:string;body:string;parentCommentId?:string|null},now=new Date()):Promise<PortalReportComment>{const body=input.body.trim();if(!body||body.length>4000)throw new Error("A comment between 1 and 4,000 characters is required.");return withTenantWrite(pool,principal.organisationId,async db=>{const found=await db.query<{client_id:string}>(`SELECT j.client_id FROM nzi_console.report_versions r JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id)=(r.organisation_id,r.job_id) WHERE r.report_version_id=$1 AND r.job_id=$2 AND r.status='published'`,[input.reportVersionId,input.jobId]);if(!found.rows[0])throw new Error("The current published report is unavailable.");if(input.parentCommentId){const parent=await db.query(`SELECT 1 FROM nzi_console.portal_report_comments WHERE comment_id=$1 AND report_version_id=$2`,[input.parentCommentId,input.reportVersionId]);if(!parent.rows[0])throw new Error("The parent comment is unavailable.");}const commentId=randomUUID(),createdAt=now.toISOString(),displayName=`NZI ${principal.role}`;await db.query(`INSERT INTO nzi_console.portal_report_comments(organisation_id,comment_id,report_version_id,job_id,client_id,parent_comment_id,author_principal,author_id,author_display_name,body,created_at) VALUES($1,$2,$3,$4,$5,$6,'staff',$7,$8,$9,$10)`,[principal.organisationId,commentId,input.reportVersionId,input.jobId,found.rows[0].client_id,input.parentCommentId??null,principal.userId,displayName,body,createdAt]);await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'staff','portal.report.comment.reply','report_comment',$4,$5,jsonb_build_object('reportVersionId',$6,'jobId',$7))`,[principal.organisationId,`audit-${commentId}`,principal.userId,commentId,commentId,input.reportVersionId,input.jobId]);return{commentId,reportVersionId:input.reportVersionId,parentCommentId:input.parentCommentId??null,authorPrincipal:"staff",authorDisplayName:displayName,body,createdAt};});}

export async function approveGrantedPublishedReport(pool:PoolLike,session:PortalSession,input:{jobId:string;reportVersionId:string},now=new Date()):Promise<PortalReportApproval>{return withTenantWrite(pool,session.organisationId,async db=>{const found=await db.query<{report_version_id:string}>(`SELECT r.report_version_id FROM nzi_console.report_versions r JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id)=(r.organisation_id,r.job_id) JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.job_id,g.client_id)=(j.organisation_id,j.job_id,j.client_id) WHERE r.report_version_id=$1 AND r.job_id=$2 AND r.status='published' AND g.portal_user_id=$3 AND g.client_id=$4 AND g.revoked_at IS NULL`,[input.reportVersionId,input.jobId,session.userId,session.clientId]);if(!found.rows[0])throw new Error("The published report is unavailable or is no longer the current version.");const existing=await db.query<{approval_id:string;approved_at:Date|string;statement_version:1}>(`SELECT approval_id,approved_at,statement_version FROM nzi_console.portal_report_approvals WHERE report_version_id=$1 AND portal_user_id=$2`,[input.reportVersionId,session.userId]);if(existing.rows[0])return{approvalId:existing.rows[0].approval_id,reportVersionId:input.reportVersionId,approvedAt:existing.rows[0].approved_at instanceof Date?existing.rows[0].approved_at.toISOString():String(existing.rows[0].approved_at),statementVersion:existing.rows[0].statement_version};const approvalId=randomUUID(),approvedAt=now.toISOString();await db.query(`INSERT INTO nzi_console.portal_report_approvals(organisation_id,approval_id,report_version_id,job_id,portal_user_id,client_id,approved_at) VALUES($1,$2,$3,$4,$5,$6,$7)`,[session.organisationId,approvalId,input.reportVersionId,input.jobId,session.userId,session.clientId,approvedAt]);await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,before_json,after_json) VALUES($1,$2,$3,'portal','portal.report.approve','report_version',$4,$5,'{}'::jsonb,jsonb_build_object('approvalId',$2,'statementVersion',1))`,[session.organisationId,`audit-${approvalId}`,session.userId,input.reportVersionId,approvalId]);return{approvalId,reportVersionId:input.reportVersionId,approvedAt,statementVersion:1};});}
