import {randomUUID} from "node:crypto";
import type {PoolLike} from "./postgres";
import {withTenantRead,withTenantWrite} from "./postgres";
import type {PortalPrincipal,StaffPrincipal} from "./auth";
import {AuthorizationError} from "./auth";

export type PortalAccessJob={jobId:string;jobNumber:string;title:string;reportingYear:number|null;granted:boolean;grantId:string|null;dataEntryStartsAt:string|null;dataEntryExpiresAt:string|null};
export type PortalDataEntryAccess={jobId:string;startsAt:string;expiresAt:string;state:"scheduled"|"open"};
export type PortalAccessUser={portalUserId:string;clientId:string;clientName:string;email:string;displayName:string;status:"invited"|"active"|"disabled";jobs:PortalAccessJob[]};
export class PortalAccessValidationError extends Error{constructor(message:string){super(message);this.name="PortalAccessValidationError";}}

function requirePortalAccess(principal:StaffPrincipal){if(!principal.permissions.includes("portal.access.manage"))throw new AuthorizationError("portal.access.manage");}

export async function listPortalAccess(pool:PoolLike,principal:StaffPrincipal):Promise<PortalAccessUser[]>{requirePortalAccess(principal);return withTenantRead(pool,principal.organisationId,async db=>{const {rows}=await db.query<{portal_user_id:string;client_id:string;client_name:string;email_normalized:string;display_name:string;status:PortalAccessUser["status"];jobs:PortalAccessJob[]}>(`SELECT u.portal_user_id,u.client_id,c.name AS client_name,u.email_normalized,u.display_name,u.status,coalesce((SELECT jsonb_agg(jsonb_build_object('jobId',j.job_id,'jobNumber',j.job_number,'title',j.title,'reportingYear',j.reporting_year,'granted',g.revoked_at IS NULL,'grantId',g.grant_id,'dataEntryStartsAt',g.data_entry_starts_at,'dataEntryExpiresAt',g.data_entry_expires_at) ORDER BY j.sequence DESC) FROM nzi_console.jobs j LEFT JOIN nzi_console.portal_access_grants g ON (g.organisation_id,g.portal_user_id,g.job_id)=(u.organisation_id,u.portal_user_id,j.job_id) WHERE (j.organisation_id,j.client_id)=(u.organisation_id,u.client_id)),'[]'::jsonb) AS jobs FROM nzi_console.portal_users u JOIN nzi_console.clients c ON (c.organisation_id,c.client_id)=(u.organisation_id,u.client_id) ORDER BY c.name,u.display_name,u.email_normalized`);return rows.map(row=>({portalUserId:row.portal_user_id,clientId:row.client_id,clientName:row.client_name,email:row.email_normalized,displayName:row.display_name,status:row.status,jobs:row.jobs??[]}));});}

export async function setPortalDataEntryWindow(pool:PoolLike,principal:StaffPrincipal,input:{portalUserId:string;jobId:string;startsAt:string|null;expiresAt:string|null},now=new Date()):Promise<{jobId:string;startsAt:string|null;expiresAt:string|null}>{requirePortalAccess(principal);const starts=input.startsAt===null?null:new Date(input.startsAt),expires=input.expiresAt===null?null:new Date(input.expiresAt);if(!input.portalUserId.trim()||!input.jobId.trim()||starts&&!Number.isFinite(starts.getTime())||expires&&!Number.isFinite(expires.getTime())||Boolean(starts)!==Boolean(expires)||starts&&expires&&expires<=starts)throw new PortalAccessValidationError("Enter a valid data-entry start and expiry, with expiry after start, or clear both values.");return withTenantWrite(pool,principal.organisationId,async db=>{const found=await db.query<{grant_id:string}>(`SELECT g.grant_id FROM nzi_console.portal_access_grants g JOIN nzi_console.portal_users u ON (u.organisation_id,u.portal_user_id,u.client_id)=(g.organisation_id,g.portal_user_id,g.client_id) JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id,j.client_id)=(g.organisation_id,g.job_id,g.client_id) WHERE g.portal_user_id=$1 AND g.job_id=$2 AND g.revoked_at IS NULL FOR UPDATE OF g`,[input.portalUserId,input.jobId]),grant=found.rows[0];if(!grant)throw new PortalAccessValidationError("Active job access is required before data entry can be scheduled.");const startsAt=starts?.toISOString()??null,expiresAt=expires?.toISOString()??null;await db.query(`UPDATE nzi_console.portal_access_grants SET data_entry_starts_at=$2,data_entry_expires_at=$3 WHERE grant_id=$1`,[grant.grant_id,startsAt,expiresAt]);const auditId=randomUUID();await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'staff','portal.data_entry.window.set','portal_access_grant',$4,$2,jsonb_build_object('portalUserId',$5,'jobId',$6,'startsAt',$7,'expiresAt',$8,'enabled',$9))`,[principal.organisationId,`audit-${auditId}`,principal.userId,grant.grant_id,input.portalUserId,input.jobId,startsAt,expiresAt,Boolean(expiresAt)]);return{jobId:input.jobId,startsAt,expiresAt};});}

export async function getPortalDataEntryAccess(pool:PoolLike,principal:PortalPrincipal,jobId:string,now=new Date()):Promise<PortalDataEntryAccess|null>{if(!jobId.trim())return null;return withTenantRead(pool,principal.organisationId,async db=>{const found=await db.query<{data_entry_starts_at:Date|string;data_entry_expires_at:Date|string}>(`SELECT g.data_entry_starts_at,g.data_entry_expires_at FROM nzi_console.portal_access_grants g JOIN nzi_console.jobs j ON (j.organisation_id,j.job_id,j.client_id)=(g.organisation_id,g.job_id,g.client_id) WHERE g.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3 AND g.revoked_at IS NULL AND g.data_entry_starts_at IS NOT NULL AND g.data_entry_expires_at>$4`,[principal.userId,principal.clientId,jobId,now.toISOString()]),row=found.rows[0];if(!row)return null;const startsAt=new Date(row.data_entry_starts_at).toISOString(),expiresAt=new Date(row.data_entry_expires_at).toISOString();return{jobId,startsAt,expiresAt,state:new Date(startsAt)>now?"scheduled":"open"};});}

export async function setPortalJobAccess(pool:PoolLike,principal:StaffPrincipal,input:{portalUserId:string;jobId:string;granted:boolean},now=new Date()):Promise<{grantId:string;granted:boolean}>{requirePortalAccess(principal);if(!input.portalUserId.trim()||!input.jobId.trim())throw new PortalAccessValidationError("A portal user and job are required.");return withTenantWrite(pool,principal.organisationId,async db=>{const match=await db.query<{client_id:string}>(`SELECT u.client_id FROM nzi_console.portal_users u JOIN nzi_console.jobs j ON (j.organisation_id,j.client_id)=(u.organisation_id,u.client_id) WHERE u.portal_user_id=$1 AND j.job_id=$2`,[input.portalUserId,input.jobId]);if(!match.rows[0])throw new PortalAccessValidationError("The portal user and job do not belong to the same client.");const existing=await db.query<{grant_id:string;revoked_at:Date|string|null}>(`SELECT grant_id,revoked_at FROM nzi_console.portal_access_grants WHERE portal_user_id=$1 AND job_id=$2 FOR UPDATE`,[input.portalUserId,input.jobId]);const grantId=existing.rows[0]?.grant_id??randomUUID(),changedAt=now.toISOString();if(input.granted){if(existing.rows[0])await db.query(`UPDATE nzi_console.portal_access_grants SET revoked_at=NULL WHERE grant_id=$1`,[grantId]);else await db.query(`INSERT INTO nzi_console.portal_access_grants(organisation_id,grant_id,client_id,portal_user_id,job_id) VALUES($1,$2,$3,$4,$5)`,[principal.organisationId,grantId,match.rows[0].client_id,input.portalUserId,input.jobId]);}else{if(!existing.rows[0]||existing.rows[0].revoked_at)return{grantId,granted:false};await db.query(`UPDATE nzi_console.portal_access_grants SET revoked_at=$2 WHERE grant_id=$1`,[grantId,changedAt]);const remaining=await db.query(`SELECT 1 FROM nzi_console.portal_access_grants WHERE portal_user_id=$1 AND revoked_at IS NULL LIMIT 1`,[input.portalUserId]);if(!remaining.rows[0])await db.query(`SELECT nzi_console.revoke_portal_user_sessions($1,$2,$3)`,[principal.organisationId,input.portalUserId,changedAt]);}await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'staff',$4,'portal_access_grant',$5,$2,jsonb_build_object('portalUserId',$6,'jobId',$7,'granted',$8))`,[principal.organisationId,`audit-${randomUUID()}`,principal.userId,input.granted?"portal.access.grant":"portal.access.revoke",grantId,input.portalUserId,input.jobId,input.granted]);return{grantId,granted:input.granted};});}

export async function setPortalUserEnabled(pool:PoolLike,principal:StaffPrincipal,input:{portalUserId:string;enabled:boolean},now=new Date()):Promise<{enabled:boolean}>{requirePortalAccess(principal);return withTenantWrite(pool,principal.organisationId,async db=>{const found=await db.query<{status:PortalAccessUser["status"]}>(`SELECT status FROM nzi_console.portal_users WHERE portal_user_id=$1 FOR UPDATE`,[input.portalUserId]),user=found.rows[0];if(!user)throw new PortalAccessValidationError("The portal user is unavailable.");if(user.status==="invited"&&input.enabled)throw new PortalAccessValidationError("The user must complete their invitation before activation.");const status=input.enabled?"active":"disabled",changedAt=now.toISOString();await db.query(`UPDATE nzi_console.portal_users SET status=$2 WHERE portal_user_id=$1`,[input.portalUserId,status]);if(!input.enabled)await db.query(`SELECT nzi_console.revoke_portal_user_sessions($1,$2,$3)`,[principal.organisationId,input.portalUserId,changedAt]);const auditId=randomUUID();await db.query(`INSERT INTO nzi_console.audit_events(organisation_id,audit_event_id,actor_id,principal_type,action,entity_type,entity_id,correlation_id,after_json) VALUES($1,$2,$3,'staff',$4,'portal_user',$5,$2,jsonb_build_object('enabled',$6))`,[principal.organisationId,`audit-${auditId}`,principal.userId,input.enabled?"portal.user.enable":"portal.user.disable",input.portalUserId,input.enabled]);return{enabled:input.enabled};});}
