"use client";

import {FormEvent,useState} from "react";

export function StaffAccount(){
  const [notice,setNotice]=useState<{message:string;ok:boolean}|null>(null),[pending,setPending]=useState(false),[passwordLength,setPasswordLength]=useState(0);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setPending(true);setNotice(null);const element=event.currentTarget,form=new FormData(element),newPassword=String(form.get("newPassword")??""),confirmation=String(form.get("confirmation")??"");if(newPassword!==confirmation){setPending(false);setNotice({message:"New password confirmation does not match.",ok:false});return;}try{const response=await fetch("/api/auth/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword})}),body=await response.json();if(!response.ok)throw new Error(body.message??"Password change failed.");if(body.changed!==true)throw new Error("The password service returned an invalid confirmation.");setNotice({message:"Password changed. Other staff sessions have been signed out; MFA remains active.",ok:true});element.reset();setPasswordLength(0);}catch(error){setNotice({message:error instanceof Error?error.message:"The password service could not be reached. Your password has not been changed.",ok:false});}finally{setPending(false);}}
  return <main className="nz-account-shell"><header className="nz-account-header"><a href="/" className="nz-portal-brand"><span>N</span><div><b>NZI Pro</b><small>Staff console</small></div></a><a href="/" className="nz-btn">Back to console</a></header><section className="nz-account-layout"><aside className="nz-account-brief"><span className="nz-eyebrow light">Account protection</span><h1>Keep your staff workspace secure.</h1><p>Use a strong, unique password for access to client delivery, evidence and publication workflows.</p><div className="nz-account-trust"><span><i>✓</i> Minimum 12 characters</span><span><i>✓</i> MFA remains active</span><span><i>✓</i> Other sessions revoked</span></div></aside><form onSubmit={submit} className="nz-account-card" aria-busy={pending}><span className="nz-eyebrow">Staff account security</span><h2>Change password</h2><p>Confirm your temporary or current password, then choose a new one used only for NZI Pro.</p><label className="nz-fl">Current password<input className="nz-inp" name="currentPassword" type="password" autoComplete="current-password" required disabled={pending}/></label><div className="nz-account-divider"/><label className="nz-fl">New password<input className="nz-inp" name="newPassword" type="password" minLength={12} autoComplete="new-password" required disabled={pending} onChange={event=>setPasswordLength(event.target.value.length)} aria-describedby="staff-new-password-guidance"/></label><div className={`nz-password-meter ${passwordLength>=12?"ready":""}`} id="staff-new-password-guidance"><span><i style={{width:`${Math.min(100,passwordLength/12*100)}%`}}/></span><small>{passwordLength>=12?"Minimum length met — use a unique password.":`${passwordLength} of 12 characters minimum`}</small></div><label className="nz-fl">Confirm new password<input className="nz-inp" name="confirmation" type="password" minLength={12} autoComplete="new-password" required disabled={pending}/></label>{notice&&<div className={`nz-banner ${notice.ok?"ok":"warn"}`} role={notice.ok?"status":"alert"}>{notice.message}</div>}<button className="nz-btn pri nz-auth-submit" disabled={pending}>{pending?"Changing…":"Change password securely"}</button></form></section></main>;
}
