import assert from "node:assert/strict";
import {describe,it} from "node:test";
import {approveScopeRow,calculateScopeRow,CommandValidationError,createJob,createReviewedCrpSnapshot,createScopeRow,publishCrpReport,validateCrpReport,VersionConflictError} from "../src/index";

type Stored={request_hash:string;outcome_json:Record<string,unknown>};

function lifecyclePool(options:{incomplete?:boolean;startEmpty?:boolean}={}){
  const idempotency=new Map<string,Stored>(),audits:string[]=[],outbox:string[]=[];
  let snapshot:{id:string;hash:string;payload:Record<string,unknown>;createdAt:string}|undefined,report:{id:string;status:string;manifest:number;snapshotId:string}|undefined;
  let jobId="job-a",jobVersion=options.startEmpty?1:5;
  const rows:Array<Record<string,unknown>>=options.startEmpty?[]:["1","2","3.1"].map((scope,index)=>({scope_row_id:`row-${scope}`,version:4,scope,source_label:`Scope ${scope} evidence`,site_id:null,site_label:null,purchased_goods_category_id:scope==="3.1"?"category-a":null,purchased_goods_category_label:scope==="3.1"?"Purchased materials":null,calculated_tco2e:String((index+1)*10),override_tco2e:null,factor_label:"Governed factor",factor_version:"2026.1",quality_tier:"measured",review_status:options.incomplete&&scope==="3.1"?"pending":"approved",reviewed_by:options.incomplete&&scope==="3.1"?null:"reviewer-a",enabled:true,provenance_json:{calculatedBy:"consultant-a"}}));
  const client={async query(sql:string,values:readonly unknown[]=[]){
    if(sql.includes("FROM nzi_console.command_idempotency")){const stored=idempotency.get(String(values[1]));return{rows:stored?[stored]:[]};}
    if(sql.includes("INSERT INTO nzi_console.command_idempotency")){idempotency.set(String(values[1]),{request_hash:String(values[3]),outcome_json:JSON.parse(String(values[4]))});return{rows:[]};}
    if(sql.includes("INSERT INTO nzi_console.audit_events")){audits.push(String(values[4]));return{rows:[]};}
    if(sql.includes("INSERT INTO nzi_console.transactional_outbox")){outbox.push(String(values[2]));return{rows:[]};}
    if(sql.includes("allocate_job_sequence"))return{rows:[{sequence:717}]};
    if(sql.includes("INSERT INTO nzi_console.jobs")){jobId=String(values[1]);return{rows:[{job_number:"J000717"}]};}
    if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};
    if(sql.includes("SELECT 1 FROM nzi_console.purchased_goods_categories"))return{rows:[{}]};
    if(sql.includes("INSERT INTO nzi_console.job_scope_rows")){rows.push({scope_row_id:String(values[1]),version:1,scope:String(values[3]),source_label:String(values[4]),site_id:null,site_label:null,purchased_goods_category_id:values[6],purchased_goods_category_label:values[6]?"Purchased materials":null,quantity:String(values[7]),unit:String(values[8]),dataset_id:String(values[9]),factor_id:String(values[10]),factor_label:String(values[12]),factor_version:String(values[11]),quality_tier:String(values[13]),calculated_tco2e:null,override_tco2e:null,review_status:"pending",reviewed_by:null,enabled:true,provenance_json:JSON.parse(String(values[14]))});return{rows:[]};}
    if(sql.includes("SELECT version,quantity,unit,scope")){const row=rows.find(item=>item.scope_row_id===values[2]);return{rows:row?[row]:[]};}
    if(sql.includes("SELECT f.label,f.activity_unit"))return{rows:[{label:"Governed factor",activity_unit:"kWh",kgco2e_per_unit:"1",version:"2026.1",synthetic:true}]};
    if(sql.includes("SET factor_version=")&&sql.includes("RETURNING version,calculated_tco2e")){const row=rows.find(item=>item.scope_row_id===values[2])!;if(row.version!==values[8])return{rows:[]};row.version=Number(row.version)+1;row.calculated_tco2e=String(Number(row.quantity)/1000);row.provenance_json=JSON.parse(String(values[6]));return{rows:[{version:row.version,calculated_tco2e:row.calculated_tco2e}]};}
    if(sql.includes("SELECT version,enabled,calculated_tco2e")){const row=rows.find(item=>item.scope_row_id===values[2]);return{rows:row?[row]:[]};}
    if(sql.includes("SET review_status=")&&sql.includes("RETURNING version")){const row=rows.find(item=>item.scope_row_id===values[2])!;if(row.version!==values[4])return{rows:[]};row.review_status=values[3];row.reviewed_by=values[5];row.version=Number(row.version)+1;return{rows:[{version:row.version}]};}
    if(sql.includes("SELECT j.version"))return{rows:[{version:jobVersion,job_family:"crp",job_number:"J000717",client_id:"client-a",reporting_year:2026,start_date:"2026-01-01",client_name:"Lifecycle Client"}]};
    if(sql.includes("FROM nzi_console.job_emissions_targets"))return{rows:[{job_id:"job-a",baseline_year:2025,baseline_tco2e:"75",interim_year:2030,interim_reduction_percent:"50",net_zero_year:2050,version:1,updated_by:"staff-a",updated_at:"2026-08-28T08:00:00.000Z"}]};
    if(sql.includes("FROM nzi_console.job_intensity_targets"))return{rows:[{job_id:"job-a",metric:"turnover",denominator_unit:"£m revenue",reporting_denominator:"10",baseline_year:2025,baseline_intensity:"7.5",interim_year:2030,interim_reduction_percent:"50",net_zero_year:2050,version:1,updated_by:"staff-a",updated_at:"2026-08-28T08:00:00.000Z"}]};
    if(sql.includes("SELECT scope_row_id"))return{rows};
    if(sql.includes("SELECT DISTINCT ON"))return{rows:[{snapshot_id:"snapshot-2025",data_hash:`sha256:${"a".repeat(64)}`,reporting_year:2025,measurements:[{scope:"1",tco2e:12},{scope:"2",tco2e:18},{scope:"3",tco2e:45}]}]};
    if(sql.includes("SELECT snapshot_id,snapshot_version"))return{rows:[]};
    if(sql.includes("coalesce(max(snapshot_version)"))return{rows:[{version:1}]};
    if(sql.includes("INSERT INTO nzi_console.reviewed_crp_snapshots")){snapshot={id:String(values[1]),hash:String(values[5]),payload:JSON.parse(String(values[6])),createdAt:"2026-08-28T08:10:00.000Z"};return{rows:[]};}
    if(sql.includes("FROM nzi_console.reviewed_crp_snapshots WHERE"))return{rows:snapshot?[{job_id:"job-a",data_hash:snapshot.hash,created_at:snapshot.createdAt,payload_json:snapshot.payload}]:[]};
    if(sql.includes("INSERT INTO nzi_console.report_versions(")){report={id:String(values[1]),status:"validated",manifest:Number(values[3]),snapshotId:String(values[4])};return{rows:[]};}
    if(sql.includes("SELECT job_id,status,manifest_version"))return{rows:report?[{job_id:"job-a",status:report.status,manifest_version:report.manifest,reviewed_snapshot_id:report.snapshotId}]:[]};
    if(sql.includes("SET status='superseded'"))return{rows:[]};
    if(sql.includes("SET status='published'")){if(report?.status!=="validated")return{rows:[]};report.status="published";return{rows:[{published_at:"2026-08-28T08:15:00.000Z"}]};}
    return{rows:[]};
  },release(){}};
  return{pool:{connect:async()=>client} as never,state:()=>({snapshot,report,audits,outbox,rows,jobId})};
}

const context=(key:string,actorId="reviewer-a")=>({organisationId:"org-a",actorId,principal:"staff" as const,idempotencyKey:key,correlationId:`corr-${key}`});

describe("canonical CRP lifecycle acceptance",()=>{
  it("runs from CRP job configuration through calculation, independent review and immutable publication",async()=>{const state=lifecyclePool({startEmpty:true}),job=await createJob(state.pool,{clientId:"client-a",family:"crp",title:"2026 lifecycle CRP",workflowStage:"Setup",owner:"Consultant A",startDate:"2026-01-01",dueDate:"2026-12-31",reportingYear:2026},context("job","consultant-a"));for(const [index,scope] of ["1","2","3.1"].entries()){const created=await createScopeRow(state.pool,{jobId:job.data.jobId,scope,sourceLabel:`Scope ${scope} evidence`,siteId:null,siteLabel:null,purchasedGoodsCategoryId:scope==="3.1"?"category-a":null,purchasedGoodsCategoryLabel:scope==="3.1"?"Purchased materials":null,quantity:(index+1)*10000,unit:"kWh",datasetId:"dataset-a",factorId:"factor-a",factorVersion:"2026.1",factorLabel:"Governed factor",qualityTier:"measured"},context(`row-${index}`,"consultant-a")),calculated=await calculateScopeRow(state.pool,{jobId:job.data.jobId,rowId:created.data.rowId,expectedVersion:created.data.version},context(`calculate-${index}`,"consultant-a"));await assert.rejects(()=>approveScopeRow(state.pool,{jobId:job.data.jobId,rowIds:[created.data.rowId],expectedReviewVersion:created.data.version,reviewerNote:"stale"},context(`stale-${index}`,"reviewer-a")),VersionConflictError);await approveScopeRow(state.pool,{jobId:job.data.jobId,rowIds:[created.data.rowId],expectedReviewVersion:calculated.data.version,reviewerNote:"Evidence independently checked"},context(`review-${index}`,"reviewer-a"));}await assert.rejects(()=>createReviewedCrpSnapshot(state.pool,{jobId:job.data.jobId,expectedJobVersion:2},context("stale-job","reviewer-a")),VersionConflictError);const frozen=await createReviewedCrpSnapshot(state.pool,{jobId:job.data.jobId,expectedJobVersion:1},context("full-snapshot","reviewer-a")),validated=await validateCrpReport(state.pool,{reviewedSnapshotId:frozen.data.snapshotId,manifestVersion:1},context("full-validate","reviewer-a")),published=await publishCrpReport(state.pool,{reportVersionId:validated.data.reportVersionId,expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:frozen.data.snapshotId},context("full-publish","reviewer-a"));assert.equal(published.data.status,"published");assert.equal(state.state().rows.length,3);assert.equal(state.state().audits.length,13);});
  it("freezes approved evidence, validates the shared manifest, and publishes that exact version",async()=>{const state=lifecyclePool(),snapshot=await createReviewedCrpSnapshot(state.pool,{jobId:"job-a",expectedJobVersion:5},context("snapshot")),validated=await validateCrpReport(state.pool,{reviewedSnapshotId:snapshot.data.snapshotId,manifestVersion:1},context("validate")),published=await publishCrpReport(state.pool,{reportVersionId:validated.data.reportVersionId,expectedStatus:"validated",manifestVersion:validated.data.manifestVersion,reviewedSnapshotId:snapshot.data.snapshotId},context("publish"));assert.equal(published.data.status,"published");assert.equal(published.data.reviewedSnapshotId,snapshot.data.snapshotId);assert.equal(state.state().report?.id,validated.data.reportVersionId);assert.deepEqual(state.state().audits,["reviewed_snapshot_created","report_validated","report_published"]);assert.deepEqual(state.state().outbox,["report.snapshot.created","report.validated","portal.report.published"]);});
  it("blocks snapshot creation while enabled evidence is not independently approved",async()=>{await assert.rejects(()=>createReviewedCrpSnapshot(lifecyclePool({incomplete:true}).pool,{jobId:"job-a",expectedJobVersion:5},context("incomplete")),(error:unknown)=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="QA_INCOMPLETE"));});
  it("blocks mismatched evidence and repeat publication",async()=>{const state=lifecyclePool(),snapshot=await createReviewedCrpSnapshot(state.pool,{jobId:"job-a",expectedJobVersion:5},context("snapshot-mismatch")),validated=await validateCrpReport(state.pool,{reviewedSnapshotId:snapshot.data.snapshotId,manifestVersion:1},context("validate-mismatch"));await assert.rejects(()=>publishCrpReport(state.pool,{reportVersionId:validated.data.reportVersionId,expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:"different-snapshot"},context("publish-mismatch")),CommandValidationError);await publishCrpReport(state.pool,{reportVersionId:validated.data.reportVersionId,expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:snapshot.data.snapshotId},context("publish-once"));await assert.rejects(()=>publishCrpReport(state.pool,{reportVersionId:validated.data.reportVersionId,expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:snapshot.data.snapshotId},context("publish-twice")),CommandValidationError);});
});
