import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { IsolatedStore, runIsolatedCommand, type TenantRecord } from "../src/index";
type JobRecord = TenantRecord & { title: string };
const context = { organisationId: "org-a", actorId: "user-a", principal: "staff" as const, idempotencyKey: "idem-1", correlationId: "corr-1" };
describe("isolated backend boundary", () => {
  it("prevents cross-tenant reads", async () => { const store = new IsolatedStore(); await store.transaction(async (unit) => { unit.repository<JobRecord>("org-a").insert({ id: "job-1", organisationId: "org-a", version: 1, title: "A" }); return null; }); await store.transaction(async (unit) => { assert.equal(unit.repository<JobRecord>("org-b").get("job-1"), undefined); return null; }); });
  it("rolls back records, audit and outbox on forced failure", async () => { const store = new IsolatedStore(); const result = await runIsolatedCommand(store, "job.stage.change", context, async (unit) => { unit.repository<JobRecord>("org-a").insert({ id: "job-1", organisationId: "org-a", version: 1, title: "Draft" }); throw new Error("forced failure"); }); assert.equal(result.state, "failed"); const state = store.snapshot(); assert.equal(state.records.size, 0); assert.equal(state.audits.length, 0); assert.equal(state.outbox.length, 0); });
  it("executes an idempotent command once and replays its outcome", async () => { const store = new IsolatedStore(); let calls = 0; const handler = async (unit: Parameters<Parameters<typeof store.transaction>[0]>[0]) => { calls += 1; unit.repository<JobRecord>("org-a").insert({ id: "job-1", organisationId: "org-a", version: 1, title: "Created" }); return { data: { jobNumber: "J000720" }, entityId: "job-1", outbox: { topic: "job.created", payload: { jobNumber: "J000720" } } }; }; const first = await runIsolatedCommand(store, "sales.opportunity.convert", context, handler); const second = await runIsolatedCommand(store, "sales.opportunity.convert", context, handler); assert.equal(first.state, "success"); assert.equal(second.state, "success"); if (second.state === "success") assert.equal(second.replayed, true); assert.equal(calls, 1); const state = store.snapshot(); assert.equal(state.audits.length, 1); assert.equal(state.outbox.length, 1); });
  it("denies commands without tenant context", async () => { const store = new IsolatedStore(); const result = await runIsolatedCommand(store, "report.publish", { ...context, organisationId: "" }, async () => ({ data: {}, entityId: "r1" })); assert.equal(result.state, "denied"); });
});
