import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { requiredMigrationInvariants, validateDatabaseBoundary } from "../src/index";
const here = dirname(fileURLToPath(import.meta.url));
const schema = readFileSync(resolve(here, "../migrations/0001_core_schema.sql"), "utf8");
const security = readFileSync(resolve(here, "../migrations/0002_rls_and_roles.sql"), "utf8");
const membership = readFileSync(resolve(here, "../migrations/0003_runtime_role_membership.sql"), "utf8");
const screenFields = readFileSync(resolve(here, "../migrations/0004_client_job_screen_fields.sql"), "utf8");
const staffRoles = readFileSync(resolve(here, "../migrations/0005_staff_roles.sql"), "utf8");
const staffAuth = readFileSync(resolve(here, "../migrations/0006_staff_authentication.sql"), "utf8");
const authMembership = readFileSync(resolve(here, "../migrations/0007_auth_membership_lookup.sql"), "utf8");
const scopeEvidence = readFileSync(resolve(here, "../migrations/0008_scope_row_evidence_metadata.sql"), "utf8");
const syntheticSeed = readFileSync(resolve(here, "../seeds/0001_synthetic_demo.sql"), "utf8");
const syntheticScopeSeed = readFileSync(resolve(here, "../seeds/0002_synthetic_crp_scope_rows.sql"), "utf8");
const factorMigration = readFileSync(resolve(here, "../migrations/0009_factor_resolution.sql"), "utf8");
const syntheticFactorSeed = readFileSync(resolve(here, "../seeds/0003_synthetic_factors.sql"), "utf8");
const reviewMigration = readFileSync(resolve(here, "../migrations/0010_scope_row_review_evidence.sql"), "utf8");
const snapshotMigration = readFileSync(resolve(here,"../migrations/0011_reviewed_crp_snapshots.sql"),"utf8");
const targetMigration = readFileSync(resolve(here,"../migrations/0012_emissions_targets.sql"),"utf8");
const siteMigration = readFileSync(resolve(here,"../migrations/0013_client_sites.sql"),"utf8");
const intensityMigration=readFileSync(resolve(here,"../migrations/0014_intensity_targets.sql"),"utf8");
const purchasedGoodsMigration=readFileSync(resolve(here,"../migrations/0015_purchased_goods_categories.sql"),"utf8");
const reportIntegrityMigration=readFileSync(resolve(here,"../migrations/0016_report_snapshot_integrity.sql"),"utf8");
const reportPublicationMigration=readFileSync(resolve(here,"../migrations/0017_one_published_report_per_job.sql"),"utf8");
const portalIdentityMigration=readFileSync(resolve(here,"../migrations/0018_portal_identity.sql"),"utf8");
describe("isolated Postgres migrations", () => {
  it("contains every required tenant and command invariant", () => { const sql = `${schema}\n${security}`; for (const invariant of requiredMigrationInvariants) assert.ok(sql.includes(invariant), invariant); });
  it("uses composite tenant foreign keys for client, job, scope and report links", () => { assert.match(schema, /FOREIGN KEY \(organisation_id, client_id\)/); assert.match(schema, /FOREIGN KEY \(organisation_id, job_id\)/); });
  it("makes audit history non-updateable and non-deleteable", () => { assert.match(security, /REVOKE DELETE ON nzi_console\.audit_events/); assert.match(security, /REVOKE UPDATE ON nzi_console\.audit_events/); });
  it("allocates the global job sequence inside the caller transaction", () => { assert.match(schema, /CREATE FUNCTION allocate_job_sequence/); assert.match(schema, /UPDATE job_number_counter SET last_sequence = last_sequence \+ 1/); assert.match(security, /GRANT EXECUTE ON FUNCTION nzi_console\.allocate_job_sequence/); });
  it("allows the pooler principal to assume the RLS-bound runtime roles", () => { assert.match(membership, /GRANT nzi_console_app, nzi_console_worker TO CURRENT_USER/); });
  it("adds constrained screen fields through a migration rather than request-time DDL", () => { assert.match(screenFields, /completeness_percent integer CHECK/); assert.match(screenFields, /progress_percent integer CHECK/); assert.match(screenFields, /detail_json jsonb/); });
  it("constrains memberships to the agreed staff roles", () => { for (const role of ["administrator", "consultant", "reviewer", "finance", "methodology-data-admin", "read-only"]) assert.ok(staffRoles.includes(`'${role}'`)); });
  it("isolates credentials behind a dedicated non-login database role", () => { assert.match(staffAuth, /CREATE ROLE nzi_console_auth .*NOBYPASSRLS NOLOGIN/); assert.match(staffAuth, /REVOKE ALL ON staff_credentials, staff_login_challenges, staff_sessions FROM PUBLIC/); assert.match(staffAuth, /GRANT SELECT, INSERT, UPDATE ON staff_credentials/); });
  it("lets only the authentication role inspect credential-backed membership state", () => { assert.match(authMembership, /FOR SELECT\s+TO nzi_console_auth/i); assert.match(authMembership, /EXISTS \(\s*SELECT 1\s+FROM nzi_console\.staff_credentials/i); assert.match(authMembership, /credential\.enabled = true/i); assert.doesNotMatch(authMembership, /FOR (?:INSERT|UPDATE|DELETE|ALL)/i); });
  it("adds mandatory evidence metadata to the canonical scope-row model", () => { for (const field of ["quality_tier", "provenance_json", "lineage_json", "factor_version", "enabled", "updated_at"]) assert.ok(scopeEvidence.includes(field)); assert.match(scopeEvidence, /quality_tier IN \('measured','estimated','spend-based','survey'\)/); });
  it("keeps the demonstration seed synthetic, idempotent and on the official number range", () => {
    assert.match(syntheticSeed, /Synthetic demonstration records only/);
    assert.match(syntheticSeed, /demo-nzi-console/);
    assert.match(syntheticSeed, /ON CONFLICT/);
    assert.match(syntheticSeed, /GREATEST\(last_sequence, 716\)/);
    const emailDomains = [...syntheticSeed.matchAll(/@[a-z0-9.-]+/gi)].map((match) => match[0]);
    assert.ok(emailDomains.length > 0);
    assert.ok(emailDomains.every((domain) => domain === "@synthetic.invalid"));
  });
  it("seeds canonical scope rows only for the synthetic demonstrator", () => { assert.match(syntheticScopeSeed, /Fictional activity data/); assert.match(syntheticScopeSeed, /job_scope_rows/); assert.match(syntheticScopeSeed, /demo-nzi-console/); assert.match(syntheticScopeSeed, /ON CONFLICT .* DO NOTHING/i); assert.doesNotMatch(syntheticScopeSeed, /crp_scope_entries/i); });
  it("owns factor resolution in tenant-isolated migrations", () => { assert.match(factorMigration,/emission_factor_datasets/); assert.match(factorMigration,/job_dataset_selections/); assert.match(factorMigration,/ENABLE ROW LEVEL SECURITY/); assert.match(factorMigration,/selection_source <> 'manual'/); });
  it("labels demonstration factors synthetic and never presents them as official values", () => { assert.match(syntheticFactorSeed,/Synthetic GB activity factors/); assert.match(syntheticFactorSeed,/Demonstration only/); assert.match(syntheticFactorSeed,/synthetic-gb-2026/); assert.doesNotMatch(syntheticFactorSeed,/UK Government GHG Conversion Factors/); });
  it("keeps row review history immutable and tenant isolated",()=>{assert.match(reviewMigration,/scope_row_review_history/);assert.match(reviewMigration,/reviewed_row_version/);assert.match(reviewMigration,/ENABLE ROW LEVEL SECURITY/);assert.match(reviewMigration,/REVOKE UPDATE,DELETE/);assert.match(reviewMigration,/scope_row_rejection_note/);});
  it("stores reviewed snapshots immutably with content identity",()=>{assert.match(snapshotMigration,/reviewed_crp_snapshots/);assert.match(snapshotMigration,/data_hash.*sha256/);assert.match(snapshotMigration,/UNIQUE \(organisation_id,job_id,data_hash\)/);assert.match(snapshotMigration,/REVOKE UPDATE,DELETE/);});
  it("keeps versioned emissions targets tenant isolated and chronologically constrained",()=>{assert.match(targetMigration,/job_emissions_targets/);assert.match(targetMigration,/baseline_year < interim_year AND interim_year < net_zero_year/);assert.match(targetMigration,/FORCE ROW LEVEL SECURITY/);assert.match(targetMigration,/PRIMARY KEY \(organisation_id,job_id\)/);});
  it("owns the client site dimension and tenant-safe scope-row link",()=>{assert.match(siteMigration,/client_sites/);assert.match(siteMigration,/scope_row_site_fk/);assert.match(siteMigration,/FOREIGN KEY \(organisation_id,site_id\)/);assert.match(siteMigration,/FORCE ROW LEVEL SECURITY/);});
  it("stores constrained tenant-isolated intensity targets",()=>{assert.match(intensityMigration,/job_intensity_targets/);assert.match(intensityMigration,/reporting_denominator>0/);assert.match(intensityMigration,/baseline_year<interim_year AND interim_year<net_zero_year/);assert.match(intensityMigration,/FORCE ROW LEVEL SECURITY/);});
  it("owns a tenant-isolated purchased-goods category dimension",()=>{assert.match(purchasedGoodsMigration,/purchased_goods_categories/);assert.match(purchasedGoodsMigration,/scope_row_purchased_goods_category_fk/);assert.match(purchasedGoodsMigration,/FORCE ROW LEVEL SECURITY/);});
  it("binds validated report versions to one reviewed snapshot and manifest",()=>{assert.match(reportIntegrityMigration,/report_version_snapshot_fk/);assert.match(reportIntegrityMigration,/report_version_validated_snapshot_unique/);assert.match(reportIntegrityMigration,/WHERE status IN \('validated','published'\)/);});
  it("allows only one current portal publication per job",()=>{assert.match(reportPublicationMigration,/report_version_one_published_per_job/);assert.match(reportPublicationMigration,/WHERE status='published'/);});
  it("separates portal identity and binds every job grant to that user's client",()=>{assert.match(portalIdentityMigration,/portal_users/);assert.match(portalIdentityMigration,/portal_credentials/);assert.match(portalIdentityMigration,/portal_sessions/);assert.match(portalIdentityMigration,/portal_access_grant_user_client_fk/);assert.match(portalIdentityMigration,/auth_portal_user_lookup/);});
  it("refuses missing, production, or unconfirmed database targets", () => { assert.throws(() => validateDatabaseBoundary({ appEnv: "staging" })); assert.throws(() => validateDatabaseBoundary({ appEnv: "production", boundaryToken: "isolated-non-production", isolatedDatabaseUrl: "postgresql://db/test" })); const url = validateDatabaseBoundary({ appEnv: "staging", boundaryToken: "isolated-non-production", isolatedDatabaseUrl: "postgresql://db/test" }); assert.equal(url.searchParams.get("application_name"), "nzi-console-isolated"); });
});
