import assert from "node:assert/strict";
import {it} from "node:test";
import {createPortalDataEntryRecord,decidePortalDataEntryReview,listPortalDataEntryBuckets,listPortalDataEntryRecords,listPortalDataEntryReviewQueue,parsePortalSpendDetail,PortalAccessValidationError,rolePermissions,setPortalDataEntryBucketGrant,submitPortalDataEntryRecord,type PortalPrincipal,type StaffPrincipal} from "../src/index";

const staff:StaffPrincipal={organisationId:"org-a",userId:"staff-a",sessionId:"staff-session",issuedAt:1,expiresAt:2,role:"administrator",permissions:rolePermissions.administrator};
const portal:PortalPrincipal={principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"portal-session",issuedAt:1,expiresAt:2,displayName:"Portal User",email:"portal@example.invalid"};

it("derives allowed units from compatible job factors and audits the typed bucket grant",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.1"}]};if(sql.includes("SELECT DISTINCT f.factor_id"))return{rows:[{factor_id:"factor-a",activity_unit:"GBP"}]};if(sql.includes("FROM nzi_console.client_sites"))return{rows:[{site_id:"site-a"}]};if(sql.includes("SELECT bucket_grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",entryKind:"spend",factorIds:["factor-a","factor-a"],siteIds:["site-a"]});assert.equal(result.entryKind,"spend");assert.deepEqual(result.factorIds,["factor-a"]);assert.deepEqual(result.units,["GBP"]);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_bucket_grants")));assert.ok(calls.some(call=>call.values?.includes("spend")));assert.ok(calls.some(call=>call.sql.includes("'portal.data_entry.bucket.grant'")));});

it("rejects specialised entry types outside their canonical scope",async()=>{const client={async query(sql:string){if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.7"}]};return{rows:[]}},release(){}};await assert.rejects(()=>setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",entryKind:"spend",factorIds:["factor-a"],siteIds:[]}),PortalAccessValidationError);});

it("returns only labelled buckets behind the current portal user, client, job and open window",async()=>{const client={async query(sql:string,values?:readonly unknown[]){if(!sql.includes("SELECT b.bucket_grant_id"))return{rows:[]};assert.ok(sql.includes("g.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3"));assert.ok(sql.includes("g.data_entry_starts_at<=$4 AND g.data_entry_expires_at>$4"));assert.ok(sql.includes("f.factor_id=ANY(b.allowed_factor_ids)"));assert.ok(sql.includes("s.site_id=ANY(b.allowed_site_ids)"));assert.deepEqual(values?.slice(0,3),["portal-a","client-a","job-a"]);assert.ok(sql.includes("c.category_id=ANY(b.allowed_pgs_category_ids)"));return{rows:[{bucket_grant_id:"bucket-a",scope_row_id:"row-a",scope:"3.1",source_label:"Purchased goods",entry_kind:"spend",factors:[{id:"factor-a",label:"Spend factor",unit:"GBP"}],sites:[{id:"site-a",name:"Head office"}],allowed_units:["GBP"],pgs_categories:[{id:"pgs-a",name:"Stationery"}]}]}},release(){}};const buckets=await listPortalDataEntryBuckets({connect:async()=>client} as never,portal,"job-a",new Date("2026-09-02T09:00:00Z"));assert.deepEqual(buckets,[{bucketGrantId:"bucket-a",scopeRowId:"row-a",scope:"3.1",sourceLabel:"Purchased goods",entryKind:"spend",factors:[{id:"factor-a",label:"Spend factor",unit:"GBP"}],sites:[{id:"site-a",name:"Head office"}],units:["GBP"],pgsCategories:[{id:"pgs-a",name:"Stationery"}]}]);});

it("creates a constrained draft without changing canonical emissions rows",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT b.allowed_factor_ids"))return{rows:[{allowed_factor_ids:["factor-a"],allowed_site_ids:["site-a"],allowed_units:["GBP"]}]};if(sql.includes("SELECT 1 FROM nzi_console.emission_factors"))return{rows:[{}]};return{rows:[]}},release(){}};const result=await createPortalDataEntryRecord({connect:async()=>client} as never,portal,"job-a",{bucketGrantId:"bucket-a",quantity:125,unit:"GBP",factorId:"factor-a",siteId:"site-a",note:"Client evidence"},new Date("2026-09-02T09:00:00Z"));assert.equal(result.status,"draft");assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_records")));assert.equal(calls.some(call=>/UPDATE nzi_console\.job_scope_rows/i.test(call.sql)),false);assert.ok(calls.some(call=>call.values?.includes("portal.data_entry.record.create")));});

it("submits an owned draft into a distinct pending staff review queue",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT version,status,bucket_grant_id"))return{rows:[{version:2,status:"draft",bucket_grant_id:"bucket-a"}]};if(sql.includes("SELECT b.allowed_factor_ids"))return{rows:[{allowed_factor_ids:["factor-a"],allowed_site_ids:[],allowed_units:["GBP"]}]};return{rows:[]}},release(){}};const result=await submitPortalDataEntryRecord({connect:async()=>client} as never,portal,"job-a","record-a",2,new Date("2026-09-02T09:00:00Z"));assert.equal(result.status,"submitted");assert.equal(result.version,3);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_review_queue")));assert.ok(calls.some(call=>call.values?.includes("portal.data_entry.record.submit")));assert.equal(calls.some(call=>/UPDATE nzi_console\.job_scope_rows/i.test(call.sql)),false);});

it("filters the staff review queue by job at the tenant-scoped query boundary",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});return{rows:[]}},release(){}};const result=await listPortalDataEntryReviewQueue({connect:async()=>client} as never,staff,"job-a");const queueQuery=calls.find(call=>call.sql.includes("FROM nzi_console.portal_data_entry_review_queue"));assert.ok(queueQuery?.sql.includes("($1::text IS NULL OR g.job_id=$1)"));assert.deepEqual(queueQuery?.values,["job-a"]);assert.deepEqual(result,[]);});

it("accepts a submission only as pending uncalculated canonical evidence",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FOR UPDATE OF q"))return{rows:[{record_id:"record-a",submitted_version:3,status:"pending",scope_row_id:"row-a",job_id:"job-a",quantity:"125",unit:"GBP",factor_id:"factor-a",site_id:null,portal_user_id:"portal-a"}]};if(sql.includes("SELECT f.dataset_id"))return{rows:[{dataset_id:"dataset-a",label:"Spend factor",version:"2026"}]};if(sql.includes("UPDATE nzi_console.job_scope_rows"))return{rows:[{version:8}]};return{rows:[]}},release(){}};const result=await decidePortalDataEntryReview({connect:async()=>client} as never,staff,{queueId:"queue-a",expectedSubmittedVersion:3,decision:"accept",note:""},new Date("2026-09-03T09:00:00Z"));assert.equal(result.scopeRowVersion,8);const promotion=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows"));assert.ok(promotion?.sql.includes("review_status='pending'"));assert.ok(promotion?.sql.includes("calculated_tco2e=NULL"));assert.ok(promotion?.sql.includes("monthly_activity_json=$4::jsonb"));assert.equal(promotion?.values?.[3],"[]");assert.equal(promotion?.values?.[11],null);assert.doesNotMatch(promotion?.sql??"",/review_status='approved'/);assert.ok(calls.some(call=>call.values?.includes("portal.data_entry.review.accepted")));});

it("requires a reason to reject and never changes the canonical row",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FOR UPDATE OF q"))return{rows:[{record_id:"record-a",submitted_version:3,status:"pending",scope_row_id:"row-a",job_id:"job-a",quantity:"125",unit:"GBP",factor_id:"factor-a",site_id:null,portal_user_id:"portal-a"}]};return{rows:[]}},release(){}};await assert.rejects(()=>decidePortalDataEntryReview({connect:async()=>client} as never,staff,{queueId:"queue-a",expectedSubmittedVersion:3,decision:"reject",note:""}),PortalAccessValidationError);const result=await decidePortalDataEntryReview({connect:async()=>client} as never,staff,{queueId:"queue-a",expectedSubmittedVersion:3,decision:"reject",note:"Invoice is missing."});assert.equal(result.status,"rejected");assert.equal(calls.some(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows")),false);assert.ok(calls.some(call=>call.values?.includes("portal.data_entry.review.rejected")));});

// --- B5: portal spend mirror ------------------------------------------------

it("validates the submitted spend detail against the authorised category set",()=>{
  assert.equal(parsePortalSpendDetail({netValue:1240,vatPercent:20,glCode:"7504",pgsCategoryId:"pgs-a",invoiceDate:"2025-03-14",monthlyActivity:[{month:"2025-03",quantity:1240}]},["pgs-a","pgs-b"]).ok,true);
  assert.equal(parsePortalSpendDetail({netValue:1240,pgsCategoryId:"pgs-x"},["pgs-a"]).ok,false); // category outside the allowed set
  assert.equal(parsePortalSpendDetail({netValue:-5,pgsCategoryId:"pgs-a"},["pgs-a"]).ok,false); // negative net
  assert.equal(parsePortalSpendDetail({netValue:10,vatPercent:150,pgsCategoryId:"pgs-a"},["pgs-a"]).ok,false); // VAT out of range
  assert.equal(parsePortalSpendDetail({netValue:10,pgsCategoryId:"pgs-a",monthlyActivity:[{month:"2025-13",quantity:1}]},["pgs-a"]).ok,false); // bad month
});

it("stores the controlled PG&S categories on a spend bucket grant and audits them",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.1"}]};if(sql.includes("SELECT DISTINCT f.factor_id"))return{rows:[{factor_id:"factor-a",activity_unit:"GBP"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c"))return{rows:[{category_id:"pgs-a"},{category_id:"pgs-b"}]};if(sql.includes("SELECT bucket_grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",entryKind:"spend",factorIds:["factor-a"],siteIds:[],pgsCategoryIds:["pgs-a","pgs-b"]});assert.deepEqual(result.pgsCategoryIds,["pgs-a","pgs-b"]);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_bucket_grants"));assert.ok(insert?.sql.includes("allowed_pgs_category_ids"));assert.ok(insert?.values?.some(value=>Array.isArray(value)&&value[0]==="pgs-a"));assert.ok(calls.some(call=>call.sql.includes("'pgsCategoryIds',$12")));});

it("rejects a bucket category that does not belong to the job client",async()=>{const client={async query(sql:string){if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.1"}]};if(sql.includes("SELECT DISTINCT f.factor_id"))return{rows:[{factor_id:"factor-a",activity_unit:"GBP"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c"))return{rows:[{category_id:"pgs-a"}]};return{rows:[]}},release(){}};await assert.rejects(()=>setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",entryKind:"spend",factorIds:["factor-a"],siteIds:[],pgsCategoryIds:["pgs-a","pgs-elsewhere"]}),PortalAccessValidationError);});

it("drops PG&S categories from a non-spend grant",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.7"}]};if(sql.includes("SELECT DISTINCT f.factor_id"))return{rows:[{factor_id:"factor-a",activity_unit:"miles"}]};if(sql.includes("SELECT bucket_grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",entryKind:"commuting",factorIds:["factor-a"],siteIds:[],pgsCategoryIds:["pgs-a"]});assert.deepEqual(result.pgsCategoryIds,[]);assert.equal(calls.some(call=>call.sql.includes("FROM nzi_console.purchased_goods_categories c")),false);});

it("creates a spend draft whose quantity is the net value and detail is persisted",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT b.allowed_factor_ids"))return{rows:[{allowed_factor_ids:["factor-a"],allowed_site_ids:[],allowed_units:["GBP"],entry_kind:"spend",allowed_pgs_category_ids:["pgs-a"]}]};if(sql.includes("SELECT 1 FROM nzi_console.emission_factors"))return{rows:[{}]};return{rows:[]}},release(){}};const result=await createPortalDataEntryRecord({connect:async()=>client} as never,portal,"job-a",{bucketGrantId:"bucket-a",quantity:0,unit:"GBP",factorId:"factor-a",siteId:null,note:"Q1 stationery",detail:{netValue:1240,vatPercent:20,glCode:"7504",pgsCategoryId:"pgs-a",invoiceDate:"2025-03-14",monthlyActivity:[]}},new Date("2026-09-02T09:00:00Z"));assert.equal(result.status,"draft");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_records"));assert.ok(insert?.sql.includes("entry_kind"));assert.ok(insert?.sql.includes("detail_json"));assert.equal(insert?.values?.[5],1240); // quantity forced to the net value
assert.ok(String(insert?.values?.[10]).includes("\"pgsCategoryId\":\"pgs-a\""));assert.equal(calls.some(call=>/UPDATE nzi_console\.job_scope_rows/i.test(call.sql)),false);});

it("rejects a spend draft whose category is outside the authorised set",async()=>{const client={async query(sql:string){if(sql.includes("SELECT b.allowed_factor_ids"))return{rows:[{allowed_factor_ids:["factor-a"],allowed_site_ids:[],allowed_units:["GBP"],entry_kind:"spend",allowed_pgs_category_ids:["pgs-a"]}]};if(sql.includes("SELECT 1 FROM nzi_console.emission_factors"))return{rows:[{}]};return{rows:[]}},release(){}};await assert.rejects(()=>createPortalDataEntryRecord({connect:async()=>client} as never,portal,"job-a",{bucketGrantId:"bucket-a",quantity:0,unit:"GBP",factorId:"factor-a",siteId:null,note:"",detail:{netValue:100,pgsCategoryId:"pgs-forbidden"}},new Date("2026-09-02T09:00:00Z")),PortalAccessValidationError);});

it("accepts a portal spend submission onto a spend-based Scope 3.1 row with the category and monthly split",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FOR UPDATE OF q"))return{rows:[{record_id:"record-a",submitted_version:3,status:"pending",scope_row_id:"row-a",job_id:"job-a",entry_kind:"spend",quantity:"1240",unit:"GBP",factor_id:"factor-a",site_id:null,portal_user_id:"portal-a",note:"Q1 stationery",detail_json:{kind:"spend",netValue:1240,vatPercent:20,glCode:"7504",pgsCategoryId:"pgs-a",invoiceDate:"2025-03-14",monthlyActivity:[{month:"2025-03",quantity:1240}]}}]};if(sql.includes("SELECT f.dataset_id"))return{rows:[{dataset_id:"dataset-a",label:"Spend factor",version:"2026"}]};if(sql.includes("SELECT name FROM nzi_console.purchased_goods_categories"))return{rows:[{name:"Stationery"}]};if(sql.includes("UPDATE nzi_console.job_scope_rows"))return{rows:[{version:9}]};return{rows:[]}},release(){}};const result=await decidePortalDataEntryReview({connect:async()=>client} as never,staff,{queueId:"queue-a",expectedSubmittedVersion:3,decision:"accept",note:""},new Date("2026-09-03T09:00:00Z"));assert.equal(result.scopeRowVersion,9);const promotion=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows"));assert.ok(promotion?.sql.includes("quality_tier=$12"));assert.ok(promotion?.sql.includes("purchased_goods_category_id=$13"));assert.equal(promotion?.values?.[11],"spend-based");assert.equal(promotion?.values?.[12],"pgs-a");assert.ok(String(promotion?.values?.[3]).includes("2025-03"));assert.ok(String(promotion?.values?.[13]).includes("\"spendDetail\""));assert.ok(String(promotion?.values?.[13]).includes("Stationery"));assert.ok(promotion?.sql.includes("review_status='pending'"));assert.ok(promotion?.sql.includes("calculated_tco2e=NULL"));});

it("binds the spend draft and its list to the acting portal user, client and job",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT b.allowed_factor_ids"))return{rows:[{allowed_factor_ids:["factor-a"],allowed_site_ids:[],allowed_units:["GBP"],entry_kind:"spend",allowed_pgs_category_ids:["pgs-a"]}]};if(sql.includes("SELECT 1 FROM nzi_console.emission_factors"))return{rows:[{}]};return{rows:[]}},release(){}};await createPortalDataEntryRecord({connect:async()=>client} as never,portal,"job-a",{bucketGrantId:"bucket-a",quantity:0,unit:"GBP",factorId:"factor-a",siteId:null,note:"",detail:{netValue:50,pgsCategoryId:"pgs-a"}},new Date("2026-09-02T09:00:00Z"));const boundary=calls.find(call=>call.sql.includes("SELECT b.allowed_factor_ids"));assert.deepEqual(boundary?.values?.slice(0,4),["bucket-a","portal-a","client-a","job-a"]);await listPortalDataEntryRecords({connect:async()=>client} as never,portal,"job-a",new Date("2026-09-02T09:00:00Z"));const list=calls.find(call=>call.sql.includes("FROM nzi_console.portal_data_entry_records r JOIN"));assert.ok(list?.sql.includes("r.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3"));assert.deepEqual(list?.values?.slice(0,3),["portal-a","client-a","job-a"]);});

it("blocks a portal spend accept when the submitted category is no longer configured",async()=>{const client={async query(sql:string){if(sql.includes("FOR UPDATE OF q"))return{rows:[{record_id:"record-a",submitted_version:3,status:"pending",scope_row_id:"row-a",job_id:"job-a",entry_kind:"spend",quantity:"1240",unit:"GBP",factor_id:"factor-a",site_id:null,portal_user_id:"portal-a",note:"",detail_json:{kind:"spend",netValue:1240,vatPercent:null,glCode:null,pgsCategoryId:"pgs-gone",invoiceDate:null,monthlyActivity:[]}}]};if(sql.includes("SELECT f.dataset_id"))return{rows:[{dataset_id:"dataset-a",label:"Spend factor",version:"2026"}]};if(sql.includes("SELECT name FROM nzi_console.purchased_goods_categories"))return{rows:[]};return{rows:[]}},release(){}};await assert.rejects(()=>decidePortalDataEntryReview({connect:async()=>client} as never,staff,{queueId:"queue-a",expectedSubmittedVersion:3,decision:"accept",note:""}),PortalAccessValidationError);});
