import assert from "node:assert/strict";
import {it} from "node:test";
import {addGrantedReportComment,addStaffReportComment,approveGrantedPublishedReport,listStaffReportThreads} from "../src/index";

it("binds portal approval to the granted current report and audits the portal principal",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT r.report_version_id"))return{rows:[{report_version_id:"report-a"}]};if(sql.includes("SELECT approval_id"))return{rows:[]};return{rows:[]}},release(){}};const approval=await approveGrantedPublishedReport({connect:async()=>client} as never,{principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"session-a",issuedAt:1,expiresAt:2},{jobId:"job-a",reportVersionId:"report-a"},new Date("2026-08-25T15:00:00Z"));assert.equal(approval.reportVersionId,"report-a");assert.equal(approval.approvedAt,"2026-08-25T15:00:00.000Z");assert.ok(calls.some(call=>call.sql.includes("r.status='published'")&&call.sql.includes("g.revoked_at IS NULL")));assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_report_approvals")));assert.ok(calls.some(call=>call.sql.includes("'portal','portal.report.approve'")));});

it("returns an existing approval without duplicating its immutable record",async()=>{const calls:string[]=[],client={async query(sql:string){calls.push(sql);if(sql.includes("SELECT r.report_version_id"))return{rows:[{report_version_id:"report-a"}]};if(sql.includes("SELECT approval_id"))return{rows:[{approval_id:"approval-a",approved_at:"2026-08-25T14:00:00Z",statement_version:1}]};return{rows:[]}},release(){}};const approval=await approveGrantedPublishedReport({connect:async()=>client} as never,{principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"session-a",issuedAt:1,expiresAt:2},{jobId:"job-a",reportVersionId:"report-a"});assert.equal(approval.approvalId,"approval-a");assert.equal(calls.some(sql=>sql.includes("INSERT INTO nzi_console.portal_report_approvals")),false);});

it("creates an immutable version-bound portal comment and audit event",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT r.report_version_id"))return{rows:[{report_version_id:"report-a"}]};return{rows:[]}},release(){}};const comment=await addGrantedReportComment({connect:async()=>client} as never,{principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"session-a",issuedAt:1,expiresAt:2,displayName:"Synthetic Client User"},{jobId:"job-a",reportVersionId:"report-a",body:"  Please explain the Scope 3 change.  "},new Date("2026-08-25T16:00:00Z"));assert.equal(comment.body,"Please explain the Scope 3 change.");assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_report_comments")));assert.ok(calls.some(call=>call.sql.includes("portal.report.comment.create")));});

it("lets a report reviewer reply as an audited staff principal",async()=>{const calls:string[]=[],client={async query(sql:string){calls.push(sql);if(sql.includes("SELECT j.client_id"))return{rows:[{client_id:"client-a"}]};return{rows:[]}},release(){}};const comment=await addStaffReportComment({connect:async()=>client} as never,{organisationId:"org-a",userId:"reviewer-a",sessionId:"session-a",issuedAt:1,expiresAt:2,role:"reviewer",permissions:["reports.publish"]},{jobId:"job-a",reportVersionId:"report-a",body:"Thank you. We have added an explanation."},new Date("2026-08-25T17:00:00Z"));assert.equal(comment.authorPrincipal,"staff");assert.equal(comment.authorDisplayName,"NZI reviewer");assert.ok(calls.some(sql=>sql.includes("portal.report.comment.reply")));});

it("returns approval evidence and flags a client's latest message for staff action",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.report_versions r"))return{rows:[{report_version_id:"report-a",job_id:"job-a",job_number:"J000612",client_name:"Synthetic Client",reporting_year:2026,approvals:[{approvalId:"approval-a",portalUserId:"portal-a",displayName:"Synthetic Approver",approvedAt:"2026-08-25T18:00:00Z"}],comments:[{commentId:"comment-a",reportVersionId:"report-a",parentCommentId:null,authorPrincipal:"portal",authorDisplayName:"Synthetic Approver",body:"One question",createdAt:"2026-08-25T18:01:00Z"}]}]};return{rows:[]}},release(){}};const threads=await listStaffReportThreads({connect:async()=>client} as never,{organisationId:"org-a",userId:"reviewer-a",sessionId:"session-a",issuedAt:1,expiresAt:2,role:"reviewer",permissions:["reports.publish"]});assert.equal(threads[0]?.approvals[0]?.displayName,"Synthetic Approver");assert.equal(threads[0]?.awaitingApproval,false);assert.equal(threads[0]?.needsReply,true);});
