import assert from "node:assert/strict";
import {it} from "node:test";
import type {PublishedCrpReportReadModel} from "@nzi/contracts";
import {portalDeliverableHeaders,portalDeliverableKinds,portalDeliverableRecords,portalPublicationEvidence} from "../src/index";

const report={reportVersionId:"report-v4",manifestVersion:1,publishedAt:"2026-09-04T10:00:00.000Z",dataHash:"a".repeat(64),snapshot:{id:"snapshot-v4",jobId:"job-a",jobNumber:"J000900",client:"Example Client",reportingYear:2025,version:4,jobVersion:8,createdAt:"2026-09-03T10:00:00.000Z",createdBy:"reviewer-a",dataHash:"a".repeat(64),target:null,intensityTarget:null,annualComparison:[],sections:[],gapResolutions:[],measurements:[]}} as PublishedCrpReportReadModel;

it("exposes exactly three PDF records bound to one immutable publication",()=>{const documents=portalDeliverableRecords(report);assert.deepEqual(documents.map(item=>item.kind),["report","certificate","methodology"]);assert.equal(new Set(documents.map(item=>item.documentId)).size,3);for(const document of documents){assert.equal(document.reportVersionId,report.reportVersionId);assert.equal(document.snapshotId,report.snapshot.id);assert.equal(document.evidenceHash,report.dataHash);assert.equal(document.contentType,"application/pdf");assert.ok(document.filename.endsWith(`-${report.reportVersionId}.pdf`));}});
it("accepts only supported portal deliverable routes",()=>{for(const kind of ["report","certificate","methodology"])assert.equal(portalDeliverableKinds(kind),true);for(const kind of ["","invoice","../report"])assert.equal(portalDeliverableKinds(kind),false);});
it("returns verifiable PDF identity without allowing shared caching or content sniffing",()=>{const record=portalDeliverableRecords(report)[0]!,headers=portalDeliverableHeaders(record,Buffer.from("%PDF-1.4\nimmutable"));assert.equal(headers["Content-Type"],"application/pdf");assert.equal(headers["X-Content-Type-Options"],"nosniff");assert.equal(headers["X-NZI-Document-Id"],record.documentId);assert.equal(headers["X-NZI-Report-Version"],report.reportVersionId);assert.equal(headers["X-NZI-Snapshot-Id"],report.snapshot.id);assert.equal(headers["X-NZI-Evidence-Hash"],report.dataHash);assert.match(headers["Content-Digest"],/^sha-256=:[A-Za-z0-9+/]+={0,2}:$/);assert.equal(headers.ETag,`"sha256-${headers["Content-Digest"].slice(9,-1)}"`);assert.equal(headers["Cache-Control"],"private, no-store");});
it("projects screen, print and download evidence from the same reviewed measurements",()=>{const populated={...report,snapshot:{...report.snapshot,measurements:[{rowId:"row-1",scope:"1" as const,scopeCode:"1",sourceLabel:"Fleet fuel",siteId:null,siteLabel:null,purchasedGoodsCategoryId:null,purchasedGoodsCategoryLabel:null,tco2e:12.5,factorSet:"Factor A v1",qualityTier:"measured" as const,reviewedBy:"reviewer"},{rowId:"row-2",scope:"3" as const,scopeCode:"3.1",sourceLabel:"Purchased goods",siteId:null,siteLabel:null,purchasedGoodsCategoryId:null,purchasedGoodsCategoryLabel:null,tco2e:7.25,factorSet:"Factor B v2",qualityTier:"spend-based" as const,reviewedBy:"reviewer"}]}} as PublishedCrpReportReadModel,evidence=portalPublicationEvidence(populated);assert.deepEqual(evidence.scopeTotals,[{scope:"1",tco2e:12.5},{scope:"2",tco2e:0},{scope:"3",tco2e:7.25}]);assert.deepEqual(evidence.measurements.map(item=>[item.rowId,item.scopeCode,item.sourceLabel,item.tco2e,item.factorSet]),[["row-1","1","Fleet fuel",12.5,"Factor A v1"],["row-2","3.1","Purchased goods",7.25,"Factor B v2"]]);assert.equal(evidence.reportVersionId,populated.reportVersionId);assert.equal(evidence.snapshotId,populated.snapshot.id);assert.equal(evidence.evidenceHash,populated.dataHash);});
it("refuses to project contradictory publication and snapshot hashes",()=>{assert.throws(()=>portalPublicationEvidence({...report,dataHash:"b".repeat(64)}),/hashes do not match/);});
