import assert from "node:assert/strict";
import {it} from "node:test";
import {AuthorizationError,listPortalAccess,rolePermissions,setPortalJobAccess,type StaffPrincipal} from "../src/index";

const principal=(role:StaffPrincipal["role"]):StaffPrincipal=>({organisationId:"org-a",userId:"staff-a",sessionId:"session-a",issuedAt:1,expiresAt:2,role,permissions:rolePermissions[role]});

it("lists portal users with only their client's jobs and current grant state",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.portal_users u"))return{rows:[{portal_user_id:"portal-a",client_id:"client-a",client_name:"Synthetic Client",email_normalized:"person@synthetic.invalid",display_name:"Portal Person",status:"active",jobs:[{jobId:"job-a",jobNumber:"J000612",title:"CRP",reportingYear:2026,granted:true,grantId:"grant-a"}]}]};return{rows:[]}},release(){}};const users=await listPortalAccess({connect:async()=>client} as never,principal("reviewer"));assert.equal(users[0]?.jobs[0]?.jobNumber,"J000612");assert.equal(users[0]?.jobs[0]?.granted,true);});

it("grants matching client job access and records the staff action",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT u.client_id"))return{rows:[{client_id:"client-a"}]};if(sql.includes("SELECT grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalJobAccess({connect:async()=>client} as never,principal("administrator"),{portalUserId:"portal-a",jobId:"job-a",granted:true});assert.equal(result.granted,true);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_access_grants")));assert.ok(calls.some(call=>call.values?.includes("portal.access.grant")));});

it("revokes the final grant and active portal sessions atomically",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT u.client_id"))return{rows:[{client_id:"client-a"}]};if(sql.includes("SELECT grant_id"))return{rows:[{grant_id:"grant-a",revoked_at:null}]};if(sql.includes("SELECT 1 FROM nzi_console.portal_access_grants"))return{rows:[]};return{rows:[]}},release(){}};await setPortalJobAccess({connect:async()=>client} as never,principal("reviewer"),{portalUserId:"portal-a",jobId:"job-a",granted:false},new Date("2026-08-25T22:00:00Z"));assert.ok(calls.some(call=>call.sql.includes("UPDATE nzi_console.portal_access_grants")));assert.ok(calls.some(call=>call.sql.includes("UPDATE nzi_console.portal_sessions")));assert.ok(calls.some(call=>call.values?.includes("portal.access.revoke")));});

it("denies portal access administration to unauthorised staff",async()=>{await assert.rejects(()=>listPortalAccess({} as never,principal("consultant")),AuthorizationError);});
