import assert from "node:assert/strict";
import {it} from "node:test";
import {listPortalDataEntryBuckets,rolePermissions,setPortalDataEntryBucketGrant,type PortalPrincipal,type StaffPrincipal} from "../src/index";

const staff:StaffPrincipal={organisationId:"org-a",userId:"staff-a",sessionId:"staff-session",issuedAt:1,expiresAt:2,role:"administrator",permissions:rolePermissions.administrator};
const portal:PortalPrincipal={principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"portal-session",issuedAt:1,expiresAt:2,displayName:"Portal User",email:"portal@example.invalid"};

it("derives allowed units from compatible job factors and audits the bucket grant",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT g.grant_id,r.scope"))return{rows:[{grant_id:"grant-a",scope:"3.1"}]};if(sql.includes("SELECT DISTINCT f.factor_id"))return{rows:[{factor_id:"factor-a",activity_unit:"GBP"}]};if(sql.includes("FROM nzi_console.client_sites"))return{rows:[{site_id:"site-a"}]};if(sql.includes("SELECT bucket_grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalDataEntryBucketGrant({connect:async()=>client} as never,staff,{portalUserId:"portal-a",jobId:"job-a",scopeRowId:"row-a",factorIds:["factor-a","factor-a"],siteIds:["site-a"]});assert.deepEqual(result.factorIds,["factor-a"]);assert.deepEqual(result.units,["GBP"]);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_data_entry_bucket_grants")));assert.ok(calls.some(call=>call.sql.includes("'portal.data_entry.bucket.grant'")));});

it("returns only labelled buckets behind the current portal user, client, job and open window",async()=>{const client={async query(sql:string,values?:readonly unknown[]){if(!sql.includes("SELECT b.bucket_grant_id"))return{rows:[]};assert.ok(sql.includes("g.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3"));assert.ok(sql.includes("g.data_entry_starts_at<=$4 AND g.data_entry_expires_at>$4"));assert.ok(sql.includes("f.factor_id=ANY(b.allowed_factor_ids)"));assert.ok(sql.includes("s.site_id=ANY(b.allowed_site_ids)"));assert.deepEqual(values?.slice(0,3),["portal-a","client-a","job-a"]);return{rows:[{bucket_grant_id:"bucket-a",scope_row_id:"row-a",scope:"3.1",source_label:"Purchased goods",factors:[{id:"factor-a",label:"Spend factor",unit:"GBP"}],sites:[{id:"site-a",name:"Head office"}],allowed_units:["GBP"]}]}},release(){}};const buckets=await listPortalDataEntryBuckets({connect:async()=>client} as never,portal,"job-a",new Date("2026-09-02T09:00:00Z"));assert.deepEqual(buckets,[{bucketGrantId:"bucket-a",scopeRowId:"row-a",scope:"3.1",sourceLabel:"Purchased goods",factors:[{id:"factor-a",label:"Spend factor",unit:"GBP"}],sites:[{id:"site-a",name:"Head office"}],units:["GBP"]}]);});
