import assert from "node:assert/strict";
import {it} from "node:test";
import {completePortalInvitationSetup,createPortalInvitation,encryptTotpSecret,PortalInvitationError,rolePermissions,startPortalInvitationSetup,totpCode,type StaffPrincipal} from "../src/index";

const admin:StaffPrincipal={organisationId:"org-a",userId:"admin-a",sessionId:"session-a",issuedAt:1,expiresAt:2,role:"administrator",permissions:rolePermissions.administrator};
const encryptionKey=Buffer.alloc(32,7).toString("base64"),now=new Date("2026-08-26T09:00:00Z");

it("creates an expiring invitation without creating or returning a password",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.clients"))return{rows:[{}]};if(sql.includes("FROM nzi_console.portal_users WHERE"))return{rows:[]};return{rows:[]}},release(){}};const invitation=await createPortalInvitation({connect:async()=>client} as never,admin,{clientId:"client-a",email:" PERSON@Example.com ",displayName:"Portal Person"},now);assert.equal(invitation.expiresAt,"2026-08-29T09:00:00.000Z");assert.ok(invitation.token.length>=40);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_invitations")&&!call.values?.includes(invitation.token)));assert.ok(calls.some(call=>call.sql.includes("'portal.invitation.create'")));});

it("stores disabled credentials while MFA enrolment is incomplete",async()=>{const calls:string[]=[],client={async query(sql:string){calls.push(sql);if(sql.includes("SELECT i.organisation_id"))return{rows:[{organisation_id:"org-a",invitation_id:"invite-a",portal_user_id:"portal-a",email_normalized:"person@example.com",display_name:"Portal Person",expires_at:"2026-08-27T09:00:00Z",consumed_at:null}]};return{rows:[]}},release(){}};const setup=await startPortalInvitationSetup({connect:async()=>client} as never,{token:"invite-token",password:"a-secure-new-password"},encryptionKey,now);assert.equal(setup.email,"person@example.com");assert.ok(setup.totpSecret.length>=32);assert.ok(calls.some(sql=>sql.includes("enabled) VALUES")&&sql.includes("false")));});

it("activates the portal account only after a valid authenticator code",async()=>{const secret="JBSWY3DPEHPK3PXP",encrypted=encryptTotpSecret(secret,encryptionKey),calls:string[]=[],client={async query(sql:string){calls.push(sql);if(sql.includes("SELECT i.organisation_id"))return{rows:[{organisation_id:"org-a",invitation_id:"invite-a",portal_user_id:"portal-a",expires_at:"2026-08-27T09:00:00Z",consumed_at:null,setup_started_at:"2026-08-26T08:59:00Z",totp_ciphertext:encrypted.ciphertext,totp_iv:encrypted.iv,totp_tag:encrypted.tag}]};return{rows:[]}},release(){}};const result=await completePortalInvitationSetup({connect:async()=>client} as never,{token:"invite-token",code:totpCode(secret,now.getTime())},encryptionKey,now);assert.equal(result.activated,true);assert.ok(calls.some(sql=>sql.includes("portal_credentials SET enabled=true")));assert.ok(calls.some(sql=>sql.includes("portal_users SET status='active'")));assert.ok(calls.some(sql=>sql.includes("portal_invitations SET consumed_at")));});
it("does not activate or consume an invitation after an invalid authenticator code",async()=>{const encrypted=encryptTotpSecret("JBSWY3DPEHPK3PXP",encryptionKey),calls:string[]=[],client={async query(sql:string){calls.push(sql);if(sql.includes("SELECT i.organisation_id"))return{rows:[{organisation_id:"org-a",invitation_id:"invite-a",portal_user_id:"portal-a",expires_at:"2026-08-27T09:00:00Z",consumed_at:null,setup_started_at:"2026-08-26T08:59:00Z",totp_ciphertext:encrypted.ciphertext,totp_iv:encrypted.iv,totp_tag:encrypted.tag}]};return{rows:[]}},release(){}};await assert.rejects(()=>completePortalInvitationSetup({connect:async()=>client} as never,{token:"invite-token",code:"000000"},encryptionKey,now),PortalInvitationError);assert.equal(calls.some(sql=>sql.includes("enabled=true")),false);assert.equal(calls.some(sql=>sql.includes("consumed_at=$3")),false);});
