import assert from "node:assert/strict";
import {it} from "node:test";
import {AuthorizationError,getPortalDataEntryAccess,listPortalAccess,PortalAccessValidationError,rolePermissions,setPortalDataEntryWindow,setPortalJobAccess,setPortalUserEnabled,type PortalPrincipal,type StaffPrincipal} from "../src/index";

const principal=(role:StaffPrincipal["role"]):StaffPrincipal=>({organisationId:"org-a",userId:"staff-a",sessionId:"session-a",issuedAt:1,expiresAt:2,role,permissions:rolePermissions[role]});

it("lists portal users with only their client's jobs and current grant state",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.portal_users u"))return{rows:[{portal_user_id:"portal-a",client_id:"client-a",client_name:"Synthetic Client",email_normalized:"person@synthetic.invalid",display_name:"Portal Person",status:"active",jobs:[{jobId:"job-a",jobNumber:"J000612",title:"CRP",reportingYear:2026,granted:true,grantId:"grant-a"}]}]};return{rows:[]}},release(){}};const users=await listPortalAccess({connect:async()=>client} as never,principal("reviewer"));assert.equal(users[0]?.jobs[0]?.jobNumber,"J000612");assert.equal(users[0]?.jobs[0]?.granted,true);});

it("grants matching client job access and records the staff action",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT u.client_id"))return{rows:[{client_id:"client-a"}]};if(sql.includes("SELECT grant_id"))return{rows:[]};return{rows:[]}},release(){}};const result=await setPortalJobAccess({connect:async()=>client} as never,principal("administrator"),{portalUserId:"portal-a",jobId:"job-a",granted:true});assert.equal(result.granted,true);assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.portal_access_grants")));assert.ok(calls.some(call=>call.values?.includes("portal.access.grant")));});

it("revokes the final grant and active portal sessions atomically",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT u.client_id"))return{rows:[{client_id:"client-a"}]};if(sql.includes("SELECT grant_id"))return{rows:[{grant_id:"grant-a",revoked_at:null}]};if(sql.includes("SELECT 1 FROM nzi_console.portal_access_grants"))return{rows:[]};return{rows:[]}},release(){}};await setPortalJobAccess({connect:async()=>client} as never,principal("reviewer"),{portalUserId:"portal-a",jobId:"job-a",granted:false},new Date("2026-08-25T22:00:00Z"));assert.ok(calls.some(call=>call.sql.includes("UPDATE nzi_console.portal_access_grants")));assert.ok(calls.some(call=>call.sql.includes("revoke_portal_user_sessions")));assert.ok(calls.some(call=>call.values?.includes("portal.access.revoke")));});

it("disables a portal account, revokes sessions and audits the action",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT status"))return{rows:[{status:"active"}]};return{rows:[]}},release(){}};const result=await setPortalUserEnabled({connect:async()=>client} as never,principal("administrator"),{portalUserId:"portal-a",enabled:false});assert.equal(result.enabled,false);assert.ok(calls.some(call=>call.sql.includes("revoke_portal_user_sessions")));assert.ok(calls.some(call=>call.values?.includes("portal.user.disable")));});

it("denies portal access administration to unauthorised staff",async()=>{await assert.rejects(()=>listPortalAccess({} as never,principal("consultant")),AuthorizationError);});

it("sets an ordered data-entry window only on an active matching grant and audits it",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("SELECT g.grant_id"))return{rows:[{grant_id:"grant-a"}]};return{rows:[]}},release(){}};const result=await setPortalDataEntryWindow({connect:async()=>client} as never,principal("administrator"),{portalUserId:"portal-a",jobId:"job-a",startsAt:"2026-09-01T09:00:00Z",expiresAt:"2026-09-30T17:00:00Z"});assert.equal(result.startsAt,"2026-09-01T09:00:00.000Z");assert.equal(result.expiresAt,"2026-09-30T17:00:00.000Z");assert.ok(calls.some(call=>call.sql.includes("SET data_entry_starts_at=$2,data_entry_expires_at=$3")));assert.ok(calls.some(call=>call.sql.includes("'portal.data_entry.window.set'")));});

it("rejects missing, incomplete, and reversed data-entry windows",async()=>{const pool={} as never;await assert.rejects(()=>setPortalDataEntryWindow(pool,principal("administrator"),{portalUserId:"portal-a",jobId:"job-a",startsAt:"2026-09-01T09:00:00Z",expiresAt:null}),PortalAccessValidationError);await assert.rejects(()=>setPortalDataEntryWindow(pool,principal("administrator"),{portalUserId:"portal-a",jobId:"job-a",startsAt:"2026-10-01T09:00:00Z",expiresAt:"2026-09-01T09:00:00Z"}),PortalAccessValidationError);});

it("returns only a current or scheduled client-bound data-entry window",async()=>{const portal:PortalPrincipal={principal:"portal",organisationId:"org-a",userId:"portal-a",clientId:"client-a",sessionId:"session-a",issuedAt:1,expiresAt:2,displayName:"Portal User",email:"portal@example.invalid"},client={async query(sql:string,values?:readonly unknown[]){if(!sql.includes("SELECT g.data_entry_starts_at"))return{rows:[]};assert.ok(sql.includes("g.portal_user_id=$1 AND g.client_id=$2 AND g.job_id=$3"));assert.deepEqual(values?.slice(0,3),["portal-a","client-a","job-a"]);return{rows:[{data_entry_starts_at:"2026-09-01T09:00:00Z",data_entry_expires_at:"2026-09-30T17:00:00Z"}]}},release(){}};const scheduled=await getPortalDataEntryAccess({connect:async()=>client} as never,portal,"job-a",new Date("2026-08-30T09:00:00Z"));assert.equal(scheduled?.state,"scheduled");const open=await getPortalDataEntryAccess({connect:async()=>client} as never,portal,"job-a",new Date("2026-09-02T09:00:00Z"));assert.equal(open?.state,"open");});
