import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {getCrpReportVersion, getCurrentPublishedCrpReport,getGrantedPublishedCrpReport,listAuditEvents,listClients,listDatasetRegistry,listGrantedPortalJobs,listJobEmissionSourceRegister,listJobFactorOptions,listReportVersionRegister,listStaffRoleGovernance, listJobs, listScopeRows, withTenantRead, type Queryable } from "../src/index";

describe("isolated Postgres adapter", () => {
  it("maps canonical client and family-job rows into their screen contracts", async () => {
    const db = {
      query: async (sql: string) => ({ rows: sql.includes("FROM nzi_console.clients")
        ? [{ client_id: "client-a", name: "Synthetic Client", status: "active", sector: "Services", location: "London, UK", owner_name: "A. Owner", member_since: 2026, latest_footprint_tco2e: "1418", yoy_percent: "-7.4", completeness_percent: 92, next_report_due_label: "31 Mar 2027", contact_name: "Synthetic Team", contact_role: "ESG", contact_email: "team@synthetic.invalid", open_jobs: "1", jobs: [{ number: "J000612", year: 2026, status: "Data entry" }], sites: [{ id: "site-a", name: "London HQ" }] }]
        : [{ job_id: "job-a", client_id: "client-a", client_name: "Synthetic Client", sequence: 612, job_number: "J000612", job_family: "crp", title: "Synthetic CRP", reporting_year: 2026, status: "open", workflow_stage: "Data entry", owner_name: "A. Owner", start_date: "2026-01-01", due_date: "2026-03-31", quote_id: null, progress_percent: 66, detail_json: { kind: "crp", reportingPeriod: "2026", includedScopes: ["1", "2", "3"], reviewedRows: 10, totalRows: 15 } }] }),
    } as Queryable;
    assert.equal((await listClients(db))[0]?.latestFootprint, "1,418 tCO₂e");
    assert.deepEqual((await listClients(db))[0]?.sites, [{ id: "site-a", name: "London HQ" }]);
    assert.equal((await listJobs(db))[0]?.header.number, "J000612");
  });

  it("sets the runtime role and tenant context inside a read-only transaction", async () => {
    const calls: Array<{ sql: string; values?: readonly unknown[] }> = [];
    const client = { query: async (sql: string, values?: readonly unknown[]) => { calls.push({ sql, values }); return { rows: [] }; }, release: () => undefined };
    const pool = { connect: async () => client };
    await withTenantRead(pool as never, "org-a", async () => "ok");
    assert.deepEqual(calls.map((call) => call.sql), ["BEGIN READ ONLY", "SET LOCAL ROLE nzi_console_app", "SELECT set_config('app.organisation_id', $1, true)", "COMMIT"]);
    assert.deepEqual(calls[2]?.values, ["org-a"]);
  });

  it("maps canonical scope-row evidence without treating missing calculation as zero", async () => {
    const db = { query: async () => ({ rows: [{ scope_row_id: "row-a", job_id: "job-a", scope: "3.1", source_label: "Purchased goods", quantity: "1250.5", unit: "GBP", dataset_id: "dataset-a", factor_id: "factor-a", factor_version: "2026 v1", factor_label: "Synthetic factor", quality_tier: "spend-based", calculated_tco2e: null, override_tco2e: null, override_reason: null, review_status: "pending", version: 3, enabled: true, provenance_json: { source: "synthetic" }, lineage_json: [{ title: "Captured", detail: "Synthetic" }] }] }) } as Queryable;
    const row = (await listScopeRows(db, "job-a"))[0]!;
    assert.equal(row.quantity, 1250.5); assert.equal(row.calculatedTco2e, null); assert.equal(row.qualityTier, "spend-based"); assert.equal(row.version, 3);
  });

  it("maps governed datasets, provenance usage and explicit selection warnings",async()=>{let call=0;const db={query:async()=>({rows:call++===0?[{dataset_id:"dataset-a",name:"Published factors",version:"2026",valid_from:"2026-01-01",valid_to:"2026-12-31",country_code:"GB",status:"active",source_name:"Publisher",licence:"OGL",synthetic:false,factor_count:"2",job_count:"1",scopes:["1","2"],spend_count:"0",activity_count:"2"}]:[{dataset_id:"dataset-a",job_number:"J000612",warning:"Manual geography exception."}]})} as Queryable,result=await listDatasetRegistry(db);assert.equal(result.datasets[0]?.factorCount,2);assert.deepEqual(result.datasets[0]?.scopes,["1","2"]);assert.equal(result.issues[0]?.jobNumber,"J000612");});

  it("lists eligible client factors alongside selected dataset factors",async()=>{let sql="";const db={query:async(statement:string)=>{sql=statement;return{rows:[{dataset_id:null,dataset_name:"Client factors",dataset_version:"v2",factor_id:"cf-a",label:"Supplier EPD",activity_unit:"unit",kgco2e_per_unit:"12.4",scopes:["3.1"],selection_source:"client",factor_source:"client",client_factor_id:"cf-a",evidence_hash:"sha256:epd",synthetic:false,warnings_json:[]}]}}} as Queryable;const factors=await listJobFactorOptions(db,"job-a");assert.equal(factors[0]?.factorSource,"client");assert.deepEqual(factors[0]?.scopes,["3.1"]);assert.equal(factors[0]?.clientFactorId,"cf-a");assert.equal(factors[0]?.evidenceHash,"sha256:epd");assert.ok(sql.includes("cf.job_id IS NULL OR cf.job_id=j.job_id"));
    // UNION ALL branches must agree on column types: the dataset branch's numeric factor value is cast to text to match the client branch (Postgres rejects numeric∪text).
    assert.ok(sql.includes("f.kgco2e_per_unit::text"),"dataset factor value must be cast to text for the UNION");
    assert.ok(sql.includes("cf.kgco2e_per_unit::text"),"client factor value must be cast to text for the UNION");});

  it("derives staff governance from live membership counts and enforced permissions",async()=>{const db={query:async()=>({rows:[{role_id:"reviewer",members:"3"}]})} as Queryable,roles=await listStaffRoleGovernance(db),reviewer=roles.find(role=>role.id==="reviewer");assert.equal(reviewer?.members,3);assert.ok(reviewer?.permissions.includes("reports.publish"));assert.ok(reviewer?.restricted.includes("finance.manage"));});

  it("loads the current published report from its matching frozen snapshot",async()=>{const db={query:async()=>({rows:[{report_version_id:"report-a",manifest_version:1,report_data_hash:"sha256:abc",published_at:"2026-08-25T18:00:00Z",snapshot_id:"snapshot-a",job_id:"job-a",snapshot_version:2,job_version:8,data_hash:"sha256:abc",payload_json:{jobNumber:"J000612",client:"Synthetic Client",reportingYear:2026,measurements:[]},created_by:"reviewer-a",created_at:"2026-08-25T17:00:00Z"}]})} as Queryable;const report=await getCurrentPublishedCrpReport(db,"job-a");assert.equal(report?.snapshot.jobNumber,"J000612");assert.equal(report?.reportVersionId,"report-a");});
  it("loads one immutable staff report version from its exact matching snapshot",async()=>{const db={query:async()=>({rows:[{report_version_id:"report-a",status:"validated",manifest_version:1,report_data_hash:"sha256:abc",published_at:null,snapshot_id:"snapshot-a",job_id:"job-a",snapshot_version:2,job_version:8,data_hash:"sha256:abc",payload_json:{jobNumber:"J000612",client:"Synthetic Client",reportingYear:2026,measurements:[]},created_by:"reviewer-a",created_at:"2026-08-25T17:00:00Z"}]})} as Queryable,report=await getCrpReportVersion(db,"report-a");assert.equal(report?.status,"validated");assert.equal(report?.publishedAt,null);assert.equal(report?.snapshot.id,"snapshot-a");});
  it("returns no portal report unless the user, client and job grant all match",async()=>{const db={query:async(sql:string)=>({rows:sql.includes("portal_access_grants")?[]:[{report_version_id:"should-not-load"}]})} as Queryable;assert.equal(await getGrantedPublishedCrpReport(db,{portalUserId:"user-a",clientId:"client-a",jobId:"job-a"}),null);});
  it("surfaces approval and unread NZI response state on the portal job list",async()=>{const db={query:async()=>({rows:[{job_id:"job-a",job_number:"J000612",title:"Synthetic CRP",reporting_year:2026,report_version_id:"report-a",approved_at:"2026-08-25T18:00:00Z",has_unread_nzi_response:true}]})} as Queryable;const jobs=await listGrantedPortalJobs(db,{portalUserId:"portal-a",clientId:"client-a"});assert.equal(jobs[0]?.approved,true);assert.equal(jobs[0]?.approvedAt,"2026-08-25T18:00:00Z");assert.equal(jobs[0]?.hasUnreadNziResponse,true);});
  it("maps immutable tenant audit history without inventing denied events",async()=>{const db={query:async()=>({rows:[{audit_event_id:"audit-a",occurred_at:"2026-08-25T20:00:00Z",actor_id:"reviewer-a",principal_type:"staff",organisation_id:"org-a",action:"report.publish",entity_type:"report_version",entity_id:"report-a",correlation_id:"request-a",reason:null,before_json:{status:"validated"},after_json:{status:"published"}}]})} as Queryable;const events=await listAuditEvents(db);assert.equal(events[0]?.result,"allowed");assert.equal(events[0]?.action,"report.publish");assert.equal(events[0]?.after,'{"status":"published"}');});
  it("maps the immutable report register with client review counts",async()=>{const db={query:async()=>({rows:[{report_version_id:"report-a",job_id:"job-a",job_number:"J000612",client_name:"Synthetic Client",reporting_year:2026,status:"published",manifest_version:1,reviewed_snapshot_id:"snapshot-a",data_hash:"sha256:abc",created_at:"2026-08-25T18:00:00Z",published_at:"2026-08-25T19:00:00Z",approval_count:"1",comment_count:"2"}]})} as Queryable;const reports=await listReportVersionRegister(db);assert.equal(reports[0]?.jobNumber,"J000612");assert.equal(reports[0]?.approvalCount,1);assert.equal(reports[0]?.commentCount,2);});

  it("distinguishes source review from canonical row sync and review status",async()=>{const db={query:async(sql:string)=>({rows:sql.includes("job_emission_groups")?[]:[{source_id:"source-a",job_id:"job-a",group_id:null,scope:"3.7",source_type:"commuting",source_subtype:null,site_id:null,source_name:"Employee A",asset_identifier:"EMP-001",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1200",unit:"km",apply_pct:"100",data_source:"HR survey",data_confidence:"M",monthly_activity_json:[],detail_json:{kind:"commuting"},notes:null,calculated_tco2e:null,enabled:true,submitted_by_portal:false,review_status:null,version:1,scope_row_id:"row-a",scope_row_version:3,scope_row_review_status:"pending"}]})} as Queryable;const register=await listJobEmissionSourceRegister(db,"job-a"),source=register.sources[0]!;assert.equal(source.reviewStatus,null);assert.equal(source.scopeRowId,"row-a");assert.equal(source.scopeRowVersion,3);assert.equal(source.scopeRowReviewStatus,"pending");assert.equal(source.rolledForwardFromSourceId,null);assert.equal(source.factorVersionMoved,false);assert.equal(source.yoyPriorQuantity,null);});

  it("carries the prior year's quantity and a moved-version flag on a rolled-forward source",async()=>{const db={query:async(sql:string)=>({rows:sql.includes("job_emission_groups")?[]:[{source_id:"rf-1",job_id:"job-2026",group_id:null,scope:"3.1",source_type:"spend",source_subtype:"7504",site_id:null,source_name:"Office paper",asset_identifier:null,purchased_goods_category_id:"pgs-paper",rolled_forward_from_source_id:"prior-1",factor_version_moved:true,yoy_prior_quantity:"1240",yoy_prior_unit:"GBP",dataset_id:"ds-2025",factor_id:"f-paper",factor_source:"dataset",client_factor_id:null,quantity:"3900",unit:"GBP",apply_pct:"100",data_source:"Rolled forward from J000700 · FY2025",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend"},notes:null,calculated_tco2e:null,enabled:true,submitted_by_portal:false,review_status:"pending",version:1,scope_row_id:null,scope_row_version:null,scope_row_review_status:null}]})} as Queryable;const register=await listJobEmissionSourceRegister(db,"job-2026"),source=register.sources[0]!;assert.equal(source.rolledForwardFromSourceId,"prior-1");assert.equal(source.factorVersionMoved,true);assert.equal(source.yoyPriorQuantity,1240);assert.equal(source.yoyPriorUnit,"GBP");});

  it("rolls back and releases the connection when a read fails", async () => {
    const calls: string[] = [];
    let released = false;
    const client = { query: async (sql: string) => { calls.push(sql); return { rows: [] }; }, release: () => { released = true; } };
    const pool = { connect: async () => client };
    await assert.rejects(() => withTenantRead(pool as never, "org-a", async () => { throw new Error("forced"); }));
    assert.equal(calls.at(-1), "ROLLBACK");
    assert.equal(released, true);
  });
});
