import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { encodeImportIdentity, type SpendImportIdentity } from "@nzi/contracts";
import { addManualDataset,approveScopeRow,archiveClientFactor,calculateScopeRow, changeJobStage, CommandValidationError,commitSpendImport,createClientFactor,createEmissionSource,createEmissionSourceGroup, createJob,createReviewedCrpSnapshot, createScopeRow, IdempotencyConflictError,listClientFactors,publishCrpReport,rejectScopeRow, rollforwardSpendSources, runPostgresCommand,saveClientImportMapping,signSpendImportIdentity,syncEmissionSourceGroupToScope,syncEmissionSourceToScope,updateClientFactor,updateEmissionSourceActivity,updateEmissionSourceStatus, updateScopeRow,validateCrpReport, voidSpendImportBatch,VersionConflictError } from "../src/index";

const context = { organisationId: "org-a", actorId: "staff-a", principal: "staff" as const, idempotencyKey: "create-job-1", correlationId: "corr-create-job-1" };
const input = { clientId: "client-a", family: "crp" as const, title: "Synthetic CRP", workflowStage: "Setup", owner: "A. Owner", startDate: "2026-08-25", dueDate: "2026-12-31", reportingYear: 2026 };

function commandPool() {
  const calls: string[] = [];
  let stored: { request_hash: string; outcome_json: Record<string, unknown> } | undefined;
  let auditCount = 0;
  let outboxCount = 0;
  let allocationCount = 0;
  const client = {
    async query(sql: string, values?: readonly unknown[]) {
      calls.push(sql);
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: stored ? [stored] : [] };
      if (sql.includes("allocate_job_sequence")) { allocationCount += 1; return { rows: [{ sequence: 717 }] }; }
      if (sql.includes("INSERT INTO nzi_console.jobs")) return { rows: [{ job_number: "J000717" }] };
      if (sql.includes("INSERT INTO nzi_console.audit_events")) auditCount += 1;
      if (sql.includes("INSERT INTO nzi_console.transactional_outbox")) outboxCount += 1;
      if (sql.includes("INSERT INTO nzi_console.command_idempotency")) stored = { request_hash: String(values?.[3]), outcome_json: JSON.parse(String(values?.[4])) as Record<string, unknown> };
      return { rows: [] };
    },
    release() { calls.push("RELEASE"); },
  };
  return { pool: { connect: async () => client } as never, calls, metrics: () => ({ auditCount, outboxCount, allocationCount }) };
}

describe("Postgres command boundary", () => {
  it("creates and numbers a job once, then replays the stored outcome", async () => {
    const state = commandPool();
    const first = await createJob(state.pool, input, context);
    const replay = await createJob(state.pool, input, context);
    assert.equal(first.data.jobNumber, "J000717");
    assert.equal(first.replayed, false);
    assert.equal(replay.replayed, true);
    assert.equal(replay.data.jobNumber, "J000717");
    assert.deepEqual(state.metrics(), { auditCount: 1, outboxCount: 1, allocationCount: 1 });
  });

  it("rejects reuse of an idempotency key with a different request", async () => {
    const state = commandPool();
    await createJob(state.pool, input, context);
    await assert.rejects(() => createJob(state.pool, { ...input, title: "Different" }, context), IdempotencyConflictError);
  });

  it("rolls back the whole command when its handler fails", async () => {
    const state = commandPool();
    await assert.rejects(() => runPostgresCommand(state.pool, "client.create", { name: "Synthetic", status: "active", sector: "Services", location: "London", owner: "A. Owner" }, context, async () => { throw new Error("forced failure"); }));
    assert.ok(state.calls.includes("ROLLBACK"));
    assert.equal(state.calls.includes("COMMIT"), false);
    assert.deepEqual(state.metrics(), { auditCount: 0, outboxCount: 0, allocationCount: 0 });
  });

  it("moves a job one adjacent stage and records history in the same transaction", async () => {
    const calls: string[] = [];
    const client = { async query(sql: string) {
      calls.push(sql);
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] };
      if (sql.includes("SELECT job_family")) return { rows: [{ job_family: "crp", workflow_stage: "Data entry", version: 3 }] };
      if (sql.includes("UPDATE nzi_console.jobs SET workflow_stage")) return { rows: [{ version: 4 }] };
      return { rows: [] };
    }, release() {} };
    const result = await changeJobStage({ connect: async () => client } as never, { jobId: "712", fromStage: "Data entry", toStage: "Review & QA", expectedVersion: 3, note: "Data collection complete" }, { ...context, idempotencyKey: "stage-1" });
    assert.equal(result.data.version, 4);
    assert.equal(result.data.toStage, "Review & QA");
    assert.ok(calls.some((sql) => sql.includes("INSERT INTO nzi_console.job_stage_history")));
    assert.ok(calls.some((sql) => sql.includes("INSERT INTO nzi_console.audit_events")));
    assert.ok(calls.some((sql) => sql.includes("COMMIT")));
  });

  it("rejects stale versions and skipped stages", async () => {
    const poolFor = (version: number) => ({ connect: async () => ({ async query(sql: string) {
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] };
      if (sql.includes("SELECT job_family")) return { rows: [{ job_family: "crp", workflow_stage: "Data entry", version }] };
      return { rows: [] };
    }, release() {} }) }) as never;
    await assert.rejects(() => changeJobStage(poolFor(4), { jobId: "712", fromStage: "Data entry", toStage: "Review & QA", expectedVersion: 3 }, { ...context, idempotencyKey: "stage-stale" }), VersionConflictError);
    await assert.rejects(() => changeJobStage(poolFor(3), { jobId: "712", fromStage: "Data entry", toStage: "Report & publish", expectedVersion: 3 }, { ...context, idempotencyKey: "stage-skip" }), CommandValidationError);
  });

  it("creates and version-updates canonical scope rows while invalidating stale calculations", async () => {
    const calls: Array<{ sql: string; values?: readonly unknown[] }> = [];
    const client = { async query(sql: string, values?: readonly unknown[]) { calls.push({ sql, values }); if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] }; if (sql.includes("SELECT job_family FROM")) return { rows: [{ job_family: "crp" }] }; if (sql.includes("UPDATE nzi_console.job_scope_rows")) return { rows: [{ version: 2 }] }; return { rows: [] }; }, release() {} };
    const pool = { connect: async () => client } as never;
    const fields = { scope: "3.1", sourceLabel: "Synthetic purchased goods", assetIdentifier:"INV-BATCH-14", columnText:"Purchased materials", applyPct:75, dataConfidence:"H" as const, sourceQuantity:1600, sourceUnit:"GBP", notes:"Invoice batch checked", quantity: 1200, unit: "GBP", datasetId: "dataset-a", factorId: "factor-a", factorVersion: "2026 v1", factorLabel: "Synthetic factor", qualityTier: "spend-based" as const };
    const created = await createScopeRow(pool, { jobId: "job-a", ...fields }, { ...context, idempotencyKey: "scope-create" });
    const updated = await updateScopeRow(pool, { jobId: "job-a", rowId: created.data.rowId, expectedVersion: 1, enabled: true, ...fields, quantity: 1400 }, { ...context, idempotencyKey: "scope-update" });
    assert.equal(updated.data.version, 2);
    const updateSql = calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.sql ?? "";
    assert.match(updateSql, /calculated_tco2e=NULL/); assert.match(updateSql, /review_status='pending'/);assert.match(updateSql,/reviewed_by=NULL/);
    assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes("Invoice batch checked"));
    assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes("INV-BATCH-14"));
    for(const value of ["Purchased materials",75,"H",1600])assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes(value));
    assert.ok(calls.filter((call) => call.sql.includes("INSERT INTO nzi_console.audit_events")).length >= 2);
    const insert = calls.find((call) => call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));
    assert.match(insert?.sql ?? "", /category_code/);
    assert.ok(insert?.values?.includes("3.1"), "Scope 3 granular scope is auto-filed as its category_code (NZC-046/UX1c)");
    assert.match(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.sql ?? "", /category_code=\$35/);
  });

  it("stamps an explicit NZC-046 category_code from the accordion Add-entry flow (UX1c)", async () => {
    const calls: Array<{ sql: string; values?: readonly unknown[] }> = [];
    const client = { async query(sql: string, values?: readonly unknown[]) { calls.push({ sql, values }); if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] }; if (sql.includes("SELECT job_family FROM")) return { rows: [{ job_family: "crp" }] }; return { rows: [] }; }, release() {} };
    await createScopeRow({ connect: async () => client } as never, { jobId: "job-a", scope: "1", categoryCode: "1.company-vehicles", sourceLabel: "AB12 CDE", quantity: 6200, unit: "litres", datasetId: "dataset-a", factorId: "factor-a", factorVersion: "v1", factorLabel: "Diesel LGV", qualityTier: "measured" }, { ...context, idempotencyKey: "cat-create" });
    const insert = calls.find((call) => call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));
    assert.ok(insert?.values?.includes("1.company-vehicles"));
  });

  it("derives annual activity from reporting-period monthly slots",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-02-28"}]};return{rows:[]};},release(){}};await createScopeRow({connect:async()=>client} as never,{jobId:"job-a",scope:"1",sourceLabel:"Gas",quantity:999,unit:"kWh",datasetId:"dataset-a",factorId:"factor-a",factorVersion:"v1",factorLabel:"Gas factor",qualityTier:"measured",monthlyActivity:[{month:"2026-01",quantity:10},{month:"2026-02",quantity:20}]},{...context,idempotencyKey:"monthly-create"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.equal(insert?.values?.[7],30);assert.deepEqual(JSON.parse(String(insert?.values?.[21])),[{month:"2026-01",quantity:10},{month:"2026-02",quantity:20}]);});

  it("calculates with an eligible client factor and hashes its evidence into provenance",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT version,quantity"))return{rows:[{version:2,quantity:"500",unit:"unit",scope:"3.1",dataset_id:null,factor_id:"cf-a",factor_source:"client",client_factor_id:"cf-a",override_tco2e:null,override_reason:null,monthly_activity_json:[]}]};if(sql.includes("FROM nzi_console.client_factors cf"))return{rows:[{label:"Supplier EPD",activity_unit:"unit",kgco2e_per_unit:"12.4",version:"1",synthetic:false,evidence_hash:"sha256:epd"}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET factor_version"))return{rows:[{version:3,calculated_tco2e:"6.2"}]};return{rows:[]}},release(){}};const result=await calculateScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowId:"row-a",expectedVersion:2},{...context,idempotencyKey:"client-factor-calc"});assert.equal(result.data.calculatedTco2e,6.2);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET factor_version"));const provenance=JSON.parse(String(update?.values?.[6]));assert.equal(provenance.factorSource,"client");assert.equal(provenance.clientFactorId,"cf-a");assert.equal(provenance.evidenceHash,"sha256:epd");assert.ok(calls.some(call=>call.sql.includes("cf.job_id IS NULL OR cf.job_id=j.job_id")));});

  it("creates an audited reusable client factor with hashed evidence",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT client_id FROM"))return{rows:[{client_id:"client-a"}]};return{rows:[]}},release(){}};const result=await createClientFactor({connect:async()=>client} as never,{jobId:"job-a",scope:"3.1",reportLabel:"Supplier EPD",description:"Widget",unit:"unit",kgco2ePerUnit:12.4,geography:"gb",vintageYear:2026,source:"Supplier",reusable:true,evidenceFileName:"epd.pdf",evidenceStorageProvider:"sharepoint",evidenceUrl:null,evidenceExternalItemId:"doc-a",evidenceHash:"sha256:epd"},{...context,idempotencyKey:"client-factor-create"});assert.equal(result.data.label,"Supplier EPD");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.client_factors"));assert.equal(insert?.values?.[3],null);assert.ok(insert?.values?.includes("sha256:epd"));assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")));});

  // S2 — client factor lifecycle
  const clientFactorRow={version:2,unit:"unit",kgco2e_per_unit:"12.4",geography:"GB",vintage_year:2026};
  const updateInput={clientFactorId:"cf-a",expectedVersion:2,reportLabel:"Supplier EPD",description:"Widget",unit:"unit",kgco2ePerUnit:12.4,geography:"GB",vintageYear:2026,source:"Supplier",evidenceFileName:null,evidenceStorageProvider:null,evidenceUrl:null,evidenceExternalItemId:null,evidenceHash:null};
  const cfClient=(row:Record<string,unknown>|null,calls:Array<{sql:string;values?:readonly unknown[]}>)=>({async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("FROM nzi_console.client_factors WHERE organisation_id=$1 AND client_factor_id"))return{rows:row?[row]:[]};if(sql.includes("count(*)::text AS count FROM nzi_console.job_scope_rows"))return{rows:[{count:String(row?.refs??0)}]};return{rows:[]}},release(){}});

  it("bumps the client factor version only when a value field changes",async()=>{const bumped:Array<{sql:string;values?:readonly unknown[]}>=[];const b=await updateClientFactor({connect:async()=>cfClient(clientFactorRow,bumped)} as never,{...updateInput,kgco2ePerUnit:15.1},{...context,idempotencyKey:"cf-update-1"});assert.equal(b.data.versionBumped,true);assert.equal(b.data.version,3);const bUpdate=bumped.find(call=>call.sql.includes("UPDATE nzi_console.client_factors SET report_label"));assert.equal(bUpdate?.values?.[14],3);
    const kept:Array<{sql:string;values?:readonly unknown[]}>=[];const k=await updateClientFactor({connect:async()=>cfClient(clientFactorRow,kept)} as never,{...updateInput,reportLabel:"Supplier EPD (updated wording)"},{...context,idempotencyKey:"cf-update-2"});assert.equal(k.data.versionBumped,false);assert.equal(k.data.version,2);});

  it("rejects a stale client factor edit",async()=>{await assert.rejects(()=>updateClientFactor({connect:async()=>cfClient(clientFactorRow,[])} as never,{...updateInput,expectedVersion:1},{...context,idempotencyKey:"cf-update-stale"}),VersionConflictError);});

  it("blocks archiving a client factor while active rows reference it, and allows it when clear",async()=>{
    await assert.rejects(()=>archiveClientFactor({connect:async()=>cfClient({archived:false,refs:3},[])} as never,{clientFactorId:"cf-a",archived:true},{...context,idempotencyKey:"cf-archive-blocked"}),CommandValidationError);
    const ok:Array<{sql:string;values?:readonly unknown[]}>=[];const result=await archiveClientFactor({connect:async()=>cfClient({archived:false,refs:0},ok)} as never,{clientFactorId:"cf-a",archived:true},{...context,idempotencyKey:"cf-archive-ok"});assert.equal(result.data.archived,true);assert.ok(ok.some(call=>call.sql.includes("UPDATE nzi_console.client_factors SET archived")));
    const back:Array<{sql:string;values?:readonly unknown[]}>=[];const restored=await archiveClientFactor({connect:async()=>cfClient({archived:true,refs:5},back)} as never,{clientFactorId:"cf-a",archived:false},{...context,idempotencyKey:"cf-unarchive"});assert.equal(restored.data.archived,false);assert.equal(back.some(call=>call.sql.includes("count(*)::text AS count")),false);});

  it("lists a client's factors with a usage count and job-pin filter",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});return{rows:[{client_factor_id:"cf-a",client_id:"client-a",job_id:null,scope:"3.1",category_path_json:["Scope 3","Purchased goods"],report_label:"Supplier EPD",description:"Widget",unit:"unit",ghg_unit:"kgCO2e",kgco2e_per_unit:"12.4",geography:"GB",vintage_year:2026,version:2,source:"Supplier",evidence_file_name:"epd.pdf",evidence_storage_provider:"sharepoint",evidence_url:null,evidence_external_item_id:"doc-a",evidence_hash:"sha256:epd",archived:false,usage_count:4,created_by:"staff-a",created_at:"2026-08-01T00:00:00Z",updated_by:null,updated_at:null}]}},release(){}};const rows=await listClientFactors(client as never,"org-a","client-a",{jobId:"job-a"});assert.equal(rows[0]!.usageCount,4);assert.equal(rows[0]!.evidenceHash,"sha256:epd");const query=calls[0]!;assert.ok(query.sql.includes("($3::text IS NULL OR cf.job_id IS NULL OR cf.job_id=$3)"));assert.deepEqual(query.values,["org-a","client-a","job-a"]);});

  // S1 — group roll-up (NZC-043)
  const groupSyncClient=(members:Array<Record<string,unknown>>,existingRowId:string|null,calls:Array<{sql:string;values?:readonly unknown[]}>,groupOverride?:Record<string,unknown>)=>({async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT name,dataset_id,factor_id FROM nzi_console.job_emission_groups"))return{rows:[{name:"Fleet",dataset_id:"ds-a",factor_id:"f-a",...groupOverride}]};if(sql.includes("SELECT f.label,f.activity_unit,d.version FROM nzi_console.emission_factors f JOIN"))return{rows:[{label:"Fleet diesel",activity_unit:"litres",version:"2026"}]};if(sql.includes("FROM nzi_console.job_emission_sources WHERE organisation_id=$1 AND job_id=$2 AND group_id=$3 AND enabled=true"))return{rows:members};if(sql.includes("SELECT scope_row_id FROM nzi_console.job_scope_rows WHERE organisation_id=$1 AND job_id=$2 AND group_id=$3"))return{rows:existingRowId?[{scope_row_id:existingRowId}]:[]};return{rows:[]}},release(){}});

  it("rolls an emission-source group up into one auto-generated scope row from enabled members",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const members=[{source_id:"m1",scope:"1",source_type:"vehicle",quantity:"1000",unit:"litres",apply_pct:"100",monthly_activity_json:[]},{source_id:"m2",scope:"1",source_type:"vehicle",quantity:"500",unit:"litres",apply_pct:"100",monthly_activity_json:[]}];const result=await syncEmissionSourceGroupToScope({connect:async()=>groupSyncClient(members,null,calls)} as never,{jobId:"job-a",groupId:"grp-a"},{...context,idempotencyKey:"grp-sync-1"});assert.equal(result.data.enabledMemberCount,2);assert.equal(result.data.summedQuantity,1500);
    assert.ok(calls.some(call=>call.sql.includes("DELETE FROM nzi_console.job_scope_rows WHERE organisation_id=$1 AND job_id=$2 AND source_id IN")),"per-source rows are cleared to avoid double count");
    const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.ok(insert?.sql.includes("group_id"));assert.ok(insert?.sql.includes("review_status"));assert.ok(insert?.sql.includes("'pending'"));assert.ok(insert?.values?.includes(1500));const provenance=insert?.values?.map(String).find(v=>v.includes('"sourceType":"group-rollup"'));assert.ok(provenance?.includes('"m1"')&&provenance?.includes('"m2"'),"provenance names the members");});

  it("re-aggregates an existing group roll-up row and returns it to pending",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const members=[{source_id:"m1",scope:"1",source_type:"vehicle",quantity:"800",unit:"litres",apply_pct:"50",monthly_activity_json:[]}];await syncEmissionSourceGroupToScope({connect:async()=>groupSyncClient(members,"row-existing",calls)} as never,{jobId:"job-a",groupId:"grp-a"},{...context,idempotencyKey:"grp-sync-2"});const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET scope=$3"));assert.ok(update?.sql.includes("review_status='pending'"));assert.ok(update?.sql.includes("reviewed_by=NULL"));assert.equal(update?.values?.[4],400,"apply_pct is applied per member (800 * 50%)");});

  it("rejects a group roll-up with mixed member scopes or no group factor",async()=>{
    const mixed=[{source_id:"m1",scope:"1",source_type:"vehicle",quantity:"1",unit:"litres",apply_pct:"100",monthly_activity_json:[]},{source_id:"m2",scope:"3.6",source_type:"vehicle",quantity:"1",unit:"litres",apply_pct:"100",monthly_activity_json:[]}];
    await assert.rejects(()=>syncEmissionSourceGroupToScope({connect:async()=>groupSyncClient(mixed,null,[])} as never,{jobId:"job-a",groupId:"grp-a"},{...context,idempotencyKey:"grp-mixed"}),CommandValidationError);
    await assert.rejects(()=>syncEmissionSourceGroupToScope({connect:async()=>groupSyncClient([{source_id:"m1",scope:"1",source_type:"vehicle",quantity:"1",unit:"litres",apply_pct:"100",monthly_activity_json:[]}],null,[],{factor_id:null,dataset_id:null})} as never,{jobId:"job-a",groupId:"grp-a"},{...context,idempotencyKey:"grp-nofactor"}),CommandValidationError);});

  it("refuses to sync a grouped source individually (no double count)",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT group_id FROM nzi_console.job_emission_sources"))return{rows:[{group_id:"grp-a"}]};return{rows:[]}},release(){}};await assert.rejects(()=>syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"m1"},{...context,idempotencyKey:"src-grouped-sync"}),CommandValidationError);});

  it("refuses a manual edit of a group roll-up row",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT group_id FROM nzi_console.job_scope_rows"))return{rows:[{group_id:"grp-a"}]};return{rows:[]}},release(){}};await assert.rejects(()=>updateScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowId:"row-rollup",expectedVersion:2,enabled:true,scope:"1",sourceLabel:"Fleet",quantity:1500,unit:"litres",datasetId:"ds-a",factorId:"f-a",factorVersion:"2026",factorLabel:"Fleet diesel",qualityTier:"measured"},{...context,idempotencyKey:"edit-rollup"}),CommandValidationError);});

  it("tags a bulk-imported commuting source with its import batch id (S1.1)",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{ok:1}]};return{rows:[]}},release(){}};await createEmissionSource({connect:async()=>client} as never,{jobId:"job-a",groupId:null,scope:"3.7",sourceType:"commuting",sourceSubtype:null,siteId:null,sourceName:"A. Example",assetIdentifier:"A. Example",purchasedGoodsCategoryId:null,datasetId:"dataset-a",factorId:"factor-a",factorSource:"dataset",clientFactorId:null,quantity:7500,unit:"km",applyPct:100,dataSource:"Commuting bulk import",dataConfidence:"M",monthlyActivity:[],detail:{kind:"commuting",vehicleRegistration:null,commuteMode:"Rail",distanceUnit:"km",wfhDaysPerYear:52,wfhHoursPerDay:7.5,employeeName:"A. Example"},notes:null,importBatchId:"batch-77"},{...context,idempotencyKey:"commute-bulk-1"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.sql.includes("import_batch_id"));assert.equal(insert?.values?.[23],"batch-77");});

  it("creates audited emission-source groups and typed sources inside the job boundary",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_groups WHERE"))return{rows:[{exists:1}]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never;const group=await createEmissionSourceGroup(pool,{jobId:"job-a",name:"Employee commuting"},{...context,idempotencyKey:"source-group-create"});assert.equal(group.data.name,"Employee commuting");const source=await createEmissionSource(pool,{jobId:"job-a",groupId:"group-a",scope:"3.7",sourceType:"commuting",sourceSubtype:null,siteId:null,sourceName:"Employee A",assetIdentifier:"EMP-001",purchasedGoodsCategoryId:null,datasetId:null,factorId:null,factorSource:"dataset",clientFactorId:null,quantity:1200,unit:"km",applyPct:100,dataSource:"HR survey",dataConfidence:"M",monthlyActivity:[],detail:{kind:"commuting",vehicleRegistration:null,commuteMode:"rail",distanceUnit:"km",wfhDaysPerYear:80,wfhHoursPerDay:8,employeeName:"Employee A"},notes:null},{...context,idempotencyKey:"source-create"});assert.equal(source.data.sourceName,"Employee A");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.values?.includes("EMP-001"));assert.ok(insert?.values?.some(value=>String(value).includes('"kind":"commuting"')));assert.ok(calls.filter(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")).length>=2);});

  it("validates and persists the controlled purchased-goods category on a spend source, and carries it into the synced row",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"src-spend",scope:"3.1",source_type:"spend",source_name:"Office paper",site_id:null,asset_identifier:null,purchased_goods_category_id:"pgs-paper",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1240",unit:"GBP",apply_pct:"100",data_source:"Spend ledger",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend"},notes:null,factor_label:"PG&S paper",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never;await createEmissionSource(pool,{jobId:"job-a",groupId:null,scope:"3.1",sourceType:"spend",sourceSubtype:"7504",siteId:null,sourceName:"Office paper",assetIdentifier:null,purchasedGoodsCategoryId:"pgs-paper",datasetId:"dataset-a",factorId:"factor-a",factorSource:"dataset",clientFactorId:null,quantity:1240,unit:"GBP",applyPct:100,dataSource:"Spend ledger",dataConfidence:null,monthlyActivity:[],detail:{kind:"spend",netValue:1240,vatPercent:20,glCode:"7504",category:"Paper"},notes:null},{...context,idempotencyKey:"spend-create"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.sql.includes("purchased_goods_category_id"));assert.ok(insert?.values?.includes("pgs-paper"));assert.ok(calls.some(call=>call.sql.includes("FROM nzi_console.purchased_goods_categories c JOIN")));const sync=await syncEmissionSourceToScope(pool,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"spend-sync-2"});assert.equal(sync.data.created,true);const rowInsert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.ok(rowInsert?.sql.includes("purchased_goods_category_id"));assert.ok(rowInsert?.values?.includes("pgs-paper"));assert.ok(rowInsert?.values?.includes("spend-based"));const provenance=rowInsert?.values?.map(String).find(value=>value.includes('"sourceType":"register"'));assert.ok(provenance?.includes('"dataHash":"sha256:'),"synced row provenance carries a data hash");assert.match(provenance??"",/"asAt":"\d{4}-\d{2}-\d{2}"/);});

  it("version-updates source activity and rejects stale edits",async()=>{let stale=false;const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:stale?[]:[{version:2}]};if(sql.includes("SELECT version FROM nzi_console.job_emission_sources"))return{rows:[{version:2}]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never,input={jobId:"job-a",sourceId:"source-a",expectedVersion:1,quantity:1500,unit:"km",applyPct:75,dataConfidence:"H" as const,monthlyActivity:[],notes:"Updated survey"};const result=await updateEmissionSourceActivity(pool,input,{...context,idempotencyKey:"source-update"});assert.equal(result.data.version,2);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_emission_sources"));assert.ok(update?.sql.includes("calculated_tco2e=NULL"));assert.ok(update?.sql.includes("review_status='pending'"));stale=true;await assert.rejects(()=>updateEmissionSourceActivity(pool,input,{...context,idempotencyKey:"source-update-stale"}),error=>error instanceof VersionConflictError&&error.message.includes("expected v1, found v2"));});

  it("derives source annual activity from reporting-period monthly slots",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-02-28"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:[{version:3}]};return{rows:[]}},release(){}};const result=await updateEmissionSourceActivity({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:2,quantity:999,unit:"km",applyPct:100,dataConfidence:"M" as const,monthlyActivity:[{month:"2026-01",quantity:100},{month:"2026-02",quantity:50}],notes:null},{...context,idempotencyKey:"source-monthly-update"});assert.equal(result.data.version,3);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_emission_sources"));assert.equal(update?.values?.[4],150);assert.deepEqual(JSON.parse(String(update?.values?.[8])),[{month:"2026-01",quantity:100},{month:"2026-02",quantity:50}]);});

  it("rejects source monthly slots that do not span the reporting period in order",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-03-31"}]};return{rows:[]}},release(){}};await assert.rejects(()=>updateEmissionSourceActivity({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:2,quantity:null,unit:"km",applyPct:100,dataConfidence:null,monthlyActivity:[{month:"2026-01",quantity:10}],notes:null},{...context,idempotencyKey:"source-monthly-bad"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="REPORTING_PERIOD_MISMATCH"));});

  it("derives a spend source's annual quantity from its invoice-month slots on create",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{ok:1}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-03-31"}]};return{rows:[]}},release(){}};await createEmissionSource({connect:async()=>client} as never,{jobId:"job-a",groupId:null,scope:"3.1",sourceType:"spend",sourceSubtype:"7504",siteId:null,sourceName:"Office paper",assetIdentifier:"2026-02-14",purchasedGoodsCategoryId:"pgs-paper",datasetId:"dataset-a",factorId:"factor-a",factorSource:"dataset",clientFactorId:null,quantity:1240,unit:"GBP",applyPct:100,dataSource:"Spend ledger",dataConfidence:null,monthlyActivity:[{month:"2026-01",quantity:null},{month:"2026-02",quantity:1240},{month:"2026-03",quantity:null}],detail:{kind:"spend",netValue:1240,vatPercent:20,glCode:"7504",category:"Paper"},notes:null},{...context,idempotencyKey:"spend-monthly-create"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.equal(insert?.values?.[15],1240);assert.deepEqual(JSON.parse(String(insert?.values?.[20])),[{month:"2026-01",quantity:null},{month:"2026-02",quantity:1240},{month:"2026-03",quantity:null}]);});

  it("rejects a create whose monthly slots do not span the reporting period",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{ok:1}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-03-31"}]};return{rows:[]}},release(){}};await assert.rejects(()=>createEmissionSource({connect:async()=>client} as never,{jobId:"job-a",groupId:null,scope:"3.1",sourceType:"spend",sourceSubtype:null,siteId:null,sourceName:"Office paper",assetIdentifier:null,purchasedGoodsCategoryId:"pgs-paper",datasetId:"dataset-a",factorId:"factor-a",factorSource:"dataset",clientFactorId:null,quantity:1240,unit:"GBP",applyPct:100,dataSource:"Spend ledger",dataConfidence:null,monthlyActivity:[{month:"2026-02",quantity:1240}],detail:{kind:"spend",netValue:1240,vatPercent:20,glCode:null,category:"Paper"},notes:null},{...context,idempotencyKey:"spend-monthly-bad"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="REPORTING_PERIOD_MISMATCH"));});

  it("archives a source and excludes its canonical row in the same transaction",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:[{version:4}]};return{rows:[]}},release(){}};const result=await updateEmissionSourceStatus({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:3,enabled:false},{...context,idempotencyKey:"source-archive"});assert.equal(result.data.enabled,false);const rowUpdate=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET enabled"));assert.equal(rowUpdate?.values?.[3],false);assert.ok(rowUpdate?.sql.includes("reviewed_row_version=NULL"));assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")));});

  it("syncs a locked register source into its one auto-generated canonical row",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"source-a",scope:"3.7",source_name:"Employee A",site_id:null,asset_identifier:"EMP-001",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1200",unit:"km",apply_pct:"100",data_source:"HR survey",data_confidence:"M",monthly_activity_json:[],detail_json:{kind:"commuting"},notes:null,factor_label:"Travel",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[{scope_row_id:"row-a",version:2}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET"))return{rows:[{version:3}]};return{rows:[]}},release(){}};const result=await syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a"},{...context,idempotencyKey:"source-sync"});assert.equal(result.data.created,false);assert.equal(result.data.version,3);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET"));assert.ok(update?.sql.includes("is_auto_generated=true"));assert.ok(update?.values?.includes("source-a"));assert.ok(calls.some(call=>call.sql.includes("FOR UPDATE OF s")));});

  it("syncs a spend source into a new Scope 3.1 row carrying the spend-based quality tier",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"src-spend",scope:"3.1",source_type:"spend",source_name:"Office paper",site_id:null,asset_identifier:"2025-03-14",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1240",unit:"GBP",apply_pct:"100",data_source:"Spend ledger",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend",category:"Paper"},notes:null,factor_label:"PG&S paper",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[]};return{rows:[]}},release(){}};const result=await syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"spend-sync"});assert.equal(result.data.created,true);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.ok(insert?.sql.includes("quality_tier"));assert.ok(insert?.values?.includes("spend-based"));assert.ok(insert?.values?.includes("3.1"));assert.ok(insert?.sql.includes("category_code"));assert.ok(insert?.values?.includes("3.1"),"spend source files under category 3.1");});

  it("stamps category_code on a synced register row — vehicle→Company Vehicles, commuting→3.7 (NZC-046/UX1c)",async()=>{
    const rowFor=(over:Record<string,unknown>)=>({source_id:"s1",site_id:null,asset_identifier:"AB12 CDE",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"6200",unit:"litres",apply_pct:"100",data_source:"Fuel card",data_confidence:"M",monthly_activity_json:[],detail_json:{kind:"vehicle"},notes:null,factor_label:"Diesel LGV",factor_version:"2026",...over});
    const run=async(over:Record<string,unknown>)=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[rowFor(over)]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[]};return{rows:[]}},release(){}};await syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"s1"},{...context,idempotencyKey:`sync-${Math.random()}`});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));return insert?.values??[];};
    assert.ok((await run({scope:"1",source_type:"vehicle"})).includes("1.company-vehicles"));
    assert.ok((await run({scope:"3.7",source_type:"commuting"})).includes("3.7"));
    assert.equal((await run({scope:"1",source_type:"asset"})).find(v=>v==="1.natural-gas"),undefined);
  });

  it("re-syncs an unchanged spend source to the same row with a stable evidence hash",async()=>{const rowState:{scope_row_id:string;version:number}|null={scope_row_id:"row-spend",version:2};const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"src-spend",scope:"3.1",source_type:"spend",source_name:"Office paper",site_id:null,asset_identifier:"2026-02-14",purchased_goods_category_id:"pgs-paper",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1240",unit:"GBP",apply_pct:"100",data_source:"Spend ledger",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend",category:"Paper"},notes:null,factor_label:"PG&S paper",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[rowState]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET"))return{rows:[{version:++rowState.version}]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never;const first=await syncEmissionSourceToScope(pool,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"resync-1"});const second=await syncEmissionSourceToScope(pool,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"resync-2"});assert.equal(first.data.created,false);assert.equal(first.data.rowId,second.data.rowId);const updates=calls.filter(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET"));const hashOf=(call?:{values?:readonly unknown[]})=>/"dataHash":"(sha256:[0-9a-f]+)"/.exec(call?.values?.map(String).find(v=>v.includes('"dataHash"'))??"")?.[1];assert.ok(hashOf(updates[0]),"first re-sync writes an evidence hash");assert.equal(hashOf(updates[0]),hashOf(updates[1]),"an unchanged source re-syncs to the same evidence hash");});

  it("rolls previous-year spend mappings forward, re-pinning the factor version and copying no amount",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT client_id,reporting_year,start_date"))return{rows:[{client_id:"client-a",reporting_year:2026,start_date:"2026-01-01"}]};if(sql.includes("j.client_id=$2 AND j.job_family='crp'"))return{rows:[{job_id:"job-2025",job_number:"J000700",reporting_year:2025}]};if(sql.includes("AND NOT EXISTS(SELECT 1 FROM nzi_console.job_emission_sources rf"))return{rows:[{source_id:"prior-src-1",source_name:"Office paper",source_subtype:"7504",scope:"3.1",purchased_goods_category_id:"pgs-paper",dataset_id:"ds-2025",factor_id:"f-paper",factor_source:"dataset",client_factor_id:null,unit:"GBP",apply_pct:"100",detail_json:{kind:"spend",netValue:1240,vatPercent:20,glCode:"7504",category:"Paper"},notes:null}]};if(sql.includes("SELECT 1 FROM nzi_console.job_dataset_selections WHERE organisation_id=$1 AND job_id=$2 AND dataset_id=$3"))return{rows:[]};if(sql.includes("SELECT 1 FROM nzi_console.emission_factor_datasets WHERE organisation_id=$1 AND dataset_id=$2"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{ok:1}]};return{rows:[]}},release(){}};const result=await rollforwardSpendSources({connect:async()=>client} as never,{jobId:"job-2026",fromJobId:null},{...context,idempotencyKey:"rf-1"});assert.equal(result.data.rolledForward,1);assert.equal(result.data.priorJobNumber,"J000700");const sel=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_dataset_selections"));assert.ok(sel?.values?.some(v=>String(v).includes("NZC-030")),"re-pinned dataset added with an audited reason");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.sql.includes("rolled_forward_from_source_id"));assert.ok(insert?.values?.includes("prior-src-1"));assert.ok(insert?.values?.includes("ds-2025")&&insert?.values?.includes("f-paper"),"pins the prior dataset + factor");assert.ok(insert?.values?.some(v=>String(v).startsWith("Rolled forward from J000700")));const detail=JSON.parse(String(insert?.values?.map(String).find(v=>v.includes('"kind":"spend"'))));assert.equal(detail.netValue,0);});

  it("rejects a rollforward when the client has no prior-year CRP job with spend",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT client_id,reporting_year,start_date"))return{rows:[{client_id:"client-a",reporting_year:2026,start_date:"2026-01-01"}]};return{rows:[]}},release(){}};await assert.rejects(()=>rollforwardSpendSources({connect:async()=>client} as never,{jobId:"job-2026",fromJobId:null},{...context,idempotencyKey:"rf-none"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="NO_PRIOR_YEAR"));});

  const SI_SECRET="0123456789abcdef0123456789abcdef";
  const spendIdentity:SpendImportIdentity={jobId:"job-a",jobNumber:"J000712",clientName:"Bushy Tails",jobName:"Annual CRP",reportingYear:2024,reportingFrom:"2024-01-01",reportingTo:"2024-12-31",domain:"spend",templateVersion:1};
  const spendImportMock=()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from,reporting_to FROM nzi_console.job_emissions_config"))return{rows:[{reporting_from:"2024-01-01",reporting_to:"2024-12-31"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{category_id:"pg-1"}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{factor_id:"f-1"}]};if(sql.includes("FROM nzi_console.client_factors cf JOIN"))return{rows:[]};if(sql.includes("source_type='spend' AND voided_at IS NULL"))return{rows:[]};return{rows:[]}},release(){}};return{calls,pool:{connect:async()=>client} as never};};
  const spendRow=(over:Record<string,unknown>={})=>({rowNumber:1,description:"Office paper",netValue:1240,vatPercent:20,glCode:"7504",invoiceDate:"2024-03-14",purchasedGoodsCategoryId:"pg-1",factorSource:"dataset" as const,factorId:"f-1",datasetId:"d-1",clientFactorId:null,monthly:[],...over});

  it("commits a verified spend import as a tagged batch, skipping blocked rows",async()=>{const {calls,pool}=spendImportMock();const token=encodeImportIdentity(spendIdentity,signSpendImportIdentity(spendIdentity,SI_SECRET));const result=await commitSpendImport(pool,{jobId:"job-a",token,rows:[spendRow(),spendRow({rowNumber:2,description:"",purchasedGoodsCategoryId:"nope"})]},{...context,idempotencyKey:"si-commit"},SI_SECRET);assert.equal(result.data.created,1);assert.equal(result.data.blocked,1);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.sql.includes("import_batch_id"));assert.ok(insert?.values?.includes(result.data.batchId));assert.ok(insert?.sql.includes("'3.1','spend'"));});

  it("rejects a commit whose token was signed for a different job or is stale",async()=>{const {pool}=spendImportMock();const wrongJob=encodeImportIdentity({...spendIdentity,jobId:"other"},signSpendImportIdentity({...spendIdentity,jobId:"other"},SI_SECRET));await assert.rejects(()=>commitSpendImport(pool,{jobId:"job-a",token:wrongJob,rows:[spendRow()]},{...context,idempotencyKey:"si-wrongjob"},SI_SECRET),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.field==="token"&&issue.code==="WRONG_JOB"));
    const stale=encodeImportIdentity({...spendIdentity,templateVersion:99},signSpendImportIdentity({...spendIdentity,templateVersion:99},SI_SECRET));await assert.rejects(()=>commitSpendImport(spendImportMock().pool,{jobId:"job-a",token:stale,rows:[spendRow()]},{...context,idempotencyKey:"si-stale"},SI_SECRET),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="STALE_TEMPLATE"));
    await assert.rejects(()=>commitSpendImport(spendImportMock().pool,{jobId:"job-a",token:"garbage",rows:[spendRow()]},{...context,idempotencyKey:"si-bad"},SI_SECRET),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.field==="token"));});

  it("soft-voids only the pending, unsynced rows of an import batch",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("s.import_batch_id=$3 AND s.voided_at IS NULL"))return{rows:[{source_id:"a",review_status:"pending",scope_row_id:null},{source_id:"b",review_status:"pending",scope_row_id:"row-b"},{source_id:"c",review_status:"approved",scope_row_id:null}]};return{rows:[]}},release(){}};const result=await voidSpendImportBatch({connect:async()=>client} as never,{jobId:"job-a",batchId:"batch-1"},{...context,idempotencyKey:"si-void"});assert.equal(result.data.voided,1);assert.equal(result.data.skipped,2);const update=calls.find(call=>call.sql.includes("SET voided_at=now()"));assert.deepEqual(update?.values?.[2],["a"]);});

  it("rejects a void for an unknown batch",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};return{rows:[]}},release(){}};await assert.rejects(()=>voidSpendImportBatch({connect:async()=>client} as never,{jobId:"job-a",batchId:"nope"},{...context,idempotencyKey:"si-void-none"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="NOT_FOUND"));});

  it("upserts a client's remembered import column map and bumps the version",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT 1 FROM nzi_console.clients"))return{rows:[{ok:1}]};if(sql.includes("INSERT INTO nzi_console.client_import_mappings"))return{rows:[{version:3}]};return{rows:[]}},release(){}};const result=await saveClientImportMapping({connect:async()=>client} as never,{clientId:"c-1",importKind:"spend",columns:{description:"Detail",netValue:"Amount"}},{...context,idempotencyKey:"map-save"});assert.equal(result.data.version,3);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.client_import_mappings"));assert.ok(insert?.sql.includes("version=client_import_mappings.version+1"));assert.ok(insert?.values?.some(v=>String(v).includes('"description":"Detail"')));});

  it("rejects a mapping save for an unknown client",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT 1 FROM nzi_console.clients"))return{rows:[]};return{rows:[]}},release(){}};await assert.rejects(()=>saveClientImportMapping({connect:async()=>client} as never,{clientId:"nope",importKind:"spend",columns:{}},{...context,idempotencyKey:"map-save-bad"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="NOT_FOUND"));});

  it("records warned manual dataset exceptions with their dedicated audit reason", async () => {
    const calls:Array<{sql:string;values?:readonly unknown[]}>=[];
    const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.emission_factor_datasets d"))return{rows:[{valid_from:"2026-01-01",valid_to:"2026-12-31",dataset_country:"US",status:"active",reporting_from:"2026-01-01",reporting_to:"2026-12-31",job_country:"GB"}]};if(sql.includes("INSERT INTO nzi_console.job_dataset_selections"))return{rows:[{dataset_id:"synthetic-us-2026"}]};return{rows:[]};},release(){}};
    const result=await addManualDataset({connect:async()=>client} as never,{jobId:"job-a",scope:"all",datasetId:"synthetic-us-2026",reportingFrom:"2026-01-01",reportingTo:"2026-12-31"},{...context,idempotencyKey:"dataset-manual",reason:"Client methodology exception"});
    assert.match(result.data.warnings[0]??"",/US.*GB/);
    const selection=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_dataset_selections"));assert.equal(selection?.values?.[3],"Client methodology exception");
    const audit=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.audit_events"));assert.equal(audit?.values?.[8],"Client methodology exception");
  });
  it("requires independent complete evidence and writes immutable review history",async()=>{const calls:string[]=[];const client={async query(sql:string){calls.push(sql);if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT version,enabled"))return{rows:[{version:3,enabled:true,calculated_tco2e:"12.3",override_tco2e:null,quality_tier:"measured",provenance_json:{calculatedBy:"consultant-a"}}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET review_status"))return{rows:[{version:4}]};return{rows:[]};},release(){}};const result=await approveScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:3,reviewerNote:"Evidence checked"},{...context,idempotencyKey:"review-a",actorId:"reviewer-a"});assert.equal(result.data.decision,"approved");assert.ok(calls.some(sql=>sql.includes("INSERT INTO nzi_console.scope_row_review_history")));await assert.rejects(()=>approveScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:3},{...context,idempotencyKey:"review-self",actorId:"consultant-a"}),CommandValidationError);});
  it("requires a note when rejecting",()=>assert.rejects(()=>rejectScopeRow(commandPool().pool,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:1,reviewerNote:""},{...context,idempotencyKey:"reject-empty"}),CommandValidationError));
  it("publishes only the exact validated report and supersedes the prior portal version",async()=>{const calls:string[]=[];const client={async query(sql:string){calls.push(sql);if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_id,status"))return{rows:[{job_id:"job-a",status:"validated",manifest_version:1,reviewed_snapshot_id:"snapshot-a"}]};if(sql.includes("RETURNING published_at"))return{rows:[{published_at:"2026-08-25T17:00:00.000Z"}]};return{rows:[]};},release(){}};const result=await publishCrpReport({connect:async()=>client} as never,{reportVersionId:"report-a",expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:"snapshot-a"},{...context,idempotencyKey:"publish-a"});assert.equal(result.data.status,"published");assert.ok(calls.some(sql=>sql.includes("status='superseded'")));assert.ok(calls.some(sql=>sql.includes("status='published'")));});
  it("does not request update-strength locks when reading an immutable reviewed snapshot",()=>{const source=String(validateCrpReport);assert.doesNotMatch(source,/reviewed_crp_snapshots[^`]*FOR SHARE/);});
  it("creates one content-addressed snapshot only from approved evidence",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT j.version"))return{rows:[{version:5,job_family:"crp",job_number:"J000717",reporting_year:2026,start_date:"2026-01-01",client_name:"Synthetic Client"}]};if(sql.includes("SELECT scope_row_id"))return{rows:[{scope_row_id:"row-a",version:4,scope:"1",source_label:"Synthetic fuel",asset_identifier:"METER-7",factor_source:"dataset",client_factor_id:null,is_custom_entry:false,apply_pct:"80",data_confidence:"H",source_quantity:"1250",source_unit:"kWh",column_text:"Stationary combustion",calculated_tco2e:"2.5",override_tco2e:null,factor_label:"Demo factor",factor_version:"v1",quality_tier:"measured",review_status:"approved",reviewed_by:"reviewer-a",enabled:true}]};if(sql.includes("SELECT snapshot_id"))return{rows:[]};if(sql.includes("coalesce(max(snapshot_version)"))return{rows:[{version:1}]};return{rows:[]};},release(){}};const result=await createReviewedCrpSnapshot({connect:async()=>client} as never,{jobId:"job-a",expectedJobVersion:5},{...context,idempotencyKey:"snapshot-a",actorId:"reviewer-a"});assert.equal(result.data.version,1);assert.match(result.data.dataHash,/^sha256:[0-9a-f]{64}$/);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.reviewed_crp_snapshots"));assert.ok(insert);const payload=JSON.parse(String(insert?.values?.[6]));assert.equal(payload.measurements[0].rowVersion,4);assert.equal(payload.measurements[0].assetIdentifier,"METER-7");assert.equal(payload.measurements[0].applyPct,80);assert.equal(payload.measurements[0].dataConfidence,"H");assert.equal(payload.measurements[0].sourceQuantity,1250);assert.equal(payload.measurements[0].columnText,"Stationary combustion");assert.equal(payload.measurements[0].reviewedBy,"reviewer-a");});
});
