import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { addManualDataset,approveScopeRow,calculateScopeRow, changeJobStage, CommandValidationError,createClientFactor,createEmissionSource,createEmissionSourceGroup, createJob,createReviewedCrpSnapshot, createScopeRow, IdempotencyConflictError,publishCrpReport,rejectScopeRow, runPostgresCommand,syncEmissionSourceToScope,updateEmissionSourceActivity,updateEmissionSourceStatus, updateScopeRow,validateCrpReport, VersionConflictError } from "../src/index";

const context = { organisationId: "org-a", actorId: "staff-a", principal: "staff" as const, idempotencyKey: "create-job-1", correlationId: "corr-create-job-1" };
const input = { clientId: "client-a", family: "crp" as const, title: "Synthetic CRP", workflowStage: "Setup", owner: "A. Owner", startDate: "2026-08-25", dueDate: "2026-12-31", reportingYear: 2026 };

function commandPool() {
  const calls: string[] = [];
  let stored: { request_hash: string; outcome_json: Record<string, unknown> } | undefined;
  let auditCount = 0;
  let outboxCount = 0;
  let allocationCount = 0;
  const client = {
    async query(sql: string, values?: readonly unknown[]) {
      calls.push(sql);
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: stored ? [stored] : [] };
      if (sql.includes("allocate_job_sequence")) { allocationCount += 1; return { rows: [{ sequence: 717 }] }; }
      if (sql.includes("INSERT INTO nzi_console.jobs")) return { rows: [{ job_number: "J000717" }] };
      if (sql.includes("INSERT INTO nzi_console.audit_events")) auditCount += 1;
      if (sql.includes("INSERT INTO nzi_console.transactional_outbox")) outboxCount += 1;
      if (sql.includes("INSERT INTO nzi_console.command_idempotency")) stored = { request_hash: String(values?.[3]), outcome_json: JSON.parse(String(values?.[4])) as Record<string, unknown> };
      return { rows: [] };
    },
    release() { calls.push("RELEASE"); },
  };
  return { pool: { connect: async () => client } as never, calls, metrics: () => ({ auditCount, outboxCount, allocationCount }) };
}

describe("Postgres command boundary", () => {
  it("creates and numbers a job once, then replays the stored outcome", async () => {
    const state = commandPool();
    const first = await createJob(state.pool, input, context);
    const replay = await createJob(state.pool, input, context);
    assert.equal(first.data.jobNumber, "J000717");
    assert.equal(first.replayed, false);
    assert.equal(replay.replayed, true);
    assert.equal(replay.data.jobNumber, "J000717");
    assert.deepEqual(state.metrics(), { auditCount: 1, outboxCount: 1, allocationCount: 1 });
  });

  it("rejects reuse of an idempotency key with a different request", async () => {
    const state = commandPool();
    await createJob(state.pool, input, context);
    await assert.rejects(() => createJob(state.pool, { ...input, title: "Different" }, context), IdempotencyConflictError);
  });

  it("rolls back the whole command when its handler fails", async () => {
    const state = commandPool();
    await assert.rejects(() => runPostgresCommand(state.pool, "client.create", { name: "Synthetic", status: "active", sector: "Services", location: "London", owner: "A. Owner" }, context, async () => { throw new Error("forced failure"); }));
    assert.ok(state.calls.includes("ROLLBACK"));
    assert.equal(state.calls.includes("COMMIT"), false);
    assert.deepEqual(state.metrics(), { auditCount: 0, outboxCount: 0, allocationCount: 0 });
  });

  it("moves a job one adjacent stage and records history in the same transaction", async () => {
    const calls: string[] = [];
    const client = { async query(sql: string) {
      calls.push(sql);
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] };
      if (sql.includes("SELECT job_family")) return { rows: [{ job_family: "crp", workflow_stage: "Data entry", version: 3 }] };
      if (sql.includes("UPDATE nzi_console.jobs SET workflow_stage")) return { rows: [{ version: 4 }] };
      return { rows: [] };
    }, release() {} };
    const result = await changeJobStage({ connect: async () => client } as never, { jobId: "712", fromStage: "Data entry", toStage: "Factor mapping", expectedVersion: 3, note: "Data collection complete" }, { ...context, idempotencyKey: "stage-1" });
    assert.equal(result.data.version, 4);
    assert.equal(result.data.toStage, "Factor mapping");
    assert.ok(calls.some((sql) => sql.includes("INSERT INTO nzi_console.job_stage_history")));
    assert.ok(calls.some((sql) => sql.includes("INSERT INTO nzi_console.audit_events")));
    assert.ok(calls.some((sql) => sql.includes("COMMIT")));
  });

  it("rejects stale versions and skipped stages", async () => {
    const poolFor = (version: number) => ({ connect: async () => ({ async query(sql: string) {
      if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] };
      if (sql.includes("SELECT job_family")) return { rows: [{ job_family: "crp", workflow_stage: "Data entry", version }] };
      return { rows: [] };
    }, release() {} }) }) as never;
    await assert.rejects(() => changeJobStage(poolFor(4), { jobId: "712", fromStage: "Data entry", toStage: "Factor mapping", expectedVersion: 3 }, { ...context, idempotencyKey: "stage-stale" }), VersionConflictError);
    await assert.rejects(() => changeJobStage(poolFor(3), { jobId: "712", fromStage: "Data entry", toStage: "Report & publish", expectedVersion: 3 }, { ...context, idempotencyKey: "stage-skip" }), CommandValidationError);
  });

  it("creates and version-updates canonical scope rows while invalidating stale calculations", async () => {
    const calls: Array<{ sql: string; values?: readonly unknown[] }> = [];
    const client = { async query(sql: string, values?: readonly unknown[]) { calls.push({ sql, values }); if (sql.includes("FROM nzi_console.command_idempotency")) return { rows: [] }; if (sql.includes("SELECT job_family FROM")) return { rows: [{ job_family: "crp" }] }; if (sql.includes("UPDATE nzi_console.job_scope_rows")) return { rows: [{ version: 2 }] }; return { rows: [] }; }, release() {} };
    const pool = { connect: async () => client } as never;
    const fields = { scope: "3.1", sourceLabel: "Synthetic purchased goods", assetIdentifier:"INV-BATCH-14", columnText:"Purchased materials", applyPct:75, dataConfidence:"H" as const, sourceQuantity:1600, sourceUnit:"GBP", notes:"Invoice batch checked", quantity: 1200, unit: "GBP", datasetId: "dataset-a", factorId: "factor-a", factorVersion: "2026 v1", factorLabel: "Synthetic factor", qualityTier: "spend-based" as const };
    const created = await createScopeRow(pool, { jobId: "job-a", ...fields }, { ...context, idempotencyKey: "scope-create" });
    const updated = await updateScopeRow(pool, { jobId: "job-a", rowId: created.data.rowId, expectedVersion: 1, enabled: true, ...fields, quantity: 1400 }, { ...context, idempotencyKey: "scope-update" });
    assert.equal(updated.data.version, 2);
    const updateSql = calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.sql ?? "";
    assert.match(updateSql, /calculated_tco2e=NULL/); assert.match(updateSql, /review_status='pending'/);assert.match(updateSql,/reviewed_by=NULL/);
    assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes("Invoice batch checked"));
    assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes("INV-BATCH-14"));
    for(const value of ["Purchased materials",75,"H",1600])assert.ok(calls.find((call) => call.sql.includes("UPDATE nzi_console.job_scope_rows"))?.values?.includes(value));
    assert.ok(calls.filter((call) => call.sql.includes("INSERT INTO nzi_console.audit_events")).length >= 2);
  });

  it("derives annual activity from reporting-period monthly slots",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-02-28"}]};return{rows:[]};},release(){}};await createScopeRow({connect:async()=>client} as never,{jobId:"job-a",scope:"1",sourceLabel:"Gas",quantity:999,unit:"kWh",datasetId:"dataset-a",factorId:"factor-a",factorVersion:"v1",factorLabel:"Gas factor",qualityTier:"measured",monthlyActivity:[{month:"2026-01",quantity:10},{month:"2026-02",quantity:20}]},{...context,idempotencyKey:"monthly-create"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.equal(insert?.values?.[7],30);assert.deepEqual(JSON.parse(String(insert?.values?.[21])),[{month:"2026-01",quantity:10},{month:"2026-02",quantity:20}]);});

  it("calculates with an eligible client factor and hashes its evidence into provenance",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT version,quantity"))return{rows:[{version:2,quantity:"500",unit:"unit",scope:"3.1",dataset_id:null,factor_id:"cf-a",factor_source:"client",client_factor_id:"cf-a",override_tco2e:null,override_reason:null,monthly_activity_json:[]}]};if(sql.includes("FROM nzi_console.client_factors cf"))return{rows:[{label:"Supplier EPD",activity_unit:"unit",kgco2e_per_unit:"12.4",version:"1",synthetic:false,evidence_hash:"sha256:epd"}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET factor_version"))return{rows:[{version:3,calculated_tco2e:"6.2"}]};return{rows:[]}},release(){}};const result=await calculateScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowId:"row-a",expectedVersion:2},{...context,idempotencyKey:"client-factor-calc"});assert.equal(result.data.calculatedTco2e,6.2);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET factor_version"));const provenance=JSON.parse(String(update?.values?.[6]));assert.equal(provenance.factorSource,"client");assert.equal(provenance.clientFactorId,"cf-a");assert.equal(provenance.evidenceHash,"sha256:epd");assert.ok(calls.some(call=>call.sql.includes("cf.job_id IS NULL OR cf.job_id=j.job_id")));});

  it("creates an audited reusable client factor with hashed evidence",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT client_id FROM"))return{rows:[{client_id:"client-a"}]};return{rows:[]}},release(){}};const result=await createClientFactor({connect:async()=>client} as never,{jobId:"job-a",scope:"3.1",reportLabel:"Supplier EPD",description:"Widget",unit:"unit",kgco2ePerUnit:12.4,geography:"gb",vintageYear:2026,source:"Supplier",reusable:true,evidenceFileName:"epd.pdf",evidenceStorageProvider:"sharepoint",evidenceUrl:null,evidenceExternalItemId:"doc-a",evidenceHash:"sha256:epd"},{...context,idempotencyKey:"client-factor-create"});assert.equal(result.data.label,"Supplier EPD");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.client_factors"));assert.equal(insert?.values?.[3],null);assert.ok(insert?.values?.includes("sha256:epd"));assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")));});

  it("creates audited emission-source groups and typed sources inside the job boundary",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_groups WHERE"))return{rows:[{exists:1}]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never;const group=await createEmissionSourceGroup(pool,{jobId:"job-a",name:"Employee commuting"},{...context,idempotencyKey:"source-group-create"});assert.equal(group.data.name,"Employee commuting");const source=await createEmissionSource(pool,{jobId:"job-a",groupId:"group-a",scope:"3.7",sourceType:"commuting",sourceSubtype:null,siteId:null,sourceName:"Employee A",assetIdentifier:"EMP-001",purchasedGoodsCategoryId:null,datasetId:null,factorId:null,factorSource:"dataset",clientFactorId:null,quantity:1200,unit:"km",applyPct:100,dataSource:"HR survey",dataConfidence:"M",monthlyActivity:[],detail:{kind:"commuting",vehicleRegistration:null,commuteMode:"rail",distanceUnit:"km",wfhDaysPerYear:80,wfhHoursPerDay:8,employeeName:"Employee A"},notes:null},{...context,idempotencyKey:"source-create"});assert.equal(source.data.sourceName,"Employee A");const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.values?.includes("EMP-001"));assert.ok(insert?.values?.some(value=>String(value).includes('"kind":"commuting"')));assert.ok(calls.filter(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")).length>=2);});

  it("validates and persists the controlled purchased-goods category on a spend source, and carries it into the synced row",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.purchased_goods_categories c JOIN"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_dataset_selections s JOIN nzi_console.emission_factors f"))return{rows:[{ok:1}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"src-spend",scope:"3.1",source_type:"spend",source_name:"Office paper",site_id:null,asset_identifier:null,purchased_goods_category_id:"pgs-paper",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1240",unit:"GBP",apply_pct:"100",data_source:"Spend ledger",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend"},notes:null,factor_label:"PG&S paper",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never;await createEmissionSource(pool,{jobId:"job-a",groupId:null,scope:"3.1",sourceType:"spend",sourceSubtype:"7504",siteId:null,sourceName:"Office paper",assetIdentifier:null,purchasedGoodsCategoryId:"pgs-paper",datasetId:"dataset-a",factorId:"factor-a",factorSource:"dataset",clientFactorId:null,quantity:1240,unit:"GBP",applyPct:100,dataSource:"Spend ledger",dataConfidence:null,monthlyActivity:[],detail:{kind:"spend",netValue:1240,vatPercent:20,glCode:"7504",category:"Paper"},notes:null},{...context,idempotencyKey:"spend-create"});const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_emission_sources"));assert.ok(insert?.sql.includes("purchased_goods_category_id"));assert.ok(insert?.values?.includes("pgs-paper"));assert.ok(calls.some(call=>call.sql.includes("FROM nzi_console.purchased_goods_categories c JOIN")));const sync=await syncEmissionSourceToScope(pool,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"spend-sync-2"});assert.equal(sync.data.created,true);const rowInsert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.ok(rowInsert?.sql.includes("purchased_goods_category_id"));assert.ok(rowInsert?.values?.includes("pgs-paper"));assert.ok(rowInsert?.values?.includes("spend-based"));});

  it("version-updates source activity and rejects stale edits",async()=>{let stale=false;const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:stale?[]:[{version:2}]};if(sql.includes("SELECT version FROM nzi_console.job_emission_sources"))return{rows:[{version:2}]};return{rows:[]}},release(){}};const pool={connect:async()=>client} as never,input={jobId:"job-a",sourceId:"source-a",expectedVersion:1,quantity:1500,unit:"km",applyPct:75,dataConfidence:"H" as const,monthlyActivity:[],notes:"Updated survey"};const result=await updateEmissionSourceActivity(pool,input,{...context,idempotencyKey:"source-update"});assert.equal(result.data.version,2);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_emission_sources"));assert.ok(update?.sql.includes("calculated_tco2e=NULL"));assert.ok(update?.sql.includes("review_status='pending'"));stale=true;await assert.rejects(()=>updateEmissionSourceActivity(pool,input,{...context,idempotencyKey:"source-update-stale"}),error=>error instanceof VersionConflictError&&error.message.includes("expected v1, found v2"));});

  it("derives source annual activity from reporting-period monthly slots",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-02-28"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:[{version:3}]};return{rows:[]}},release(){}};const result=await updateEmissionSourceActivity({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:2,quantity:999,unit:"km",applyPct:100,dataConfidence:"M" as const,monthlyActivity:[{month:"2026-01",quantity:100},{month:"2026-02",quantity:50}],notes:null},{...context,idempotencyKey:"source-monthly-update"});assert.equal(result.data.version,3);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_emission_sources"));assert.equal(update?.values?.[4],150);assert.deepEqual(JSON.parse(String(update?.values?.[8])),[{month:"2026-01",quantity:100},{month:"2026-02",quantity:50}]);});

  it("rejects source monthly slots that do not span the reporting period in order",async()=>{const client={async query(sql:string){if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT reporting_from"))return{rows:[{reporting_from:"2026-01-01",reporting_to:"2026-03-31"}]};return{rows:[]}},release(){}};await assert.rejects(()=>updateEmissionSourceActivity({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:2,quantity:null,unit:"km",applyPct:100,dataConfidence:null,monthlyActivity:[{month:"2026-01",quantity:10}],notes:null},{...context,idempotencyKey:"source-monthly-bad"}),error=>error instanceof CommandValidationError&&error.issues.some(issue=>issue.code==="REPORTING_PERIOD_MISMATCH"));});

  it("archives a source and excludes its canonical row in the same transaction",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("UPDATE nzi_console.job_emission_sources"))return{rows:[{version:4}]};return{rows:[]}},release(){}};const result=await updateEmissionSourceStatus({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a",expectedVersion:3,enabled:false},{...context,idempotencyKey:"source-archive"});assert.equal(result.data.enabled,false);const rowUpdate=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET enabled"));assert.equal(rowUpdate?.values?.[3],false);assert.ok(rowUpdate?.sql.includes("reviewed_row_version=NULL"));assert.ok(calls.some(call=>call.sql.includes("INSERT INTO nzi_console.audit_events")));});

  it("syncs a locked register source into its one auto-generated canonical row",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"source-a",scope:"3.7",source_name:"Employee A",site_id:null,asset_identifier:"EMP-001",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1200",unit:"km",apply_pct:"100",data_source:"HR survey",data_confidence:"M",monthly_activity_json:[],detail_json:{kind:"commuting"},notes:null,factor_label:"Travel",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[{scope_row_id:"row-a",version:2}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET"))return{rows:[{version:3}]};return{rows:[]}},release(){}};const result=await syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"source-a"},{...context,idempotencyKey:"source-sync"});assert.equal(result.data.created,false);assert.equal(result.data.version,3);const update=calls.find(call=>call.sql.includes("UPDATE nzi_console.job_scope_rows SET"));assert.ok(update?.sql.includes("is_auto_generated=true"));assert.ok(update?.values?.includes("source-a"));assert.ok(calls.some(call=>call.sql.includes("FOR UPDATE OF s")));});

  it("syncs a spend source into a new Scope 3.1 row carrying the spend-based quality tier",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[],client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.job_emission_sources s"))return{rows:[{source_id:"src-spend",scope:"3.1",source_type:"spend",source_name:"Office paper",site_id:null,asset_identifier:"2025-03-14",dataset_id:"dataset-a",factor_id:"factor-a",factor_source:"dataset",client_factor_id:null,quantity:"1240",unit:"GBP",apply_pct:"100",data_source:"Spend ledger",data_confidence:null,monthly_activity_json:[],detail_json:{kind:"spend",category:"Paper"},notes:null,factor_label:"PG&S paper",factor_version:"2026"}]};if(sql.includes("SELECT scope_row_id,version"))return{rows:[]};return{rows:[]}},release(){}};const result=await syncEmissionSourceToScope({connect:async()=>client} as never,{jobId:"job-a",sourceId:"src-spend"},{...context,idempotencyKey:"spend-sync"});assert.equal(result.data.created,true);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_scope_rows"));assert.ok(insert?.sql.includes("quality_tier"));assert.ok(insert?.values?.includes("spend-based"));assert.ok(insert?.values?.includes("3.1"));});

  it("records warned manual dataset exceptions with their dedicated audit reason", async () => {
    const calls:Array<{sql:string;values?:readonly unknown[]}>=[];
    const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("FROM nzi_console.emission_factor_datasets d"))return{rows:[{valid_from:"2026-01-01",valid_to:"2026-12-31",dataset_country:"US",status:"active",reporting_from:"2026-01-01",reporting_to:"2026-12-31",job_country:"GB"}]};if(sql.includes("INSERT INTO nzi_console.job_dataset_selections"))return{rows:[{dataset_id:"synthetic-us-2026"}]};return{rows:[]};},release(){}};
    const result=await addManualDataset({connect:async()=>client} as never,{jobId:"job-a",scope:"all",datasetId:"synthetic-us-2026",reportingFrom:"2026-01-01",reportingTo:"2026-12-31"},{...context,idempotencyKey:"dataset-manual",reason:"Client methodology exception"});
    assert.match(result.data.warnings[0]??"",/US.*GB/);
    const selection=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.job_dataset_selections"));assert.equal(selection?.values?.[3],"Client methodology exception");
    const audit=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.audit_events"));assert.equal(audit?.values?.[8],"Client methodology exception");
  });
  it("requires independent complete evidence and writes immutable review history",async()=>{const calls:string[]=[];const client={async query(sql:string){calls.push(sql);if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_family FROM"))return{rows:[{job_family:"crp"}]};if(sql.includes("SELECT version,enabled"))return{rows:[{version:3,enabled:true,calculated_tco2e:"12.3",override_tco2e:null,quality_tier:"measured",provenance_json:{calculatedBy:"consultant-a"}}]};if(sql.includes("UPDATE nzi_console.job_scope_rows SET review_status"))return{rows:[{version:4}]};return{rows:[]};},release(){}};const result=await approveScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:3,reviewerNote:"Evidence checked"},{...context,idempotencyKey:"review-a",actorId:"reviewer-a"});assert.equal(result.data.decision,"approved");assert.ok(calls.some(sql=>sql.includes("INSERT INTO nzi_console.scope_row_review_history")));await assert.rejects(()=>approveScopeRow({connect:async()=>client} as never,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:3},{...context,idempotencyKey:"review-self",actorId:"consultant-a"}),CommandValidationError);});
  it("requires a note when rejecting",()=>assert.rejects(()=>rejectScopeRow(commandPool().pool,{jobId:"job-a",rowIds:["row-a"],expectedReviewVersion:1,reviewerNote:""},{...context,idempotencyKey:"reject-empty"}),CommandValidationError));
  it("publishes only the exact validated report and supersedes the prior portal version",async()=>{const calls:string[]=[];const client={async query(sql:string){calls.push(sql);if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT job_id,status"))return{rows:[{job_id:"job-a",status:"validated",manifest_version:1,reviewed_snapshot_id:"snapshot-a"}]};if(sql.includes("RETURNING published_at"))return{rows:[{published_at:"2026-08-25T17:00:00.000Z"}]};return{rows:[]};},release(){}};const result=await publishCrpReport({connect:async()=>client} as never,{reportVersionId:"report-a",expectedStatus:"validated",manifestVersion:1,reviewedSnapshotId:"snapshot-a"},{...context,idempotencyKey:"publish-a"});assert.equal(result.data.status,"published");assert.ok(calls.some(sql=>sql.includes("status='superseded'")));assert.ok(calls.some(sql=>sql.includes("status='published'")));});
  it("does not request update-strength locks when reading an immutable reviewed snapshot",()=>{const source=String(validateCrpReport);assert.doesNotMatch(source,/reviewed_crp_snapshots[^`]*FOR SHARE/);});
  it("creates one content-addressed snapshot only from approved evidence",async()=>{const calls:Array<{sql:string;values?:readonly unknown[]}>=[];const client={async query(sql:string,values?:readonly unknown[]){calls.push({sql,values});if(sql.includes("FROM nzi_console.command_idempotency"))return{rows:[]};if(sql.includes("SELECT j.version"))return{rows:[{version:5,job_family:"crp",job_number:"J000717",reporting_year:2026,start_date:"2026-01-01",client_name:"Synthetic Client"}]};if(sql.includes("SELECT scope_row_id"))return{rows:[{scope_row_id:"row-a",version:4,scope:"1",source_label:"Synthetic fuel",asset_identifier:"METER-7",factor_source:"dataset",client_factor_id:null,is_custom_entry:false,apply_pct:"80",data_confidence:"H",source_quantity:"1250",source_unit:"kWh",column_text:"Stationary combustion",calculated_tco2e:"2.5",override_tco2e:null,factor_label:"Demo factor",factor_version:"v1",quality_tier:"measured",review_status:"approved",reviewed_by:"reviewer-a",enabled:true}]};if(sql.includes("SELECT snapshot_id"))return{rows:[]};if(sql.includes("coalesce(max(snapshot_version)"))return{rows:[{version:1}]};return{rows:[]};},release(){}};const result=await createReviewedCrpSnapshot({connect:async()=>client} as never,{jobId:"job-a",expectedJobVersion:5},{...context,idempotencyKey:"snapshot-a",actorId:"reviewer-a"});assert.equal(result.data.version,1);assert.match(result.data.dataHash,/^sha256:[0-9a-f]{64}$/);const insert=calls.find(call=>call.sql.includes("INSERT INTO nzi_console.reviewed_crp_snapshots"));assert.ok(insert);const payload=JSON.parse(String(insert?.values?.[6]));assert.equal(payload.measurements[0].rowVersion,4);assert.equal(payload.measurements[0].assetIdentifier,"METER-7");assert.equal(payload.measurements[0].applyPct,80);assert.equal(payload.measurements[0].dataConfidence,"H");assert.equal(payload.measurements[0].sourceQuantity,1250);assert.equal(payload.measurements[0].columnText,"Stationary combustion");assert.equal(payload.measurements[0].reviewedBy,"reviewer-a");});
});
