"use client";
import {FormEvent,useState} from "react";

export function PortalLoginForm(){
  const [challenge,setChallenge]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setPending(true);setError("");try{const form=new FormData(event.currentTarget),response=await fetch(challenge?"/api/portal/auth/mfa":"/api/portal/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(challenge?{challengeToken:challenge,code:form.get("code")}:{email:form.get("email"),password:form.get("password")})}),body=await response.json();if(!response.ok){setError(body.message??"Sign-in failed.");return}if(challenge){if(body.authenticated!==true)throw new Error();window.location.assign("/portal");return}if(body.mfaRequired!==true||typeof body.challengeToken!=="string"||!body.challengeToken.trim())throw new Error();setChallenge(body.challengeToken)}catch{setError("The secure client sign-in service could not verify the outcome. Please retry the current step.")}finally{setPending(false)}}
  function restart(){setChallenge("");setError("")}
  return <form onSubmit={submit} className="nz-auth-card"><div className="nz-auth-step"><span className="nz-eyebrow">Secure client workspace</span><span>Step {challenge?"2":"1"} of 2</span></div><h1>{challenge?"Verify your identity":"Client portal sign in"}</h1><p>{challenge?"Your password was accepted. Enter the six-digit code from your authenticator app.":"Use your independent NZI client portal account."}</p><div className="nz-auth-progress" aria-label={`Authentication step ${challenge?2:1} of 2`}><i className="done"/><i className={challenge?"done":""}/></div>{challenge?<label className="nz-fl">MFA code<input className="nz-inp num" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required disabled={pending} autoFocus/></label>:<><label className="nz-fl">Email<input className="nz-inp" name="email" type="email" autoComplete="username" required disabled={pending} autoFocus/></label><label className="nz-fl">Password<input className="nz-inp" name="password" type="password" autoComplete="current-password" required disabled={pending}/></label></>}{error?<div className="nz-banner warn" role="alert" style={{marginTop:14}}>{error}</div>:null}<button className="nz-btn pri nz-auth-submit" disabled={pending}>{pending?"Checking…":challenge?"Verify and continue":"Continue securely"}</button>{challenge?<button type="button" className="nz-auth-secondary" disabled={pending} onClick={restart}>Use another client account</button>:null}<div className="nz-auth-support"><b>{challenge?"Authenticator unavailable?":"Forgotten your password?"}</b><span>Contact your NZI representative. Portal credentials and MFA can only be reset through the governed client-access process.</span></div></form>
}
