import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {it} from "node:test";

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8"),styles=read("../../../packages/ui/src/styles.css"),charts=read("../../../packages/charts/src/ManifestChartSet.tsx"),layout=read("../app/portal/layout.tsx"),workspace=read("../app/portal-preview/PortalWorkspace.tsx"),login=read("../app/portal/login/PortalLoginForm.tsx"),root=read("../app/layout.tsx");
it("provides one keyboard skip target across every client portal route",()=>{assert.match(layout,/className="nz-skip-link"/);assert.match(layout,/href="#portal-route-content"/);assert.match(layout,/id="portal-route-content"/);assert.match(layout,/tabIndex=\{-1\}/);});
it("preserves skip navigation as the initial portal login focus",()=>{assert.match(login,/querySelector<HTMLAnchorElement>\("\.nz-skip-link"\)\?\.focus\(\)/);});
it("implements the ARIA tab keyboard pattern for the report workspace",()=>{for(const token of ['role="tablist"','role="tab"','role="tabpanel"','aria-selected','aria-controls','aria-labelledby','tabIndex={tab===item.id?0:-1}','ArrowLeft','ArrowRight','Home','End'])assert.ok(workspace.includes(token),token);});
it("keeps focus visible for links, buttons, inputs, selects and textareas",()=>{for(const selector of ["a:focus-visible","button:focus-visible",".nz-inp:focus-visible",".nz-sel:focus-visible",".nz-notes:focus-visible",'[role="tab"]:focus-visible'])assert.ok(styles.includes(selector),selector);assert.match(styles,/outline:3px solid #0B7A4B/);});
it("uses contrast-safe primary controls and removes nonessential motion",()=>{assert.match(styles,/\.nz-btn\.pri\{background:var\(--pine\).*color:#fff/);assert.match(styles,/\.nz-portal-brand>span\{[^}]*color:#052E1F/);assert.match(styles,/@media \(prefers-reduced-motion:reduce\)/);assert.match(styles,/transition-duration:\.01ms!important/);});
it("declares the document language",()=>{assert.match(root,/<html lang="en"/);});
it("defines coherent tablet, phone and narrow-phone portal layouts",()=>{assert.match(styles,/@media \(max-width:900px\)[\s\S]*\.nz-portal-summary\{grid-template-columns:repeat\(2/);assert.match(styles,/@media \(max-width:900px\)[\s\S]*\.nz-portal-job\{grid-template-columns:72px 1fr/);assert.match(styles,/@media \(max-width:680px\)[\s\S]*\.nz-published-main form\.nz-panel\{grid-template-columns:1fr!important/);assert.match(styles,/@media \(max-width:420px\)[\s\S]*\.nz-portal-summary\{grid-template-columns:1fr/);});
it("contains report navigation, charts and immutable identifiers within narrow viewports",()=>{assert.match(styles,/\.nz-portal-tabs\{max-width:100%;overflow-x:auto/);assert.match(styles,/@media\(max-width:820px\)\{\.nz-chart-manifest-grid\.two-column\{grid-template-columns:minmax\(0,1fr\)\}\}/);assert.match(charts,/className=\{`nz-chart-manifest-grid/);assert.match(styles,/\.nz-document-proof dd\{overflow-wrap:anywhere;word-break:break-word\}/);});
