import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,it} from "node:test";

const root=process.cwd();
const read=(path:string)=>readFileSync(join(root,path),"utf8");
const routes=["apps/console/app/clients/page.tsx","apps/console/app/clients/[clientId]/page.tsx","apps/console/app/jobs/page.tsx","apps/console/app/jobs/[jobId]/page.tsx","apps/console/app/datasets/page.tsx","apps/console/app/reports/page.tsx","apps/console/app/reports/[versionId]/page.tsx","apps/console/app/platform/page.tsx"];

// The client page renders through these; they carry its empty states and must not reach for stand-in data.
const clientWorkspace=["apps/console/app/clients/[clientId]/ClientWorkspaceView.tsx","apps/console/app/clients/[clientId]/ClientSites.tsx","apps/console/app/clients/[clientId]/FigureEvidence.tsx","apps/console/app/clients/[clientId]/ClientContacts.tsx","apps/console/app/clients/[clientId]/ClientIdentity.tsx"];

describe("staff workspace acceptance contracts",()=>{
  it("gates each client-workspace control on the capability its command enforces (NZC-022)",()=>{const view=read("apps/console/app/clients/[clientId]/ClientWorkspaceView.tsx");for(const capability of ["site.manage","contact.manage","client.edit"])assert.ok(view.includes(`useEditAccess(\"${capability}\"`),capability);assert.doesNotMatch(read("apps/console/app/lib/useEditAccess.ts"),/permissions?.includes/);});
  it("shows contact role badges and the v9 role checkboxes, removing by deactivation (client workspace v9)",()=>{const source=read("apps/console/app/clients/[clientId]/ClientContacts.tsx");for(const token of ["nz-rolebadges","nz-tag rr","Primary","nz-rolechk","Primary contact","/deactivate","Save contact","Signee appears on published reports"])assert.ok(source.includes(token),token);});
  it("edits the financial year end as a month and uploads the logo with a monogram fallback (client workspace v9)",()=>{const source=read("apps/console/app/clients/[clientId]/ClientIdentity.tsx");for(const token of ["Financial year end","MONTHS.map","300–400 day rule","⭱ Upload logo","clientLogoContentTypes","monogram(client.name)","onError"])assert.ok(source.includes(token),token);assert.ok(read("apps/console/app/lib/LogoMark.tsx").includes("monogramOf(name)"));for(const surface of ["apps/console/app/portal/PortalHome.tsx","apps/console/app/reports/[versionId]/page.tsx","apps/console/app/portal/jobs/[jobId]/print/page.tsx"])assert.ok(read(surface).includes("<LogoMark"),surface);});
  it("renders each client from its own resolved figures and sites — no shared mock evidence or sites (NZC-005/070)",()=>{for(const file of ["apps/console/app/clients/[clientId]/page.tsx",...clientWorkspace]){const source=read(file);assert.doesNotMatch(source,/clientFigureEvidence|clientSites|documentHistory|financials/,file)}});
  it("keeps every canonical staff workspace free of mock record fallbacks",()=>{for(const route of routes){const source=read(route);assert.doesNotMatch(source,/loadFixtureScreen|fixtureClients|fixtureJobs|reportVersions|reportTemplates|platformServices|staffRoles|datasetAuditIssues/ ,route)}});
  it("loads live staff resources through the isolated boundary",()=>{for(const route of routes){const source=read(route);if(route.endsWith("reports/page.tsx"))continue;assert.match(source,/loadScreen|LiveReportRegister/,route)}});
  it("protects governance reads with staff identity and tenant context",()=>{for(const route of ["datasets","platform-governance","audit-events","report-versions"]){const source=read(`apps/console/app/api/isolated/${route}/route.ts`);assert.match(source,/currentStaff\(request\)/,route);assert.match(source,/withTenantRead/,route);assert.match(source,/private, no-store/,route)}});
  it("returns every collection required by the platform screen contract",()=>{const source=read("apps/console/app/api/isolated/platform-governance/route.ts");for(const token of ["listStaffRoleGovernance","auditEventsFor","roles,services,events"])assert.ok(source.includes(token),token)});
  it("provides shared keyboard focus, skip navigation, reduced motion and responsive breakpoints",()=>{const shell=read("packages/ui/src/index.tsx"),styles=read("packages/ui/src/styles.css");assert.match(shell,/className="nz-skip-link"/);assert.match(shell,/id="nzi-main-content"/);for(const token of ["a:focus-visible","button:focus-visible",'[role="tab"]:focus-visible',"prefers-reduced-motion:reduce","max-width:1200px","max-width:900px","max-width:680px","max-width:420px"])assert.ok(styles.includes(token),token)});
  it("exposes honest empty and failure states instead of inferred records",()=>{const combined=[...routes,"apps/console/app/datasets/DatasetBoard.tsx",...clientWorkspace].map(read).join("\n");for(const token of ["No engagements","No sites configured","No governed factor datasets","Live report version unavailable"])assert.ok(combined.includes(token),token)});
});
