import {createPortalDataEntryRecord,deletePortalDataEntryRecord,listPortalDataEntryRecords,PortalAccessValidationError,submitPortalDataEntryRecord,updatePortalDataEntryRecord,VersionConflictError} from "@nzi/isolated-backend";
import {portalAuthFailure} from "../../../../../lib/authResponse";
import {isolatedPool} from "../../../../../lib/isolatedDatabase";
import {currentPortalUser,requirePortalOrigin} from "../../../../../lib/portalSession";
const failure=(error:unknown)=>error instanceof VersionConflictError?Response.json({code:"VERSION_CONFLICT",message:error.message},{status:409}):error instanceof PortalAccessValidationError?Response.json({code:"INVALID_DATA_ENTRY_RECORD",message:error.message},{status:422}):portalAuthFailure(error);
export async function GET(request:Request,{params}:{params:Promise<{jobId:string}>}){try{const user=await currentPortalUser(request),{jobId}=await params;return Response.json({records:await listPortalDataEntryRecords(isolatedPool(),user,jobId)},{headers:{"Cache-Control":"private, no-store"}});}catch(error){return failure(error)}}
export async function POST(request:Request,{params}:{params:Promise<{jobId:string}>}){try{requirePortalOrigin(request);const user=await currentPortalUser(request),{jobId}=await params,body=await request.json() as Record<string,unknown>;if(body.action==="submit"&&typeof body.recordId==="string"&&typeof body.expectedVersion==="number")return Response.json(await submitPortalDataEntryRecord(isolatedPool(),user,jobId,body.recordId,body.expectedVersion),{headers:{"Cache-Control":"no-store"}});if(typeof body.bucketGrantId!=="string"||typeof body.quantity!=="number"||typeof body.unit!=="string"||typeof body.factorId!=="string")throw new PortalAccessValidationError("A bucket, quantity, unit and factor are required.");const result=await createPortalDataEntryRecord(isolatedPool(),user,jobId,{bucketGrantId:body.bucketGrantId,quantity:body.quantity,unit:body.unit,factorId:body.factorId,siteId:typeof body.siteId==="string"?body.siteId:null,note:typeof body.note==="string"?body.note:"",detail:body.detail});return Response.json(result,{status:201,headers:{"Cache-Control":"no-store"}});}catch(error){return failure(error)}}
export async function PATCH(request:Request,{params}:{params:Promise<{jobId:string}>}){try{requirePortalOrigin(request);const user=await currentPortalUser(request),{jobId}=await params,body=await request.json() as Record<string,unknown>;if(typeof body.recordId!=="string"||typeof body.expectedVersion!=="number"||typeof body.bucketGrantId!=="string"||typeof body.quantity!=="number"||typeof body.unit!=="string"||typeof body.factorId!=="string")throw new PortalAccessValidationError("A record version and complete authorised entry are required.");return Response.json(await updatePortalDataEntryRecord(isolatedPool(),user,jobId,body.recordId,body.expectedVersion,{bucketGrantId:body.bucketGrantId,quantity:body.quantity,unit:body.unit,factorId:body.factorId,siteId:typeof body.siteId==="string"?body.siteId:null,note:typeof body.note==="string"?body.note:"",detail:body.detail}),{headers:{"Cache-Control":"no-store"}});}catch(error){return failure(error)}}
export async function DELETE(request:Request,{params}:{params:Promise<{jobId:string}>}){try{requirePortalOrigin(request);const user=await currentPortalUser(request),{jobId}=await params,body=await request.json() as Record<string,unknown>;if(typeof body.recordId!=="string"||typeof body.expectedVersion!=="number")throw new PortalAccessValidationError("A record and expected version are required.");return Response.json(await deletePortalDataEntryRecord(isolatedPool(),user,jobId,body.recordId,body.expectedVersion),{headers:{"Cache-Control":"no-store"}});}catch(error){return failure(error)}}
