import {headers} from "next/headers";
import Link from "next/link";
import {redirect} from "next/navigation";
import type {PublishedCrpReportReadModel} from "@nzi/contracts";
import type {PortalReportApproval} from "@nzi/isolated-backend";
import {PortalWorkspace} from "../../../portal-preview/PortalWorkspace";
export const dynamic="force-dynamic";
export default async function PortalReportPage({params}:{params:Promise<{jobId:string}>}){const {jobId}=await params,cookie=(await headers()).get("cookie"),base=(process.env.NZI_ISOLATED_API_URL??"").replace(/\/$/,"");let response:Response;try{response=await fetch(`${base}/api/portal/jobs/${jobId}/published-report`,{cache:"no-store",headers:cookie?{cookie}:{}})}catch{return <ReportState jobId={jobId} state="failed"/>}if(response.status===401)redirect(`/portal/login?next=${encodeURIComponent(`/portal/jobs/${jobId}`)}`);if(!response.ok)return <ReportState jobId={jobId} state={response.status===403?"denied":response.status===404?"missing":"failed"}/>;let body:unknown;try{body=await response.json()}catch{return <ReportState jobId={jobId} state="failed"/>}if(!isReportBody(body))return <ReportState jobId={jobId} state="failed"/>;return <PortalWorkspace report={body.report} approval={body.approval} clientMode/>}

function isReportBody(value:unknown):value is {report:PublishedCrpReportReadModel;approval:PortalReportApproval|null}{if(!value||typeof value!=="object")return false;const candidate=value as {report?:Partial<PublishedCrpReportReadModel>;approval?:Partial<PortalReportApproval>|null},report=candidate.report,snapshot=report?.snapshot,approval=candidate.approval;if(!report||typeof report.reportVersionId!=="string"||typeof report.publishedAt!=="string"||typeof report.dataHash!=="string"||typeof report.manifestVersion!=="number"||!snapshot||typeof snapshot.id!=="string"||typeof snapshot.jobId!=="string"||typeof snapshot.jobNumber!=="string"||typeof snapshot.client!=="string"||typeof snapshot.reportingYear!=="number"||typeof snapshot.createdAt!=="string"||typeof snapshot.dataHash!=="string"||!Array.isArray(snapshot.measurements))return false;return approval===null||(Boolean(approval)&&typeof approval?.approvalId==="string"&&approval.reportVersionId===report.reportVersionId&&typeof approval.approvedAt==="string")}
function ReportState({jobId,state}:{jobId:string;state:"denied"|"missing"|"failed"}){const denied=state==="denied",missing=state==="missing";return <main className="nz-portal-report-state"><section className={denied||missing?"unavailable":"failed"} role={denied||missing?"status":"alert"}><i>{denied?"×":missing?"—":"!"}</i><div><span className="nz-eyebrow">Published report</span><h1>{denied?"This report is not granted to your account.":missing?"No published report is available yet.":"The published report could not be loaded."}</h1><p>{denied?"Ask your NZI adviser to review your job-level access.":missing?"Your NZI team will release the verified version when assurance is complete.":"No conclusion has been made about your access or the report’s publication state."}</p><div><Link className="nz-btn" href="/portal">Back to reporting jobs</Link>{!denied&&!missing?<Link className="nz-btn pri" href={`/portal/jobs/${jobId}`}>Try again</Link>:null}</div></div></section></main>}
