import {crpProfessionalManifest} from "@nzi/charts";
import type {PublishedCrpReportReadModel,ReviewedCrpSnapshotReadModel} from "@nzi/contracts";
import type {PortalReportApproval} from "@nzi/isolated-backend";

type Snapshot=ReviewedCrpSnapshotReadModel;
const finiteNonNegative=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value)&&value>=0;
const positiveVersion=(value:unknown):value is number=>Number.isInteger(value)&&Number(value)>0;
const validDate=(value:unknown):value is string=>typeof value==="string"&&Number.isFinite(Date.parse(value));

function isMeasurement(value:unknown){if(!value||typeof value!=="object")return false;const row=value as Snapshot["measurements"][number];return typeof row.rowId==="string"&&row.rowId.length>0&&positiveVersion(row.rowVersion)&&(row.scope==="1"||row.scope==="2"||row.scope==="3")&&typeof row.sourceLabel==="string"&&row.sourceLabel.length>0&&finiteNonNegative(row.tco2e)&&typeof row.factorSet==="string"&&row.factorSet.length>0&&(["measured","estimated","spend-based","survey"] as const).includes(row.qualityTier)&&typeof row.reviewedBy==="string"&&row.reviewedBy.length>0}
function isTarget(value:unknown,jobId:string){if(value===null)return true;if(!value||typeof value!=="object")return false;const target=value as NonNullable<Snapshot["target"]>;return target.jobId===jobId&&Number.isInteger(target.baselineYear)&&finiteNonNegative(target.baselineTco2e)&&Number.isInteger(target.interimYear)&&finiteNonNegative(target.interimReductionPercent)&&target.interimReductionPercent<=100&&Number.isInteger(target.netZeroYear)&&target.baselineYear<=target.interimYear&&target.interimYear<=target.netZeroYear&&positiveVersion(target.version)&&validDate(target.updatedAt)&&typeof target.updatedBy==="string"&&target.updatedBy.length>0}
function isIntensityTarget(value:unknown,jobId:string){if(value===null)return true;if(!value||typeof value!=="object")return false;const target=value as NonNullable<Snapshot["intensityTarget"]>;return target.jobId===jobId&&(["turnover","employee","floor-area"] as const).includes(target.metric)&&typeof target.denominatorUnit==="string"&&target.denominatorUnit.length>0&&typeof target.reportingDenominator==="number"&&Number.isFinite(target.reportingDenominator)&&target.reportingDenominator>0&&Number.isInteger(target.baselineYear)&&finiteNonNegative(target.baselineIntensity)&&Number.isInteger(target.interimYear)&&finiteNonNegative(target.interimReductionPercent)&&target.interimReductionPercent<=100&&Number.isInteger(target.netZeroYear)&&target.baselineYear<=target.interimYear&&target.interimYear<=target.netZeroYear&&positiveVersion(target.version)&&validDate(target.updatedAt)&&typeof target.updatedBy==="string"&&target.updatedBy.length>0}
function isAnnualComparison(value:unknown){if(!Array.isArray(value))return false;const years=new Set<number>();for(const item of value){if(!item||typeof item!=="object")return false;const comparison=item as Snapshot["annualComparison"][number];if(!Number.isInteger(comparison.year)||years.has(comparison.year)||typeof comparison.sourceSnapshotId!=="string"||comparison.sourceSnapshotId.length===0||typeof comparison.sourceDataHash!=="string"||comparison.sourceDataHash.length===0||!Array.isArray(comparison.values)||comparison.values.length!==3)return false;years.add(comparison.year);const scopes=new Set<string>();for(const point of comparison.values){if(!point||typeof point!=="object"||(point.scope!=="1"&&point.scope!=="2"&&point.scope!=="3")||scopes.has(point.scope)||!finiteNonNegative(point.value))return false;scopes.add(point.scope)}}return true}

export function isPublishedCrpReport(value:unknown,expectedJobId:string):value is PublishedCrpReportReadModel{if(!value||typeof value!=="object")return false;const report=value as Partial<PublishedCrpReportReadModel>,snapshot=report.snapshot as Partial<Snapshot>|undefined,measurements=snapshot?.measurements,publishedAt=validDate(report.publishedAt)?Date.parse(report.publishedAt):NaN,createdAt=validDate(snapshot?.createdAt)?Date.parse(snapshot.createdAt):NaN;if(typeof report.reportVersionId!=="string"||report.reportVersionId.length===0||!Number.isFinite(publishedAt)||typeof report.dataHash!=="string"||report.dataHash.length===0||report.manifestVersion!==crpProfessionalManifest.version||!snapshot||typeof snapshot.id!=="string"||snapshot.id.length===0||snapshot.jobId!==expectedJobId||typeof snapshot.jobNumber!=="string"||snapshot.jobNumber.length===0||typeof snapshot.client!=="string"||snapshot.client.length===0||!Number.isInteger(snapshot.reportingYear)||!positiveVersion(snapshot.version)||!positiveVersion(snapshot.jobVersion)||!Number.isFinite(createdAt)||publishedAt<createdAt||typeof snapshot.createdBy!=="string"||snapshot.createdBy.length===0||typeof snapshot.dataHash!=="string"||snapshot.dataHash.length===0||report.dataHash!==snapshot.dataHash||!Array.isArray(measurements)||!measurements.every(isMeasurement)||new Set(measurements.map(row=>row.rowId)).size!==measurements.length||!isTarget(snapshot.target,expectedJobId)||!isIntensityTarget(snapshot.intensityTarget,expectedJobId)||!isAnnualComparison(snapshot.annualComparison))return false;return true}
export function isPortalReportApproval(value:unknown,reportVersionId:string):value is PortalReportApproval{if(!value||typeof value!=="object")return false;const approval=value as Partial<PortalReportApproval>;return typeof approval.approvalId==="string"&&approval.approvalId.length>0&&approval.reportVersionId===reportVersionId&&validDate(approval.approvedAt)&&approval.statementVersion===1}
