"use client";
import { useState } from "react";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { assessmentReadiness, type LcaAssessment, type LcaLineItem, type MappingState } from "@nzi/mock-data";
import { LcaStageBar, RENDERER_VERSION, TOKENS_VERSION, type LcaStageBarData } from "@nzi/charts";
import { NAV, USER } from "../lib/nav";

type View = "inventory" | "transport" | "scenarios";
type Filter = "all" | MappingState;
const unavailable = "This workflow is not connected in the isolated staging environment.";

export function LcaBoard({ assessments }: { assessments: LcaAssessment[] }) {
  const [assessmentId, setAssessmentId] = useState(assessments[0]?.id ?? "");
  const [selectedLineId, setSelectedLineId] = useState(assessments[0]?.lines[0]?.id ?? "");
  const [view, setView] = useState<View>("inventory");
  const [filter, setFilter] = useState<Filter>("all");
  if(assessments.length===0)return <AppShell rail={<WorkspaceRail sections={NAV} activeId="lca" user={USER}/>}><TopBar searchPlaceholder="Search assessments…" crumbs={<><b>LCA / PCF / CBAM</b><span className="muted">/</span> Assessments</>}/><div className="nz-head"><div className="nz-eyebrow">Product assurance</div><h1>Life-cycle assessments</h1><div className="sub">Product footprints, boundaries, inventory evidence and scenarios</div></div><div className="nz-body nz-lca-empty"><section><i>0</i><div><h2>No assessments available</h2><p>Create an LCA or PCF engagement before importing a bill of materials or modelling product impacts.</p><a className="nz-btn pri" href="/jobs">Open engagements</a></div></section></div></AppShell>;
  const assessment = assessments.find((item) => item.id === assessmentId) ?? assessments[0]!;
  const selectedLine = assessment.lines.find((line) => line.id === selectedLineId) ?? assessment.lines[0];
  const readiness = assessmentReadiness(assessment);
  const inventoryComplete = assessment.lines.length > 0 && readiness.unmappedLines === 0 && readiness.reviewLines === 0;
  const transportComplete = assessment.transportLegs > 0 && assessment.mappedTransportLegs === assessment.transportLegs;
  const modelReady = inventoryComplete && transportComplete;
  const stageValues = Object.entries(assessment.lines.reduce<Record<string,{value:number;provisional:boolean}>>((totals,line)=>{const current=totals[line.module]??{value:0,provisional:false};current.value+=line.kgCo2e??0;current.provisional ||= line.mappingState!=="mapped";totals[line.module]=current;return totals},{}));
  const stageChart:LcaStageBarData={spec:{id:"lca_stage_bar",type:"lca_stage_bar",title:"Life-cycle impact by module",subtitle:assessment.boundary,family:assessment.kind==="pcf"?"pcf":"lca",specVersion:1},unit:"kgCO₂e",functionalUnit:assessment.functionalUnit,state:readiness.unmappedLines?"degraded":"success",stateMessage:readiness.unmappedLines?"Includes provisional inventory lines.":undefined,provenance:{jobId:assessment.id,dataHash:`assessment:${assessment.id}:${assessment.updatedAt}`,factorSets:[...new Set(assessment.lines.map(line=>line.dataset).filter((value):value is string=>Boolean(value)))],generatedAt:assessment.updatedAt,reviewedSnapshotId:assessment.id,resolverVersion:1,tokensVersion:TOKENS_VERSION,rendererVersion:RENDERER_VERSION},stages:stageValues.map(([module,value])=>({id:module,label:module,value:value.value,status:value.provisional?"provisional":"modelled"}))};
  const lines = filter === "all" ? assessment.lines : assessment.lines.filter((line) => line.mappingState === filter);
  const chooseAssessment = (id: string) => { const next = assessments.find((item) => item.id === id); if(!next)return; setAssessmentId(id); setSelectedLineId(next.lines[0]?.id??""); };

  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="lca" user={USER} />} drawer={selectedLine?<EvidenceDrawer kicker={`${assessment.kind.toUpperCase()} evidence`} title={selectedLine.component} subtitle={`${selectedLine.module} · ${selectedLine.mappingState}`} actions={<><button className="nz-btn" disabled title={unavailable}>View source</button><button className="nz-btn pri" disabled title={unavailable}>Review mapping</button></>}><LineEvidence line={selectedLine} /></EvidenceDrawer>:undefined}>
    <TopBar searchPlaceholder="Search assessments, products, BOM lines…" crumbs={<><b>LCA / PCF / CBAM</b> <span className="muted">/</span> Assessments</>} />
    <div className="nz-head"><div className="nz-job-titleline"><div><div className="nz-eyebrow">{assessment.kind.toUpperCase()} · {assessment.jobNumber}</div><h1>{assessment.product}</h1><div className="sub">{assessment.client} · {assessment.boundary} · {assessment.standard}</div></div><div className="nz-head-actions"><label className="nz-sr-only" htmlFor="assessment-select">Assessment</label><select id="assessment-select" className="nz-btn" value={assessmentId} onChange={(event) => chooseAssessment(event.target.value)}>{assessments.map((item) => <option key={item.id} value={item.id}>{item.jobNumber} · {item.product}</option>)}</select><button className="nz-btn pri" disabled title={unavailable}>Import BOM</button></div></div></div>
    <div className="nz-body" style={{ paddingTop: 18 }}>
      <section className="nz-ops-hero"><div><span className="nz-eyebrow light">Product impact command centre</span><h2>{modelReady?"The model is ready for report validation.":assessment.lines.length===0?"Inventory evidence is required before assurance.":`${readiness.unmappedLines + readiness.reviewLines} inventory line${readiness.unmappedLines + readiness.reviewLines===1?"":"s"} and ${assessment.transportLegs-assessment.mappedTransportLegs} transport leg${assessment.transportLegs-assessment.mappedTransportLegs===1?"":"s"} remain unresolved.`}</h2><p>Connect bill-of-materials evidence, transport, factor confidence and scenarios without losing source provenance.</p></div><div className="nz-ops-trust"><span><i>{assessment.boundary.trim()?"✓":"·"}</i> Boundary explicit</span><span><i>{inventoryComplete?"✓":"·"}</i> Factors confirmed</span><span><i>{assessment.scenarios.length?"✓":"·"}</i> Scenarios recorded</span></div></section>
      <div className="nz-metrics"><Metric label="Mapping coverage" value={`${readiness.inventoryPct}%`} /><Metric label="Mapped / review" value={`${readiness.mappedLines} / ${readiness.reviewLines}`} /><Metric label="Transport coverage" value={`${readiness.transportPct}%`} /><Metric label="Scenarios" value={`${assessment.scenarios.length}`} /></div>
      {assessment.lines.length?<div style={{marginBottom:18}}><LcaStageBar data={stageChart}/></div>:<div className="nz-banner warn nz-lca-no-inventory"><div><b>No inventory evidence loaded.</b><div>Readiness and impact results remain unavailable until bill-of-materials lines are imported.</div></div></div>}
      <div className="nz-toolbar" style={{ padding: "18px 0 12px" }}><div className="nz-filters">{(["inventory", "transport", "scenarios"] as View[]).map((id) => <button type="button" key={id} aria-pressed={view === id} className={view === id ? "on" : undefined} onClick={() => setView(id)}>{id}</button>)}</div><span style={{ marginLeft: "auto", fontSize: 12, color: "var(--t3)" }}>Updated {assessment.updatedAt} · {assessment.owner}</span></div>
      {view === "inventory" && <><div className="nz-toolbar" style={{ padding: "0 0 10px" }}><div className="nz-filters">{(["all", "mapped", "review", "unmapped"] as Filter[]).map((id) => <button type="button" key={id} aria-pressed={filter === id} className={filter === id ? "on" : undefined} onClick={() => setFilter(id)}>{id}</button>)}</div><span className="sub" style={{ marginLeft: "auto" }}>{lines.length} line{lines.length === 1 ? "" : "s"}</span></div><div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Component</th><th>Supplier</th><th>Module</th><th className="num">Quantity</th><th>Factor / dataset</th><th>Confidence</th><th className="num">kgCO₂e</th><th>Status</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id} tabIndex={0} aria-selected={line.id === selectedLine?.id} className={`row${line.id === selectedLine?.id ? " sel" : ""}`} onClick={() => setSelectedLineId(line.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedLineId(line.id); } }}><td style={{ fontWeight: 600 }}>{line.component}<div className="muted" style={{ fontSize: 11 }}>{line.category}</div></td><td>{line.supplier}</td><td>{line.module}</td><td className="num">{line.quantity} {line.unit}</td><td>{line.factor ?? "No factor selected"}<div className="muted" style={{ fontSize: 11 }}>{line.dataset ?? "—"}</div></td><td><span className={`nz-st ${line.confidence === "high" ? "done" : line.confidence === "medium" ? "est" : "nof"}`}>{line.confidence}</span></td><td className="num">{line.kgCo2e?.toFixed(1) ?? "—"}</td><td><span className={`nz-st ${line.mappingState === "mapped" ? "done" : line.mappingState === "review" ? "est" : "need"}`}>{line.mappingState}</span></td></tr>)}</tbody></table>{lines.length === 0 ? <div className="nz-table-empty">{assessment.lines.length===0?"No inventory evidence has been imported.":"No inventory lines match this mapping state."}</div> : null}</div></>}
      {view === "transport" && <div className="nz-panel" style={{ padding: 22 }}><h2 style={{ marginTop: 0 }}>Transport inventory</h2><div className={`nz-banner ${readiness.transportPct === 100 ? "ok" : "warn"}`}><div><b>{assessment.mappedTransportLegs} of {assessment.transportLegs} legs mapped.</b><div style={{ marginTop: 4 }}>Routes retain origin, destination, distance method, vehicle/load assumptions, factor version and reviewer evidence.</div></div></div><button className="nz-btn pri" disabled title={unavailable}>Open transport legs</button></div>}
      {view === "scenarios" && <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Scenario</th><th>Modelling note</th><th className="num">kgCO₂e / functional unit</th><th className="num">Change</th><th>Readiness</th></tr></thead><tbody>{assessment.scenarios.map((scenario) => <tr key={scenario.id}><td style={{ fontWeight: 600 }}>{scenario.name}</td><td>{scenario.note}</td><td className="num">{scenario.kgCo2e.toFixed(1)}</td><td className="num" style={{ color: scenario.deltaPct < 0 ? "var(--green)" : undefined }}>{scenario.deltaPct === 0 ? "Baseline" : `${scenario.deltaPct}%`}</td><td><span className={`nz-st ${modelReady ? "done" : "est"}`}>{modelReady ? "reportable" : "provisional"}</span></td></tr>)}</tbody></table>{assessment.scenarios.length===0?<div className="nz-table-empty">No scenarios have been recorded for this assessment.</div>:null}</div>}
      <section className={`nz-lca-readiness ${modelReady ? "ok" : "warn"}`} aria-live="polite"><div><span className="nz-eyebrow">Assurance gate</span><h2>{assessment.lines.length===0?"Report release is blocked pending inventory evidence.":modelReady?"The model is ready for report validation.":"Report release remains blocked."}</h2><p>{assessment.lines.length===0?"No inventory lines exist, so the model cannot claim calculation or reporting readiness.":modelReady?"Every inventory mapping is confirmed and every recorded transport leg is mapped.":`${readiness.unmappedLines} unmapped, ${readiness.reviewLines} awaiting review, and ${assessment.transportLegs-assessment.mappedTransportLegs} transport legs unresolved.`} Scenario results stay provisional whenever the baseline contains unresolved factors or transport legs.</p></div><div className="nz-lca-readiness-score"><strong className="num">{readiness.inventoryPct}%</strong><span>mapping coverage</span></div></section>
    </div>
  </AppShell>;
}

function LineEvidence({ line }: { line: LcaLineItem }) { return <><div className={`nz-banner ${line.mappingState === "mapped" ? "ok" : "warn"}`}><div><b>{line.mappingState === "mapped" ? "Factor mapping is calculation-ready." : line.mappingState === "review" ? "Mapping requires reviewer confirmation." : "Excluded until a factor is selected."}</b></div></div><div className="nz-kv"><span className="k">Supplier</span><span className="v">{line.supplier}</span></div><div className="nz-kv"><span className="k">Quantity</span><span className="v num">{line.quantity} {line.unit}</span></div><div className="nz-kv"><span className="k">Life-cycle module</span><span className="v">{line.module}</span></div><div className="nz-kv"><span className="k">Factor</span><span className="v">{line.factor ?? "Not mapped"}</span></div><div className="nz-kv"><span className="k">Dataset</span><span className="v">{line.dataset ?? "—"}</span></div><div className="nz-kv"><span className="k">Confidence</span><span className="v">{line.confidence}</span></div><div className="nz-kv"><span className="k">Result</span><span className="v num">{line.kgCo2e === null ? "Excluded" : `${line.kgCo2e.toFixed(1)} kgCO₂e`}</span></div><div className="nz-sect">Source evidence</div><p style={{ fontSize: 12, color: "var(--t2)", lineHeight: 1.5 }}>{line.evidence}</p></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="nz-metric"><div className="l">{label}</div><div className="v num">{value}</div></div>; }
