"use client";
import { useMemo, useState } from "react";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { assessmentReadiness, type LcaAssessment, type LcaLineItem, type MappingState } from "@nzi/mock-data";
import { NAV, USER } from "../lib/nav";

type View = "inventory" | "transport" | "scenarios";
type Filter = "all" | MappingState;

export function LcaBoard({ assessments }: { assessments: LcaAssessment[] }) {
  const [assessmentId, setAssessmentId] = useState(assessments[0]!.id);
  const [selectedLineId, setSelectedLineId] = useState(assessments[0]!.lines[0]!.id);
  const [view, setView] = useState<View>("inventory");
  const [filter, setFilter] = useState<Filter>("all");
  const assessment = assessments.find((item) => item.id === assessmentId) ?? assessments[0]!;
  const selectedLine = assessment.lines.find((line) => line.id === selectedLineId) ?? assessment.lines[0]!;
  const readiness = assessmentReadiness(assessment);
  const lines = useMemo(() => filter === "all" ? assessment.lines : assessment.lines.filter((line) => line.mappingState === filter), [assessment, filter]);
  const chooseAssessment = (id: string) => { const next = assessments.find((item) => item.id === id)!; setAssessmentId(id); setSelectedLineId(next.lines[0]!.id); };

  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="lca" user={USER} />} drawer={<EvidenceDrawer kicker={`${assessment.kind.toUpperCase()} evidence`} title={selectedLine.component} subtitle={`${selectedLine.module} · ${selectedLine.mappingState}`} actions={<><button className="nz-btn">View source</button><button className="nz-btn pri">Review mapping</button></>}><LineEvidence line={selectedLine} /></EvidenceDrawer>}>
    <TopBar searchPlaceholder="Search assessments, products, BOM lines…" crumbs={<><b>LCA / PCF / CBAM</b> <span className="muted">/</span> Assessments</>} />
    <div className="nz-head"><div style={{ display: "flex", gap: 18, alignItems: "flex-start" }}><div><div className="eyebrow">{assessment.kind.toUpperCase()} · {assessment.jobNumber}</div><h1 style={{ marginTop: 3 }}>{assessment.product}</h1><div className="sub">{assessment.client} · {assessment.boundary} · {assessment.standard}</div></div><select className="nz-btn" style={{ marginLeft: "auto" }} value={assessmentId} onChange={(event) => chooseAssessment(event.target.value)}>{assessments.map((item) => <option key={item.id} value={item.id}>{item.jobNumber} · {item.product}</option>)}</select><button className="nz-btn pri">Import BOM</button></div></div>
    <div className="nz-body" style={{ paddingTop: 18 }}>
      <div className="nz-metrics"><Metric label="Inventory readiness" value={`${readiness.inventoryPct}%`} /><Metric label="Mapped / review" value={`${readiness.mappedLines} / ${readiness.reviewLines}`} /><Metric label="Transport coverage" value={`${readiness.transportPct}%`} /><Metric label="Scenarios" value={`${assessment.scenarios.length}`} /></div>
      <div className="nz-toolbar" style={{ padding: "18px 0 12px" }}><div className="nz-filters">{(["inventory", "transport", "scenarios"] as View[]).map((id) => <button key={id} className={view === id ? "on" : undefined} onClick={() => setView(id)}>{id}</button>)}</div><span style={{ marginLeft: "auto", fontSize: 12, color: "var(--t3)" }}>Updated {assessment.updatedAt} · {assessment.owner}</span></div>
      {view === "inventory" && <><div className="nz-toolbar" style={{ padding: "0 0 10px" }}><div className="nz-filters">{(["all", "mapped", "review", "unmapped"] as Filter[]).map((id) => <button key={id} className={filter === id ? "on" : undefined} onClick={() => setFilter(id)}>{id}</button>)}</div></div><div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Component</th><th>Supplier</th><th>Module</th><th className="num">Quantity</th><th>Factor / dataset</th><th>Confidence</th><th className="num">kgCO₂e</th><th>Status</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id} className={`row${line.id === selectedLine.id ? " sel" : ""}`} onClick={() => setSelectedLineId(line.id)}><td style={{ fontWeight: 600 }}>{line.component}<div className="muted" style={{ fontSize: 11 }}>{line.category}</div></td><td>{line.supplier}</td><td>{line.module}</td><td className="num">{line.quantity} {line.unit}</td><td>{line.factor ?? "No factor selected"}<div className="muted" style={{ fontSize: 11 }}>{line.dataset ?? "—"}</div></td><td><span className={`nz-st ${line.confidence === "high" ? "done" : line.confidence === "medium" ? "est" : "nof"}`}>{line.confidence}</span></td><td className="num">{line.kgCo2e?.toFixed(1) ?? "—"}</td><td><span className={`nz-st ${line.mappingState === "mapped" ? "done" : line.mappingState === "review" ? "est" : "need"}`}>{line.mappingState}</span></td></tr>)}</tbody></table></div></>}
      {view === "transport" && <div className="nz-panel" style={{ padding: 22 }}><h2 style={{ marginTop: 0 }}>Transport inventory</h2><div className={`nz-banner ${readiness.transportPct === 100 ? "ok" : "warn"}`}><div><b>{assessment.mappedTransportLegs} of {assessment.transportLegs} legs mapped.</b><div style={{ marginTop: 4 }}>Routes retain origin, destination, distance method, vehicle/load assumptions, factor version and reviewer evidence.</div></div></div><button className="nz-btn pri">Open transport legs</button></div>}
      {view === "scenarios" && <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Scenario</th><th>Modelling note</th><th className="num">kgCO₂e / functional unit</th><th className="num">Change</th><th>Readiness</th></tr></thead><tbody>{assessment.scenarios.map((scenario) => <tr key={scenario.id}><td style={{ fontWeight: 600 }}>{scenario.name}</td><td>{scenario.note}</td><td className="num">{scenario.kgCo2e.toFixed(1)}</td><td className="num" style={{ color: scenario.deltaPct < 0 ? "var(--green)" : undefined }}>{scenario.deltaPct === 0 ? "Baseline" : `${scenario.deltaPct}%`}</td><td><span className={`nz-st ${readiness.unmappedLines ? "est" : "done"}`}>{readiness.unmappedLines ? "provisional" : "reportable"}</span></td></tr>)}</tbody></table></div>}
      <div style={{ marginTop: 18 }} className={`nz-banner ${readiness.unmappedLines ? "warn" : "ok"}`}><div><b>{readiness.unmappedLines ? `${readiness.unmappedLines} inventory line requires a factor before report release.` : "Inventory is ready for report validation."}</b><div style={{ marginTop: 4 }}>Scenario results remain provisional whenever their baseline contains unresolved factors or transport legs.</div></div></div>
    </div>
  </AppShell>;
}

function LineEvidence({ line }: { line: LcaLineItem }) { return <><div className={`nz-banner ${line.mappingState === "mapped" ? "ok" : "warn"}`}><div><b>{line.mappingState === "mapped" ? "Factor mapping is calculation-ready." : line.mappingState === "review" ? "Mapping requires reviewer confirmation." : "Excluded until a factor is selected."}</b></div></div><div className="nz-kv"><span className="k">Supplier</span><span className="v">{line.supplier}</span></div><div className="nz-kv"><span className="k">Quantity</span><span className="v num">{line.quantity} {line.unit}</span></div><div className="nz-kv"><span className="k">Life-cycle module</span><span className="v">{line.module}</span></div><div className="nz-kv"><span className="k">Factor</span><span className="v">{line.factor ?? "Not mapped"}</span></div><div className="nz-kv"><span className="k">Dataset</span><span className="v">{line.dataset ?? "—"}</span></div><div className="nz-kv"><span className="k">Confidence</span><span className="v">{line.confidence}</span></div><div className="nz-kv"><span className="k">Result</span><span className="v num">{line.kgCo2e === null ? "Excluded" : `${line.kgCo2e.toFixed(1)} kgCO₂e`}</span></div><div className="nz-sect">Source evidence</div><p style={{ fontSize: 12, color: "var(--t2)", lineHeight: 1.5 }}>{line.evidence}</p></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="nz-metric"><div className="l">{label}</div><div className="v num">{value}</div></div>; }
