"use client";

import {useCallback,useEffect,useState} from "react";
import {postBrowserCommand} from "@nzi/api-client";
import {crpProfessionalManifest} from "@nzi/charts";
import type {ReviewedCrpSnapshotReadModel} from "@nzi/contracts";
import type {ReportVersionRegisterItem} from "@nzi/isolated-backend";

const message=(result:{state:string;message?:string;issues?:Array<{message:string}>})=>result.state==="validation_failed"?(result.issues?.[0]?.message??"Validation failed."):(result.message??"Command failed.");

export function CrpReleaseControl({jobId,readyForReporting}:{jobId:string;readyForReporting:boolean}){
  const [snapshots,setSnapshots]=useState<ReviewedCrpSnapshotReadModel[]>([]),[reports,setReports]=useState<ReportVersionRegisterItem[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [snapshotResponse,reportResponse]=await Promise.all([fetch(`/api/isolated/jobs/${jobId}/reviewed-snapshots`,{cache:"no-store"}),fetch("/api/isolated/report-versions",{cache:"no-store"})]),snapshotBody=await snapshotResponse.json(),reportBody=await reportResponse.json();if(!snapshotResponse.ok||!reportResponse.ok)throw new Error(snapshotBody.message??reportBody.message??"Publication evidence is unavailable.");setSnapshots(Array.isArray(snapshotBody.snapshots)?snapshotBody.snapshots:[]);setReports(Array.isArray(reportBody.reports)?reportBody.reports.filter((report:ReportVersionRegisterItem)=>report.jobId===jobId):[]);}catch(error){setNotice({ok:false,text:error instanceof Error?error.message:"Publication evidence is unavailable."});}finally{setLoading(false);}},[jobId]);
  useEffect(()=>{void load();},[load]);
  const snapshot=snapshots[0],validated=snapshot?reports.find(report=>report.snapshotId===snapshot.id&&report.status==="validated"):undefined,published=snapshot?reports.find(report=>report.snapshotId===snapshot.id&&report.status==="published"):undefined;
  async function validate(){if(!snapshot||pending)return;setPending(true);setNotice(null);const result=await postBrowserCommand<{reportVersionId:string}>("/api/isolated/reports/validate",{reviewedSnapshotId:snapshot.id,manifestVersion:crpProfessionalManifest.version},crypto.randomUUID());setPending(false);if(result.state!=="success")return setNotice({ok:false,text:message(result)});setNotice({ok:true,text:"The reviewed snapshot passed the governed report manifest and an immutable validated version was created."});await load();}
  async function publish(){if(!snapshot||!validated||pending)return;setPending(true);setNotice(null);const result=await postBrowserCommand<{reportVersionId:string}>("/api/isolated/reports/publish",{reportVersionId:validated.reportVersionId,expectedStatus:"validated",manifestVersion:validated.manifestVersion,reviewedSnapshotId:snapshot.id},crypto.randomUUID());setPending(false);if(result.state!=="success")return setNotice({ok:false,text:message(result)});setNotice({ok:true,text:"The exact validated version was published to authorised client portal users."});await load();}
  return <section className="nz-panel nz-config-panel" aria-busy={loading||pending}><div className="nz-config-head"><div><span className="nz-eyebrow">Controlled release</span><b>Validate and publish</b><div className="sub">The latest reviewed snapshot must pass the shared CRP manifest before its exact immutable version can be released.</div></div><span className={`nz-st ${published?"done":validated?"est":"need"}`}>{published?"Published":validated?"Validated":snapshot?"Snapshot ready":"Snapshot required"}</span></div>{loading?<div className="nz-register-loading" role="status"><i/><span><b>Loading release evidence</b><small>Checking snapshots and report versions…</small></span></div>:<div className="nz-release-lineage"><div><span>Reviewed snapshot</span><b>{snapshot?`v${snapshot.version} · ${snapshot.id.slice(0,8)}`:"Not created"}</b></div><i>→</i><div><span>Manifest</span><b>CRP professional v{crpProfessionalManifest.version}</b></div><i>→</i><div><span>Release</span><b>{published?.reportVersionId??validated?.reportVersionId??"Not validated"}</b></div></div>}{notice&&<div className={`nz-banner ${notice.ok?"ok":"warn"}`} role={notice.ok?"status":"alert"}>{notice.text}</div>}<div className="nz-config-actions"><button className="nz-btn" disabled={pending||!snapshot||Boolean(validated)||Boolean(published)} onClick={validate}>{pending?"Working…":"Validate latest snapshot"}</button><button className="nz-btn pri" disabled={pending||!validated||Boolean(published)} onClick={publish}>{published?"Published":pending?"Working…":"Publish validated version"}</button></div>{!snapshot&&<div className="nz-hint">{readyForReporting?"Create a reviewed snapshot from an approved scope row to begin release.":"Complete calculation and independent QA before creating a reviewed snapshot."}</div>}</section>;
}
