"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { patchBrowserCommand, postBrowserCommand } from "@nzi/api-client";
import type { ScopeQualityTier, ScopeRowReadModel, ScopeRowWriteFields } from "@nzi/contracts";
import type { FamilyJob } from "@nzi/mock-data";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { NAV, USER } from "../lib/nav";
import { WorkflowStageControl } from "./WorkflowStageControl";

const blank = (): ScopeRowWriteFields => ({ scope: "1", sourceLabel: "", quantity: null, unit: null, datasetId: null, factorId: null, factorVersion: null, factorLabel: null, qualityTier: null });
const qualityOptions: Array<{ value: ScopeQualityTier; label: string }> = [{ value: "measured", label: "Measured" }, { value: "estimated", label: "Estimated" }, { value: "spend-based", label: "Spend-based" }, { value: "survey", label: "Survey" }];
const number = (value: string) => value.trim() === "" ? null : Number(value);
const rowInput = (row: ScopeRowReadModel): ScopeRowWriteFields => ({ scope: row.scope, sourceLabel: row.sourceLabel, quantity: row.quantity, unit: row.unit, datasetId: row.datasetId, factorId: row.factorId, factorVersion: row.factorVersion, factorLabel: row.factorLabel, qualityTier: row.qualityTier });

export function CrpScopeWorkspace({ job, rows }: { job: FamilyJob; rows: ScopeRowReadModel[] }) {
  const router = useRouter(); const [selectedId, setSelectedId] = useState(rows[0]?.id ?? ""); const [creating, setCreating] = useState(rows.length === 0); const [draft, setDraft] = useState(blank()); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<{ kind: "ok" | "warn"; text: string } | null>(null);
  const selected = rows.find((row) => row.id === selectedId) ?? rows[0];
  async function createRow(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setNotice(null); const result = await postBrowserCommand<{ rowId: string }>(`/api/isolated/jobs/${job.header.id}/scope-rows`, draft, crypto.randomUUID()); setPending(false); if (result.state === "success") { setSelectedId(result.data.rowId); setCreating(false); setDraft(blank()); setNotice({ kind: "ok", text: "Scope row created. It remains pending until activity and factor evidence are complete." }); router.refresh(); return; } setNotice({ kind: "warn", text: result.state === "validation_failed" ? result.issues[0]?.message ?? result.message : result.message }); }
  const drawer = selected ? <EvidenceDrawer kicker={`Scope row · version ${selected.version}`} title={selected.sourceLabel} subtitle={`Scope ${selected.scope}`}><RowEditor key={`${selected.id}-${selected.version}`} jobId={job.header.id} row={selected} onNotice={setNotice} /><div className="nz-sect">Calculation lineage</div>{selected.lineage.length ? selected.lineage.map((step, index) => <div className="nz-lin" key={`${step.title}-${index}`}><div className="stepl">{step.title}<small>{step.detail}</small></div></div>) : <div className="muted" style={{ fontSize: 12 }}>No calculation lineage yet. A calculated result will not be asserted until activity and factor resolution are complete.</div>}<div className="nz-sect">Provenance</div>{Object.entries(selected.provenance).map(([key, value]) => <div className="nz-kv" key={key}><span className="k">{key}</span><span className="v">{value === null ? "—" : String(value)}</span></div>)}</EvidenceDrawer> : undefined;
  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="jobs" user={USER} />} drawer={drawer}>
    <TopBar searchPlaceholder="Search sources, factors…" crumbs={<>Jobs <span className="muted">/</span> <b>{job.header.number}</b> <span className="muted">/</span> Scope rows</>} />
    <div className="nz-head"><div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}><div><h1>{job.header.number} — {job.header.title}</h1><div className="sub">{job.header.client} · canonical job_scope_rows · owner: {job.header.owner}</div></div><button className="nz-btn pri" style={{ marginLeft: "auto" }} onClick={() => setCreating((value) => !value)}>{creating ? "Close" : "Add source"}</button></div></div>
    <WorkflowStageControl job={job} />
    <div className="nz-body" style={{ paddingTop: 16 }}>
      {notice && <div className={`nz-banner ${notice.kind}`}><div>{notice.text}</div></div>}
      {creating && <form className="nz-panel" style={{ padding: 16, marginBottom: 16 }} onSubmit={createRow}><b>Add emissions source</b><div className="sub" style={{ marginTop: 4 }}>Create the activity row first; factor resolution and calculation remain explicit later steps.</div><ScopeFields value={draft} onChange={setDraft} /><div style={{ display: "flex", justifyContent: "flex-end", marginTop: 14 }}><button className="nz-btn pri" disabled={pending}>{pending ? "Creating…" : "Create scope row"}</button></div></form>}
      {rows.length === 0 ? <div className="nz-panel" style={{ padding: 28, textAlign: "center" }}><h2 style={{ margin: 0, fontSize: 18 }}>No scope rows yet</h2><p className="sub">Add the first emissions source. An empty dataset is shown as empty—not as zero emissions.</p></div> : <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Source</th><th>Scope</th><th className="num">Activity</th><th>Unit</th><th>Factor</th><th>Quality</th><th className="num">tCO₂e</th><th>Review</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className={`row${row.id === selected?.id ? " sel" : ""}`} onClick={() => setSelectedId(row.id)}><td style={{ fontWeight: 500 }}>{row.sourceLabel}{!row.enabled && <span className="muted"> · disabled</span>}</td><td>Scope {row.scope}</td><td className="num">{row.quantity ?? <span className="muted">—</span>}</td><td>{row.unit ?? <span className="muted">—</span>}</td><td>{row.factorLabel ?? <span className="nz-st nof">No factor</span>}</td><td>{qualityOptions.find((item) => item.value === row.qualityTier)?.label ?? <span className="muted">Not set</span>}</td><td className="num">{row.overrideTco2e ?? row.calculatedTco2e ?? <span className="muted">—</span>}</td><td><span className={`nz-st ${row.reviewStatus === "approved" ? "done" : "est"}`}>{row.reviewStatus}</span></td></tr>)}</tbody></table></div>}
    </div>
  </AppShell>;
}

function ScopeFields({ value, onChange }: { value: ScopeRowWriteFields; onChange: (value: ScopeRowWriteFields) => void }) { return <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(160px, 1fr))", gap: 12, marginTop: 14 }}><label className="nz-fl" style={{ margin: 0 }}>Source label<input className="nz-inp" required value={value.sourceLabel} onChange={(event) => onChange({ ...value, sourceLabel: event.target.value })} /></label><label className="nz-fl" style={{ margin: 0 }}>Scope<input className="nz-inp" required placeholder="1, 2, 3.1…" value={value.scope} onChange={(event) => onChange({ ...value, scope: event.target.value })} /></label><label className="nz-fl" style={{ margin: 0 }}>Quality<select className="nz-sel" value={value.qualityTier ?? ""} onChange={(event) => onChange({ ...value, qualityTier: event.target.value ? event.target.value as ScopeQualityTier : null })}><option value="">Not set</option>{qualityOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="nz-fl" style={{ margin: 0 }}>Quantity<input className="nz-inp" type="number" min="0" step="any" value={value.quantity ?? ""} onChange={(event) => onChange({ ...value, quantity: number(event.target.value) })} /></label><label className="nz-fl" style={{ margin: 0 }}>Unit<input className="nz-inp" value={value.unit ?? ""} onChange={(event) => onChange({ ...value, unit: event.target.value || null })} /></label><label className="nz-fl" style={{ margin: 0 }}>Dataset ID<input className="nz-inp" value={value.datasetId ?? ""} onChange={(event) => onChange({ ...value, datasetId: event.target.value || null })} /></label><label className="nz-fl" style={{ margin: 0 }}>Factor ID<input className="nz-inp" value={value.factorId ?? ""} onChange={(event) => onChange({ ...value, factorId: event.target.value || null })} /></label><label className="nz-fl" style={{ margin: 0 }}>Factor label<input className="nz-inp" value={value.factorLabel ?? ""} onChange={(event) => onChange({ ...value, factorLabel: event.target.value || null })} /></label><label className="nz-fl" style={{ margin: 0 }}>Factor version<input className="nz-inp" value={value.factorVersion ?? ""} onChange={(event) => onChange({ ...value, factorVersion: event.target.value || null })} /></label></div>; }

function RowEditor({ jobId, row, onNotice }: { jobId: string; row: ScopeRowReadModel; onNotice: (notice: { kind: "ok" | "warn"; text: string }) => void }) { const router = useRouter(); const [value, setValue] = useState(rowInput(row)); const [enabled, setEnabled] = useState(row.enabled); const [pending, setPending] = useState(false); async function save() { setPending(true); const result = await patchBrowserCommand<{ version: number }>(`/api/isolated/jobs/${jobId}/scope-rows/${row.id}`, { ...value, enabled, expectedVersion: row.version }, crypto.randomUUID()); setPending(false); if (result.state === "success") { onNotice({ kind: "ok", text: `Scope row saved as version ${result.data.version}; calculation and review were reset pending.` }); router.refresh(); return; } onNotice({ kind: "warn", text: result.state === "validation_failed" ? result.issues[0]?.message ?? result.message : result.message }); }
  return <><div className={`nz-banner ${row.calculatedTco2e === null ? "warn" : "ok"}`}><div>{row.calculatedTco2e === null ? "No current calculated result. This row is excluded from asserted totals until calculation completes." : "A calculated result is available with evidence."}</div></div><ScopeFields value={value} onChange={setValue} /><label style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 12, fontSize: 12 }}><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} />Enabled for this job</label><div style={{ display: "flex", justifyContent: "flex-end", marginTop: 14 }}><button className="nz-btn pri" disabled={pending} onClick={save}>{pending ? "Saving…" : "Save and invalidate calculation"}</button></div></>; }
