"use client";
import { useMemo,useState,type ReactNode } from "react";
import { addManualDataset,datasets,recommendDatasets,type DatasetSelection,type Job } from "@nzi/mock-data";
import { ManifestChartSet,crpChartSamples,crpProfessionalManifest,reviewedCrpSnapshotSample,validateManifest } from "@nzi/charts";

export type CrpStage="scope"|"data"|"mapping"|"review"|"report";
const context={reportingFrom:"2024-01-01",reportingTo:"2024-12-31",country:"GB"};
export function CrpWorkspacePanel({stage,job}:{stage:CrpStage;job:Job}){if(stage==="scope")return <ScopeConfiguration/>;if(stage==="data")return <ImportWorkspace job={job}/>;if(stage==="mapping")return <FactorMapping job={job}/>;if(stage==="review")return <ReviewQueue job={job}/>;return <ReportPublish/>}

function ScopeConfiguration(){const automatic=useMemo(()=>recommendDatasets(context),[]),[manual,setManual]=useState<DatasetSelection[]>([]),[datasetId,setDatasetId]=useState("epa-2024"),[reason,setReason]=useState(""),[error,setError]=useState("");function add(){try{setManual(items=>[...items,addManualDataset(datasetId,context,reason)]);setReason("");setError("")}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}}return <WorkspacePanel eyebrow="Calculation boundary" title="Scope and datasets" subtitle="The reporting period selects applicable factor datasets. Every manual exception remains explicit and auditable." state={<span className="nz-st done">Period matched</span>}>
  <div className="nz-metrics"><Metric label="Reporting from" value="1 Jan 2024"/><Metric label="Reporting to" value="31 Dec 2024"/><Metric label="Geography" value="United Kingdom"/><Metric label="Included scopes" value="1 · 2 · 3"/></div>
  <PanelSection title="Automatically selected" description="Recommendations are resolved from period, geography and included scopes."><DatasetTable selections={automatic}/></PanelSection>
  <PanelSection title="Manual dataset exception" description="A reason is required and retained with the selection."><div className="nz-dataset-add"><label className="nz-fl">Dataset<select className="nz-sel" value={datasetId} onChange={e=>setDatasetId(e.target.value)}>{datasets.map(d=><option key={d.id} value={d.id}>{d.name} · {d.version} · {d.country}</option>)}</select></label><label className="nz-fl">Justification<input className={`nz-inp${error?" bad":""}`} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason required for manual addition" aria-describedby={error?"dataset-error":undefined}/></label><button className="nz-btn pri" onClick={add}>Add dataset</button></div>{error&&<div id="dataset-error" className="nz-hint bad" role="alert">{error}</div>}{manual.length>0&&<div className="nz-section-result"><DatasetTable selections={manual}/></div>}</PanelSection>
 </WorkspacePanel>}

function DatasetTable({selections}:{selections:DatasetSelection[]}){return <div className="nz-table-wrap"><table className="nz-tbl"><thead><tr><th>Dataset</th><th>Version</th><th>Scopes</th><th>Method</th><th>Selection</th><th>Validation</th></tr></thead><tbody>{selections.map(item=><tr key={`${item.source}-${item.dataset.id}`}><td><b>{item.dataset.name}</b></td><td>{item.dataset.version}</td><td>{item.dataset.scopes.join(", ")}</td><td>{item.dataset.method}</td><td><span className={`nz-st ${item.source==="automatic"?"done":"est"}`}>{item.source}</span></td><td>{item.warnings.length?<><span className="nz-st nof">Review required</span><div className="nz-cell-note">{item.warnings.join(" ")}</div></>:<span className="nz-st done">Matched</span>}</td></tr>)}</tbody></table></div>}

function ImportWorkspace({job}:{job:Job}){return <WorkspacePanel eyebrow="Controlled ingestion" title="Data collection and import" subtitle="Preflight validates structure, units and duplicates before any activity rows are committed." state={<span className="nz-st nof">7 exceptions</span>}><div className="nz-metrics"><Metric label="Template" value="CRP 2024 · v3"/><Metric label="Rows detected" value="214"/><Metric label="Ready to import" value="207"/><Metric label="Needs attention" value="7"/></div><div className="nz-banner warn"><div><b>Preflight only — no data committed.</b><div>Seven rows need unit or duplicate resolution before import can proceed.</div></div></div><ActionBar><button className="nz-btn">Download template</button><button className="nz-btn">Run preflight</button><button className="nz-btn pri">Commit {job.rows.length} validated examples</button></ActionBar></WorkspacePanel>}

function FactorMapping({job}:{job:Job}){const missing=job.rows.filter(row=>!row.factorMatched);return <WorkspacePanel eyebrow="Calculation lineage" title="Factor mapping" subtitle="Automatic matches use the governed dataset set; exceptions retain their reason and provenance." state={<span className={`nz-st ${missing.length?"nof":"done"}`}>{missing.length?`${missing.length} unmatched`:"Mapping complete"}</span>}><div className="nz-metrics"><Metric label="Rows" value={`${job.counts.all}`}/><Metric label="Matched" value={`${job.rows.filter(row=>row.factorMatched).length}`}/><Metric label="Unmatched" value={`${missing.length}`}/><Metric label="Dataset exceptions" value="0"/></div><div className="nz-exception-list">{missing.map(row=><div className="nz-banner warn" key={row.id}><div><b>{row.source}</b><div>{row.factorText}</div></div><button className="nz-btn pri">Match factor</button></div>)}</div></WorkspacePanel>}

function ReviewQueue({job}:{job:Job}){const review=job.rows.filter(row=>row.status!=="complete"||row.quality==="Estimated"||row.quality==="Spend-based");return <WorkspacePanel eyebrow="Independent assurance" title="Review and QA" subtitle="Review covers unresolved activity data, estimates, spend proxies and material overrides." state={<span className={`nz-st ${review.length?"est":"done"}`}>{review.length?`${review.length} pending`:"Review complete"}</span>}><div className="nz-metrics"><Metric label="Pending review" value={`${review.length}`}/><Metric label="Estimated" value={`${job.counts.estimated}`}/><Metric label="Needs data" value={`${job.counts.needs}`}/><Metric label="Overrides" value="0"/></div><div className="nz-table-wrap"><table className="nz-tbl"><thead><tr><th>Source</th><th>Scope</th><th>Quality</th><th>Result (tCO₂e)</th><th>QA state</th></tr></thead><tbody>{review.map(row=><tr key={row.id}><td><b>{row.source}</b></td><td>{row.scope}</td><td>{row.quality}</td><td className="num">{row.tco2e??"—"}</td><td><span className={`nz-st ${row.status==="needs"?"nof":"est"}`}>{row.status==="needs"?"Blocked":"Review"}</span></td></tr>)}</tbody></table></div></WorkspacePanel>}

function ReportPublish(){const [published,setPublished]=useState(false),charts=crpChartSamples,validation=validateManifest(crpProfessionalManifest,charts,reviewedCrpSnapshotSample.id);return <WorkspacePanel eyebrow="Release control" title="Report, validation and portal release" subtitle="One manifest and one validator govern the report, PDF and client portal publication." state={<span className={`nz-st ${validation.valid?"done":"nof"}`}>{validation.valid?"Manifest valid":"Publication blocked"}</span>}><div className="nz-release-lineage"><div><span>Manifest</span><b>CRP professional v{validation.manifestVersion}</b></div><i>→</i><div><span>Reviewed snapshot</span><b>{validation.reviewedSnapshotId}</b></div><i>→</i><div><span>Release</span><b>{published?"CRP-J000712-v1":"Not published"}</b></div></div><ManifestChartSet manifest={crpProfessionalManifest} charts={charts} reviewedSnapshotId={reviewedCrpSnapshotSample.id}/><div className={`nz-banner ${published?"ok":"warn"}`}><div><b>{published?"Published to the client portal.":"Validated and ready to publish."}</b><div>{published?"Immutable report version CRP-J000712-v1 was created from the reviewed snapshot.":"Publication creates an immutable version and releases that exact version to authorised portal users."}</div></div></div><ActionBar><a className="nz-btn" href="/report-preview">Preview report</a><a className="nz-btn" href="/portal-preview">Preview portal</a><button className="nz-btn pri" disabled={!validation.valid||published} onClick={()=>setPublished(true)}>{published?"Published":"Publish immutable version"}</button></ActionBar></WorkspacePanel>}

function WorkspacePanel({eyebrow,title,subtitle,state,children}:{eyebrow:string;title:string;subtitle:string;state:ReactNode;children:ReactNode}){return <div className="nz-body nz-workspace-body"><section className="nz-panel nz-workspace-panel"><div className="nz-config-head"><div><span className="nz-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div>{state}</div><div className="nz-workspace-content">{children}</div></section></div>}
function PanelSection({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="nz-panel-section"><div className="nz-section-head"><h3>{title}</h3><p>{description}</p></div>{children}</section>}
function ActionBar({children}:{children:ReactNode}){return <div className="nz-action-bar">{children}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="nz-metric"><div className="l">{label}</div><div className="v">{value}</div></div>}
