"use client";
import {useCallback,useEffect,useState} from "react";
import {patchBrowserCommand,postBrowserCommand} from "@nzi/api-client";
import {crpScopeOptions,type EmissionSource,type EmissionSourceDetail,type EmissionSourceGroup,type EmissionSourceKind,type FactorOption,type SiteOption} from "@nzi/contracts";

type Register={groups:EmissionSourceGroup[];sources:EmissionSource[]};
type Notice=(value:{kind:"ok"|"warn";text:string})=>void;
type ActivityEdit={source:EmissionSource;quantity:string;unit:string;applyPct:string;dataConfidence:"H"|"M"|"L";notes:string};
const kinds:EmissionSourceKind[]=["asset","vehicle","commuting","spend"];
const blank=()=>({groupId:"",scope:"3.7",sourceType:"commuting" as EmissionSourceKind,siteId:"",sourceName:"",assetIdentifier:"",factorId:"",quantity:0,unit:"km",applyPct:100,dataSource:"Source Register",dataConfidence:"M" as "H"|"M"|"L",notes:"",employeeName:"",vehicleRegistration:""});
const detailFor=(kind:EmissionSourceKind,employeeName:string,registration:string):EmissionSourceDetail=>kind==="commuting"?{kind,vehicleRegistration:registration||null,commuteMode:"car",distanceUnit:"km",wfhDaysPerYear:null,wfhHoursPerDay:null,employeeName:employeeName||null}:kind==="vehicle"?{kind,vehicleRegistration:registration||null,make:null,model:null,fuel:null}:kind==="spend"?{kind,netValue:0,vatPercent:null,glCode:null,category:"Uncategorised"}:{kind:"asset"};

export function EmissionSourceRegister({jobId,factors,sites,notice}:{jobId:string;factors:FactorOption[];sites:SiteOption[];notice:Notice}){
  const [register,setRegister]=useState<Register|null>(null),[error,setError]=useState(""),[pending,setPending]=useState(""),[open,setOpen]=useState(false),[groupName,setGroupName]=useState(""),[value,setValue]=useState(blank),[editing,setEditing]=useState<ActivityEdit|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/isolated/jobs/${jobId}/emission-sources`,{cache:"no-store"}),body=await response.json();if(!response.ok||!Array.isArray(body.groups)||!Array.isArray(body.sources))throw new Error(body.message??"The source register is unavailable.");setRegister(body);setError("");}catch(cause){setRegister(null);setError(cause instanceof Error?cause.message:"The source register is unavailable.");}},[jobId]);
  useEffect(()=>{void load()},[load]);
  async function sync(source:EmissionSource,quiet=false){setPending(`sync:${source.id}`);const result=await postBrowserCommand<{rowId:string;version:number}>(`/api/isolated/jobs/${jobId}/emission-sources/${source.id}/sync`,{},crypto.randomUUID());setPending("");if(result.state==="success"){if(!quiet)notice({kind:"ok",text:`${source.sourceName} synced to canonical scope row v${result.data.version}.`});await load();return true;}if(!quiet)notice({kind:"warn",text:result.state==="validation_failed"?result.issues.map(issue=>issue.message).join(" "):result.message});return false;}
  async function addGroup(){setPending("group");const result=await postBrowserCommand<{groupId:string;name:string}>(`/api/isolated/jobs/${jobId}/emission-source-groups`,{name:groupName},crypto.randomUUID());setPending("");if(result.state==="success"){setGroupName("");notice({kind:"ok",text:`Source group ${result.data.name} created.`});await load();}else notice({kind:"warn",text:result.state==="validation_failed"?result.issues.map(issue=>issue.message).join(" "):result.message});}
  async function addSource(){const selected=factors.find(item=>item.factorId===value.factorId);setPending("source");const result=await postBrowserCommand<{sourceId:string;sourceName:string}>(`/api/isolated/jobs/${jobId}/emission-sources`,{groupId:value.groupId||null,scope:value.scope,sourceType:value.sourceType,sourceSubtype:null,siteId:value.siteId||null,sourceName:value.sourceName,assetIdentifier:value.assetIdentifier||null,datasetId:selected?.factorSource==="dataset"?selected.datasetId:null,factorId:selected?.factorSource==="dataset"?selected.factorId:null,factorSource:selected?.factorSource??"dataset",clientFactorId:selected?.clientFactorId??null,quantity:value.quantity,unit:value.unit||selected?.activityUnit||null,applyPct:value.applyPct,dataSource:value.dataSource,dataConfidence:value.dataConfidence,monthlyActivity:[],detail:detailFor(value.sourceType,value.employeeName,value.vehicleRegistration),notes:value.notes||null},crypto.randomUUID());if(result.state!=="success"){setPending("");notice({kind:"warn",text:result.state==="validation_failed"?result.issues.map(issue=>issue.message).join(" "):result.message});return;}const synced=await postBrowserCommand<{rowId:string}>(`/api/isolated/jobs/${jobId}/emission-sources/${result.data.sourceId}/sync`,{},crypto.randomUUID());setPending("");setOpen(false);setValue(blank());notice(synced.state==="success"?{kind:"ok",text:`${result.data.sourceName} created and synced to scope.`}:{kind:"warn",text:"The source was created, but its scope row still needs syncing."});await load();}
  async function saveEdit(){if(!editing)return;setPending(`edit:${editing.source.id}`);const quantity=editing.quantity.trim()===""?null:Number(editing.quantity),result=await patchBrowserCommand<{sourceId:string;version:number}>(`/api/isolated/jobs/${jobId}/emission-sources/${editing.source.id}`,{expectedVersion:editing.source.version,quantity,unit:editing.unit||null,applyPct:Number(editing.applyPct),dataConfidence:editing.dataConfidence,notes:editing.notes||null},crypto.randomUUID());if(result.state==="success"){const synced=await postBrowserCommand<{rowId:string}>(`/api/isolated/jobs/${jobId}/emission-sources/${editing.source.id}/sync`,{},crypto.randomUUID());setPending("");setEditing(null);notice(synced.state==="success"?{kind:"ok",text:`${editing.source.sourceName} updated and re-synced.`}:{kind:"warn",text:"Source activity was updated, but the canonical row still needs re-syncing."});await load();return;}setPending("");if(result.state==="conflict")await load();notice({kind:"warn",text:result.state==="validation_failed"?result.issues.map(issue=>issue.message).join(" "):result.message});}
  const applicable=factors.filter(item=>item.scopes.includes(value.scope.split(".")[0]!)||item.scopes.includes(value.scope));
  return <section className="nz-panel nz-config-panel">
    <div className="nz-config-head"><div><span className="nz-eyebrow">Per-entity register</span><b>Assets, vehicles, employees and spend sources</b><div className="sub">Each source links to one canonical scope row with explicit sync status.</div></div><span className={`nz-st ${register?.sources.length?"done":"need"}`}>{register?.sources.length??0} sources</span></div>
    {error?<div className="nz-banner warn" role="alert">{error}</div>:register===null?<div className="nz-table-empty">Loading source register...</div>:<>
      <div style={{display:"flex",gap:8,marginBottom:12}}><input className="nz-inp" value={groupName} placeholder="New roll-up group" onChange={event=>setGroupName(event.target.value)}/><button className="nz-btn" disabled={pending!==""||!groupName.trim()} onClick={()=>void addGroup()}>{pending==="group"?"Creating...":"Add group"}</button><button className="nz-btn pri" style={{marginLeft:"auto"}} onClick={()=>setOpen(!open)}>{open?"Close":"Add source"}</button></div>
      {open?<div className="nz-config-grid">
        <label className="nz-fl">Source name<input className="nz-inp" value={value.sourceName} onChange={event=>setValue({...value,sourceName:event.target.value})}/></label>
        <label className="nz-fl">Type<select className="nz-sel" value={value.sourceType} onChange={event=>setValue({...value,sourceType:event.target.value as EmissionSourceKind})}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select></label>
        <label className="nz-fl">Scope<select className="nz-sel" value={value.scope} onChange={event=>setValue({...value,scope:event.target.value})}>{crpScopeOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
        <label className="nz-fl">Roll-up group<select className="nz-sel" value={value.groupId} onChange={event=>setValue({...value,groupId:event.target.value})}><option value="">Ungrouped</option>{register.groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label>
        <label className="nz-fl">Factor<select className="nz-sel" value={value.factorId} onChange={event=>{const next=factors.find(item=>item.factorId===event.target.value);setValue({...value,factorId:event.target.value,unit:next?.activityUnit??value.unit})}}><option value="">No factor yet</option>{applicable.map(item=><option key={`${item.factorSource}:${item.factorId}`} value={item.factorId}>{item.label}</option>)}</select></label>
        <label className="nz-fl">Site<select className="nz-sel" value={value.siteId} onChange={event=>setValue({...value,siteId:event.target.value})}><option value="">No site</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label>
        <label className="nz-fl">Quantity<input className="nz-inp" type="number" min="0" step="any" value={value.quantity} onChange={event=>setValue({...value,quantity:Number(event.target.value)})}/></label>
        <label className="nz-fl">Unit<input className="nz-inp" value={value.unit} onChange={event=>setValue({...value,unit:event.target.value})}/></label>
        <label className="nz-fl">Apply %<input className="nz-inp" type="number" min="0" max="100" value={value.applyPct} onChange={event=>setValue({...value,applyPct:Number(event.target.value)})}/></label>
        <label className="nz-fl">Asset / employee ID<input className="nz-inp" value={value.assetIdentifier} onChange={event=>setValue({...value,assetIdentifier:event.target.value})}/></label>
        {value.sourceType==="commuting"?<label className="nz-fl">Employee name<input className="nz-inp" value={value.employeeName} onChange={event=>setValue({...value,employeeName:event.target.value})}/></label>:null}
        {value.sourceType==="vehicle"||value.sourceType==="commuting"?<label className="nz-fl">Vehicle registration<input className="nz-inp" value={value.vehicleRegistration} onChange={event=>setValue({...value,vehicleRegistration:event.target.value})}/></label>:null}
        <div className="nz-config-actions"><button className="nz-btn pri" disabled={pending!==""||!value.sourceName.trim()} onClick={()=>void addSource()}>{pending==="source"?"Creating...":"Create source"}</button></div>
      </div>:null}
      <div style={{overflowX:"auto"}}><table className="nz-tbl"><thead><tr><th>Source</th><th>Type</th><th>Scope</th><th>Group</th><th>Activity</th><th>Canonical row</th><th></th></tr></thead><tbody>{register.sources.map(source=>editing?.source.id===source.id?<tr key={source.id}><td colSpan={7}><div className="nz-config-grid"><label className="nz-fl">Quantity<input className="nz-inp" type="number" min="0" step="any" value={editing.quantity} onChange={event=>setEditing({...editing,quantity:event.target.value})}/></label><label className="nz-fl">Unit<input className="nz-inp" value={editing.unit} onChange={event=>setEditing({...editing,unit:event.target.value})}/></label><label className="nz-fl">Apply %<input className="nz-inp" type="number" min="0" max="100" value={editing.applyPct} onChange={event=>setEditing({...editing,applyPct:event.target.value})}/></label><label className="nz-fl">Confidence<select className="nz-sel" value={editing.dataConfidence} onChange={event=>setEditing({...editing,dataConfidence:event.target.value as ActivityEdit["dataConfidence"]})}><option value="H">High</option><option value="M">Medium</option><option value="L">Low</option></select></label><label className="nz-fl" style={{gridColumn:"1/-1"}}>Notes<textarea className="nz-notes" value={editing.notes} onChange={event=>setEditing({...editing,notes:event.target.value})}/></label><div className="nz-config-actions"><button className="nz-btn" disabled={pending!==""} onClick={()=>setEditing(null)}>Cancel</button><button className="nz-btn pri" disabled={pending!==""} onClick={()=>void saveEdit()}>{pending===`edit:${source.id}`?"Saving...":"Save and re-sync"}</button></div></div></td></tr>:<tr key={source.id}><td><b>{source.sourceName}</b><div className="muted">{source.assetIdentifier??source.dataSource}</div></td><td>{source.sourceType}</td><td>{source.scope}</td><td>{register.groups.find(group=>group.id===source.groupId)?.name??"Ungrouped"}</td><td className="num">{source.quantity??"-"} {source.unit??""}<div className="muted">{source.applyPct}% applied</div></td><td>{source.scopeRowId?<><span className={`nz-st ${source.scopeRowReviewStatus==="approved"?"done":"need"}`}>{source.scopeRowReviewStatus??"pending"}</span><div className="muted">v{source.scopeRowVersion}</div></>:<span className="nz-st nof">Not synced</span>}</td><td><button className="nz-btn" disabled={pending!==""} onClick={()=>setEditing({source,quantity:source.quantity===null?"":String(source.quantity),unit:source.unit??"",applyPct:String(source.applyPct??100),dataConfidence:source.dataConfidence??"M",notes:source.notes??""})}>Edit</button> <button className="nz-btn" disabled={pending!==""} onClick={()=>void sync(source)}>{pending===`sync:${source.id}`?"Syncing...":source.scopeRowId?"Re-sync":"Sync"}</button></td></tr>)}</tbody></table>{register.sources.length===0?<div className="nz-table-empty">No per-entity emission sources have been added.</div>:null}</div>
    </>}
  </section>;
}
