"use client";
import { useMemo, useState } from "react";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { platformSummary, tenantIsolationPass, type AuditEvent, type PlatformService, type StaffRole } from "@nzi/mock-data";
import { NAV, USER } from "../lib/nav";

type View = "overview" | "audit" | "access" | "workers";
export function PlatformBoard({ services, events, roles }: { services: PlatformService[]; events: AuditEvent[]; roles: StaffRole[] }) {
  const [view, setView] = useState<View>("overview");
  const [selectedId, setSelectedId] = useState(events[0]!.id);
  const [result, setResult] = useState<"all" | AuditEvent["result"]>("all");
  const selected = events.find((event) => event.id === selectedId) ?? events[0]!;
  const summary = platformSummary(services);
  const visibleEvents = useMemo(() => result === "all" ? events : events.filter((event) => event.result === result), [events, result]);
  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="platform" user={USER} />} drawer={<EvidenceDrawer kicker={`Audit · ${selected.result}`} title={selected.action} subtitle={`${selected.entity} · ${selected.entityId}`} actions={<><button className="nz-btn">Export event</button><button className="nz-btn pri">Open record</button></>}><AuditEvidence event={selected} /></EvidenceDrawer>}>
    <TopBar searchPlaceholder="Search events, actors, correlation IDs…" crumbs={<><b>Platform & audit</b> <span className="muted">/</span> Operations</>} />
    <div className="nz-head"><div style={{ display: "flex", alignItems: "flex-start" }}><div><div className="eyebrow">Isolated environment · mock data</div><h1>Platform & audit</h1><div className="sub">Health · tenancy · permissions · immutable activity history</div></div><button className="nz-btn" style={{ marginLeft: "auto" }}>Export audit</button><button className="nz-btn pri" style={{ marginLeft: 8 }}>Run checks</button></div></div>
    <div className="nz-body" style={{ paddingTop: 18 }}><div className="nz-metrics"><Metric label="Healthy services" value={`${summary.healthy}/${services.length}`} /><Metric label="Degraded" value={`${summary.degraded}`} /><Metric label="Critical audit events" value={`${events.filter((event) => event.severity === "critical").length}`} /><Metric label="Tenant checks" value={tenantIsolationPass(events) ? "Passing" : "Failed"} /></div>
      <div className="nz-toolbar" style={{ padding: "18px 0 12px" }}><div className="nz-filters">{(["overview", "audit", "access", "workers"] as View[]).map((id) => <button key={id} className={view === id ? "on" : undefined} onClick={() => setView(id)}>{id}</button>)}</div>{view === "audit" ? <div className="nz-filters" style={{ marginLeft: "auto" }}>{(["all", "allowed", "denied", "failed"] as const).map((id) => <button key={id} className={result === id ? "on" : undefined} onClick={() => setResult(id)}>{id}</button>)}</div> : null}</div>
      {view === "overview" && <Overview services={services} events={events} select={setSelectedId} />}
      {view === "audit" && <AuditLog events={visibleEvents} selectedId={selectedId} select={setSelectedId} />}
      {view === "access" && <Access roles={roles} />}
      {view === "workers" && <Services services={services.filter((service) => service.area === "Background" || service.area === "Integration")} />}
    </div>
  </AppShell>;
}
function Overview({ services, events, select }: { services: PlatformService[]; events: AuditEvent[]; select: (id: string) => void }) { return <div style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 16, alignItems: "start" }}><div><h2 style={{ fontSize: 17 }}>Environment health</h2><Services services={services} /></div><div><h2 style={{ fontSize: 17 }}>Recent material events</h2><AuditLog events={events.slice(0, 4)} selectedId="" select={select} /></div></div>; }
function Services({ services }: { services: PlatformService[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Service</th><th>Area</th><th>State</th><th className="num">Latency</th></tr></thead><tbody>{services.map((item) => <tr key={item.id}><td style={{ fontWeight: 600 }}>{item.name}<div className="muted" style={{ fontSize: 11 }}>{item.detail}</div></td><td>{item.area}</td><td><State value={item.state} /></td><td className="num">{item.latencyMs ? `${item.latencyMs} ms` : "—"}</td></tr>)}</tbody></table></div>; }
function AuditLog({ events, selectedId, select }: { events: AuditEvent[]; selectedId: string; select: (id: string) => void }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Time / actor</th><th>Action</th><th>Record</th><th>Organisation</th><th>Result</th><th>Correlation</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} className={`row${selectedId === event.id ? " sel" : ""}`} onClick={() => select(event.id)}><td>{event.at}<div className="muted" style={{ fontSize: 11 }}>{event.actor} · {event.principal}</div></td><td style={{ fontWeight: 600 }}>{event.action}</td><td>{event.entity}<div className="muted" style={{ fontSize: 11 }}>{event.entityId}</div></td><td>{event.organisation}</td><td><span className={`nz-st ${event.result === "allowed" ? "done" : event.result === "denied" ? "est" : "nof"}`}>{event.result}</span></td><td className="num">{event.correlationId}</td></tr>)}</tbody></table></div>; }
function Access({ roles }: { roles: StaffRole[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Role</th><th className="num">Members</th><th>Allowed capabilities</th><th>Restricted</th></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td style={{ fontWeight: 600 }}>{role.name}</td><td className="num">{role.members}</td><td>{role.permissions.join(" · ")}</td><td>{role.restricted.length ? role.restricted.join(" · ") : "None"}</td></tr>)}</tbody></table><div className="nz-banner warn" style={{ margin: 16 }}><div><b>UI visibility is not enforcement.</b><div style={{ marginTop: 4 }}>Every command is checked server-side against named permissions, tenant context and record scope. Emergency overrides require a reason and audit event.</div></div></div></div>; }
function AuditEvidence({ event }: { event: AuditEvent }) { return <><div className={`nz-banner ${event.result === "allowed" ? "ok" : "warn"}`}><div><b>{event.result === "allowed" ? "Command authorised and recorded." : event.reason}</b></div></div><div className="nz-kv"><span className="k">Actor</span><span className="v">{event.actor} · {event.principal}</span></div><div className="nz-kv"><span className="k">Organisation</span><span className="v">{event.organisation}</span></div><div className="nz-kv"><span className="k">Timestamp</span><span className="v">{event.at}</span></div><div className="nz-kv"><span className="k">Correlation ID</span><span className="v num">{event.correlationId}</span></div>{event.reason ? <div className="nz-kv"><span className="k">Reason</span><span className="v">{event.reason}</span></div> : null}<div className="nz-sect">Change</div><div className="nz-kv"><span className="k">Before</span><span className="v">{event.before ?? "—"}</span></div><div className="nz-kv"><span className="k">After</span><span className="v">{event.after ?? "—"}</span></div><div className="nz-sect">Tenant boundary</div><p style={{ fontSize: 12, color: "var(--t2)", lineHeight: 1.5 }}>The event retains organisation context and a correlation identifier. Missing tenant context defaults to denial.</p></>; }
function State({ value }: { value: PlatformService["state"] }) { return <span className={`nz-st ${value === "success" ? "done" : value === "degraded" ? "est" : value === "failed" ? "nof" : "need"}`}>{value}</span>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="nz-metric"><div className="l">{label}</div><div className="v num">{value}</div></div>; }
