"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { platformSummary, tenantIsolationPass, type AuditEvent, type PlatformService, type StaffRole } from "@nzi/mock-data";
import { commandDefinitions } from "@nzi/contracts";
import { NAV, USER } from "../lib/nav";
import {PortalAccessAdmin} from "./PortalAccessAdmin";
import {PortalInviteAdmin} from "./PortalInviteAdmin";

type View = "overview" | "audit" | "access" | "commands" | "workers";
const unavailable = "This workflow is not connected in the isolated staging environment.";
export function PlatformBoard({ services, events, roles }: { services: PlatformService[]; events: AuditEvent[]; roles: StaffRole[] }) {
  const [view, setView] = useState<View>("overview");
  const [liveEvents,setLiveEvents]=useState(events);
  const [selectedId, setSelectedId] = useState(events[0]?.id ?? "");
  const [result, setResult] = useState<"all" | AuditEvent["result"]>("all");
  useEffect(()=>{fetch("/api/isolated/audit-events",{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(body=>{if(Array.isArray(body.events))setLiveEvents(body.events)}).catch(()=>undefined)},[]);
  const selected = liveEvents.find((event) => event.id === selectedId) ?? liveEvents[0];
  const summary = platformSummary(services);
  const tenantAssurance = liveEvents.length ? tenantIsolationPass(liveEvents) : null;
  const visibleEvents = useMemo(() => result === "all" ? liveEvents : liveEvents.filter((event) => event.result === result), [liveEvents, result]);
  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="platform" user={USER} />} drawer={selected?<EvidenceDrawer kicker={`Audit · ${selected.result}`} title={selected.action} subtitle={`${selected.entity} · ${selected.entityId}`} actions={<><button className="nz-btn" disabled title={unavailable}>Export event</button><button className="nz-btn pri" disabled title={unavailable}>Open record</button></>}><AuditEvidence event={selected} /></EvidenceDrawer>:undefined}>
    <TopBar searchPlaceholder="Search events, actors, correlation IDs…" crumbs={<><b>Platform & audit</b> <span className="muted">/</span> Operations</>} />
    <div className="nz-head"><div className="nz-job-titleline"><div><div className="nz-eyebrow">Trust & control</div><h1>Platform governance</h1><div className="sub">Operational health, tenant isolation, permissions and immutable activity history</div></div><div className="nz-head-actions"><button className="nz-btn" disabled title={unavailable}>Export audit</button><button className="nz-btn pri" disabled title={unavailable}>Run assurance checks</button></div></div></div>
    <div className="nz-body" style={{ paddingTop: 18 }}><section className="nz-ops-hero governance"><div><span className="nz-eyebrow light">NZI control plane</span><h2>{tenantAssurance===null?"Tenant assurance is awaiting audit evidence.":tenantAssurance?"All evidenced tenant controls are passing.":"A tenant-control exception needs attention."}</h2><p>{tenantAssurance===null?"No audit events are available, so the console cannot claim that tenant controls pass or fail.":"Live operational evidence connects service health, role enforcement, tenant boundaries and every material system command."}</p></div><div className="nz-ops-trust"><span><i>{tenantAssurance===null?"·":"✓"}</i> MFA enforced</span><span><i>{tenantAssurance===null?"·":"✓"}</i> Tenant RLS active</span><span><i>{tenantAssurance===null?"·":"✓"}</i> Audit immutable</span></div></section><div className="nz-metrics"><Metric label="Healthy services" value={`${summary.healthy}/${services.length}`} /><Metric label="Degraded services" value={`${summary.degraded}`} /><Metric label="Recorded events" value={`${liveEvents.length}`} /><Metric label="Tenant assurance" value={tenantAssurance===null?"No evidence":tenantAssurance?"Passing":"Failed"} /></div>
      <div className="nz-toolbar" style={{ padding: "18px 0 12px" }}><div className="nz-filters">{(["overview", "audit", "access", "commands", "workers"] as View[]).map((id) => <button type="button" key={id} aria-pressed={view===id} className={view === id ? "on" : undefined} onClick={() => setView(id)}>{id}</button>)}</div>{view === "audit" ? <div className="nz-filters" style={{ marginLeft: "auto" }}>{(["all", "allowed", "denied", "failed"] as const).map((id) => <button type="button" key={id} aria-pressed={result===id} className={result === id ? "on" : undefined} onClick={() => setResult(id)}>{id}</button>)}</div> : null}</div>
      {view === "overview" && <Overview services={services} events={liveEvents} select={setSelectedId} />}
      {view === "audit" && <AuditLog events={visibleEvents} selectedId={selectedId} select={setSelectedId} />}
      {view === "access" && <section className="nz-access-workspace"><div className="nz-access-brief"><div><span className="nz-eyebrow light">Identity and authorisation</span><h2>Grant the minimum access needed for each reporting relationship.</h2><p>Staff roles, client identities and job-level grants remain separate controls. Every change is tenant-scoped, permission-checked and auditable.</p></div><div className="nz-access-control-list"><span><i>1</i>Staff role matrix</span><span><i>2</i>Client invitation</span><span><i>3</i>Job-level grant</span></div></div><div className="nz-section-intro"><div><span className="nz-eyebrow">Staff access</span><h2>Permission and segregation matrix</h2><p>Named capabilities govern every server-side command.</p></div><span className="nz-st done">Enforced</span></div><Access roles={roles} /><div className="nz-section-intro"><div><span className="nz-eyebrow">Client identities</span><h2>Portal enrolment and reporting grants</h2><p>Invite independent client users, then authorise only the jobs they should see.</p></div><span className="nz-st done">MFA required</span></div><PortalInviteAdmin/><PortalAccessAdmin /></section>}
      {view === "commands" && <Commands />}
      {view === "workers" && <Services services={services.filter((service) => service.area === "Background" || service.area === "Integration")} />}
    </div>
  </AppShell>;
}
function Overview({ services, events, select }: { services: PlatformService[]; events: AuditEvent[]; select: (id: string) => void }) { return <div style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 16, alignItems: "start" }}><div><h2 style={{ fontSize: 17 }}>Environment health</h2><Services services={services} /></div><div><h2 style={{ fontSize: 17 }}>Recent material events</h2><AuditLog events={events.slice(0, 4)} selectedId="" select={select} /></div></div>; }
function Services({ services }: { services: PlatformService[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Service</th><th>Area</th><th>State</th><th className="num">Latency</th></tr></thead><tbody>{services.map((item) => <tr key={item.id}><td style={{ fontWeight: 600 }}>{item.name}<div className="muted" style={{ fontSize: 11 }}>{item.detail}</div></td><td>{item.area}</td><td><State value={item.state} /></td><td className="num">{item.latencyMs ? `${item.latencyMs} ms` : "—"}</td></tr>)}</tbody></table></div>; }
function AuditLog({ events, selectedId, select }: { events: AuditEvent[]; selectedId: string; select: (id: string) => void }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Time / actor</th><th>Action</th><th>Record</th><th>Organisation</th><th>Result</th><th>Correlation</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} tabIndex={0} aria-selected={selectedId===event.id} className={`row${selectedId === event.id ? " sel" : ""}`} onClick={() => select(event.id)} onKeyDown={(keyEvent)=>{if(keyEvent.key==="Enter"||keyEvent.key===" "){keyEvent.preventDefault();select(event.id)}}}><td>{event.at}<div className="muted" style={{ fontSize: 11 }}>{event.actor} · {event.principal}</div></td><td style={{ fontWeight: 600 }}>{event.action}</td><td>{event.entity}<div className="muted" style={{ fontSize: 11 }}>{event.entityId}</div></td><td>{event.organisation}</td><td><span className={`nz-st ${event.result === "allowed" ? "done" : event.result === "denied" ? "est" : "nof"}`}>{event.result}</span></td><td className="num">{event.correlationId}</td></tr>)}</tbody></table>{events.length===0?<div className="nz-table-empty">No audit events match this result.</div>:null}</div>; }
function Access({ roles }: { roles: StaffRole[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Role</th><th className="num">Members</th><th>Allowed capabilities</th><th>Restricted</th></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td style={{ fontWeight: 600 }}>{role.name}</td><td className="num">{role.members}</td><td>{role.permissions.join(" · ")}</td><td>{role.restricted.length ? role.restricted.join(" · ") : "None"}</td></tr>)}</tbody></table><div className="nz-banner warn" style={{ margin: 16 }}><div><b>UI visibility is not enforcement.</b><div style={{ marginTop: 4 }}>Every command is checked server-side against named permissions, tenant context and record scope. Emergency overrides require a reason and audit event.</div></div></div></div>; }
function Commands() { const rows = Object.values(commandDefinitions); return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Command</th><th>Permission</th><th>Atomic transaction</th><th>Audit action</th><th>Reason</th></tr></thead><tbody>{rows.map((item) => <tr key={item.key}><td style={{ fontWeight: 600 }}>{item.label}<div className="muted num" style={{ fontSize: 11 }}>{item.key}</div></td><td className="num">{item.permission}</td><td>{item.transaction}</td><td className="num">{item.auditAction}</td><td><span className={`nz-st ${item.reasonRequired ? "est" : "done"}`}>{item.reasonRequired ? "required" : "optional"}</span></td></tr>)}</tbody></table><div className="nz-banner ok" style={{ margin: 16 }}><div><b>All commands require tenant, actor, idempotency and correlation context.</b><div style={{ marginTop: 4 }}>Outcomes remain distinct: success, conflict, denied, validation failed and transport failed.</div></div></div></div>; }
function AuditEvidence({ event }: { event: AuditEvent }) { return <><div className={`nz-banner ${event.result === "allowed" ? "ok" : "warn"}`}><div><b>{event.result === "allowed" ? "Command authorised and recorded." : event.reason}</b></div></div><div className="nz-kv"><span className="k">Actor</span><span className="v">{event.actor} · {event.principal}</span></div><div className="nz-kv"><span className="k">Organisation</span><span className="v">{event.organisation}</span></div><div className="nz-kv"><span className="k">Timestamp</span><span className="v">{event.at}</span></div><div className="nz-kv"><span className="k">Correlation ID</span><span className="v num">{event.correlationId}</span></div>{event.reason ? <div className="nz-kv"><span className="k">Reason</span><span className="v">{event.reason}</span></div> : null}<div className="nz-sect">Change</div><div className="nz-kv"><span className="k">Before</span><span className="v">{event.before ?? "—"}</span></div><div className="nz-kv"><span className="k">After</span><span className="v">{event.after ?? "—"}</span></div><div className="nz-sect">Tenant boundary</div><p style={{ fontSize: 12, color: "var(--t2)", lineHeight: 1.5 }}>The event retains organisation context and a correlation identifier. Missing tenant context defaults to denial.</p></>; }
function State({ value }: { value: PlatformService["state"] }) { return <span className={`nz-st ${value === "success" ? "done" : value === "degraded" ? "est" : value === "failed" ? "nof" : "need"}`}>{value}</span>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="nz-metric"><div className="l">{label}</div><div className="v num">{value}</div></div>; }
