"use client";
import {FormEvent,useEffect,useState} from "react";
import type {ClientScreenReadModel} from "@nzi/isolated-backend";

export function PortalInviteAdmin(){
  const [clients,setClients]=useState<ClientScreenReadModel[]|null>(null),[clientError,setClientError]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(false),[link,setLink]=useState(""),[copied,setCopied]=useState(false);
  useEffect(()=>{fetch("/api/isolated/clients",{cache:"no-store"}).then(response=>response.json().then(body=>({response,body}))).then(({response,body})=>{if(!response.ok)throw new Error("Clients are unavailable.");if(!Array.isArray(body.clients))throw new Error("The client register returned an invalid response.");setClients(body.clients)}).catch(cause=>setClientError(cause instanceof Error?cause.message:"Clients are unavailable."))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setPending(true);setError("");setLink("");setCopied(false);const form=event.currentTarget,data=new FormData(form);try{const response=await fetch("/api/isolated/portal-invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId:data.get("clientId"),displayName:data.get("displayName"),email:data.get("email")})}),body=await response.json();if(!response.ok)throw new Error(body.message??"Invitation could not be created.");if(typeof body.invitation?.token!=="string")throw new Error("Invitation creation returned an invalid response.");setLink(`${window.location.origin}/portal/invite?token=${encodeURIComponent(body.invitation.token)}`);form.reset()}catch(cause){setError(cause instanceof Error?cause.message:"Invitation could not be created.")}finally{setPending(false)}}
  async function copy(){try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setError("The setup link could not be copied automatically. Select and copy it manually.")}}
  return <section className="nz-panel nz-portal-invite-admin"><div className="nz-portal-invite-head"><div><span className="nz-eyebrow">Independent client identity</span><h2>Invite a portal user</h2><p className="sub">Creates a single-use setup link valid for 72 hours. The client chooses their own password and enrols MFA.</p></div><span className="nz-st done">72-hour expiry</span></div><form className="nz-portal-invite-form" onSubmit={submit}><label className="nz-fl">Client<select className="nz-inp" name="clientId" required defaultValue="" disabled={clients===null||pending}><option value="" disabled>{clientError?"Clients unavailable":clients===null?"Loading clients…":"Select client…"}</option>{clients?.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="nz-fl">Name<input className="nz-inp" name="displayName" required maxLength={120} disabled={pending||clients===null} autoComplete="name"/></label><label className="nz-fl">Email<input className="nz-inp" name="email" type="email" required disabled={pending||clients===null} autoComplete="email"/></label><button className="nz-btn pri" disabled={pending||clients===null||clients.length===0}>{pending?"Creating...":"Create invitation"}</button></form>{clientError?<div className="nz-banner warn" role="alert">{clientError}</div>:null}{!clientError&&clients?.length===0?<div className="nz-table-empty">No eligible clients are available for portal invitations.</div>:null}{error?<div className="nz-banner warn" role="alert">{error}</div>:null}{link?<div className="nz-invite-result" role="status"><div><span className="nz-eyebrow">Single-use credential</span><b>Invitation created — copy this link now</b><p>Share it through an approved channel. The link will not reveal the client&apos;s password or MFA secret.</p></div><output className="num">{link}</output><button type="button" className="nz-btn" onClick={copy}>{copied?"Copied securely":"Copy setup link"}</button></div>:null}</section>
}
