"use client";
import {useEffect,useState} from "react";
import type {PortalAccessUser} from "@nzi/isolated-backend";

export function PortalAccessAdmin(){
  const [users,setUsers]=useState<PortalAccessUser[]|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState("");
  async function load(){setError("");try{const response=await fetch("/api/isolated/portal-access",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.message??"Portal access is unavailable.");if(!Array.isArray(body.users))throw new Error("Portal access returned an invalid response.");setUsers(body.users)}catch(cause){setError(cause instanceof Error?cause.message:"Portal access is unavailable.");setUsers(null)}}
  useEffect(()=>{void load()},[]);
  async function change(user:PortalAccessUser,job:PortalAccessUser["jobs"][number]){if(job.granted&&!window.confirm(`Revoke ${user.displayName}'s access to ${job.jobNumber}? Their active portal session will be rechecked immediately.`))return;const key=`${user.portalUserId}:${job.jobId}`;setPending(key);setError("");setNotice("");const response=await fetch("/api/isolated/portal-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portalUserId:user.portalUserId,jobId:job.jobId,granted:!job.granted})}),body=await response.json();setPending("");if(!response.ok){setError(body.message??"Portal access could not be changed.");return}setNotice(`${job.jobNumber} access ${job.granted?"revoked from":"granted to"} ${user.displayName}.`);await load()}
  async function toggle(user:PortalAccessUser){if(user.status==="active"&&!window.confirm(`Disable ${user.displayName}'s portal account? All active sessions will end.`))return;const key=`user:${user.portalUserId}`;setPending(key);setError("");setNotice("");const response=await fetch("/api/isolated/portal-users/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portalUserId:user.portalUserId,enabled:user.status==="disabled"})}),body=await response.json();setPending("");if(!response.ok){setError(body.message??"Portal account status could not be changed.");return}setNotice(`${user.displayName}'s portal account is now ${user.status==="disabled"?"enabled":"disabled"}.`);await load()}
  const registerState=error?{label:"Register unavailable",cls:"nof"}:users===null?{label:"Loading register",cls:"need"}:{label:"Access register loaded",cls:"done"};
  return <div><div className="nz-portal-access-head"><div><span className="nz-eyebrow">Least-privilege control</span><h2>Client portal access</h2><p className="sub">Access is granted per portal user and job. Disabling an account or revoking its final job ends active sessions.</p></div><span className={`nz-st ${registerState.cls}`}>{registerState.label}</span></div>{error?<div className="nz-banner warn" role="alert">{error}</div>:null}{notice?<div className="nz-banner ok" role="status">{notice}</div>:null}{error?null:users===null?<p className="sub" role="status">Loading portal access...</p>:users.length===0?<div className="nz-table-empty">No portal accounts are configured.</div>:users.map(user=><section className="nz-panel nz-access-user" key={user.portalUserId}><div className="nz-access-user-head"><div><b>{user.displayName}</b><span className="sub">{user.email} · {user.clientName}</span></div><span className={`nz-st ${user.status==="active"?"done":"est"}`}>{user.status}</span>{user.status!=="invited"?<button className="nz-btn" disabled={pending===`user:${user.portalUserId}`} onClick={()=>toggle(user)}>{pending===`user:${user.portalUserId}`?"Saving...":user.status==="active"?"Disable account":"Enable account"}</button>:null}</div><table className="nz-tbl"><thead><tr><th>Job</th><th>Reporting year</th><th>Access</th><th></th></tr></thead><tbody>{user.jobs.map(job=>{const key=`${user.portalUserId}:${job.jobId}`;return <tr key={job.jobId}><td><b>{job.jobNumber}</b><div className="muted">{job.title}</div></td><td>{job.reportingYear??"—"}</td><td><span className={`nz-st ${job.granted?"done":"nof"}`}>{job.granted?"Granted":"Not granted"}</span></td><td style={{textAlign:"right"}}><button className={`nz-btn ${job.granted?"":"pri"}`} disabled={pending===key||user.status!=="active"} title={user.status!=="active"?"Enable this account before changing job access.":undefined} onClick={()=>change(user,job)}>{pending===key?"Saving...":job.granted?"Revoke":"Grant access"}</button></td></tr>})}</tbody></table>{user.jobs.length===0?<div className="nz-table-empty">No eligible client jobs are available for this portal user.</div>:null}</section>)}</div>
}
