"use client";
import {type FormEvent,useEffect,useState} from "react";
import type {PortalAccessUser} from "@nzi/isolated-backend";

type Row={id:string;scope:string;sourceLabel:string;enabled:boolean};
type Factor={factorId:string;label:string;activityUnit:string};
type Site={id:string;name:string};
export function PortalBucketAdmin(){
  const [users,setUsers]=useState<PortalAccessUser[]>([]),[portalUserId,setPortalUserId]=useState(""),[jobId,setJobId]=useState(""),[rows,setRows]=useState<Row[]>([]),[factors,setFactors]=useState<Factor[]>([]),[sites,setSites]=useState<Site[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState(false);
  useEffect(()=>{fetch("/api/isolated/portal-access",{cache:"no-store"}).then(response=>response.json().then(body=>response.ok?body:Promise.reject(new Error(body.message)))).then(body=>setUsers(Array.isArray(body.users)?body.users:[])).catch(()=>setError("Portal bucket configuration is unavailable."))},[]);
  const user=users.find(item=>item.portalUserId===portalUserId),jobs=user?.jobs.filter(job=>job.granted&&job.dataEntryExpiresAt)??[];
  useEffect(()=>{if(!jobId){setRows([]);setFactors([]);setSites([]);return}Promise.all([fetch(`/api/isolated/jobs/${jobId}/scope-rows`).then(r=>r.json()),fetch(`/api/isolated/jobs/${jobId}/factors`).then(r=>r.json()),fetch(`/api/isolated/jobs/${jobId}/sites`).then(r=>r.json())]).then(([rowBody,factorBody,siteBody])=>{setRows(Array.isArray(rowBody.rows)?rowBody.rows:[]);setFactors(Array.isArray(factorBody.factors)?factorBody.factors:[]);setSites(Array.isArray(siteBody.sites)?siteBody.sites:[])}).catch(()=>setError("Canonical job options could not be loaded."))},[jobId]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");setNotice("");const data=new FormData(event.currentTarget),scopeRowId=String(data.get("scopeRowId")??""),factorIds=data.getAll("factorIds").map(String),siteIds=data.getAll("siteIds").map(String);try{const response=await fetch("/api/isolated/portal-data-entry-buckets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portalUserId,jobId,scopeRowId,factorIds,siteIds})}),body=await response.json();if(!response.ok)throw new Error(body.message??"The bucket grant could not be saved.");setNotice("Authorised bucket, factors, sites and derived units saved.")}catch(cause){setError(cause instanceof Error?cause.message:"The bucket grant outcome could not be verified.")}finally{setPending(false)}}
  return <section className="nz-panel" style={{padding:16,marginTop:14}}><span className="nz-eyebrow">Client data-entry permissions</span><h3 style={{margin:"6px 0"}}>Authorised scope-row buckets</h3><p className="sub">Select an active window, then constrain one canonical row to approved factors and client sites. Units are derived automatically.</p>{error?<div className="nz-banner warn" role="alert">{error}</div>:null}{notice?<div className="nz-banner ok" role="status">{notice}</div>:null}<form onSubmit={submit} style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(220px,1fr))",gap:12}}><label className="nz-fl">Portal user<select className="nz-inp" value={portalUserId} onChange={event=>{setPortalUserId(event.target.value);setJobId("")}} required><option value="">Select user</option>{users.filter(item=>item.status==="active").map(item=><option key={item.portalUserId} value={item.portalUserId}>{item.displayName} · {item.clientName}</option>)}</select></label><label className="nz-fl">Job with entry window<select className="nz-inp" value={jobId} onChange={event=>setJobId(event.target.value)} required disabled={!portalUserId}><option value="">Select job</option>{jobs.map(job=><option key={job.jobId} value={job.jobId}>{job.jobNumber} · {job.title}</option>)}</select></label><label className="nz-fl">Canonical scope row<select className="nz-inp" name="scopeRowId" required disabled={!jobId}><option value="">Select row</option>{rows.filter(row=>row.enabled).map(row=><option key={row.id} value={row.id}>{row.scope} · {row.sourceLabel}</option>)}</select></label><label className="nz-fl">Allowed factors<select className="nz-inp" name="factorIds" multiple required size={Math.min(5,Math.max(2,factors.length))} disabled={!jobId}>{factors.map(factor=><option key={factor.factorId} value={factor.factorId}>{factor.label} · {factor.activityUnit}</option>)}</select></label><label className="nz-fl">Allowed sites <span className="muted">(optional)</span><select className="nz-inp" name="siteIds" multiple size={Math.min(4,Math.max(2,sites.length))} disabled={!jobId}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><div style={{display:"flex",alignItems:"end"}}><button className="nz-btn pri" disabled={pending||!jobId}>{pending?"Saving...":"Authorise bucket"}</button></div></form></section>;
}
