"use client";
import {FormEvent,useEffect,useState} from "react";
import type {ClientContactReadModel} from "@nzi/contracts";
import type {ClientScreenReadModel} from "@nzi/isolated-backend";

/** Invitees are chosen from the client's contacts marked Portal candidate — the portal_candidate role feeds this picker. */
export function PortalInviteAdmin(){
  const [clients,setClients]=useState<ClientScreenReadModel[]|null>(null),[clientError,setClientError]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(false),[link,setLink]=useState(""),[copied,setCopied]=useState(false);
  const [clientId,setClientId]=useState(""),[candidates,setCandidates]=useState<ClientContactReadModel[]|null>(null),[candidateError,setCandidateError]=useState(""),[contactId,setContactId]=useState("");
  useEffect(()=>{fetch("/api/isolated/clients",{cache:"no-store"}).then(response=>response.json().then(body=>({response,body}))).then(({response,body})=>{if(!response.ok)throw new Error("Clients are unavailable.");if(!Array.isArray(body.clients))throw new Error("The client register returned an invalid response.");setClients(body.clients)}).catch(cause=>setClientError(cause instanceof Error?cause.message:"Clients are unavailable."))},[]);
  useEffect(()=>{setCandidates(null);setContactId("");setCandidateError("");if(!clientId)return;let live=true;fetch(`/api/isolated/clients/${encodeURIComponent(clientId)}/contacts?role=portal_candidate`,{cache:"no-store"}).then(response=>response.json().then(body=>({response,body}))).then(({response,body})=>{if(!live)return;if(!response.ok||!Array.isArray(body.contacts))throw new Error("Portal candidates are unavailable.");setCandidates(body.contacts);setContactId(body.contacts[0]?.id??"")}).catch(cause=>{if(live)setCandidateError(cause instanceof Error?cause.message:"Portal candidates are unavailable.")});return()=>{live=false}},[clientId]);
  const candidate=candidates?.find(item=>item.id===contactId)??null;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending||!candidate?.email)return;setPending(true);setError("");setLink("");setCopied(false);try{const response=await fetch("/api/isolated/portal-invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId,contactId:candidate.id,displayName:candidate.fullName,email:candidate.email})}),body=await response.json();if(!response.ok)throw new Error(body.message??"Invitation could not be created.");if(typeof body.invitation?.token!=="string")throw new Error("Invitation creation returned an invalid response.");setLink(`${window.location.origin}/portal/invite?token=${encodeURIComponent(body.invitation.token)}`)}catch(cause){setError(cause instanceof Error?cause.message:"Invitation could not be created.")}finally{setPending(false)}}
  async function copy(){try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setError("The setup link could not be copied automatically. Select and copy it manually.")}}
  return <section className="nz-panel nz-portal-invite-admin"><div className="nz-portal-invite-head"><div><span className="nz-eyebrow">Independent client identity</span><h2>Invite a portal user</h2><p className="sub">Choose one of the client&apos;s contacts marked <b>Portal candidate</b>. Creates a single-use setup link valid for 72 hours; the client chooses their own password and enrols MFA.</p></div><span className="nz-st done">72-hour expiry</span></div>
    <form className="nz-portal-invite-form" onSubmit={submit}>
      <label className="nz-fl">Client<select className="nz-inp" name="clientId" required value={clientId} onChange={event=>setClientId(event.target.value)} disabled={clients===null||pending}><option value="" disabled>{clientError?"Clients unavailable":clients===null?"Loading clients…":"Select client…"}</option>{clients?.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label>
      <label className="nz-fl">Portal candidate<select className="nz-inp" name="contactId" required value={contactId} onChange={event=>setContactId(event.target.value)} disabled={!clientId||candidates===null||candidates.length===0||pending}>{!clientId?<option value="">Select a client first</option>:candidates===null?<option value="">{candidateError||"Loading candidates…"}</option>:candidates.length===0?<option value="">No portal candidates</option>:candidates.map(item=><option key={item.id} value={item.id}>{item.fullName}{item.jobTitle?` — ${item.jobTitle}`:""}</option>)}</select></label>
      <label className="nz-fl">Email<input className="nz-inp" name="email" type="email" readOnly value={candidate?.email??""} placeholder="From the contact" /></label>
      <button className="nz-btn pri" disabled={pending||!candidate?.email}>{pending?"Creating...":"Create invitation"}</button>
    </form>
    {clientId&&candidates?.length===0?<div className="nz-table-empty">This client has no contacts marked <b>Portal candidate</b>. Tick that role on a contact in <a href={`/clients/${encodeURIComponent(clientId)}`}>the client&apos;s contacts</a>, then invite them here.</div>:null}
    {clientError?<div className="nz-banner warn" role="alert">{clientError}</div>:null}{!clientError&&clients?.length===0?<div className="nz-table-empty">No eligible clients are available for portal invitations.</div>:null}{error?<div className="nz-banner warn" role="alert">{error}</div>:null}{link?<div className="nz-invite-result" role="status"><div><span className="nz-eyebrow">Single-use credential</span><b>Invitation created — copy this link now</b><p>Share it through an approved channel. The link will not reveal the client&apos;s password or MFA secret.</p></div><output className="num">{link}</output><button type="button" className="nz-btn" onClick={copy}>{copied?"Copied securely":"Copy setup link"}</button></div>:null}</section>
}
