import type { SpendImportColumnMap, SpendImportRow } from "./spendImport";

export type CommandKey =
  | "client.create"
  | "job.create"
  | "job.stage.change"
  | "scope.row.create"
  | "scope.row.update"
  | "scope.row.calculate"
  | "scope.review.approve"
  | "scope.review.reject"
  | "report.publish"
  | "report.validate"
  | "report.snapshot.create"
  | "emissions.target.upsert"
  | "site.create"
  | "emissions.intensity.upsert"
  | "purchased.goods.category.create"
  | "client.factor.create"
  | "emission.source.group.create"
  | "emission.source.create"
  | "emission.source.sync"
  | "emission.source.activity.update"
  | "emission.source.status.update"
  | "emission.source.rollforward"
  | "emission.source.import.commit"
  | "emission.source.import.void"
  | "client.import.mapping.save"
  | "dataset.override.add"
  | "portal.access.grant"
  | "sales.opportunity.convert";

export const jobWorkflowStages = {
  crp: ["Setup", "Data entry", "Factor mapping", "Review & QA", "Report & publish"],
  consultancy: ["Scope", "Plan", "Delivery", "Client review", "Complete"],
  lca: ["Goal & scope", "Inventory", "Impact assessment", "Interpretation", "Report"],
  pcf: ["Product boundary", "BOM", "Factor mapping", "Review", "Report"],
  training: ["Course setup", "Bookings", "Delivery", "Attendance", "Certificates"],
} as const;
export type WorkflowJobFamily = keyof typeof jobWorkflowStages;
export type ScopeQualityTier = "measured" | "estimated" | "spend-based" | "survey";
export type MonthlyActivitySlot = { month:string; quantity:number|null };
export const crpScopeOptions = [
  { value: "1", label: "Scope 1 · Direct emissions", category: "Direct emissions" },
  { value: "2", label: "Scope 2 · Purchased energy", category: "Purchased energy" },
  { value: "3.1", label: "Scope 3.1 · Purchased goods and services" },
  { value: "3.2", label: "Scope 3.2 · Capital goods" },
  { value: "3.3", label: "Scope 3.3 · Fuel- and energy-related activities" },
  { value: "3.4", label: "Scope 3.4 · Upstream transportation and distribution" },
  { value: "3.5", label: "Scope 3.5 · Waste generated in operations" },
  { value: "3.6", label: "Scope 3.6 · Business travel" },
  { value: "3.7", label: "Scope 3.7 · Employee commuting" },
  { value: "3.8", label: "Scope 3.8 · Upstream leased assets" },
  { value: "3.9", label: "Scope 3.9 · Downstream transportation and distribution" },
  { value: "3.10", label: "Scope 3.10 · Processing of sold products" },
  { value: "3.11", label: "Scope 3.11 · Use of sold products" },
  { value: "3.12", label: "Scope 3.12 · End-of-life treatment of sold products" },
  { value: "3.13", label: "Scope 3.13 · Downstream leased assets" },
  { value: "3.14", label: "Scope 3.14 · Franchises" },
  { value: "3.15", label: "Scope 3.15 · Investments" },
] as const;
export type CrpScopeCode = (typeof crpScopeOptions)[number]["value"];
const crpScopeCategories: Record<CrpScopeCode, string> = {
  "1":"Direct emissions","2":"Purchased energy","3.1":"Purchased goods and services","3.2":"Capital goods","3.3":"Fuel- and energy-related activities","3.4":"Upstream transportation and distribution","3.5":"Waste generated in operations","3.6":"Business travel","3.7":"Employee commuting","3.8":"Upstream leased assets","3.9":"Downstream transportation and distribution","3.10":"Processing of sold products","3.11":"Use of sold products","3.12":"End-of-life treatment of sold products","3.13":"Downstream leased assets","3.14":"Franchises","3.15":"Investments",
};
export function crpScopeCategoryPath(scope: string): string[] {
  const option = crpScopeOptions.find((item) => item.value === scope);
  if (!option) return [];
  const category = crpScopeCategories[option.value];
  return scope.startsWith("3.") ? ["Scope 3", category] : [`Scope ${scope}`, category];
}
export type ScopeRowWriteFields = { scope: string; sourceLabel: string; assetIdentifier?:string|null; reportLabel?:string|null; notes?:string|null; monthlyActivity?:MonthlyActivitySlot[]; siteId?:string|null;siteLabel?:string|null;purchasedGoodsCategoryId?:string|null;purchasedGoodsCategoryLabel?:string|null;quantity: number | null; unit: string | null; datasetId: string | null; factorId: string | null; factorVersion: string | null; factorLabel: string | null; qualityTier: ScopeQualityTier | null; overrideTco2e?: number | null; overrideReason?: string | null; factorSource?: FactorSource; clientFactorId?: string | null; isCustomEntry?: boolean; applyPct?: number | null; dataConfidence?: DataConfidence | null; sourceQuantity?: number | null; sourceUnit?: string | null; columnText?: string | null; sourceId?: string | null; linkedRowId?: string | null; isAutoGenerated?: boolean; autoPairKind?: string | null };
export type SiteOption={id:string;name:string};
export type PurchasedGoodsCategoryOption={id:string;name:string};
export type ScopeRowReadModel = ScopeRowWriteFields & { id: string; jobId: string; reportLabel:string; categoryPath:string[]; monthlyActivity:MonthlyActivitySlot[]; calculatedTco2e: number | null; overrideTco2e: number | null; overrideReason: string | null; reviewStatus: "pending" | "approved" | "rejected"; reviewedRowVersion:number|null;reviewedBy:string|null;reviewedAt:string|null;reviewerNote:string|null; version: number; enabled: boolean; provenance: Record<string, unknown>; lineage: Array<{ title: string; detail: string }> };
export type ScopeQaReadiness={total:number;enabled:number;approved:number;pending:number;rejected:number;calculationMissing:number;qualityMissing:number;independentReviewPending:number;readyForReporting:boolean};
export type EmissionsTargetReadModel={jobId:string;baselineYear:number;baselineTco2e:number;interimYear:number;interimReductionPercent:number;netZeroYear:number;version:number;updatedAt:string;updatedBy:string};
export type IntensityTargetReadModel={jobId:string;metric:"turnover"|"employee"|"floor-area";denominatorUnit:string;reportingDenominator:number;baselineYear:number;baselineIntensity:number;interimYear:number;interimReductionPercent:number;netZeroYear:number;version:number;updatedAt:string;updatedBy:string};
export type AnnualScopeComparison={year:number;sourceSnapshotId:string;sourceDataHash:string;values:Array<{scope:"1"|"2"|"3";value:number}>};
export type ReviewedCrpSnapshotReadModel={id:string;jobId:string;jobNumber:string;client:string;reportingYear:number;version:number;jobVersion:number;createdAt:string;createdBy:string;dataHash:string;target:EmissionsTargetReadModel|null;intensityTarget:IntensityTargetReadModel|null;annualComparison:AnnualScopeComparison[];measurements:Array<{rowId:string;rowVersion:number;scope:"1"|"2"|"3";scopeCode?:string;sourceLabel:string;assetIdentifier?:string|null;reportLabel?:string;columnText?:string|null;notes?:string|null;categoryPath?:string[];monthlyActivity?:MonthlyActivitySlot[];siteId?:string|null;siteLabel?:string|null;purchasedGoodsCategoryId?:string|null;purchasedGoodsCategoryLabel?:string|null;factorSource?:FactorSource;clientFactorId?:string|null;isCustomEntry?:boolean;applyPct?:number;dataConfidence?:DataConfidence|null;sourceQuantity?:number|null;sourceUnit?:string|null;tco2e:number;factorSet:string;qualityTier:ScopeQualityTier;reviewedBy:string}>};
export type PublishedCrpReportReadModel={reportVersionId:string;manifestVersion:number;publishedAt:string;dataHash:string;snapshot:ReviewedCrpSnapshotReadModel};
export type CrpReportVersionReadModel={reportVersionId:string;status:"validated"|"published"|"superseded";manifestVersion:number;publishedAt:string|null;dataHash:string;snapshot:ReviewedCrpSnapshotReadModel};
export type FactorOption = { datasetId: string|null; datasetName: string; datasetVersion: string; factorId: string; label: string; activityUnit: string; kgco2ePerUnit: number; scopes: string[]; selectionSource: "automatic" | "manual" | "client"; factorSource:FactorSource;clientFactorId:string|null;evidenceHash:string|null; synthetic: boolean; warnings: string[] };
export type DatasetOption = { datasetId: string; name: string; version: string; validFrom: string; validTo: string; countryCode: string; status: "active" | "superseded" | "draft"; synthetic: boolean; selected: boolean; selectionSource: "automatic" | "manual" | null; applicable: boolean; warnings: string[]; reportingFrom: string; reportingTo: string; jobCountryCode: string };
export function isAllowedJobStageTransition(family: WorkflowJobFamily, from: string, to: string): boolean {
  const stages: readonly string[] = jobWorkflowStages[family];
  const fromIndex = stages.indexOf(from); const toIndex = stages.indexOf(to);
  return fromIndex >= 0 && toIndex >= 0 && Math.abs(toIndex - fromIndex) === 1;
}

export type CommandContext = {
  organisationId: string;
  actorId: string;
  principal: "staff";
  idempotencyKey: string;
  correlationId: string;
  reason?: string;
};
export type CommandIssue = { field: string; code: string; message: string };
export type CommandOutcome<T = Record<string, unknown>> =
  | { state: "success"; data: T; auditEventId: string; correlationId: string; replayed: boolean }
  | { state: "conflict"; code: string; message: string; correlationId: string }
  | { state: "denied"; permission: string; message: string; correlationId: string }
  | { state: "validation_failed"; issues: CommandIssue[]; correlationId: string }
  | { state: "failed"; code: string; message: string; retryable: boolean; correlationId: string };

export type CommandInputMap = {
  "client.create": { name: string; status: "active" | "onboarding" | "at-risk" | "prospect"; sector: string; location: string; owner: string };
  "job.create": { clientId: string; family: "crp" | "consultancy" | "lca" | "pcf" | "training"; title: string; workflowStage: string; owner: string; startDate: string; dueDate: string; reportingYear?: number };
  "job.stage.change": { jobId: string; fromStage: string; toStage: string; expectedVersion: number; note?: string };
  "scope.row.create": { jobId: string } & ScopeRowWriteFields;
  "scope.row.update": { jobId: string; rowId: string; expectedVersion: number; enabled: boolean } & ScopeRowWriteFields;
  "scope.row.calculate": { jobId: string; rowId: string; expectedVersion: number };
  "scope.review.approve": { jobId: string; rowIds: string[]; expectedReviewVersion: number; reviewerNote?: string };
  "scope.review.reject": { jobId: string; rowIds: string[]; expectedReviewVersion: number; reviewerNote: string };
  "report.publish": { reportVersionId: string; expectedStatus: "validated"; manifestVersion: number; reviewedSnapshotId: string };
  "report.validate":{reviewedSnapshotId:string;manifestVersion:number};
  "report.snapshot.create": { jobId:string;expectedJobVersion:number };
  "emissions.target.upsert": { jobId:string;baselineYear:number;baselineTco2e:number;interimYear:number;interimReductionPercent:number;netZeroYear:number;expectedVersion:number };
  "site.create": {jobId:string;name:string};
  "emissions.intensity.upsert":{jobId:string;metric:"turnover"|"employee"|"floor-area";denominatorUnit:string;reportingDenominator:number;baselineYear:number;baselineIntensity:number;interimYear:number;interimReductionPercent:number;netZeroYear:number;expectedVersion:number};
  "purchased.goods.category.create":{jobId:string;name:string};
  "client.factor.create":{jobId:string;scope:string;reportLabel:string;description:string;unit:string;kgco2ePerUnit:number;geography:string;vintageYear:number;source:string;reusable:boolean;evidenceFileName:string|null;evidenceStorageProvider:"local"|"sharepoint"|null;evidenceUrl:string|null;evidenceExternalItemId:string|null;evidenceHash:string|null};
  "emission.source.group.create":{jobId:string;name:string};
  "emission.source.create":{jobId:string;groupId:string|null;scope:string;sourceType:EmissionSourceKind;sourceSubtype:string|null;siteId:string|null;sourceName:string;assetIdentifier:string|null;purchasedGoodsCategoryId:string|null;datasetId?:string|null;factorId:string|null;factorSource:FactorSource;clientFactorId:string|null;quantity:number|null;unit:string|null;applyPct:number;dataSource:string;dataConfidence:DataConfidence|null;monthlyActivity:MonthlyActivitySlot[];detail:EmissionSourceDetail;notes:string|null};
  "emission.source.sync":{jobId:string;sourceId:string};
  "emission.source.rollforward":{jobId:string;fromJobId:string|null};
  "emission.source.import.commit":{jobId:string;token:string;rows:SpendImportRow[]};
  "emission.source.import.void":{jobId:string;batchId:string};
  "client.import.mapping.save":{clientId:string;importKind:"spend";columns:SpendImportColumnMap};
  "emission.source.activity.update":{jobId:string;sourceId:string;expectedVersion:number;quantity:number|null;unit:string|null;applyPct:number;dataConfidence:DataConfidence|null;monthlyActivity:MonthlyActivitySlot[];notes:string|null};
  "emission.source.status.update":{jobId:string;sourceId:string;expectedVersion:number;enabled:boolean};
  "dataset.override.add": { jobId: string; scope: string; datasetId: string; reportingFrom: string; reportingTo: string };
  "portal.access.grant": { clientId: string; jobIds: string[]; userId: string; dataEntryExpiresAt?: string };
  "sales.opportunity.convert": { opportunityId: string; expectedStatus: "WON"; quoteId: string; createJob: boolean };
};

export type CommandDefinition<K extends CommandKey = CommandKey> = {
  key: K; label: string; permission: string; reasonRequired: boolean; transaction: string; auditAction: string;
  validate: (input: CommandInputMap[K], context: CommandContext) => CommandIssue[];
};
const text = (value: unknown) => typeof value === "string" && value.trim().length > 0;
const positive = (value: unknown) => typeof value === "number" && Number.isInteger(value) && value > 0;
const oneOf = <T extends string>(value: unknown, allowed: readonly T[]): value is T => typeof value === "string" && allowed.includes(value as T);
const isoDate = (value: unknown) => typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
const baseIssues = (context: CommandContext, reasonRequired: boolean) => {
  const issues: CommandIssue[] = [];
  if (!text(context.organisationId)) issues.push({ field: "organisationId", code: "REQUIRED", message: "Organisation context is required." });
  if (!text(context.actorId)) issues.push({ field: "actorId", code: "REQUIRED", message: "Actor is required." });
  if (!text(context.idempotencyKey)) issues.push({ field: "idempotencyKey", code: "REQUIRED", message: "Idempotency key is required." });
  if (!text(context.correlationId)) issues.push({ field: "correlationId", code: "REQUIRED", message: "Correlation ID is required." });
  if (reasonRequired && !text(context.reason)) issues.push({ field: "reason", code: "REQUIRED", message: "A reason is required for this command." });
  return issues;
};
const required = (issues: CommandIssue[], field: string, value: unknown) => { if (!text(value)) issues.push({ field, code: "REQUIRED", message: `${field} is required.` }); };
const monthlyActivityIssues=(slots:MonthlyActivitySlot[]|undefined):CommandIssue[]=>{if(!slots?.length)return[];const issues:CommandIssue[]=[];const months=new Set<string>();for(const [index,slot] of slots.entries()){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(slot.month))issues.push({field:`monthlyActivity.${index}.month`,code:"INVALID",message:"Month must use YYYY-MM."});if(months.has(slot.month))issues.push({field:`monthlyActivity.${index}.month`,code:"DUPLICATE",message:"Each reporting month may appear only once."});months.add(slot.month);if(slot.quantity!==null&&(typeof slot.quantity!=="number"||!Number.isFinite(slot.quantity)||slot.quantity<0))issues.push({field:`monthlyActivity.${index}.quantity`,code:"INVALID",message:"Monthly quantity must be zero or greater."});}return issues;};
const scopeRowIssues = (input: ScopeRowWriteFields) => { const issues: CommandIssue[] = monthlyActivityIssues(input.monthlyActivity); required(issues, "scope", input.scope); required(issues, "sourceLabel", input.sourceLabel); if (input.assetIdentifier != null && (typeof input.assetIdentifier !== "string" || input.assetIdentifier.trim().length > 240)) issues.push({field:"assetIdentifier",code:"INVALID",message:"ID / Reference must be text of 240 characters or fewer."}); if (input.applyPct != null && (typeof input.applyPct!=="number"||!Number.isFinite(input.applyPct)||input.applyPct<0||input.applyPct>100)) issues.push({field:"applyPct",code:"INVALID",message:"Apportionment must be between 0 and 100%."}); if (input.dataConfidence != null && !(["H","M","L"] as const).includes(input.dataConfidence)) issues.push({field:"dataConfidence",code:"INVALID",message:"Data confidence must be high, medium, or low."}); if (input.sourceQuantity != null && (typeof input.sourceQuantity!=="number"||!Number.isFinite(input.sourceQuantity)||input.sourceQuantity<0)) issues.push({field:"sourceQuantity",code:"INVALID",message:"As-entered quantity must be zero or greater."}); if ((input.sourceQuantity!=null)!==Boolean(text(input.sourceUnit))) issues.push({field:"sourceUnit",code:"PAIRED",message:"As-entered quantity and unit must be provided together."}); const factorSource=input.factorSource??"dataset";if(factorSource==="client"&&(!text(input.clientFactorId)||input.isCustomEntry!==true))issues.push({field:"clientFactorId",code:"REQUIRED",message:"A client factor row must identify its client factor."});if(factorSource==="dataset"&&(text(input.clientFactorId)||input.isCustomEntry===true))issues.push({field:"factorSource",code:"INCONSISTENT",message:"Dataset factors cannot carry client-factor identity."}); if (typeof input.scope === "string" && !crpScopeOptions.some((option) => option.value === input.scope)) issues.push({ field: "scope", code: "INVALID", message: "Select a controlled Scope 1, Scope 2, or Scope 3 category." }); if (input.quantity !== null && (typeof input.quantity !== "number" || !Number.isFinite(input.quantity) || input.quantity < 0)) issues.push({ field: "quantity", code: "INVALID", message: "Quantity must be zero or greater." }); if (input.overrideTco2e != null && (typeof input.overrideTco2e !== "number" || !Number.isFinite(input.overrideTco2e) || input.overrideTco2e < 0)) issues.push({ field: "overrideTco2e", code: "INVALID", message: "Override emissions must be zero or greater." }); if (input.overrideTco2e != null && !text(input.overrideReason)) issues.push({ field: "overrideReason", code: "REQUIRED", message: "Explain why the calculated result is being overridden." }); if (input.overrideTco2e == null && text(input.overrideReason)) issues.push({ field: "overrideReason", code: "ORPHANED", message: "Remove the override reason or enter an override value." }); if (input.factorId && !input.datasetId && factorSource!=="client") issues.push({ field: "datasetId", code: "REQUIRED", message: "A dataset factor must identify its dataset." }); return issues; };

export const commandDefinitions: { [K in CommandKey]: CommandDefinition<K> } = {
  "client.create": { key: "client.create", label: "Create client", permission: "clients.create", reasonRequired: false, transaction: "client + audit + outbox + idempotency", auditAction: "client_created", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "name", input.name); required(issues, "sector", input.sector); required(issues, "location", input.location); required(issues, "owner", input.owner); if (!oneOf(input.status, ["active", "onboarding", "at-risk", "prospect"] as const)) issues.push({ field: "status", code: "INVALID", message: "Client status is invalid." }); return issues; } },
  "job.create": { key: "job.create", label: "Create job", permission: "jobs.create", reasonRequired: false, transaction: "number allocation + job + audit + outbox + idempotency", auditAction: "job_created", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "clientId", input.clientId); required(issues, "title", input.title); required(issues, "workflowStage", input.workflowStage); required(issues, "owner", input.owner); if (!oneOf(input.family, ["crp", "consultancy", "lca", "pcf", "training"] as const)) issues.push({ field: "family", code: "INVALID", message: "Job family is invalid." }); if (!isoDate(input.startDate)) issues.push({ field: "startDate", code: "INVALID", message: "Start date must use YYYY-MM-DD." }); if (!isoDate(input.dueDate)) issues.push({ field: "dueDate", code: "INVALID", message: "Due date must use YYYY-MM-DD." }); if (isoDate(input.startDate) && isoDate(input.dueDate) && input.dueDate < input.startDate) issues.push({ field: "dueDate", code: "INVALID_RANGE", message: "Due date must not precede start date." }); return issues; } },
  "job.stage.change": { key: "job.stage.change", label: "Change job stage", permission: "jobs.stage.change", reasonRequired: false, transaction: "stage history + job header", auditAction: "job_stage_changed", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "jobId", input.jobId); required(issues, "fromStage", input.fromStage); required(issues, "toStage", input.toStage); if (input.fromStage === input.toStage) issues.push({ field: "toStage", code: "NO_CHANGE", message: "New stage must differ from the current stage." }); if (!positive(input.expectedVersion)) issues.push({ field: "expectedVersion", code: "INVALID", message: "Expected version must be positive." }); return issues; } },
  "scope.row.create": { key: "scope.row.create", label: "Create scope row", permission: "emissions.data.edit", reasonRequired: false, transaction: "scope row + audit + outbox + idempotency", auditAction: "scope_row_created", validate: (input, context) => { const issues = [...baseIssues(context, false), ...scopeRowIssues(input)]; required(issues, "jobId", input.jobId); return issues; } },
  "scope.row.update": { key: "scope.row.update", label: "Update scope row", permission: "emissions.data.edit", reasonRequired: false, transaction: "versioned scope row + audit + outbox + idempotency", auditAction: "scope_row_updated", validate: (input, context) => { const issues = [...baseIssues(context, false), ...scopeRowIssues(input)]; required(issues, "jobId", input.jobId); required(issues, "rowId", input.rowId); if (!positive(input.expectedVersion)) issues.push({ field: "expectedVersion", code: "INVALID", message: "Expected version must be positive." }); return issues; } },
  "scope.row.calculate": { key: "scope.row.calculate", label: "Calculate scope row", permission: "emissions.data.edit", reasonRequired: false, transaction: "factor validation + numeric calculation + lineage", auditAction: "scope_row_calculated", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "jobId", input.jobId); required(issues, "rowId", input.rowId); if (!positive(input.expectedVersion)) issues.push({ field: "expectedVersion", code: "INVALID", message: "Expected version must be positive." }); return issues; } },
  "scope.review.approve": { key: "scope.review.approve", label: "Approve scope rows", permission: "emissions.review", reasonRequired: false, transaction: "scope rows + review history", auditAction: "scope_rows_approved", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "jobId", input.jobId); if (!input.rowIds.length) issues.push({ field: "rowIds", code: "REQUIRED", message: "Select at least one scope row." }); if (!positive(input.expectedReviewVersion)) issues.push({ field: "expectedReviewVersion", code: "INVALID", message: "Expected review version must be positive." }); return issues; } },
  "scope.review.reject": { key: "scope.review.reject", label: "Reject scope rows", permission: "emissions.review", reasonRequired: false, transaction: "scope rows + review history", auditAction: "scope_rows_rejected", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "jobId", input.jobId); required(issues,"reviewerNote",input.reviewerNote);if (!input.rowIds.length) issues.push({ field: "rowIds", code: "REQUIRED", message: "Select at least one scope row." }); if (!positive(input.expectedReviewVersion)) issues.push({ field: "expectedReviewVersion", code: "INVALID", message: "Expected review version must be positive." }); return issues; } },
  "report.publish": { key: "report.publish", label: "Publish report", permission: "reports.publish", reasonRequired: false, transaction: "immutable version + manifest + portal outbox", auditAction: "report_published", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "reportVersionId", input.reportVersionId); required(issues, "reviewedSnapshotId", input.reviewedSnapshotId); if (input.expectedStatus !== "validated") issues.push({ field: "expectedStatus", code: "PRECONDITION", message: "Only validated reports may be published." }); if (!positive(input.manifestVersion)) issues.push({ field: "manifestVersion", code: "INVALID", message: "Manifest version must be positive." }); return issues; } },
  "report.validate":{key:"report.validate",label:"Validate report version",permission:"reports.publish",reasonRequired:false,transaction:"snapshot resolution + manifest gate + immutable report version",auditAction:"report_validated",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"reviewedSnapshotId",input.reviewedSnapshotId);if(!positive(input.manifestVersion))issues.push({field:"manifestVersion",code:"INVALID",message:"Manifest version must be positive."});return issues;}},
  "report.snapshot.create": { key:"report.snapshot.create",label:"Create reviewed snapshot",permission:"reports.publish",reasonRequired:false,transaction:"QA gate + immutable snapshot + content hash",auditAction:"reviewed_snapshot_created",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);if(!positive(input.expectedJobVersion))issues.push({field:"expectedJobVersion",code:"INVALID",message:"Expected job version must be positive."});return issues;} },
  "emissions.target.upsert": { key:"emissions.target.upsert",label:"Save emissions target",permission:"emissions.data.edit",reasonRequired:false,transaction:"versioned target + audit + outbox",auditAction:"emissions_target_saved",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<0)issues.push({field:"expectedVersion",code:"INVALID",message:"Expected version must be zero or greater."});if(!Number.isInteger(input.baselineYear)||!Number.isInteger(input.interimYear)||!Number.isInteger(input.netZeroYear)||!(input.baselineYear<input.interimYear&&input.interimYear<input.netZeroYear))issues.push({field:"interimYear",code:"INVALID_RANGE",message:"Years must run baseline, interim, then net zero."});if(typeof input.baselineTco2e!=="number"||!Number.isFinite(input.baselineTco2e)||input.baselineTco2e<=0)issues.push({field:"baselineTco2e",code:"INVALID",message:"Baseline emissions must be greater than zero."});if(typeof input.interimReductionPercent!=="number"||!Number.isFinite(input.interimReductionPercent)||input.interimReductionPercent<=0||input.interimReductionPercent>=100)issues.push({field:"interimReductionPercent",code:"INVALID",message:"Interim reduction must be between 0 and 100 percent."});return issues;} },
  "site.create":{key:"site.create",label:"Create client site",permission:"emissions.data.edit",reasonRequired:false,transaction:"client site + audit + outbox",auditAction:"client_site_created",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"name",input.name);return issues;}},
  "emissions.intensity.upsert":{key:"emissions.intensity.upsert",label:"Save intensity target",permission:"emissions.data.edit",reasonRequired:false,transaction:"versioned intensity target + audit + outbox",auditAction:"intensity_target_saved",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"denominatorUnit",input.denominatorUnit);if(!oneOf(input.metric,["turnover","employee","floor-area"] as const))issues.push({field:"metric",code:"INVALID",message:"Intensity metric is invalid."});if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<0)issues.push({field:"expectedVersion",code:"INVALID",message:"Expected version must be zero or greater."});if(!(input.reportingDenominator>0))issues.push({field:"reportingDenominator",code:"INVALID",message:"Reporting denominator must be greater than zero."});if(!(input.baselineIntensity>0))issues.push({field:"baselineIntensity",code:"INVALID",message:"Baseline intensity must be greater than zero."});if(!Number.isInteger(input.baselineYear)||!Number.isInteger(input.interimYear)||!Number.isInteger(input.netZeroYear)||!(input.baselineYear<input.interimYear&&input.interimYear<input.netZeroYear))issues.push({field:"interimYear",code:"INVALID_RANGE",message:"Years must run baseline, interim, then net zero."});if(!(input.interimReductionPercent>0&&input.interimReductionPercent<100))issues.push({field:"interimReductionPercent",code:"INVALID",message:"Interim reduction must be between 0 and 100 percent."});return issues;}},
  "purchased.goods.category.create":{key:"purchased.goods.category.create",label:"Create purchased-goods category",permission:"emissions.data.edit",reasonRequired:false,transaction:"client category + audit + outbox",auditAction:"purchased_goods_category_created",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"name",input.name);return issues;}},
  "client.factor.create":{key:"client.factor.create",label:"Create client factor",permission:"datasets.override",reasonRequired:false,transaction:"client factor + audit + outbox + idempotency",auditAction:"client_factor_created",validate:(input,context)=>{const issues=baseIssues(context,false);for(const [field,value] of [["jobId",input.jobId],["scope",input.scope],["reportLabel",input.reportLabel],["unit",input.unit],["geography",input.geography],["source",input.source]] as const)required(issues,field,value);if(!crpScopeOptions.some(option=>option.value===input.scope))issues.push({field:"scope",code:"INVALID",message:"Select a controlled CRP scope category."});if(typeof input.kgco2ePerUnit!=="number"||!Number.isFinite(input.kgco2ePerUnit)||input.kgco2ePerUnit<0)issues.push({field:"kgco2ePerUnit",code:"INVALID",message:"Factor value must be zero or greater."});if(!Number.isInteger(input.vintageYear)||input.vintageYear<1990||input.vintageYear>2100)issues.push({field:"vintageYear",code:"INVALID",message:"Factor vintage year is invalid."});if(input.evidenceFileName&&(!input.evidenceHash||!input.evidenceStorageProvider))issues.push({field:"evidenceHash",code:"REQUIRED",message:"Evidence files require a storage provider and integrity hash."});return issues;}},
  "emission.source.group.create":{key:"emission.source.group.create",label:"Create emission-source group",permission:"emissions.data.edit",reasonRequired:false,transaction:"source group + audit + outbox + idempotency",auditAction:"emission_source_group_created",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"name",input.name);return issues;}},
  "emission.source.create":{key:"emission.source.create",label:"Create emission source",permission:"emissions.data.edit",reasonRequired:false,transaction:"emission source + audit + outbox + idempotency",auditAction:"emission_source_created",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"sourceName",input.sourceName);required(issues,"dataSource",input.dataSource);if(!crpScopeOptions.some(option=>option.value===input.scope))issues.push({field:"scope",code:"INVALID",message:"Select a controlled CRP scope category."});if(!(["asset","vehicle","commuting","spend"] as const).includes(input.sourceType))issues.push({field:"sourceType",code:"INVALID",message:"Source type is invalid."});if(input.quantity!==null&&(!Number.isFinite(input.quantity)||input.quantity<0))issues.push({field:"quantity",code:"INVALID",message:"Quantity must be zero or greater."});if(!Number.isFinite(input.applyPct)||input.applyPct<0||input.applyPct>100)issues.push({field:"applyPct",code:"INVALID",message:"Apportionment must be between 0 and 100 percent."});if(input.factorSource==="client"&&!input.clientFactorId)issues.push({field:"clientFactorId",code:"REQUIRED",message:"Select the client factor used by this source."});if(input.factorSource==="dataset"&&input.clientFactorId)issues.push({field:"clientFactorId",code:"INVALID",message:"Dataset sources cannot reference a client factor."});if(input.detail.kind!==input.sourceType)issues.push({field:"detail",code:"INVALID",message:"Source detail must match the selected source type."});if(input.sourceType==="spend"&&!text(input.purchasedGoodsCategoryId))issues.push({field:"purchasedGoodsCategoryId",code:"REQUIRED",message:"Select the controlled purchased-goods category for this spend line."});if(input.purchasedGoodsCategoryId!=null&&typeof input.purchasedGoodsCategoryId!=="string")issues.push({field:"purchasedGoodsCategoryId",code:"INVALID",message:"Purchased-goods category is invalid."});issues.push(...monthlyActivityIssues(input.monthlyActivity));return issues;}},
  "emission.source.sync":{key:"emission.source.sync",label:"Sync emission source to scope",permission:"emissions.data.edit",reasonRequired:false,transaction:"source-locked canonical row upsert + audit + outbox + idempotency",auditAction:"emission_source_synced",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"sourceId",input.sourceId);return issues;}},
  "emission.source.activity.update":{key:"emission.source.activity.update",label:"Update emission-source activity",permission:"emissions.data.edit",reasonRequired:false,transaction:"versioned source activity + audit + outbox + idempotency",auditAction:"emission_source_activity_updated",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"sourceId",input.sourceId);if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<1)issues.push({field:"expectedVersion",code:"INVALID",message:"Expected source version must be one or greater."});if(input.quantity!==null&&(!Number.isFinite(input.quantity)||input.quantity<0))issues.push({field:"quantity",code:"INVALID",message:"Quantity must be zero or greater."});if(!Number.isFinite(input.applyPct)||input.applyPct<0||input.applyPct>100)issues.push({field:"applyPct",code:"INVALID",message:"Apportionment must be between 0 and 100 percent."});if(input.quantity!==null&&!input.unit?.trim())issues.push({field:"unit",code:"REQUIRED",message:"Activity unit is required when quantity is present."});issues.push(...monthlyActivityIssues(input.monthlyActivity));return issues;}},
  "emission.source.status.update":{key:"emission.source.status.update",label:"Change emission-source status",permission:"emissions.data.edit",reasonRequired:false,transaction:"versioned source status + linked canonical row + audit + outbox + idempotency",auditAction:"emission_source_status_updated",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"sourceId",input.sourceId);if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<1)issues.push({field:"expectedVersion",code:"INVALID",message:"Expected source version must be one or greater."});if(typeof input.enabled!=="boolean")issues.push({field:"enabled",code:"INVALID",message:"Source status must be enabled or archived."});return issues;}},
  "emission.source.rollforward":{key:"emission.source.rollforward",label:"Roll forward previous-year spend mappings",permission:"emissions.data.edit",reasonRequired:false,transaction:"prior-year mapping copy + re-pinned datasets + audit + outbox + idempotency",auditAction:"emission_sources_rolled_forward",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);if(input.fromJobId!=null&&(typeof input.fromJobId!=="string"||input.fromJobId.trim()===""))issues.push({field:"fromJobId",code:"INVALID",message:"Source job is invalid."});return issues;}},
  "emission.source.import.commit":{key:"emission.source.import.commit",label:"Commit a spend import batch",permission:"emissions.data.edit",reasonRequired:false,transaction:"token verify + batched spend sources + audit + outbox + idempotency",auditAction:"spend_import_committed",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"token",input.token);if(!Array.isArray(input.rows)||input.rows.length===0)issues.push({field:"rows",code:"REQUIRED",message:"Import at least one row."});else if(input.rows.length>10_000)issues.push({field:"rows",code:"TOO_MANY",message:"An import may carry at most 10,000 rows."});return issues;}},
  "emission.source.import.void":{key:"emission.source.import.void",label:"Void a spend import batch",permission:"emissions.data.edit",reasonRequired:false,transaction:"audited soft-void of pending batch rows + linked rows + audit + outbox",auditAction:"spend_import_voided",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"jobId",input.jobId);required(issues,"batchId",input.batchId);return issues;}},
  "client.import.mapping.save":{key:"client.import.mapping.save",label:"Save a client's import column map",permission:"emissions.data.edit",reasonRequired:false,transaction:"versioned client import mapping + audit + outbox",auditAction:"client_import_mapping_saved",validate:(input,context)=>{const issues=baseIssues(context,false);required(issues,"clientId",input.clientId);if(input.importKind!=="spend")issues.push({field:"importKind",code:"INVALID",message:"Import kind must be spend."});if(typeof input.columns!=="object"||input.columns===null||Array.isArray(input.columns))issues.push({field:"columns",code:"INVALID",message:"Column map must be an object."});return issues;}},
  "dataset.override.add": { key: "dataset.override.add", label: "Add manual dataset", permission: "datasets.override", reasonRequired: true, transaction: "resolution + warning + audit", auditAction: "dataset_override_added", validate: (input, context) => { const issues = baseIssues(context, true); required(issues, "jobId", input.jobId); required(issues, "scope", input.scope); required(issues, "datasetId", input.datasetId); required(issues, "reportingFrom", input.reportingFrom); required(issues, "reportingTo", input.reportingTo); return issues; } },
  "portal.access.grant": { key: "portal.access.grant", label: "Grant portal access", permission: "portal.access.manage", reasonRequired: false, transaction: "access grant + job grants + invitation outbox", auditAction: "portal_access_granted", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "clientId", input.clientId); required(issues, "userId", input.userId); if (!input.jobIds.length) issues.push({ field: "jobIds", code: "REQUIRED", message: "Grant at least one job." }); return issues; } },
  "sales.opportunity.convert": { key: "sales.opportunity.convert", label: "Convert won opportunity", permission: "sales.convert", reasonRequired: false, transaction: "client + quote + optional job + outbox", auditAction: "opportunity_converted", validate: (input, context) => { const issues = baseIssues(context, false); required(issues, "opportunityId", input.opportunityId); required(issues, "quoteId", input.quoteId); if (input.expectedStatus !== "WON") issues.push({ field: "expectedStatus", code: "PRECONDITION", message: "Opportunity must be WON." }); return issues; } },
};

export function validateCommand<K extends CommandKey>(key: K, input: CommandInputMap[K], context: CommandContext) { return commandDefinitions[key].validate(input, context); }

// ---- Model-fidelity extensions (proposed canonical model, 29 Aug 2026) ----
// Additive and optional on ScopeRowWriteFields; see docs/MODEL_FIDELITY_DATA_ENTRY.md.
export type DataConfidence = "H" | "M" | "L";
export type FactorSource = "dataset" | "client";

export type ClientFactorEvidence = { fileName: string; storageProvider: "local" | "sharepoint"; url: string | null; externalItemId: string | null; hash: string };
export type ClientFactor = {
  id: string; organisationId: string; clientId: string; jobId: string | null;
  scope: string; categoryPath: string[]; reportLabel: string; description: string;
  unit: string; ghgUnit: string; kgco2ePerUnit: number;
  geography: string; vintageYear: number; version: number;
  source: string; evidence: ClientFactorEvidence | null;
  archived: boolean; createdBy: string; createdAt: string; updatedBy: string | null; updatedAt: string | null;
};

export type ClientSite = {
  id: string; organisationId: string; clientId: string; name: string;
  addressLines: string[]; postcode: string | null;
  latitude: number | null; longitude: number | null; geocodeSource: string | null; geocodePrecision: string | null;
  activeFrom: string | null; vacatedDate: string | null;
  archived: boolean; createdBy: string; createdAt: string;
};

export type EmissionSourceKind = "asset" | "vehicle" | "commuting" | "spend";
export type CommutingDetail = { kind: "commuting"; vehicleRegistration: string | null; commuteMode: string; distanceUnit: string; wfhDaysPerYear: number | null; wfhHoursPerDay: number | null; employeeName: string | null };
export type VehicleDetail = { kind: "vehicle"; vehicleRegistration: string | null; make: string | null; model: string | null; fuel: string | null };
export type SpendDetail = { kind: "spend"; netValue: number; vatPercent: number | null; glCode: string | null; category: string };
export type AssetDetail = { kind: "asset" };
export type EmissionSourceDetail = CommutingDetail | VehicleDetail | SpendDetail | AssetDetail;

export type EmissionSourceGroup = { id: string; jobId: string; name: string; datasetId: string | null; factorId: string | null; factorLabel: string | null; unit: string | null };
export type EmissionSource = {
  id: string; jobId: string; groupId: string | null;
  scope: string; sourceType: EmissionSourceKind; sourceSubtype: string | null;
  siteId: string | null; sourceName: string; assetIdentifier: string | null;
  purchasedGoodsCategoryId: string | null;
  datasetId: string | null; factorId: string | null; factorSource: FactorSource; clientFactorId: string | null;
  quantity: number | null; unit: string | null; applyPct: number | null;
  dataSource: string; dataConfidence: DataConfidence | null;
  monthlyActivity: MonthlyActivitySlot[]; detail: EmissionSourceDetail;
  notes: string | null; calculatedTco2e: number | null; enabled: boolean;
  submittedByPortal: boolean; reviewStatus: "pending" | "approved" | "rejected" | null; version: number;
  scopeRowId: string | null; scopeRowVersion: number | null; scopeRowReviewStatus: "pending" | "approved" | "rejected" | null;
  rolledForwardFromSourceId: string | null; factorVersionMoved: boolean;
  yoyPriorQuantity: number | null; yoyPriorUnit: string | null;
};

// Previous-year rollforward (NZC-030) — preview of the prior job's spend mappings.
export type SpendRollforwardLine = {
  priorSourceId: string; description: string; glCode: string | null;
  purchasedGoodsCategoryId: string | null; purchasedGoodsCategoryLabel: string | null;
  factorSource: FactorSource; factorLabel: string | null;
  pinnedFactorVersion: string | null; currentFactorVersion: string | null; factorVersionMoved: boolean;
  datasetInJobSelection: boolean; alreadyRolledForward: boolean;
};
export type SpendRollforwardPreview = {
  priorJob: { id: string; number: string; reportingYear: number } | null;
  lines: SpendRollforwardLine[];
};
