import {headers} from "next/headers";
import Link from "next/link";
import {redirect} from "next/navigation";
import type {PublishedCrpReportReadModel} from "@nzi/contracts";
import {ManifestChartSet,crpProfessionalManifest,resolveCrpCoreCharts} from "@nzi/charts";
import {PrintControls} from "./PrintControls";
import {isPublishedCrpReport} from "../publishedReportValidation";
import "./print.css";
export const dynamic="force-dynamic";
export default async function PublishedPrintPage({params}:{params:Promise<{jobId:string}>}){const {jobId}=await params,cookie=(await headers()).get("cookie"),base=(process.env.NZI_ISOLATED_API_URL??"").replace(/\/$/,"");let response:Response;try{response=await fetch(`${base}/api/portal/jobs/${jobId}/published-report`,{cache:"no-store",headers:cookie?{cookie}:{}})}catch{return <PrintUnavailable jobId={jobId} state="failed"/>}if(response.status===401)redirect(`/portal/login?next=${encodeURIComponent(`/portal/jobs/${jobId}/print`)}`);if(!response.ok)return <PrintUnavailable jobId={jobId} state={response.status===403?"denied":response.status===404?"missing":"failed"}/>;let body:unknown;try{body=await response.json()}catch{return <PrintUnavailable jobId={jobId} state="failed"/>}if(!isPublishedReportBody(body,jobId))return <PrintUnavailable jobId={jobId} state="failed"/>;const {report}=body,snapshot=report.snapshot,charts=resolveCrpCoreCharts({id:snapshot.id,jobId:snapshot.jobId,jobNumber:snapshot.jobNumber,client:snapshot.client,reportingYear:snapshot.reportingYear,generatedAt:snapshot.createdAt,dataHash:snapshot.dataHash,target:snapshot.target,intensityTarget:snapshot.intensityTarget,annualComparison:snapshot.annualComparison,measurements:snapshot.measurements.map(row=>({rowId:row.rowId,scope:row.scope,scopeCode:row.scopeCode,sourceLabel:row.sourceLabel,siteId:row.siteId,siteLabel:row.siteLabel,purchasedGoodsCategoryId:row.purchasedGoodsCategoryId,purchasedGoodsCategoryLabel:row.purchasedGoodsCategoryLabel,tco2e:row.tco2e,factorSet:row.factorSet}))});return <><PrintControls/><main className="published-print" style={{background:"#EEF2F0",padding:24,minHeight:"100vh"}}><article className="published-print-sheet" style={{maxWidth:900,margin:"0 auto",background:"white",padding:28,boxShadow:"0 4px 24px rgba(11,27,43,.08)"}}><div className="eyebrow">NZI Professional Carbon Reduction Plan</div><h1 style={{margin:"8px 0 4px"}}>{snapshot.client}</h1><p className="sub" style={{marginTop:0}}>{snapshot.jobNumber} · Reporting year {snapshot.reportingYear}</p><div className="nz-banner ok" style={{margin:"18px 0"}}><div><b>Published and verified report</b><div style={{marginTop:3}}>Immutable version {report.reportVersionId} · published {new Date(report.publishedAt).toLocaleDateString("en-GB")}</div></div></div><ManifestChartSet manifest={crpProfessionalManifest} charts={charts} reviewedSnapshotId={snapshot.id}/><footer style={{borderTop:"1px solid #E4EAE7",marginTop:24,paddingTop:12,fontSize:10,color:"#68766F"}}>Evidence identity: {report.dataHash} · Manifest v{report.manifestVersion} · Snapshot {snapshot.id}</footer></article></main></>}

function isPublishedReportBody(value:unknown,expectedJobId:string):value is {report:PublishedCrpReportReadModel}{return Boolean(value&&typeof value==="object"&&isPublishedCrpReport((value as {report?:unknown}).report,expectedJobId))}
function PrintUnavailable({jobId,state}:{jobId:string;state:"denied"|"missing"|"failed"}){const denied=state==="denied",missing=state==="missing";return <main className="nz-body"><div className="nz-banner warn"><div><b>{denied?"Report access is not granted":missing?"No published report is available":"Published report could not be loaded"}</b><div>{denied?"Ask your NZI adviser to review your job-level access.":missing?"Your NZI team will release the verified version when assurance is complete.":"No conclusion has been made about access or publication state."}</div></div></div><Link className="nz-btn" href={`/portal/jobs/${jobId}`}>Back to report workspace</Link></main>}
