import {headers} from "next/headers";
import Link from "next/link";
import {redirect} from "next/navigation";
import type {ClientFacingPublishedCrpReport} from "@nzi/contracts";
import {ManifestChartSet,crpProfessionalManifest,resolveCrpCoreCharts} from "@nzi/charts";
import {PrintControls} from "./PrintControls";
import {isPublishedCrpReport} from "../publishedReportValidation";
import "./print.css";
import "../../../../reports/[versionId]/report-composed.css";
import { formatDate } from "../../../../lib/formatDate";
import { LogoMark } from "../../../../lib/LogoMark";
import {deploymentNames} from "../../../../lib/organisationBrand";
import {organisationCopy,type OrganisationCopy} from "../../../../lib/organisationName";
import {ReportComposedView} from "../../../../reports/[versionId]/ReportComposedView";
import {PRE_COMPOSITION_LABEL,portalIssuerLogoSrc,portalReportViewOf} from "../../../portalReportView";
export const dynamic="force-dynamic";
/**
 * The client's printable report. F-4b: the same issued document the portal shows — the frozen composition, under the version
 * header (D3) — or, for a version issued before compositions were frozen, its snapshot render, labelled (D1). If the issued
 * document cannot be read, nothing is printed in its place.
 */
export default async function PublishedPrintPage({params,searchParams}:{params:Promise<{jobId:string}>;searchParams:Promise<{report?:string}>}){const {jobId}=await params,{report:wanted}=await searchParams,query=wanted?`?reportVersionId=${encodeURIComponent(wanted)}`:"",org=organisationCopy(await deploymentNames()),cookie=(await headers()).get("cookie"),base=(process.env.NZI_ISOLATED_API_URL??"").replace(/\/$/,"");let response:Response;try{response=await fetch(`${base}/api/portal/jobs/${jobId}/published-report${query}`,{cache:"no-store",headers:cookie?{cookie}:{}})}catch{return <PrintUnavailable org={org} jobId={jobId} state="failed"/>}if(response.status===401)redirect(`/portal/login?next=${encodeURIComponent(`/portal/jobs/${jobId}/print`)}`);if(!response.ok)return <PrintUnavailable org={org} jobId={jobId} state={response.status===403?"denied":response.status===404?"missing":"failed"}/>;let body:unknown;try{body=await response.json()}catch{return <PrintUnavailable org={org} jobId={jobId} state="failed"/>}if(!isPublishedReportBody(body,jobId))return <PrintUnavailable org={org} jobId={jobId} state="failed"/>;const {report}=body,snapshot=report.snapshot;
  let view;try{const composed=await fetch(`${base}/api/portal/jobs/${jobId}/published-report/composition?reportVersionId=${encodeURIComponent(report.reportVersionId)}`,{cache:"no-store",headers:cookie?{cookie}:{}});view=composed.ok?portalReportViewOf(await composed.json(),{reportVersionId:report.reportVersionId,jobId}):{state:"failed" as const,message:""}}catch{view={state:"failed" as const,message:""}}
  if(view.state==="failed")return <PrintUnavailable org={org} jobId={jobId} state="failed"/>;
  const header=<><div className="eyebrow">{report.issuer?`${report.issuer.shortName} `:""}Professional Carbon Reduction Plan</div><div className="report-client"><LogoMark src={report.clientLogoAssetId?`/api/portal/logo-assets/${encodeURIComponent(report.clientLogoAssetId)}`:null} name={snapshot.client} className="report-client-mark"/><div><h1 style={{margin:"8px 0 4px"}}>{snapshot.client}</h1><p className="sub" style={{marginTop:0}}>{snapshot.jobNumber} · Reporting year {snapshot.reportingYear}{report.scopeLabel?` · ${report.scopeLabel}`:""}</p></div></div>{report.signee?<p className="report-signee">Signed off by <b>{report.signee.name}</b>{report.signee.jobTitle?`, ${report.signee.jobTitle}`:""}</p>:null}<div className="nz-banner ok" style={{margin:"18px 0"}}><div><b>Published and verified report</b><div style={{marginTop:3}}>Immutable version {report.reportVersionId} · published {formatDate(report.publishedAt)}</div></div></div></>;
  if(view.state==="composed")return <><PrintControls/><main className="published-print" style={{background:"#EEF2F0",padding:24,minHeight:"100vh"}}><article className="published-print-sheet published-print-composed" style={{maxWidth:900,margin:"0 auto",background:"white",padding:28,boxShadow:"0 4px 24px rgba(11,27,43,.08)"}}>{header}<ReportComposedView composition={view.composition} issuerLogoSrc={portalIssuerLogoSrc(jobId)}/></article></main></>;
  const charts=resolveCrpCoreCharts({id:snapshot.id,jobId:snapshot.jobId,jobNumber:snapshot.jobNumber,client:snapshot.client,reportingYear:snapshot.reportingYear,generatedAt:snapshot.createdAt,dataHash:snapshot.dataHash,target:snapshot.target,intensityTarget:snapshot.intensityTarget,annualComparison:snapshot.annualComparison,measurements:snapshot.measurements.map(row=>({rowId:row.rowId,scope:row.scope,scopeCode:row.scopeCode,sourceLabel:row.sourceLabel,siteId:row.siteId,siteLabel:row.siteLabel,purchasedGoodsCategoryId:row.purchasedGoodsCategoryId,purchasedGoodsCategoryLabel:row.purchasedGoodsCategoryLabel,tco2e:row.tco2e,factorSet:row.factorSet}))});
  return <><PrintControls/><main className="published-print" style={{background:"#EEF2F0",padding:24,minHeight:"100vh"}}><article className="published-print-sheet" style={{maxWidth:900,margin:"0 auto",background:"white",padding:28,boxShadow:"0 4px 24px rgba(11,27,43,.08)"}}>{header}<p className="sub"><b>{PRE_COMPOSITION_LABEL}.</b> Shown as it was drawn when it was issued.</p><ManifestChartSet manifest={crpProfessionalManifest} charts={charts} reviewedSnapshotId={snapshot.id}/><footer style={{borderTop:"1px solid #E4EAE7",marginTop:24,paddingTop:12,fontSize:10,color:"#68766F"}}>Evidence identity: {report.dataHash} · Manifest v{report.manifestVersion} · Snapshot {snapshot.id}</footer></article></main></>}

function isPublishedReportBody(value:unknown,expectedJobId:string):value is {report:ClientFacingPublishedCrpReport}{return Boolean(value&&typeof value==="object"&&isPublishedCrpReport((value as {report?:unknown}).report,expectedJobId))}
function PrintUnavailable({org,jobId,state}:{org:OrganisationCopy;jobId:string;state:"denied"|"missing"|"failed"}){const denied=state==="denied",missing=state==="missing";return <main className="nz-body"><div className="nz-banner warn"><div><b>{denied?"Report access is not granted":missing?"No published report is available":"Published report could not be loaded"}</b><div>{denied?`Ask ${org.your("adviser")} to review your job-level access.`:missing?`${org.Your("team")} will release the verified version when assurance is complete.`:"No conclusion has been made about access or publication state."}</div></div></div><Link className="nz-btn" href={`/portal/jobs/${jobId}`}>Back to report workspace</Link></main>}
