"use client";
import { useMemo, useState } from "react";
import { AppShell, EvidenceDrawer, TopBar, WorkspaceRail } from "@nzi/ui";
import { weightedPipeline, type SalesOpportunity, type SalesProspect } from "@nzi/mock-data";
import { NAV, USER } from "../lib/nav";

type View = "pipeline" | "prospects" | "runs";
const money = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(value);
const unavailable = "This workflow is not connected in the isolated staging environment.";

export function SalesBoard({ opportunities, prospects, runs }: { opportunities: SalesOpportunity[]; prospects: SalesProspect[]; runs: { id: string; profile: string; state: string; candidates: number; verified: number; failed: number; startedAt: string }[] }) {
  const [view, setView] = useState<View>("pipeline");
  const [selectedId, setSelectedId] = useState(opportunities[0]?.id ?? "");
  const [status, setStatus] = useState<"OPEN" | "WON" | "LOST">("OPEN");
  const selected = opportunities.find((item) => item.id === selectedId) ?? opportunities[0];
  const visible = useMemo(() => opportunities.filter((item) => item.status === status), [opportunities, status]);
  const open = opportunities.filter((item) => item.status === "OPEN");
  const overdue = open.filter((item) => {const due=Date.parse(item.nextTaskDue);return Number.isFinite(due)&&due<Date.now()}).length;
  return <AppShell rail={<WorkspaceRail sections={NAV} activeId="bd" user={USER} />} drawer={selected?<EvidenceDrawer kicker={`Opportunity · ${selected.status}`} title={selected.company} subtitle={`${selected.service} · ${selected.stage}`} actions={<><button className="nz-btn" disabled title={unavailable}>Add activity</button><button className="nz-btn pri" disabled title={unavailable}>Open opportunity</button></>}><OpportunityEvidence item={selected} /></EvidenceDrawer>:undefined}>
    <TopBar searchPlaceholder="Search companies, contacts, opportunities…" crumbs={<><b>Sales</b> <span className="muted">/</span> Sales V2</>} />
    <div className="nz-head"><div className="nz-job-titleline"><div><div className="nz-eyebrow">Commercial intelligence</div><h1>Growth pipeline</h1><div className="sub">Evidence-led prospecting, disciplined opportunities and dependable client handoff</div></div><div className="nz-head-actions"><button className="nz-btn" disabled title={unavailable}>New prospecting run</button><button className="nz-btn pri" disabled title={unavailable}>+ New opportunity</button></div></div></div>
    <div className="nz-body" style={{ paddingTop: 18 }}><section className="nz-ops-hero"><div><span className="nz-eyebrow light">Revenue command centre</span><h2>{opportunities.length===0?"No qualified opportunities are recorded.":overdue?`${overdue} overdue commercial action${overdue===1?"":"s"} need attention.`:"The open pipeline has clear next actions."}</h2><p>{opportunities.length===0?"Pipeline value and conversion readiness remain at zero until evidence-backed opportunities are created.":"Verified evidence comes before scoring, while atomic handoff protects the transition from opportunity to client, quote and official job."}</p></div><div className="nz-ops-trust"><span><i>{opportunities.length?"✓":"·"}</i> Evidence first</span><span><i>{opportunities.length?"✓":"·"}</i> Pipeline weighted</span><span><i>{opportunities.length?"✓":"·"}</i> Handoff protected</span></div></section><div className="nz-metrics"><Metric label="Open pipeline" value={money(open.reduce((sum, item) => sum + item.value, 0))} /><Metric label="Weighted pipeline" value={money(weightedPipeline(opportunities))} /><Metric label="Open opportunities" value={`${open.length}`} /><Metric label="Overdue tasks" value={`${overdue}`} /></div>
      <div className="nz-toolbar" style={{ padding: "18px 0 12px" }}><div className="nz-filters">{(["pipeline", "prospects", "runs"] as View[]).map((id) => <button type="button" key={id} aria-pressed={view === id} className={view === id ? "on" : undefined} onClick={() => setView(id)}>{id}</button>)}</div>{view === "pipeline" ? <div className="nz-filters" style={{ marginLeft: "auto" }}>{(["OPEN", "WON", "LOST"] as const).map((id) => <button type="button" key={id} aria-pressed={status === id} className={status === id ? "on" : undefined} onClick={() => setStatus(id)}>{id}</button>)}</div> : null}</div>
      {view === "pipeline" && <Pipeline rows={visible} selectedId={selectedId} select={setSelectedId} />}
      {view === "prospects" && <Prospects rows={prospects} />}
      {view === "runs" && <Runs rows={runs} />}
      <section className="nz-sales-gate"><div><span className="nz-eyebrow">Protected conversion</span><h2>One commercial handoff, three governed outcomes.</h2><p>Canonical client, quote and job services share a single command key, so retries cannot create duplicate records.</p></div><ol><li><i>1</i><span><b>Verify evidence</b><small>Sources retained before scoring</small></span></li><li><i>2</i><span><b>Approve conversion</b><small>Permission checked at handoff</small></span></li><li><i>3</i><span><b>Commit records</b><small>Atomic and idempotent</small></span></li></ol></section>
    </div>
  </AppShell>;
}

function Pipeline({ rows, selectedId, select }: { rows: SalesOpportunity[]; selectedId: string; select: (id: string) => void }) { return <div className="nz-panel nz-sales-table"><table className="nz-tbl"><thead><tr><th>Company / contact</th><th>Service</th><th>Stage</th><th className="num">Value</th><th className="num">Probability</th><th>Next task</th><th>Owner</th><th>Handoff</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} tabIndex={0} aria-selected={selectedId === item.id} className={`row${selectedId === item.id ? " sel" : ""}`} onClick={() => select(item.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(item.id); } }}><td style={{ fontWeight: 600 }}>{item.company}<div className="muted" style={{ fontSize: 11 }}>{item.contact}</div></td><td>{item.service}</td><td><span className={`nz-st ${item.stage === "negotiation" ? "done" : item.stage === "proposal" ? "est" : "need"}`}>{item.stage}</span></td><td className="num">{money(item.value)}</td><td><span className="nz-sales-probability"><i><span style={{width:`${item.probability}%`}}/></i><b className="num">{item.probability}%</b></span></td><td>{item.nextTask}<div className="muted" style={{ fontSize: 11 }}>{item.nextTaskDue}</div></td><td>{item.owner}</td><td>{item.handoff?.jobNumber ?? item.handoff?.quoteNumber ?? "Not started"}</td></tr>)}</tbody></table>{rows.length === 0 ? <div className="nz-table-empty">No opportunities in this state.</div> : null}</div>; }
function Prospects({ rows }: { rows: SalesProspect[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Company</th><th>Status</th><th>Why it may fit</th><th className="num">Evidence</th><th>Origin</th><th>Action</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td style={{ fontWeight: 600 }}>{item.company}</td><td><span className={`nz-st ${item.status === "promoted" ? "done" : item.status === "rejected" ? "nof" : "est"}`}>{item.status}</span></td><td>{item.reason}</td><td className="num">{item.evidenceCount}</td><td>{item.source}</td><td><button className="nz-btn" disabled title={unavailable}>Review</button></td></tr>)}</tbody></table>{rows.length === 0 ? <div className="nz-table-empty">No prospects have been retained.</div> : null}</div>; }
function Runs({ rows }: { rows: { id: string; profile: string; state: string; candidates: number; verified: number; failed: number; startedAt: string }[] }) { return <div className="nz-panel"><table className="nz-tbl"><thead><tr><th>Run</th><th>Search profile</th><th>Started</th><th className="num">Candidates</th><th className="num">Verified</th><th className="num">Failed</th><th>State</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td style={{ fontWeight: 600 }}>{item.id}</td><td>{item.profile}</td><td>{item.startedAt}</td><td className="num">{item.candidates}</td><td className="num">{item.verified}</td><td className="num">{item.failed}</td><td><span className={`nz-st ${item.failed ? "est" : "done"}`}>{item.state}</span></td></tr>)}</tbody></table>{rows.length === 0 ? <div className="nz-table-empty">No prospecting runs are available.</div> : null}</div>; }
function OpportunityEvidence({ item }: { item: SalesOpportunity }) { return <><div className={`nz-banner ${item.evidence.length ? "ok" : "warn"}`}><div><b>{item.evidence.length ? `${item.evidence.length} verified evidence source${item.evidence.length === 1 ? "" : "s"}.` : "No verified evidence."}</b></div></div><div className="nz-kv"><span className="k">Stage / status</span><span className="v">{item.stage} · {item.status}</span></div><div className="nz-kv"><span className="k">Value</span><span className="v num">{money(item.value)}</span></div><div className="nz-kv"><span className="k">Owner</span><span className="v">{item.owner}</span></div><div className="nz-kv"><span className="k">Next task</span><span className="v">{item.nextTaskDue}</span></div><div className="nz-sect">Evidence before score</div>{item.evidence.map((source) => <div key={`${source.source}-${source.capturedAt}`} className="nz-kv"><span className="k">{source.source}<br /><small>{source.capturedAt}</small></span><span className="v">{source.summary}</span></div>)}<div className="nz-sect">Stage history</div>{item.history.map((event) => <div key={`${event.at}-${event.event}`} className="nz-kv"><span className="k">{event.at}</span><span className="v">{event.event}<br /><small>{event.actor}</small></span></div>)}<div className="nz-sect">Conversion guard</div><div className="nz-kv"><span className="k">Command key</span><span className="v num">{item.handoff?.commandKey ?? "Not initiated"}</span></div></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="nz-metric"><div className="l">{label}</div><div className="v num">{value}</div></div>; }
