"use client";
import {FormEvent,useEffect,useState} from "react";
import type {StaffReportThread} from "@nzi/isolated-backend";
type Filter="action"|"reply"|"approval"|"all";
function validThreads(value:unknown):value is StaffReportThread[]{return Array.isArray(value)&&value.every(thread=>thread&&typeof thread==="object"&&typeof thread.reportVersionId==="string"&&typeof thread.jobId==="string"&&typeof thread.needsReply==="boolean"&&typeof thread.awaitingApproval==="boolean"&&Array.isArray(thread.approvals)&&Array.isArray(thread.comments))}

export function ReportReviewInbox(){
  const [threads,setThreads]=useState<StaffReportThread[]|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState(""),[filter,setFilter]=useState<Filter>("action");
  async function load(){setError("");try{const response=await fetch("/api/isolated/reports/review-messages",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.message??"Review messages are unavailable.");if(!validThreads(body.threads))throw new Error("The review inbox returned an invalid response.");setThreads(body.threads)}catch(cause){setError(cause instanceof Error?cause.message:"Review messages are unavailable.");setThreads(null)}}
  useEffect(()=>{void load()},[]);
  async function reply(event:FormEvent<HTMLFormElement>,thread:StaffReportThread){event.preventDefault();if(pending)return;const form=event.currentTarget,body=String(new FormData(form).get("body")??"");setPending(thread.reportVersionId);setError("");setNotice("");try{const response=await fetch("/api/isolated/reports/review-messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:thread.jobId,reportVersionId:thread.reportVersionId,body})}),payload=await response.json();if(!response.ok)throw new Error(payload.message??"Reply could not be sent.");if(typeof payload.comment?.commentId!=="string"||payload.comment.reportVersionId!==thread.reportVersionId)throw new Error("The reply service returned an invalid confirmation.");form.reset();setNotice(`Reply recorded against immutable version ${thread.reportVersionId}.`);await load()}catch(cause){setError(cause instanceof Error?cause.message:"The reply outcome could not be verified.")}finally{setPending("")}}
  const visible=(threads??[]).filter(thread=>filter==="all"||(filter==="action"&&(thread.needsReply||thread.awaitingApproval))||(filter==="reply"&&thread.needsReply)||(filter==="approval"&&thread.awaitingApproval)).sort((a,b)=>Number(b.needsReply)-Number(a.needsReply)||Number(b.awaitingApproval)-Number(a.awaitingApproval));
  return <div className="nz-panel nz-review-inbox">
    <div className="nz-review-heading"><div><span className="nz-eyebrow">Version-bound assurance</span><h2>Client review and approval</h2><p className="sub">Action-led, version-specific approval records and conversations.</p></div><div className="nz-review-counts"><span className="nz-st nof">{threads===null?"—":threads.filter(thread=>thread.needsReply).length} need reply</span><span className="nz-st est">{threads===null?"—":threads.filter(thread=>thread.awaitingApproval).length} awaiting approval</span><span className="nz-st done">{threads===null?"—":threads.filter(thread=>!thread.awaitingApproval).length} approved</span></div></div>
    <div className="nz-review-filters">{([['action','Action needed'],['reply','Needs reply'],['approval','Awaiting approval'],['all','All']] as Array<[Filter,string]>).map(([id,label])=><button type="button" key={id} aria-pressed={filter===id} className={`nz-btn${filter===id?" pri":""}`} onClick={()=>setFilter(id)}>{label}</button>)}</div>
    {error?<div className="nz-banner warn nz-review-notice" role="alert"><div><b>Review inbox unavailable</b><div>{error}</div></div></div>:null}
    {notice?<div className="nz-banner ok nz-review-notice" role="status">{notice}</div>:null}
    {error?null:threads===null?<div className="nz-review-loading" role="status"><i aria-hidden="true"/><span>Loading version-bound review threads…</span></div>:visible.length===0?<div className="nz-review-empty"><b>No threads match this filter</b><span>{filter==="action"?"There are no client replies or approvals requiring action.":"Choose another filter to view the remaining version-specific records."}</span></div>:visible.map(thread=><section className="nz-review-thread" key={thread.reportVersionId}>
      <div className="nz-review-thread-head"><div><b>{thread.jobNumber} · {thread.client}</b><span className="sub">{thread.reportingYear??"Year not set"} · {thread.reportVersionId}</span></div>{thread.needsReply?<span className="nz-st nof">Client reply needed</span>:<span className={`nz-st ${thread.awaitingApproval?"est":"done"}`}>{thread.awaitingApproval?"Awaiting approval":"Client approved"}</span>}</div>
      {thread.approvals.map(approval=><div className="nz-approval-record" key={approval.approvalId}><i>✓</i><div><b>Approved by {approval.displayName}</b><span>{new Date(approval.approvedAt).toLocaleString("en-GB")} · immutable approval {approval.approvalId}</span></div></div>)}
      <div className="nz-review-conversation">{thread.comments.length===0?<div className="nz-thread-empty">No messages for this version.</div>:thread.comments.map(comment=><article key={comment.commentId} className={`nz-review-message ${comment.authorPrincipal}`}><header><b>{comment.authorDisplayName}</b><span>{comment.authorPrincipal==="portal"?"Client":"NZI"} · {new Date(comment.createdAt).toLocaleString("en-GB")}</span></header><p>{comment.body}</p></article>)}</div>
      <form className="nz-review-reply" onSubmit={event=>reply(event,thread)}><label className="nz-sr-only" htmlFor={`reply-${thread.reportVersionId}`}>Reply to {thread.client}</label><input id={`reply-${thread.reportVersionId}`} className="nz-inp" name="body" maxLength={4000} required disabled={pending!==""} placeholder={`Reply about ${thread.reportVersionId}…`}/><button className="nz-btn pri" disabled={pending!==""}>{pending===thread.reportVersionId?"Sending…":"Reply to client"}</button></form>
    </section>)}
  </div>;
}
