"use client";
import {FormEvent,useEffect,useState} from "react";
import type {StaffReportThread} from "@nzi/isolated-backend";
type Filter="action"|"reply"|"approval"|"all";

export function ReportReviewInbox(){
  const [threads,setThreads]=useState<StaffReportThread[]|null>(null),[error,setError]=useState(""),[pending,setPending]=useState(""),[filter,setFilter]=useState<Filter>("action");
  async function load(){try{const response=await fetch("/api/isolated/reports/review-messages",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.message??"Review messages are unavailable.");setThreads(body.threads)}catch(cause){setError(cause instanceof Error?cause.message:"Review messages are unavailable.");setThreads([])}}
  useEffect(()=>{void load()},[]);
  async function reply(event:FormEvent<HTMLFormElement>,thread:StaffReportThread){event.preventDefault();const form=event.currentTarget,body=String(new FormData(form).get("body")??"");setPending(thread.reportVersionId);setError("");const response=await fetch("/api/isolated/reports/review-messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:thread.jobId,reportVersionId:thread.reportVersionId,body})}),payload=await response.json();setPending("");if(!response.ok){setError(payload.message??"Reply could not be sent.");return}form.reset();await load()}
  const visible=(threads??[]).filter(thread=>filter==="all"||(filter==="action"&&(thread.needsReply||thread.awaitingApproval))||(filter==="reply"&&thread.needsReply)||(filter==="approval"&&thread.awaitingApproval));
  return <div className="nz-panel" style={{padding:18,marginTop:18}}>
    <div style={{display:"flex",alignItems:"center"}}><div><h2 style={{margin:0,fontSize:17}}>Client review and approval</h2><p className="sub" style={{margin:"4px 0 0"}}>Action-led, version-specific approval records and conversations.</p></div><div style={{display:"flex",gap:8,marginLeft:"auto"}}><span className="nz-st nof">{threads?.filter(thread=>thread.needsReply).length??0} need reply</span><span className="nz-st est">{threads?.filter(thread=>thread.awaitingApproval).length??0} awaiting approval</span><span className="nz-st done">{threads?.filter(thread=>!thread.awaitingApproval).length??0} approved</span></div></div>
    <div style={{display:"flex",gap:8,marginTop:16}}>{([['action','Action needed'],['reply','Needs reply'],['approval','Awaiting approval'],['all','All']] as Array<[Filter,string]>).map(([id,label])=><button key={id} className={`nz-btn${filter===id?" pri":""}`} onClick={()=>setFilter(id)}>{label}</button>)}</div>
    {error?<div className="nz-banner warn" role="alert" style={{marginTop:14}}>{error}</div>:null}
    {threads===null?<p className="sub">Loading review threads...</p>:visible.length===0?<p className="sub" style={{marginTop:16}}>No report threads match this filter.</p>:visible.map(thread=><section key={thread.reportVersionId} style={{borderTop:"1px solid #E4EAE7",paddingTop:16,marginTop:16}}>
      <div style={{display:"flex",alignItems:"baseline",gap:8}}><b>{thread.jobNumber} · {thread.client}</b><span className="sub">{thread.reportingYear??"Year not set"} · {thread.reportVersionId}</span>{thread.needsReply?<span className="nz-st nof" style={{marginLeft:"auto"}}>Client reply needed</span>:<span className={`nz-st ${thread.awaitingApproval?"est":"done"}`} style={{marginLeft:"auto"}}>{thread.awaitingApproval?"Awaiting approval":"Client approved"}</span>}</div>
      {thread.approvals.map(approval=><div className="nz-banner ok" key={approval.approvalId} style={{marginTop:10}}><div><b>Approved by {approval.displayName}</b><div style={{marginTop:3}}>{new Date(approval.approvedAt).toLocaleString("en-GB")} · immutable approval {approval.approvalId}</div></div></div>)}
      {thread.comments.length===0?<p className="sub">No messages for this version.</p>:thread.comments.map(comment=><div key={comment.commentId} style={{padding:12,background:comment.authorPrincipal==="portal"?"#FFF8E7":"#F3F7F5",borderRadius:8,marginTop:8}}><b style={{fontSize:13}}>{comment.authorDisplayName}</b><span className="sub"> · {comment.authorPrincipal==="portal"?"Client":"NZI"} · {new Date(comment.createdAt).toLocaleString("en-GB")}</span><p style={{fontSize:13,whiteSpace:"pre-wrap",margin:"6px 0 0"}}>{comment.body}</p></div>)}
      <form onSubmit={event=>reply(event,thread)} style={{display:"flex",gap:8,marginTop:10}}><input className="nz-inp" name="body" maxLength={4000} required placeholder="Reply to this client review thread..."/><button className="nz-btn pri" disabled={pending===thread.reportVersionId}>{pending===thread.reportVersionId?"Sending...":"Reply"}</button></form>
    </section>)}
  </div>;
}
