"use client";
import {useEffect,useState} from "react";
import type {PublishedCrpReportReadModel} from "@nzi/contracts";
import type {PortalDeliverableKind,PortalDeliverableRecord} from "@nzi/isolated-backend";
import {redirectIfPortalSessionEnded} from "./portalSessionClient";

const kinds:PortalDeliverableKind[]=["report","certificate","methodology"];
const titles:Record<PortalDeliverableKind,string>={report:"Published Carbon Reduction Plan",certificate:"Emissions certificate",methodology:"Methodology statement"};
function validRecord(value:unknown,report:PublishedCrpReportReadModel):value is PortalDeliverableRecord{if(!value||typeof value!=="object")return false;const item=value as PortalDeliverableRecord;return kinds.includes(item.kind)&&item.documentId===`${report.reportVersionId}:${item.kind}`&&item.reportVersionId===report.reportVersionId&&item.snapshotId===report.snapshot.id&&item.evidenceHash===report.dataHash&&item.contentType==="application/pdf"&&item.filename.endsWith(".pdf")}

export function PortalDeliverablesPanel({report,clientMode}:{report:PublishedCrpReportReadModel;clientMode:boolean}){
  const [documents,setDocuments]=useState<PortalDeliverableRecord[]|null>(clientMode?null:[]),[error,setError]=useState("");
  useEffect(()=>{if(!clientMode)return;fetch(`/api/portal/jobs/${report.snapshot.jobId}/deliverables`,{cache:"no-store"}).then(async response=>{if(await redirectIfPortalSessionEnded(response))return;const body=await response.json();if(!response.ok)throw new Error(body.message??"Documents are unavailable.");if(body.reportVersionId!==report.reportVersionId||!Array.isArray(body.documents)||body.documents.length!==3||!body.documents.every((item:unknown)=>validRecord(item,report))||new Set(body.documents.map((item:PortalDeliverableRecord)=>item.kind)).size!==3)throw new Error("The document register did not match this publication.");setDocuments(body.documents)}).catch(cause=>{setError(cause instanceof Error?cause.message:"Documents are unavailable.");setDocuments([])})},[clientMode,report]);
  const displayDocuments:PortalDeliverableRecord[]=clientMode?(documents??[]):kinds.map(kind=>({kind,title:titles[kind],documentId:`${report.reportVersionId}:${kind}`,filename:"",contentType:"application/pdf",reportVersionId:report.reportVersionId,snapshotId:report.snapshot.id,evidenceHash:report.dataHash,publishedAt:report.publishedAt}));
  return <section className="nz-panel nz-published-doc"><div className="nz-published-doc-head"><div><span className="nz-eyebrow">Published client record</span><h2>{report.snapshot.jobNumber} · Carbon Reduction Plan</h2><p>Version {report.reportVersionId} · generated from the verified evidence shown in Results</p></div><span className="nz-st done">3 version-bound PDFs</span></div><dl className="nz-document-proof"><div><dt>Report version</dt><dd>{report.reportVersionId}</dd></div><div><dt>Reviewed snapshot</dt><dd>{report.snapshot.id}</dd></div><div><dt>Evidence hash</dt><dd className="num">{report.dataHash}</dd></div></dl>{clientMode&&documents===null?<div className="nz-portal-state loading" role="status"><i>↻</i><div><b>Verifying document records</b><span>Checking file identity and access for this publication…</span></div></div>:error?<div className="nz-portal-state failed" role="alert"><i>!</i><div><b>Downloads are currently unavailable</b><span>{error} Your published results remain unchanged.</span></div></div>:<div>{displayDocuments.map(document=><div key={document.documentId} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 4px",borderTop:"1px solid #EDF1EF"}}><div><b>{document.title}</b><div className="sub">PDF · {report.reportVersionId}</div></div>{clientMode?<a className="nz-btn" style={{marginLeft:"auto"}} href={`/api/portal/jobs/${report.snapshot.jobId}/deliverables/${document.kind}?reportVersionId=${encodeURIComponent(report.reportVersionId)}`}>Download PDF</a>:<span className="nz-st done" style={{marginLeft:"auto"}}>Available to client</span>}</div>)}</div>}<div className="nz-banner ok"><div><b>One immutable evidence source</b><div>Every download identifies this report version, snapshot, evidence hash and its own SHA-256 file digest.</div></div></div></section>
}
