"use client";
import {useCallback,useEffect,useState} from "react";
import {isPortalIdentity,isPortalJobList,type PortalIdentity as User,type PortalJob as Job} from "./portalPortfolioValidation";
export function PortalHome(){
  const [jobs,setJobs]=useState<Job[]|null>(null),[user,setUser]=useState<User|null>(null),[error,setError]=useState(""),[signingOut,setSigningOut]=useState(false);
  const load=useCallback(async()=>{setError("");setJobs(null);setUser(null);try{const [jobsResponse,userResponse]=await Promise.all([fetch("/api/portal/jobs",{cache:"no-store"}),fetch("/api/portal/auth/me",{cache:"no-store"})]);if(jobsResponse.status===401||userResponse.status===401){window.location.assign("/portal/login");return}if(!jobsResponse.ok||!userResponse.ok)throw new Error("Your secure workspace could not be loaded.");const jobsBody:unknown=await jobsResponse.json(),userBody:unknown=await userResponse.json(),jobList=jobsBody&&typeof jobsBody==="object"?(jobsBody as {jobs?:unknown}).jobs:undefined;if(!isPortalJobList(jobList)||!isPortalIdentity(userBody))throw new Error("Your secure workspace returned an invalid response.");setJobs(jobList);setUser(userBody)}catch(cause){setError(cause instanceof Error?cause.message:"Your secure workspace could not be loaded.");setJobs(null)}},[]);
  useEffect(()=>{void load()},[load]);
  async function logout(){if(signingOut)return;setSigningOut(true);try{await fetch("/api/portal/auth/logout",{method:"POST"})}finally{window.location.assign("/portal/login")}}
  const published=jobs?.filter(job=>job.hasPublishedReport).length??0,approved=jobs?.filter(job=>job.approved).length??0,actions=jobs?.filter(job=>job.hasUnreadNziResponse||(job.hasPublishedReport&&!job.approved)).length??0;
  return <main className="nz-portal-home">
    <header className="nz-portal-header"><div className="nz-portal-header-inner"><a className="nz-portal-brand" href="/portal"><span>N</span><div><b>NZI Pro</b><small>Client portal</small></div></a><div className="nz-portal-user"><div><b>{user?.displayName??"Client user"}</b><small>{user?.email}</small></div><a href="/portal/account">Security</a><button disabled={signingOut} onClick={logout}>{signingOut?"Signing out…":"Sign out"}</button></div></div></header>
    <section className="nz-portal-shell">
      <div className="nz-portal-welcome"><div><span className="nz-eyebrow">Verified sustainability reporting</span><h1>Good {new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}{user?.displayName?`, ${user.displayName.split(" ")[0]}`:""}.</h1><p>Your reports, approvals and conversations with the NZI advisory team—all in one secure place.</p></div><div className="nz-trust-mark"><i>✓</i><div><b>Secure client workspace</b><span>MFA protected · access controlled</span></div></div></div>
      <div className="nz-portal-summary"><div><span>Reporting engagements</span><b>{jobs===null?"—":jobs.length}</b><small>Explicitly granted to you</small></div><div><span>Published reports</span><b>{jobs===null?"—":published}</b><small>Immutable client records</small></div><div><span>Approved</span><b>{jobs===null?"—":approved}</b><small>Version-bound approvals</small></div><div className={actions?"attention":""}><span>Actions for you</span><b>{jobs===null?"—":actions}</b><small>{actions?"Review requested":"Everything up to date"}</small></div></div>
      <div className="nz-portal-section-head"><div><span className="nz-eyebrow">Your portfolio</span><h2>Reporting engagements</h2><p>Only work explicitly authorised for your account is shown.</p></div>{actions>0&&<span className="nz-st need">{actions} action{actions===1?"":"s"} waiting</span>}</div>
      <div className="nz-portal-jobs">{error?<div className="nz-portal-state failed" role="alert"><i>!</i><div><b>Reporting engagements are temporarily unavailable</b><span>{error} No access or report totals have been inferred.</span><button className="nz-btn" onClick={()=>void load()}>Try again</button></div></div>:jobs===null?<div className="nz-portal-state loading" role="status"><i>↻</i><div><b>Loading your secure workspace</b><span>Checking your account and job-level access grants…</span></div></div>:jobs.length===0?<div className="nz-portal-state empty"><i>✓</i><div><b>No engagements available</b><span>Your NZI consultant will grant access when a reporting engagement is ready.</span></div></div>:jobs.map(job=><article className="nz-portal-job" key={job.id}><div className="nz-portal-job-year"><b>{job.reportingYear??"—"}</b><span>reporting year</span></div><div className="nz-portal-job-copy"><span>{job.number} · Carbon Reduction Plan</span><h3>{job.title}</h3><p>{job.approved&&job.approvedAt?`Approved ${new Date(job.approvedAt).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}`:job.hasPublishedReport?"Your verified report is ready for review.":"Your NZI team is preparing the report."}</p></div><div className="nz-portal-job-action">{job.hasPublishedReport?<><span className={`nz-st ${job.hasUnreadNziResponse?"nof":job.approved?"done":"est"}`}>{job.hasUnreadNziResponse?"New adviser response":job.approved?"Approved":"Approval requested"}</span><a className="nz-btn pri" href={`/portal/jobs/${job.id}`}>{job.approved?"Open report":"Review and approve"} <b>→</b></a></>:<span className="nz-st est">In preparation</span>}</div></article>)}</div>
      <footer className="nz-portal-footer"><span>NZI Pro · Net Zero International</span><span>Need help? Contact your NZI adviser</span></footer>
    </section>
  </main>;
}
