"use client";
import {useEffect,useState} from "react";
type Job={id:string;number:string;title:string;reportingYear:number|null;hasPublishedReport:boolean};
type User={displayName:string;email:string};
export function PortalHome(){
  const [jobs,setJobs]=useState<Job[]|null>(null),[user,setUser]=useState<User|null>(null);
  useEffect(()=>{Promise.all([fetch("/api/portal/jobs",{cache:"no-store"}),fetch("/api/portal/auth/me",{cache:"no-store"})]).then(async([jobsResponse,userResponse])=>{if(jobsResponse.status===401||userResponse.status===401){window.location.assign("/portal/login");return}const jobsBody=await jobsResponse.json(),userBody=await userResponse.json();setJobs(jobsBody.jobs??[]);setUser(userBody)}).catch(()=>setJobs([]))},[]);
  async function logout(){await fetch("/api/portal/auth/logout",{method:"POST"});window.location.assign("/portal/login")}
  return <main style={{minHeight:"100vh",background:"#F3F7F5",padding:"40px 24px",color:"#0B1B2B"}}><section style={{maxWidth:900,margin:"0 auto"}}><div style={{display:"flex",alignItems:"flex-start",gap:12}}><div><div className="eyebrow">NZI Client Portal</div><h1>Your reporting jobs</h1><p className="sub">Only jobs explicitly granted to your portal account appear here.</p></div><div style={{marginLeft:"auto",textAlign:"right"}}><b>{user?.displayName??"Client user"}</b><div className="sub">{user?.email}</div><div style={{display:"flex",gap:8,marginTop:10,justifyContent:"flex-end"}}><a className="nz-btn" href="/portal/account">Account security</a><button className="nz-btn" onClick={logout}>Sign out</button></div></div></div><div className="nz-panel" style={{marginTop:22}}>{jobs===null?<p>Loading...</p>:jobs.length===0?<p>No jobs have been granted to this account.</p>:jobs.map(job=><div key={job.id} style={{display:"flex",alignItems:"center",padding:"14px 0",borderBottom:"1px solid #E4EAE7"}}><div><b>{job.number} · {job.title}</b><div className="sub">{job.reportingYear??"Reporting year not set"}</div></div>{job.hasPublishedReport?<a className="nz-btn pri" style={{marginLeft:"auto"}} href={`/portal/jobs/${job.id}`}>View published report</a>:<span className="nz-st est" style={{marginLeft:"auto"}}>Report pending</span>}</div>)}</div></section></main>;
}
