"use client";
import {FormEvent,useEffect,useState} from "react";
import {ManifestChartSet,crpChartSamples,crpProfessionalManifest,resolveCrpCoreCharts,reviewedCrpSnapshotSample,validateManifest} from "@nzi/charts";
import {canEnterPortalData,portalAccessSample,portalBucketsSample,publishedReportSample} from "@nzi/mock-data";
import type {PublishedCrpReportReadModel} from "@nzi/contracts";
import type {PortalReportApproval,PortalReportComment} from "@nzi/isolated-backend";

type Tab="results"|"data"|"documents"|"messages";
function isComment(value:unknown,reportVersionId?:string,expectedAuthor?:PortalReportComment["authorPrincipal"]):value is PortalReportComment{if(!value||typeof value!=="object")return false;const comment=value as Partial<PortalReportComment>;return typeof comment.commentId==="string"&&comment.commentId.length>0&&typeof comment.reportVersionId==="string"&&comment.reportVersionId.length>0&&(!reportVersionId||comment.reportVersionId===reportVersionId)&&(comment.parentCommentId===null||typeof comment.parentCommentId==="string")&&(comment.authorPrincipal==="portal"||comment.authorPrincipal==="staff")&&(!expectedAuthor||comment.authorPrincipal===expectedAuthor)&&typeof comment.authorDisplayName==="string"&&comment.authorDisplayName.length>0&&typeof comment.createdAt==="string"&&!Number.isNaN(Date.parse(comment.createdAt))&&typeof comment.body==="string"&&comment.body.trim().length>0&&comment.body.length<=4000}
function isApproval(value:unknown,reportVersionId?:string):value is PortalReportApproval{if(!value||typeof value!=="object")return false;const approval=value as Partial<PortalReportApproval>;return typeof approval.approvalId==="string"&&approval.approvalId.length>0&&typeof approval.reportVersionId==="string"&&approval.reportVersionId.length>0&&(!reportVersionId||approval.reportVersionId===reportVersionId)&&typeof approval.approvedAt==="string"&&!Number.isNaN(Date.parse(approval.approvedAt))&&approval.statementVersion===1}
export function PortalWorkspace({report,approval=null,clientMode=false}:{report?:PublishedCrpReportReadModel;approval?:PortalReportApproval|null;clientMode?:boolean}){
  const [tab,setTab]=useState<Tab>("results"),snapshot=report?.snapshot;
  const tabs:Array<{id:Tab;label:string}>=report?[{id:"results",label:"Published results"},{id:"documents",label:"Documents"},{id:"messages",label:"Review messages"}]:[{id:"results",label:"Results"},{id:"data",label:"Data entry"},{id:"documents",label:"Documents"},{id:"messages",label:"Messages"}];
  return <div className="nz-published-workspace">
    {!clientMode&&<aside className="nz-preview-boundary" role="note"><div><b>Staff preview</b><span>Read-only representation of the client experience · you are not signed in as a client</span></div><a href={report?`/jobs/${snapshot?.jobId}`:"/reports"}>Exit preview</a></aside>}
    <header className="nz-published-header"><div><div className="nz-published-mark">N</div><div className="nz-published-brand"><b>NZI Pro</b><span>Client portal</span></div><div className="nz-published-user"><b>{report?snapshot?.client:"Priya Nair"}</b><span>{report?(clientMode?"Authorised client user":"Staff publication preview"):"Bushy Tails Ltd · client user"}</span></div></div></header>
    {clientMode?<div className="nz-portal-context"><div><a href="/portal">← Reporting jobs</a><span>Published report workspace</span></div><a href="/portal/account">Account security</a></div>:null}
    <div className="nz-portal-tabs"><div role="tablist" aria-label="Published report sections">{tabs.map(item=><button type="button" role="tab" key={item.id} aria-selected={tab===item.id} onClick={()=>setTab(item.id)} className={tab===item.id?"active":undefined}>{item.label}</button>)}</div></div>
    <main className="nz-published-main"><div className="nz-published-heading"><div><span className="nz-eyebrow">{snapshot?.jobNumber??"J000712"} · Carbon Reduction Plan</span><h1>{tab==="results"?"Your carbon impact":tab==="data"?"Provide activity data":tab==="documents"?"Reports and documents":"Review messages"}</h1><p>Reporting year {snapshot?.reportingYear??2024} · published and verified by NZI consultants</p></div><span className="nz-st done">{report?"Current published version":"Published version v1"}</span></div>
      {tab==="results"&&<Results report={report} initialApproval={approval} clientMode={clientMode}/>} {!report&&tab==="data"&&<DataEntry/>}{report&&tab==="documents"?<PublishedDocuments report={report} clientMode={clientMode}/>:!report&&tab==="documents"?<Documents/>:null}{report&&tab==="messages"?<ReportMessages report={report} clientMode={clientMode}/>:!report&&tab==="messages"?<Messages/>:null}
    </main>
  </div>;
}

function ReportMessages({report,clientMode}:{report:PublishedCrpReportReadModel;clientMode:boolean}){
  const [comments,setComments]=useState<PortalReportComment[]|null>(clientMode?null:[]),[loadError,setLoadError]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState(false);
  const endpoint=`/api/portal/jobs/${report.snapshot.jobId}/published-report/comments`,query=`?reportVersionId=${encodeURIComponent(report.reportVersionId)}`;
  useEffect(()=>{if(!clientMode)return;fetch(endpoint+query,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message??"Messages are unavailable.");if(!Array.isArray(body.comments)||!body.comments.every((comment:unknown)=>isComment(comment,report.reportVersionId))||new Set(body.comments.map((comment:PortalReportComment)=>comment.commentId)).size!==body.comments.length)throw new Error("The review thread returned an invalid response.");setComments(body.comments);void fetch(`${endpoint}/read`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportVersionId:report.reportVersionId})}).catch(()=>undefined)}).catch(cause=>{setLoadError(cause instanceof Error?cause.message:"Messages are unavailable.");setComments(null)})},[clientMode,endpoint,query,report.reportVersionId]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;const form=event.currentTarget,body=String(new FormData(form).get("body")??"");setPending(true);setError("");setNotice("");try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportVersionId:report.reportVersionId,body})}),payload=await response.json();if(!response.ok)throw new Error(payload.message??"The message could not be sent.");if(!isComment(payload.comment,report.reportVersionId,"portal"))throw new Error("The message service returned an invalid confirmation.");setComments(current=>current?.some(comment=>comment.commentId===payload.comment.commentId)?current:[...(current??[]),payload.comment]);setNotice(`Message recorded against ${report.reportVersionId}.`);form.reset()}catch(cause){setError(cause instanceof Error?cause.message:"The message outcome could not be verified.")}finally{setPending(false)}}
  return <div style={card}><div className="nz-banner ok"><div><b>Version-specific review thread</b><div style={{marginTop:3}}>Every message below relates to {report.reportVersionId}; a later publication has its own thread.</div></div></div><div style={{marginTop:16}}>{loadError?<p className="sub">No messages are shown because the review thread is unavailable.</p>:comments===null?<p className="sub" role="status">Loading messages...</p>:comments.length===0?<p className="sub">No review messages have been added for this report version.</p>:comments.map(comment=><div key={comment.commentId} style={{padding:14,borderRadius:8,background:comment.authorPrincipal==="staff"?"#DFF5E9":"#F6F8F7",marginTop:8}}><div style={{display:"flex",gap:8}}><b>{comment.authorDisplayName}</b><span className="sub">{comment.authorPrincipal==="staff"?"NZI reviewer":"Client"} · {new Date(comment.createdAt).toLocaleString("en-GB")}</span></div><p style={{margin:"6px 0 0",color:"#51605A",fontSize:13,whiteSpace:"pre-wrap"}}>{comment.body}</p></div>)}</div>{loadError?<div className="nz-banner warn" role="alert" style={{marginTop:14}}>{loadError}</div>:null}{error?<div className="nz-banner warn" role="alert" style={{marginTop:14}}>{error}</div>:null}{notice?<div className="nz-banner ok" role="status" style={{marginTop:14}}>{notice}</div>:null}{clientMode?<form onSubmit={submit}><label className="nz-sr-only" htmlFor="portal-review-message">Message for the NZI review team</label><textarea id="portal-review-message" className="nz-notes" name="body" maxLength={4000} required disabled={pending||Boolean(loadError)} style={{marginTop:16,width:"100%"}} placeholder="Ask the NZI review team about this published report..."/><div style={{textAlign:"right",marginTop:10}}><button className="nz-btn pri" disabled={pending||Boolean(loadError)}>{pending?"Sending...":"Send message"}</button></div></form>:<p className="sub" style={{marginTop:16}}>Client messages will appear here after publication.</p>}</div>
}

function PublishedDocuments({report,clientMode}:{report:PublishedCrpReportReadModel;clientMode:boolean}){return <section className="nz-panel nz-published-doc"><div className="nz-published-doc-head"><div><span className="nz-eyebrow">Published client record</span><h2>{report.snapshot.jobNumber} · Carbon Reduction Plan</h2><p>Version {report.reportVersionId} · generated from the verified graphics shown in Results</p></div>{clientMode?<a className="nz-btn pri" href={`/portal/jobs/${report.snapshot.jobId}/print`} target="_blank" rel="noreferrer">Print or save PDF</a>:<span className="nz-st done">Print-ready</span>}</div><dl className="nz-document-proof"><div><dt>Report version</dt><dd>{report.reportVersionId}</dd></div><div><dt>Reviewed snapshot</dt><dd>{report.snapshot.id}</dd></div><div><dt>Evidence hash</dt><dd className="num">{report.dataHash}</dd></div></dl><div className="nz-banner ok"><div><b>One verified graphics source</b><div>Screen, portal and print resolve from the same immutable evidence record.</div></div></div></section>}

function Results({report,initialApproval,clientMode}:{report?:PublishedCrpReportReadModel;initialApproval:PortalReportApproval|null;clientMode:boolean}){
  const [approval,setApproval]=useState(initialApproval),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState("");
  const snapshot=report?.snapshot;
  const charts=snapshot?resolveCrpCoreCharts({id:snapshot.id,jobId:snapshot.jobId,jobNumber:snapshot.jobNumber,client:snapshot.client,reportingYear:snapshot.reportingYear,generatedAt:snapshot.createdAt,dataHash:snapshot.dataHash,target:snapshot.target,intensityTarget:snapshot.intensityTarget,annualComparison:snapshot.annualComparison,measurements:snapshot.measurements.map(row=>({rowId:row.rowId,scope:row.scope,scopeCode:row.scopeCode,sourceLabel:row.sourceLabel,siteId:row.siteId,siteLabel:row.siteLabel,purchasedGoodsCategoryId:row.purchasedGoodsCategoryId,purchasedGoodsCategoryLabel:row.purchasedGoodsCategoryLabel,tco2e:row.tco2e,factorSet:row.factorSet}))}):crpChartSamples;
  const snapshotId=snapshot?.id??reviewedCrpSnapshotSample.id,validation=validateManifest(crpProfessionalManifest,charts,snapshotId),versionId=report?.reportVersionId??publishedReportSample.id;
  async function approve(){if(!report||pending)return;setPending(true);setError("");try{const response=await fetch(`/api/portal/jobs/${report.snapshot.jobId}/published-report/approval`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportVersionId:report.reportVersionId})}),body=await response.json();if(!response.ok)throw new Error(body.message??"The report could not be approved.");if(!isApproval(body.approval)||body.approval.reportVersionId!==report.reportVersionId)throw new Error("The approval service returned an invalid confirmation.");setApproval(body.approval)}catch(cause){setError(cause instanceof Error?cause.message:"The approval outcome could not be verified.")}finally{setPending(false)}}
  return <><div style={notice}><div><b>Verified report version</b><div style={small}>This view is fixed to {versionId}; later consultant edits cannot silently change it.</div></div><span style={{marginLeft:"auto",fontSize:12}}>{validation.valid&&(!report||report.dataHash===snapshot?.dataHash)?"Evidence matched":"Unavailable"}</span></div>{report&&clientMode?<div style={{...card,marginBottom:18}}>{approval?<div className="nz-banner ok"><div><b>Report approved</b><div style={{marginTop:3}}>You approved this exact report version on {new Date(approval.approvedAt).toLocaleString("en-GB")}. This record is permanent.</div></div></div>:<><h2 style={{marginTop:0}}>Client approval</h2><p className="sub">Approval applies only to report version <b>{report.reportVersionId}</b> and cannot be transferred to a later publication.</p><label style={{display:"flex",alignItems:"flex-start",gap:10,fontSize:13}}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} style={{marginTop:3}}/><span>I have reviewed this published Carbon Reduction Plan and approve it as the client record for this reporting period.</span></label>{error?<div className="nz-banner warn" role="alert" style={{marginTop:12}}>{error}</div>:null}<button className="nz-btn pri" disabled={!confirmed||pending} onClick={approve} style={{marginTop:14}}>{pending?"Recording approval...":"Approve this report version"}</button></>}</div>:null}<ManifestChartSet manifest={crpProfessionalManifest} charts={charts} reviewedSnapshotId={snapshotId}/></>;
}

function DataEntry(){const open=canEnterPortalData(portalAccessSample,"2026-08-24T00:00:00Z");return <><div style={notice}><div><b>{open?"Data-entry window is open":"Data-entry window is closed"}</b><div style={small}>Access expires 30 Sep 2026. You can only see categories authorised for this job.</div></div></div><div style={card}><table className="nz-tbl"><thead><tr><th>Category</th><th>Scope</th><th>Allowed units</th><th className="num">Rows</th><th>Status</th><th/></tr></thead><tbody>{portalBucketsSample.map(bucket=><tr key={bucket.id}><td style={{fontWeight:600}}>{bucket.label}</td><td>{bucket.scope}</td><td>{bucket.allowedUnits.join(" · ")}</td><td className="num">{bucket.rows}</td><td><span className={`nz-st ${bucket.status==="complete"?"done":bucket.status==="submitted"?"est":"need"}`}>{bucket.status.replace("-"," ")}</span></td><td><button className="nz-btn" disabled={!open}>{bucket.rows?"Open":"Add data"}</button></td></tr>)}</tbody></table></div><p style={foot}>Factor selection and final calculations remain consultant-controlled. Submitted data enters the internal review queue before inclusion.</p></>}
function Documents(){return <div style={card}>{[["CRP-J000712-v1.pdf","Published report · 2.4 MB"],["Emissions certificate.pdf","Certificate · 340 KB"],["Methodology statement.pdf","Reference · 520 KB"]].map(([name,detail])=><div key={name} style={{display:"flex",padding:"16px 4px",borderBottom:"1px solid #EDF1EF",alignItems:"center"}}><div><b>{name}</b><div style={small}>{detail}</div></div><button className="nz-btn" style={{marginLeft:"auto"}}>Download</button></div>)}</div>}
function Messages(){return <div style={card}><div style={{padding:14,borderRadius:8,background:"#F6F8F7"}}><b>A. Shaw · NZI reviewer</b><p style={{margin:"6px 0 0",color:"#51605A",fontSize:13}}>The 2024 report is published. Please use this thread for questions about the results or supporting evidence.</p></div><textarea className="nz-notes" style={{marginTop:16,width:"100%"}} placeholder="Reply to the NZI review team..."/><div style={{textAlign:"right",marginTop:10}}><button className="nz-btn pri">Send message</button></div></div>}
const card={background:"white",border:"1px solid #E4EAE7",borderRadius:12,padding:18};
const notice={display:"flex",alignItems:"center",background:"#DFF5E9",color:"#0B7A4B",border:"1px solid #BCE8D0",borderRadius:10,padding:"13px 16px",marginBottom:18};
const small={fontSize:12,color:"#68766F",marginTop:3};
const foot={fontSize:12,color:"#68766F",marginTop:12};
